using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.AdvancedStartOptions;
using TaleWorlds.CampaignSystem.BarterSystem;
using TaleWorlds.CampaignSystem.BarterSystem.Barterables;
using TaleWorlds.CampaignSystem.BattleWreckages;
using TaleWorlds.CampaignSystem.CampaignBehaviors;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.ComponentInterfaces;
using TaleWorlds.CampaignSystem.Conversation.Persuasion;
using TaleWorlds.CampaignSystem.CraftingSystem;
using TaleWorlds.CampaignSystem.Election;
using TaleWorlds.CampaignSystem.Encounters;
using TaleWorlds.CampaignSystem.GameState;
using TaleWorlds.CampaignSystem.Handlers;
using TaleWorlds.CampaignSystem.Incidents;
using TaleWorlds.CampaignSystem.Issues;
using TaleWorlds.CampaignSystem.Issues.IssueQuestTasks;
using TaleWorlds.CampaignSystem.LogEntries;
using TaleWorlds.CampaignSystem.Map;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.MapNotificationTypes;
using TaleWorlds.CampaignSystem.Naval;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.SaveCompability;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.CampaignSystem.Settlements.Buildings;
using TaleWorlds.CampaignSystem.Settlements.Locations;
using TaleWorlds.CampaignSystem.Settlements.Workshops;
using TaleWorlds.CampaignSystem.Siege;
using TaleWorlds.CampaignSystem.TournamentGames;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem;

public class SaveableCampaignTypeDefiner : SaveableTypeDefiner
{
	public SaveableCampaignTypeDefiner()
		: base(330000)
	{
	}

	protected override void DefineClassTypes()
	{
		AddClassDefinition(typeof(Army), 3);
		AddClassDefinition(typeof(BarterManager), 4);
		AddClassDefinition(typeof(BarterResult), 12);
		AddClassDefinition(typeof(Building), 13);
		AddClassDefinition(typeof(BuildingType), 15);
		AddClassDefinition(typeof(Campaign), 16);
		AddClassDefinition(typeof(CampaignBehaviorDataStore), 17);
		AddClassDefinition(typeof(CampaignInformationManager), 22);
		AddClassDefinition(typeof(CampaignObjectBase), 23);
		AddClassDefinition(typeof(MapTimeTracker), 24);
		AddClassDefinition(typeof(HeroDeveloper), 29);
		AddClassDefinition(typeof(CharacterObject), 30);
		AddClassDefinition(typeof(CharacterRelationManager), 31);
		AddClassDefinition(typeof(Clan), 32);
		AddClassDefinition(typeof(Alley), 33);
		AddClassDefinition(typeof(Concept), 35);
		AddClassDefinition(typeof(CultureTrait), 37);
		AddClassDefinition(typeof(CultureObject), 38);
		AddClassDefinition(typeof(FactionManager), 42);
		AddClassDefinition(typeof(MapStateData), 46);
		AddClassDefinition(typeof(MenuContext), 47);
		AddClassDefinition(typeof(Hero), 48);
		AddClassDefinition(typeof(Hideout), 49);
		AddClassDefinition(typeof(IssueBase), 50);
		AddClassDefinition(typeof(IssueEffect), 51);
		AddClassDefinition(typeof(IssueManager), 52);
		AddClassDefinition(typeof(Kingdom), 53);
		AddClassDefinition(typeof(KingdomManager), 54);
		AddClassDefinition(typeof(Location), 55);
		AddClassDefinition(typeof(AccompanyingCharacter), 56);
		AddClassDefinition(typeof(LocationComplex), 57);
		AddClassDefinition(typeof(LogEntry), 60);
		AddClassDefinition(typeof(LogEntryHistory), 61);
		AddClassDefinition(typeof(MapEvent), 63);
		AddClassDefinition(typeof(MapEventManager), 64);
		AddClassDefinition(typeof(MapEventParty), 65);
		AddClassDefinition(typeof(MapEventSide), 67);
		AddClassDefinition(typeof(FakeMarketData), 68);
		AddClassDefinition(typeof(VillageMarketData), 69);
		AddClassDefinition(typeof(TownMarketData), 70);
		AddClassDefinition(typeof(PartyTemplateObject), 71);
		AddClassDefinition(typeof(MobileParty), 74);
		AddClassDefinition(typeof(MobilePartyAi), 76);
		AddClassDefinition(typeof(PartyBase), 77);
		AddClassDefinition(typeof(PlayerCaptivity), 79);
		AddClassDefinition(typeof(CampaignBattleResult), 80);
		AddClassDefinition(typeof(PlayerEncounter), 81);
		AddClassDefinition(typeof(PolicyObject), 85);
		AddClassDefinition(typeof(QuestBase), 86);
		AddClassDefinition(typeof(JournalLog), 87);
		AddClassDefinition(typeof(QuestManager), 88);
		AddClassDefinition(typeof(QuestTaskBase), 89);
		AddClassDefinition(typeof(Romance), 90);
		AddClassDefinition(typeof(ItemRoster), 91);
		AddClassDefinition(typeof(TroopRoster), 93);
		AddClassDefinition(typeof(FlattenedTroopRoster), 94);
		AddClassDefinition(typeof(Settlement), 95);
		AddClassDefinition(typeof(SettlementArea), 96);
		AddClassDefinition(typeof(SettlementComponent), 97);
		AddClassDefinition(typeof(SiegeEvent), 98);
		AddClassDefinition(typeof(SiegeEventManager), 99);
		AddClassDefinition(typeof(SiegeStrategy), 100);
		AddClassDefinition(typeof(TournamentGame), 101);
		AddClassDefinition(typeof(Fief), 102);
		AddClassDefinition(typeof(Town), 103);
		AddClassDefinition(typeof(Track), 104);
		AddClassDefinition(typeof(TrackedObject), 106);
		AddClassDefinition(typeof(TraitObject), 109);
		AddClassDefinition(typeof(Village), 112);
		AddClassDefinition(typeof(VillageType), 113);
		AddClassDefinition(typeof(VisualTrackerManager), 114);
		AddClassDefinition(typeof(Workshop), 115);
		AddClassDefinition(typeof(WorkshopType), 116);
		AddClassDefinition(typeof(FightTournamentGame), 119);
		AddClassDefinition(typeof(TournamentManager), 122);
		AddClassDefinition(typeof(CaptureAndBringNpcTask), 123);
		AddClassDefinition(typeof(ChangeCommonAreaOwnerQuestTask), 124);
		AddClassDefinition(typeof(ChangeSettlementOwnerTask), 125);
		AddClassDefinition(typeof(DefeatPartyQuestTask), 126);
		AddClassDefinition(typeof(ArmyCreationLogEntry), 128);
		AddClassDefinition(typeof(ArmyDispersionLogEntry), 129);
		AddClassDefinition(typeof(BattleStartedLogEntry), 130);
		AddClassDefinition(typeof(BesiegeSettlementLogEntry), 131);
		AddClassDefinition(typeof(ChangeAlleyOwnerLogEntry), 132);
		AddClassDefinition(typeof(ChangeRomanticStateLogEntry), 133);
		AddClassDefinition(typeof(ChangeSettlementOwnerLogEntry), 134);
		AddClassDefinition(typeof(CharacterBecameFugitiveLogEntry), 135);
		AddClassDefinition(typeof(CharacterBornLogEntry), 136);
		AddClassDefinition(typeof(CharacterInsultedLogEntry), 137);
		AddClassDefinition(typeof(CharacterKilledLogEntry), 138);
		AddClassDefinition(typeof(CharacterMarriedLogEntry), 139);
		AddClassDefinition(typeof(ChildbirthLogEntry), 140);
		AddClassDefinition(typeof(ClanChangeKingdomLogEntry), 141);
		AddClassDefinition(typeof(ClanLeaderChangedLogEntry), 142);
		AddClassDefinition(typeof(CommonAreaFightLogEntry), 143);
		AddClassDefinition(typeof(DeclareWarLogEntry), 145);
		AddClassDefinition(typeof(DefeatCharacterLogEntry), 146);
		AddClassDefinition(typeof(DestroyMobilePartyLogEntry), 147);
		AddClassDefinition(typeof(GatherArmyLogEntry), 148);
		AddClassDefinition(typeof(KingdomDecisionConcludedLogEntry), 149);
		AddClassDefinition(typeof(MakePeaceLogEntry), 150);
		AddClassDefinition(typeof(MercenaryClanChangedKingdomLogEntry), 151);
		AddClassDefinition(typeof(OverruleInfluenceLogEntry), 152);
		AddClassDefinition(typeof(PlayerAttackAlleyLogEntry), 153);
		AddClassDefinition(typeof(PlayerBattleEndedLogEntry), 154);
		AddClassDefinition(typeof(PlayerMeetLordLogEntry), 155);
		AddClassDefinition(typeof(PregnancyLogEntry), 156);
		AddClassDefinition(typeof(RebellionStartedLogEntry), 157);
		AddClassDefinition(typeof(SettlementClaimedLogEntry), 158);
		AddClassDefinition(typeof(TakePrisonerLogEntry), 159);
		AddClassDefinition(typeof(EndCaptivityLogEntry), 160);
		AddClassDefinition(typeof(TournamentWonLogEntry), 161);
		AddClassDefinition(typeof(VillageStateChangedLogEntry), 162);
		AddClassDefinition(typeof(DecisionOutcome), 164);
		AddClassDefinition(typeof(ExpelClanFromKingdomDecision), 165);
		AddClassDefinition(typeof(KingdomDecision), 166);
		AddClassDefinition(typeof(KingdomPolicyDecision), 167);
		AddClassDefinition(typeof(SettlementClaimantDecision), 168);
		AddClassDefinition(typeof(SettlementClaimantPreliminaryDecision), 169);
		AddClassDefinition(typeof(Supporter), 170);
		AddClassDefinition(typeof(Barterable), 173);
		AddClassDefinition(typeof(FiefBarterable), 174);
		AddClassDefinition(typeof(GoldBarterable), 175);
		AddClassDefinition(typeof(ItemBarterable), 176);
		AddClassDefinition(typeof(JoinKingdomAsClanBarterable), 177);
		AddClassDefinition(typeof(LeaveKingdomAsClanBarterable), 178);
		AddClassDefinition(typeof(MarriageBarterable), 179);
		AddClassDefinition(typeof(MercenaryJoinKingdomBarterable), 180);
		AddClassDefinition(typeof(PeaceBarterable), 181);
		AddClassDefinition(typeof(SetPrisonerFreeBarterable), 182);
		AddClassDefinition(typeof(TradeRumor), 183);
		AddClassDefinition(typeof(CampaignBehaviorDataStore.BehaviorSaveData), 184);
		AddClassDefinition(typeof(CharacterRelationManager.HeroRelations), 186);
		AddClassDefinition(typeof(StanceLink), 188);
		AddClassDefinition(typeof(Romance.RomanticState), 191);
		AddClassDefinition(typeof(SiegeEvent.RangedSiegeEngine), 194);
		AddClassDefinition(typeof(SiegeEvent.SiegeEngineConstructionProgress), 195);
		AddClassDefinition(typeof(ExpelClanFromKingdomDecision.ExpelClanDecisionOutcome), 203);
		AddClassDefinition(typeof(KingdomPolicyDecision.PolicyDecisionOutcome), 204);
		AddClassDefinition(typeof(SettlementClaimantDecision.ClanAsDecisionOutcome), 205);
		AddClassDefinition(typeof(SettlementClaimantPreliminaryDecision.SettlementClaimantPreliminaryOutcome), 206);
		AddClassDefinition(typeof(SiegeEvent.SiegeEnginesContainer), 226);
		AddClassDefinition(typeof(SiegeEvent.SiegeEngineMissile), 227);
		AddClassDefinition(typeof(SiegeEvent.SiegeEnginesContainer.RemovedSiegeEngine), 228);
		AddClassDefinition(typeof(SafePassageBarterable), 229);
		AddClassDefinition(typeof(CampaignBehaviorManager), 230);
		AddClassDefinition(typeof(JournalLogEntry), 236);
		AddClassDefinition(typeof(DeclareWarDecision), 237);
		AddClassDefinition(typeof(DeclareWarDecision.DeclareWarDecisionOutcome), 238);
		AddClassDefinition(typeof(MakePeaceKingdomDecision), 239);
		AddClassDefinition(typeof(MakePeaceKingdomDecision.MakePeaceDecisionOutcome), 240);
		AddClassDefinition(typeof(PerkObject), 241);
		AddClassDefinition(typeof(PlayerReputationChangesLogEntry), 243);
		AddClassDefinition(typeof(BesiegerCamp), 245);
		AddClassDefinition(typeof(KingdomDecisionAddedLogEntry), 246);
		AddClassDefinition(typeof(ArmyCreationMapNotification), 247);
		AddClassDefinition(typeof(ArmyDispersionMapNotification), 248);
		AddClassDefinition(typeof(ChildBornMapNotification), 249);
		AddClassDefinition(typeof(DeathMapNotification), 250);
		AddClassDefinition(typeof(KingdomDecisionMapNotification), 251);
		AddClassDefinition(typeof(MarriageMapNotification), 252);
		AddClassDefinition(typeof(PeaceMapNotification), 253);
		AddClassDefinition(typeof(SettlementRebellionMapNotification), 254);
		AddClassDefinition(typeof(WarMapNotification), 256);
		AddClassDefinition(typeof(KingSelectionKingdomDecision), 257);
		AddClassDefinition(typeof(KingSelectionKingdomDecision.KingSelectionDecisionOutcome), 258);
		AddClassDefinition(typeof(PersuasionOptionArgs), 259);
		AddClassDefinition(typeof(PersuasionAttempt), 260);
		AddClassDefinition(typeof(CampaignOptions), 261);
		AddClassDefinition(typeof(TransferPrisonerBarterable), 262);
		AddClassDefinition(typeof(KingdomDestroyedLogEntry), 263);
		AddClassDefinition(typeof(SettlementUnderSiegeMapNotification), 264);
		AddClassDefinition(typeof(SettlementOwnerChangedMapNotification), 265);
		AddClassDefinition(typeof(IssueQuestLogEntry), 266);
		AddClassDefinition(typeof(IssueQuestStartLogEntry), 267);
		AddClassDefinition(typeof(IssueCoolDownData), 268);
		AddClassDefinition(typeof(HeroRelatedIssueCoolDownData), 269);
		AddClassDefinition(typeof(EducationMapNotification), 271);
		AddClassDefinition(typeof(PartyComponent), 272);
		AddClassDefinition(typeof(GarrisonPartyComponent), 273);
		AddClassDefinition(typeof(LordPartyComponent), 274);
		AddClassDefinition(typeof(VillagerPartyComponent), 275);
		AddClassDefinition(typeof(BanditPartyComponent), 277);
		AddClassDefinition(typeof(CaravanPartyComponent), 278);
		AddClassDefinition(typeof(MilitiaPartyComponent), 280);
		AddClassDefinition(typeof(FactionManagerStancesData), 281);
		AddClassDefinition(typeof(CampaignObjectManager), 282);
		AddClassDefinition(typeof(TraitChangedMapNotification), 283);
		AddClassDefinition(typeof(WarPartyComponent), 284);
		AddClassDefinition(typeof(RansomOfferMapNotification), 285);
		AddClassDefinition(typeof(CampaignPeriodicEventManager), 286);
		AddClassDefinition(typeof(CustomPartyComponent), 287);
		AddClassDefinition(typeof(CraftingOrder), 289);
		AddClassDefinition(typeof(PeaceOfferMapNotification), 291);
		AddClassDefinition(typeof(PlayerCharacterChangedLogEntry), 292);
		AddClassDefinition(typeof(CampaignPeriodicEventManager.PeriodicTicker<>), 293);
		AddClassDefinition(typeof(OrderOfBattleCampaignBehavior.OrderOfBattleFormationData), 295);
		AddClassDefinition(typeof(MarriageOfferMapNotification), 297);
		AddClassDefinition(typeof(PartyLeaderChangeNotification), 298);
		AddClassDefinition(typeof(MercenaryOfferMapNotification), 299);
		AddClassDefinition(typeof(VassalOfferMapNotification), 300);
		AddClassDefinition(typeof(HeirComeOfAgeMapNotification), 301);
		AddClassDefinition(typeof(KingdomDestroyedMapNotification), 302);
		AddClassDefinition(typeof(ClanDestroyedLogEntry), 303);
		AddClassDefinition(typeof(SiegeAftermathLogEntry), 304);
		AddClassDefinition(typeof(AlleyLeaderDiedMapNotification), 305);
		AddClassDefinition(typeof(AlleyUnderAttackMapNotification), 306);
		AddClassDefinition(typeof(PlayerRetiredLogEntry), 307);
		AddClassDefinition(typeof(RetirementSettlementComponent), 308);
		AddClassDefinition(typeof(MapEventComponent), 309);
		AddClassDefinition(typeof(ForceSuppliesEventComponent), 310);
		AddClassDefinition(typeof(ForceVolunteersEventComponent), 311);
		AddClassDefinition(typeof(RaidEventComponent), 312);
		AddClassDefinition(typeof(FieldBattleEventComponent), 313);
		AddClassDefinition(typeof(HideoutEventComponent), 314);
		AddClassDefinition(typeof(SiegeAmbushEventComponent), 315);
		AddClassDefinition(typeof(Ship), 316);
		AddClassDefinition(typeof(AnchorPoint), 319);
		AddClassDefinition(typeof(Incident), 322);
		AddClassDefinition(typeof(BlockadeBattleEventComponent), 325);
		AddClassDefinition(typeof(Figurehead), 326);
		AddClassDefinition(typeof(MobilePartyAi.FleeingData), 327);
		AddClassDefinition(typeof(MapMarker), 328);
		AddClassDefinition(typeof(MapTrackerManager), 329);
		AddClassDefinition(typeof(PatrolPartyComponent), 330);
		AddClassDefinition(typeof(TradeAgreementDecision), 331);
		AddClassDefinition(typeof(TradeAgreementDecision.TradeAgreementDecisionOutcome), 332);
		AddClassDefinition(typeof(TradeAgreementLogEntry), 333);
		AddClassDefinition(typeof(StartAllianceDecision), 334);
		AddClassDefinition(typeof(ProposeCallToWarAgreementDecision), 335);
		AddClassDefinition(typeof(StartAllianceLogEntry), 336);
		AddClassDefinition(typeof(EndAllianceLogEntry), 337);
		AddClassDefinition(typeof(StartCallToWarAgreementLogEntry), 338);
		AddClassDefinition(typeof(EndCallToWarAgreementLogEntry), 339);
		AddClassDefinition(typeof(AcceptCallToWarAgreementDecision), 340);
		AddClassDefinition(typeof(AllianceOfferMapNotification), 341);
		AddClassDefinition(typeof(ProposeCallToWarOfferMapNotification), 342);
		AddClassDefinition(typeof(AcceptCallToWarOfferMapNotification), 343);
		AddClassDefinition(typeof(TributeFinishedMapNotification), 344);
		AddClassDefinition(typeof(BattleWreckage), 345);
		AddClassDefinition(typeof(SiegeAssaultEventComponent), 346);
		AddClassDefinition(typeof(SiegeSallyOutEventComponent), 347);
		AddClassDefinition(typeof(SiegeOutsideEventComponent), 348);
		AddClassDefinition(typeof(PartyConfiguration), 349);
		AddClassDefinition(typeof(WreckageCreatedLogEntry), 350);
		AddClassDefinition(typeof(BloodFeudClanMemberGotExecutedMapNotification), 351);
		AddClassDefinition(typeof(BloodFeudClanMemberExecuteCancelledMapNotification), 352);
		AddClassDefinition(typeof(BloodFeudClanMemberExecutedLordMapNotification), 353);
		AddClassDefinition(typeof(BloodFeudStartedMapNotification), 354);
		AddClassDefinition(typeof(BloodFeudEndedMapNotification), 355);
		AddClassDefinition(typeof(BloodFeudClanMemberCapturedMapNotification), 356);
		AddClassDefinition(typeof(PlayerDataForNavalAutoTravel), 364);
		AddClassDefinition(typeof(IncidentManager), 365);
		AddClassDefinition(typeof(AdvancedStartOptionsData), 366);
		AddClassDefinition(typeof(AdvancedStartData), 367);
		AddClassDefinition(typeof(AdvancedStartData<>), 368);
	}

	protected override void DefineStructTypes()
	{
		AddStructDefinition(typeof(CampaignTime), 1001);
		AddStructDefinition(typeof(ItemData), 1002);
		AddStructDefinition(typeof(PartyTemplateStack), 1003);
		AddStructDefinition(typeof(FlattenedTroopRosterElement), 1004);
		AddStructDefinition(typeof(TroopRosterElement), 1005);
		AddStructDefinition(typeof(Town.SellLog), 1009);
		AddStructDefinition(typeof(CampaignVec2), 1022);
	}

	protected override void DefineEnumTypes()
	{
		AddEnumDefinition(typeof(CampaignTimeControlMode), 2001);
		AddEnumDefinition(typeof(Occupation), 2002);
		AddEnumDefinition(typeof(CampaignGameMode), 2008);
		AddEnumDefinition(typeof(ImportanceEnum), 2009);
		AddEnumDefinition(typeof(MapEventState), 2011);
		AddEnumDefinition(typeof(AiBehavior), 2013);
		AddEnumDefinition(typeof(MoveModeType), 2014);
		AddEnumDefinition(typeof(PlayerEncounterState), 2015);
		AddEnumDefinition(typeof(RosterTroopState), 2016);
		AddEnumDefinition(typeof(Army.ArmyTypes), 2021);
		AddEnumDefinition(typeof(Army.ArmyDispersionReason), 2023, new ArmyDispersionReasonEnumResolver());
		AddEnumDefinition(typeof(StanceType), 2029);
		AddEnumDefinition(typeof(ActionNotes), 2030);
		AddEnumDefinition(typeof(MenuContext.MenuContextState), 2031);
		AddEnumDefinition(typeof(Hero.CharacterStates), 2032);
		AddEnumDefinition(typeof(IssueBase.IssueState), 2034);
		AddEnumDefinition(typeof(MapEvent.BattleTypes), 2036, new BattleTypeEnumResolver());
		AddEnumDefinition(typeof(QuestBase.QuestStates), 2041);
		AddEnumDefinition(typeof(QuestTaskBase.FinishStates), 2042);
		AddEnumDefinition(typeof(Romance.RomanceLevelEnum), 2043);
		AddEnumDefinition(typeof(Settlement.SiegeState), 2048);
		AddEnumDefinition(typeof(SettlementComponent.ProsperityLevel), 2049);
		AddEnumDefinition(typeof(TournamentGame.QualificationMode), 2051);
		AddEnumDefinition(typeof(Village.VillageStates), 2055);
		AddEnumDefinition(typeof(KingdomDecision.SupportStatus), 2056);
		AddEnumDefinition(typeof(Supporter.SupportWeights), 2057);
		AddEnumDefinition(typeof(KillCharacterAction.KillCharacterActionDetail), 2058);
		AddEnumDefinition(typeof(SiegeBombardTargets), 2059);
		AddEnumDefinition(typeof(QuestBase.QuestCompleteDetails), 2061);
		AddEnumDefinition(typeof(Track.PartyTypeEnum), 2062);
		AddEnumDefinition(typeof(SettlementAccessModel.AccessLevel), 2067);
		AddEnumDefinition(typeof(SettlementAccessModel.AccessMethod), 2068);
		AddEnumDefinition(typeof(SettlementAccessModel.AccessLimitationReason), 2069);
		AddEnumDefinition(typeof(SettlementAccessModel.LimitedAccessSolution), 2070);
		AddEnumDefinition(typeof(SettlementAccessModel.PreliminaryActionObligation), 2071);
		AddEnumDefinition(typeof(SettlementAccessModel.PreliminaryActionType), 2072);
		AddEnumDefinition(typeof(PersuasionOptionResult), 2075);
		AddEnumDefinition(typeof(PersuasionArgumentStrength), 2076);
		AddEnumDefinition(typeof(TraitEffect), 2077);
		AddEnumDefinition(typeof(CampaignOptions.Difficulty), 2078);
		AddEnumDefinition(typeof(LogType), 2079);
		AddEnumDefinition(typeof(EndCaptivityDetail), 2080, new EndCaptivityDetailEnumResolver());
		AddEnumDefinition(typeof(BuildingEffectEnum), 2090);
		AddEnumDefinition(typeof(SiegeAftermathAction.SiegeAftermath), 2100);
		AddEnumDefinition(typeof(IssueBase.IssueUpdateDetails), 2120);
		AddEnumDefinition(typeof(DeploymentFormationClass), 2130);
		AddEnumDefinition(typeof(FormationFilterType), 2140);
		AddEnumDefinition(typeof(MobileParty.NavigationType), 2150);
		AddEnumDefinition(typeof(GameAccelerationMode), 2160);
		AddEnumDefinition(typeof(HideoutEventComponent.HideoutBattleEndState), 2161);
		AddEnumDefinition(typeof(BattleWreckage.WreckageType), 2162);
	}

	protected override void DefineInterfaceTypes()
	{
		AddInterfaceDefinition(typeof(IFaction), 3001);
		AddInterfaceDefinition(typeof(ITrackableCampaignObject), 3002);
		AddInterfaceDefinition(typeof(ILocatable<>), 3003);
		AddInterfaceDefinition(typeof(ISiegeEventSide), 3004);
		AddInterfaceDefinition(typeof(ITrackableBase), 3006);
		AddInterfaceDefinition(typeof(ICustomSystemManager), 3007);
	}

	protected override void DefineGenericClassDefinitions()
	{
		ConstructGenericClassDefinition(typeof(MBReadOnlyDictionary<Hero, short>));
		ConstructGenericClassDefinition(typeof(Tuple<CampaignTime, IFaction>));
		ConstructGenericClassDefinition(typeof(Tuple<Kingdom, Kingdom>));
		ConstructGenericClassDefinition(typeof(Tuple<Kingdom, CampaignTime>));
		ConstructGenericClassDefinition(typeof(Tuple<TraitObject, int>));
		ConstructGenericClassDefinition(typeof(PriorityQueue<int, KeyValuePair<UniqueTroopDescriptor, MapEventParty>>));
		ConstructGenericClassDefinition(typeof(CampaignPeriodicEventManager.PeriodicTicker<MobileParty>));
		ConstructGenericClassDefinition(typeof(CampaignPeriodicEventManager.PeriodicTicker<Settlement>));
		ConstructGenericClassDefinition(typeof(CampaignPeriodicEventManager.PeriodicTicker<Clan>));
		ConstructGenericClassDefinition(typeof(CampaignPeriodicEventManager.PeriodicTicker<Town>));
		ConstructGenericClassDefinition(typeof(CampaignPeriodicEventManager.PeriodicTicker<Hero>));
		ConstructGenericClassDefinition(typeof(PropertyOwner<PerkObject>));
		ConstructGenericClassDefinition(typeof(PropertyOwner<TraitObject>));
		ConstructGenericClassDefinition(typeof(PropertyOwner<PropertyObject>));
		ConstructGenericClassDefinition(typeof(AdvancedStartData<bool>));
		ConstructGenericClassDefinition(typeof(AdvancedStartData<int>));
		ConstructGenericClassDefinition(typeof(AdvancedStartData<uint>));
		ConstructGenericClassDefinition(typeof(AdvancedStartData<float>));
		ConstructGenericClassDefinition(typeof(AdvancedStartData<string>));
	}

	protected override void DefineConflictResolvers()
	{
		AddConflictResolver(26, new CharacterPerksResolver());
		AddConflictResolver(27, new CharacterTraitsResolver());
		AddConflictResolver(288, new CharacterAttributesResolver());
		AddConflictResolver(28, new HeroTraitDeveloperResolver());
		AddConflictResolver(29, new HeroDeveloperResolver());
	}

	protected override void DefineGenericStructDefinitions()
	{
		ConstructGenericStructDefinition(typeof((IFaction, IFaction)));
		ConstructGenericStructDefinition(typeof((Kingdom, Kingdom)));
		ConstructGenericStructDefinition(typeof(KeyValuePair<UniqueTroopDescriptor, MapEventParty>));
		ConstructGenericStructDefinition(typeof(KeyValuePair<int, KeyValuePair<UniqueTroopDescriptor, MapEventParty>>));
		ConstructGenericStructDefinition(typeof(KeyValuePair<Hero, short>));
		ConstructGenericStructDefinition(typeof(KeyValuePair<Hero, CraftingOrder>));
		ConstructGenericStructDefinition(typeof(KeyValuePair<Settlement, ItemRoster>));
		ConstructGenericStructDefinition(typeof((Clan, CampaignTime)));
	}

	protected override void DefineContainerDefinitions()
	{
		ConstructContainerDefinition(typeof(VillageType[]));
		ConstructContainerDefinition(typeof(BuildingType[]));
		ConstructContainerDefinition(typeof(Hero[]));
		ConstructContainerDefinition(typeof(Town[]));
		ConstructContainerDefinition(typeof(CharacterObject[]));
		ConstructContainerDefinition(typeof(Workshop[]));
		ConstructContainerDefinition(typeof(MapEventSide[]));
		ConstructContainerDefinition(typeof(Clan[]));
		ConstructContainerDefinition(typeof(SiegeEvent.SiegeEngineConstructionProgress[]));
		ConstructContainerDefinition(typeof(TroopRosterElement[]));
		ConstructContainerDefinition(typeof(Town.SellLog[]));
		ConstructContainerDefinition(typeof(CampaignTime[]));
		ConstructContainerDefinition(typeof(MobileParty[]));
		ConstructContainerDefinition(typeof(Settlement[]));
		ConstructContainerDefinition(typeof(CraftingOrder[]));
		ConstructContainerDefinition(typeof(CultureObject[]));
		ConstructContainerDefinition(typeof(KeyValuePair<Hero, CraftingOrder>[]));
		ConstructContainerDefinition(typeof(KeyValuePair<Hero, short>[]));
		ConstructContainerDefinition(typeof(Tuple<TraitObject, int>[]));
		ConstructContainerDefinition(typeof(List<KingdomDecision>));
		ConstructContainerDefinition(typeof(List<QuestBase>));
		ConstructContainerDefinition(typeof(List<Hero>));
		ConstructContainerDefinition(typeof(List<Romance.RomanticState>));
		ConstructContainerDefinition(typeof(List<SiegeEvent>));
		ConstructContainerDefinition(typeof(List<MapEvent>));
		ConstructContainerDefinition(typeof(List<LogEntry>));
		ConstructContainerDefinition(typeof(List<TrackedObject>));
		ConstructContainerDefinition(typeof(List<TournamentGame>));
		ConstructContainerDefinition(typeof(List<Track>));
		ConstructContainerDefinition(typeof(List<Workshop>));
		ConstructContainerDefinition(typeof(List<Alley>));
		ConstructContainerDefinition(typeof(List<MobileParty>));
		ConstructContainerDefinition(typeof(List<SettlementComponent>));
		ConstructContainerDefinition(typeof(List<Village>));
		ConstructContainerDefinition(typeof(List<CharacterObject>));
		ConstructContainerDefinition(typeof(List<CultureObject>));
		ConstructContainerDefinition(typeof(List<IFaction>));
		ConstructContainerDefinition(typeof(List<Clan>));
		ConstructContainerDefinition(typeof(List<Kingdom>));
		ConstructContainerDefinition(typeof(List<TraitObject>));
		ConstructContainerDefinition(typeof(List<VillageType>));
		ConstructContainerDefinition(typeof(List<BuildingType>));
		ConstructContainerDefinition(typeof(List<PartyTemplateObject>));
		ConstructContainerDefinition(typeof(List<Settlement>));
		ConstructContainerDefinition(typeof(List<WorkshopType>));
		ConstructContainerDefinition(typeof(List<Hideout>));
		ConstructContainerDefinition(typeof(List<RetirementSettlementComponent>));
		ConstructContainerDefinition(typeof(List<Town>));
		ConstructContainerDefinition(typeof(List<MenuContext>));
		ConstructContainerDefinition(typeof(List<PolicyObject>));
		ConstructContainerDefinition(typeof(List<Concept>));
		ConstructContainerDefinition(typeof(List<IssueBase>));
		ConstructContainerDefinition(typeof(List<IssueEffect>));
		ConstructContainerDefinition(typeof(List<SiegeStrategy>));
		ConstructContainerDefinition(typeof(List<Building>));
		ConstructContainerDefinition(typeof(List<Army>));
		ConstructContainerDefinition(typeof(List<Location>));
		ConstructContainerDefinition(typeof(List<SiegeEvent.SiegeEngineConstructionProgress>));
		ConstructContainerDefinition(typeof(List<AccompanyingCharacter>));
		ConstructContainerDefinition(typeof(List<TroopRosterElement>));
		ConstructContainerDefinition(typeof(List<PartyBase>));
		ConstructContainerDefinition(typeof(List<QuestTaskBase>));
		ConstructContainerDefinition(typeof(List<JournalLog>));
		ConstructContainerDefinition(typeof(List<KeyValuePair<int, KeyValuePair<UniqueTroopDescriptor, MapEventParty>>>));
		ConstructContainerDefinition(typeof(List<SiegeEvent.SiegeEngineMissile>));
		ConstructContainerDefinition(typeof(List<SiegeEvent.SiegeEnginesContainer.RemovedSiegeEngine>));
		ConstructContainerDefinition(typeof(List<Barterable>));
		ConstructContainerDefinition(typeof(List<TradeRumor>));
		ConstructContainerDefinition(typeof(List<ITrackableCampaignObject>));
		ConstructContainerDefinition(typeof(List<PerkObject>));
		ConstructContainerDefinition(typeof(List<CampaignTime>));
		ConstructContainerDefinition(typeof(List<Supporter>));
		ConstructContainerDefinition(typeof(List<PersuasionAttempt>));
		ConstructContainerDefinition(typeof(List<IssueBase.IssueUpdateDetails>));
		ConstructContainerDefinition(typeof(List<KeyValuePair<Hero, short>>));
		ConstructContainerDefinition(typeof(List<Tuple<Kingdom, Kingdom>>));
		ConstructContainerDefinition(typeof(List<IssueCoolDownData>));
		ConstructContainerDefinition(typeof(List<MapEventParty>));
		ConstructContainerDefinition(typeof(List<CraftingOrder>));
		ConstructContainerDefinition(typeof(List<OrderOfBattleCampaignBehavior.OrderOfBattleFormationData>));
		ConstructContainerDefinition(typeof(List<Ship>));
		ConstructContainerDefinition(typeof(List<Figurehead>));
		ConstructContainerDefinition(typeof(List<MapMarker>));
		ConstructContainerDefinition(typeof(List<BattleWreckage>));
		ConstructContainerDefinition(typeof(List<TextObject>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, short>));
		ConstructContainerDefinition(typeof(Queue<Building>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, MobileParty>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, CharacterObject>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, CultureObject>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, Clan>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, Kingdom>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, TraitObject>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, VillageType>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, BuildingType>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, PartyTemplateObject>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, Settlement>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, WorkshopType>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, Village>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, Hideout>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, RetirementSettlementComponent>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, Town>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, Hero>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, QuestBase>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, MapEvent>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, MenuContext>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, PolicyObject>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, Concept>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, IssueBase>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, IssueEffect>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, SiegeStrategy>));
		ConstructContainerDefinition(typeof(Dictionary<MBGUID, PerkObject>));
		ConstructContainerDefinition(typeof(Dictionary<string, CharacterObject>));
		ConstructContainerDefinition(typeof(Dictionary<string, CultureObject>));
		ConstructContainerDefinition(typeof(Dictionary<string, MobileParty>));
		ConstructContainerDefinition(typeof(Dictionary<string, Clan>));
		ConstructContainerDefinition(typeof(Dictionary<string, Kingdom>));
		ConstructContainerDefinition(typeof(Dictionary<string, TraitObject>));
		ConstructContainerDefinition(typeof(Dictionary<string, VillageType>));
		ConstructContainerDefinition(typeof(Dictionary<string, BuildingType>));
		ConstructContainerDefinition(typeof(Dictionary<string, PartyTemplateObject>));
		ConstructContainerDefinition(typeof(Dictionary<string, Settlement>));
		ConstructContainerDefinition(typeof(Dictionary<string, WorkshopType>));
		ConstructContainerDefinition(typeof(Dictionary<string, Village>));
		ConstructContainerDefinition(typeof(Dictionary<string, Hideout>));
		ConstructContainerDefinition(typeof(Dictionary<string, RetirementSettlementComponent>));
		ConstructContainerDefinition(typeof(Dictionary<string, Town>));
		ConstructContainerDefinition(typeof(Dictionary<string, Hero>));
		ConstructContainerDefinition(typeof(Dictionary<string, QuestBase>));
		ConstructContainerDefinition(typeof(Dictionary<string, MapEvent>));
		ConstructContainerDefinition(typeof(Dictionary<string, MenuContext>));
		ConstructContainerDefinition(typeof(Dictionary<string, PolicyObject>));
		ConstructContainerDefinition(typeof(Dictionary<string, Concept>));
		ConstructContainerDefinition(typeof(Dictionary<string, IssueBase>));
		ConstructContainerDefinition(typeof(Dictionary<string, IssueEffect>));
		ConstructContainerDefinition(typeof(Dictionary<string, SiegeStrategy>));
		ConstructContainerDefinition(typeof(Dictionary<string, Location>));
		ConstructContainerDefinition(typeof(Dictionary<string, PerkObject>));
		ConstructContainerDefinition(typeof(Dictionary<string, CampaignTime>));
		ConstructContainerDefinition(typeof(Dictionary<object, List<QuestBase>>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, IssueBase>));
		ConstructContainerDefinition(typeof(Dictionary<(IFaction, IFaction), StanceLink>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, int>));
		ConstructContainerDefinition(typeof(Dictionary<Settlement, List<TournamentGame>>));
		ConstructContainerDefinition(typeof(Dictionary<Settlement, TournamentGame>));
		ConstructContainerDefinition(typeof(Dictionary<CharacterObject, int>));
		ConstructContainerDefinition(typeof(Dictionary<Settlement, float>));
		ConstructContainerDefinition(typeof(Dictionary<Settlement, bool>));
		ConstructContainerDefinition(typeof(Dictionary<IFaction, float>));
		ConstructContainerDefinition(typeof(Dictionary<IFaction, int>));
		ConstructContainerDefinition(typeof(Dictionary<TraitObject, int>));
		ConstructContainerDefinition(typeof(Dictionary<ItemCategory, ItemData>));
		ConstructContainerDefinition(typeof(Dictionary<UniqueTroopDescriptor, MapEventParty>));
		ConstructContainerDefinition(typeof(Dictionary<PartyBase, MapEventParty>));
		ConstructContainerDefinition(typeof(Dictionary<SiegeEvent.SiegeEngineConstructionProgress, int>));
		ConstructContainerDefinition(typeof(Dictionary<IFaction, List<Settlement>>));
		ConstructContainerDefinition(typeof(Dictionary<int, PartyBase>));
		ConstructContainerDefinition(typeof(Dictionary<IssueEffect, float>));
		ConstructContainerDefinition(typeof(Dictionary<UniqueTroopDescriptor, FlattenedTroopRosterElement>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, CampaignTime>));
		ConstructContainerDefinition(typeof(Dictionary<string, CampaignBehaviorDataStore.BehaviorSaveData>));
		ConstructContainerDefinition(typeof(Dictionary<MobileParty, CampaignTime>));
		ConstructContainerDefinition(typeof(Dictionary<CharacterObject, float>));
		ConstructContainerDefinition(typeof(Dictionary<MobileParty, int>));
		ConstructContainerDefinition(typeof(Dictionary<MobileParty, float>));
		ConstructContainerDefinition(typeof(Dictionary<Settlement, CampaignTime>));
		ConstructContainerDefinition(typeof(Dictionary<Settlement, int>));
		ConstructContainerDefinition(typeof(Dictionary<CharacterObject, CharacterObject>));
		ConstructContainerDefinition(typeof(Dictionary<PerkObject, int>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, List<CampaignTime>>));
		ConstructContainerDefinition(typeof(Dictionary<MobileParty, Town>));
		ConstructContainerDefinition(typeof(Dictionary<Village, CampaignTime>));
		ConstructContainerDefinition(typeof(Dictionary<Village, bool>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, Hero.CharacterStates>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, bool>));
		ConstructContainerDefinition(typeof(Dictionary<Workshop, int>));
		ConstructContainerDefinition(typeof(Dictionary<CharacterObject, FormationClass>));
		ConstructContainerDefinition(typeof(Dictionary<PartyBase, float>));
		ConstructContainerDefinition(typeof(Dictionary<string, List<IssueCoolDownData>>));
		ConstructContainerDefinition(typeof(Dictionary<Clan, int>));
		ConstructContainerDefinition(typeof(Dictionary<Clan, CampaignTime>));
		ConstructContainerDefinition(typeof(Dictionary<CultureObject, Dictionary<int, int>>));
		ConstructContainerDefinition(typeof(Dictionary<MobileParty, List<Settlement>>));
		ConstructContainerDefinition(typeof(Dictionary<Building, int>));
		ConstructContainerDefinition(typeof(Dictionary<int, MobileParty>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, CraftingOrder>));
		ConstructContainerDefinition(typeof(Dictionary<string, List<CraftingOrder>>));
		ConstructContainerDefinition(typeof(Dictionary<ITrackableCampaignObject, List<QuestBase>>));
		ConstructContainerDefinition(typeof(Dictionary<Town, CampaignTime>));
		ConstructContainerDefinition(typeof(Dictionary<Kingdom, CampaignTime>));
		ConstructContainerDefinition(typeof(Dictionary<FormationFilterType, bool>));
		ConstructContainerDefinition(typeof(Dictionary<MobileParty, Vec2>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, (int, int)>));
		ConstructContainerDefinition(typeof(KeyValuePair<Settlement, ItemRoster>[]));
		ConstructContainerDefinition(typeof(Dictionary<Hero, Hero>));
		ConstructContainerDefinition(typeof(Dictionary<ITrackableBase, TrackedObject>));
		ConstructContainerDefinition(typeof(Dictionary<Incident, CampaignTime>));
		ConstructContainerDefinition(typeof(Dictionary<MobileParty, CampaignVec2>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, Figurehead>));
		ConstructContainerDefinition(typeof(Dictionary<MobileParty, Dictionary<MobileParty, CampaignTime>>));
		ConstructContainerDefinition(typeof(Dictionary<MobileParty, Dictionary<Settlement, CampaignTime>>));
		ConstructContainerDefinition(typeof(Dictionary<MobileParty, Settlement>));
		ConstructContainerDefinition(typeof(Dictionary<MapEvent, MobileParty>));
		ConstructContainerDefinition(typeof(List<ICustomSystemManager>));
		ConstructContainerDefinition(typeof(Dictionary<Settlement, MobileParty>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, List<Ship>>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, MapEvent>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, (Clan, CampaignTime)>));
		ConstructContainerDefinition(typeof(List<AdvancedStartData>));
		ConstructContainerDefinition(typeof(Dictionary<Hero, float>));
	}
}
