<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TaleWorlds.PlatformService.Steam</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="TaleWorlds.AchievementSystem">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.AchievementSystem.dll</HintPath>
    </Reference>
    <Reference Include="Steamworks.NET">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\Steamworks.NET.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.PlatformService">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.PlatformService.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Localization">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.Localization.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.PlayerServices">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.PlayerServices.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.ModuleManager">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.ModuleManager.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Library">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.Library.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.ActivitySystem">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.ActivitySystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Diamond">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.Diamond.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Diamond.AccessProvider.Steam">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.Diamond.AccessProvider.Steam.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>