using System.ComponentModel;
using System.Numerics;
using SandBox.ViewModelCollection.Tournament;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Tournament;

namespace SandBox.GauntletUI.AutoGenerated0;

public class Tournament__SandBox_ViewModelCollection_Tournament_TournamentVM_Dependency_4_Tournament_Match__DependendPrefab : TournamentMatchWidget
{
	private TournamentMatchWidget _widget;

	private ListPanel _widget_0;

	private Tournament__SandBox_ViewModelCollection_Tournament_TournamentVM_Dependency_6_Tournament_Team__DependendPrefab _widget_0_0;

	private Tournament__SandBox_ViewModelCollection_Tournament_TournamentVM_Dependency_6_Tournament_Team__DependendPrefab _widget_0_1;

	private Tournament__SandBox_ViewModelCollection_Tournament_TournamentVM_Dependency_6_Tournament_Team__DependendPrefab _widget_0_2;

	private Tournament__SandBox_ViewModelCollection_Tournament_TournamentVM_Dependency_6_Tournament_Team__DependendPrefab _widget_0_3;

	private TournamentMatchVM _datasource_Root;

	private TournamentTeamVM _datasource_Root_Team1;

	private TournamentTeamVM _datasource_Root_Team2;

	private TournamentTeamVM _datasource_Root_Team3;

	private TournamentTeamVM _datasource_Root_Team4;

	public Tournament__SandBox_ViewModelCollection_Tournament_TournamentVM_Dependency_4_Tournament_Match__DependendPrefab(UIContext context)
		: base(context)
	{
	}

	public void CreateWidgets()
	{
		_widget = this;
		_widget_0 = new ListPanel(base.Context);
		_widget.AddChild(_widget_0);
		_widget_0_0 = new Tournament__SandBox_ViewModelCollection_Tournament_TournamentVM_Dependency_6_Tournament_Team__DependendPrefab(base.Context);
		_widget_0.AddChild(_widget_0_0);
		_widget_0_0.CreateWidgets();
		_widget_0_1 = new Tournament__SandBox_ViewModelCollection_Tournament_TournamentVM_Dependency_6_Tournament_Team__DependendPrefab(base.Context);
		_widget_0.AddChild(_widget_0_1);
		_widget_0_1.CreateWidgets();
		_widget_0_2 = new Tournament__SandBox_ViewModelCollection_Tournament_TournamentVM_Dependency_6_Tournament_Team__DependendPrefab(base.Context);
		_widget_0.AddChild(_widget_0_2);
		_widget_0_2.CreateWidgets();
		_widget_0_3 = new Tournament__SandBox_ViewModelCollection_Tournament_TournamentVM_Dependency_6_Tournament_Team__DependendPrefab(base.Context);
		_widget_0.AddChild(_widget_0_3);
		_widget_0_3.CreateWidgets();
	}

	public void SetIds()
	{
		_widget_0_0.SetIds();
		_widget_0_1.SetIds();
		_widget_0_2.SetIds();
		_widget_0_3.SetIds();
	}

	public void SetAttributes()
	{
		base.WidthSizePolicy = SizePolicy.StretchToParent;
		base.HeightSizePolicy = SizePolicy.CoverChildren;
		base.MarginTop = 13f;
		base.MarginBottom = 13f;
		base.MarginLeft = 4f;
		base.MarginRight = 4f;
		_widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_0.StackLayout.LayoutMethod = LayoutMethod.VerticalBottomToTop;
		_widget_0_0.SetAttributes();
		_widget_0_1.SetAttributes();
		_widget_0_2.SetAttributes();
		_widget_0_3.SetAttributes();
	}

	public void DestroyDataSource()
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.PropertyChanged -= PropertyChangedListenerOf_widget;
			_widget.boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			_widget.floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			_widget.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			_widget.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			_widget.doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			_widget.intPropertyChanged -= intPropertyChangedListenerOf_widget;
			_widget.uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			_widget.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			if (_datasource_Root_Team1 != null)
			{
				_widget_0_0.DestroyDataSource();
				_datasource_Root_Team1.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1 = null;
			}
			if (_datasource_Root_Team2 != null)
			{
				_widget_0_1.DestroyDataSource();
				_datasource_Root_Team2.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2 = null;
			}
			if (_datasource_Root_Team3 != null)
			{
				_widget_0_2.DestroyDataSource();
				_datasource_Root_Team3.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3 = null;
			}
			if (_datasource_Root_Team4 != null)
			{
				_widget_0_3.DestroyDataSource();
				_datasource_Root_Team4.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4 = null;
			}
			_datasource_Root = null;
		}
	}

	public void SetDataSource(TournamentMatchVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsValid = _widget.IsVisible;
		}
		else if (propertyName == "State")
		{
			_datasource_Root.State = _widget.State;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		switch (propertyName)
		{
		case "Team1":
			RefreshDataSource_datasource_Root_Team1(_datasource_Root.Team1);
			break;
		case "Team2":
			RefreshDataSource_datasource_Root_Team2(_datasource_Root.Team2);
			break;
		case "Team3":
			RefreshDataSource_datasource_Root_Team3(_datasource_Root.Team3);
			break;
		case "Team4":
			RefreshDataSource_datasource_Root_Team4(_datasource_Root.Team4);
			break;
		case "IsValid":
			_widget.IsVisible = _datasource_Root.IsValid;
			break;
		case "State":
			_widget.State = _datasource_Root.State;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_Team1(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team1(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team1(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_Team1(string propertyName)
	{
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_Team2(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team2(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team2(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_Team2(string propertyName)
	{
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_Team3(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team3(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team3(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team3(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team3(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team3(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team3(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team3(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team3(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team3(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team3(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team3(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team3(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team3(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team3(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team3(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team3(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team3(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_Team3(string propertyName)
	{
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_Team4(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team4(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team4(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team4(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team4(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team4(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team4(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team4(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team4(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team4(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team4(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team4(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team4(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team4(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team4(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team4(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team4(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Team4(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_Team4(string propertyName)
	{
	}

	private void RefreshDataSource_datasource_Root(TournamentMatchVM newDataSource)
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.PropertyChanged -= PropertyChangedListenerOf_widget;
			_widget.boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			_widget.floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			_widget.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			_widget.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			_widget.doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			_widget.intPropertyChanged -= intPropertyChangedListenerOf_widget;
			_widget.uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			_widget.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			if (_datasource_Root_Team1 != null)
			{
				_widget_0_0.SetDataSource(null);
				_datasource_Root_Team1.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1 = null;
			}
			if (_datasource_Root_Team2 != null)
			{
				_widget_0_1.SetDataSource(null);
				_datasource_Root_Team2.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2 = null;
			}
			if (_datasource_Root_Team3 != null)
			{
				_widget_0_2.SetDataSource(null);
				_datasource_Root_Team3.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3 = null;
			}
			if (_datasource_Root_Team4 != null)
			{
				_widget_0_3.SetDataSource(null);
				_datasource_Root_Team4.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4 = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.IsVisible = _datasource_Root.IsValid;
			_widget.State = _datasource_Root.State;
			_widget.PropertyChanged += PropertyChangedListenerOf_widget;
			_widget.boolPropertyChanged += boolPropertyChangedListenerOf_widget;
			_widget.floatPropertyChanged += floatPropertyChangedListenerOf_widget;
			_widget.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget;
			_widget.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget;
			_widget.doublePropertyChanged += doublePropertyChangedListenerOf_widget;
			_widget.intPropertyChanged += intPropertyChangedListenerOf_widget;
			_widget.uintPropertyChanged += uintPropertyChangedListenerOf_widget;
			_widget.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget;
			_datasource_Root_Team1 = _datasource_Root.Team1;
			if (_datasource_Root_Team1 != null)
			{
				_datasource_Root_Team1.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team1;
				_datasource_Root_Team1.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team1;
				_widget_0_0.SetDataSource(_datasource_Root_Team1);
			}
			_datasource_Root_Team2 = _datasource_Root.Team2;
			if (_datasource_Root_Team2 != null)
			{
				_datasource_Root_Team2.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team2;
				_datasource_Root_Team2.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team2;
				_widget_0_1.SetDataSource(_datasource_Root_Team2);
			}
			_datasource_Root_Team3 = _datasource_Root.Team3;
			if (_datasource_Root_Team3 != null)
			{
				_datasource_Root_Team3.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team3;
				_datasource_Root_Team3.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team3;
				_widget_0_2.SetDataSource(_datasource_Root_Team3);
			}
			_datasource_Root_Team4 = _datasource_Root.Team4;
			if (_datasource_Root_Team4 != null)
			{
				_datasource_Root_Team4.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team4;
				_datasource_Root_Team4.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team4;
				_widget_0_3.SetDataSource(_datasource_Root_Team4);
			}
		}
	}

	private void RefreshDataSource_datasource_Root_Team1(TournamentTeamVM newDataSource)
	{
		if (_datasource_Root_Team1 != null)
		{
			_widget_0_0.SetDataSource(null);
			_datasource_Root_Team1.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1 = null;
		}
		_datasource_Root_Team1 = newDataSource;
		_datasource_Root_Team1 = _datasource_Root.Team1;
		if (_datasource_Root_Team1 != null)
		{
			_datasource_Root_Team1.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team1;
			_datasource_Root_Team1.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team1;
			_widget_0_0.SetDataSource(_datasource_Root_Team1);
		}
	}

	private void RefreshDataSource_datasource_Root_Team2(TournamentTeamVM newDataSource)
	{
		if (_datasource_Root_Team2 != null)
		{
			_widget_0_1.SetDataSource(null);
			_datasource_Root_Team2.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2 = null;
		}
		_datasource_Root_Team2 = newDataSource;
		_datasource_Root_Team2 = _datasource_Root.Team2;
		if (_datasource_Root_Team2 != null)
		{
			_datasource_Root_Team2.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team2;
			_datasource_Root_Team2.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team2;
			_widget_0_1.SetDataSource(_datasource_Root_Team2);
		}
	}

	private void RefreshDataSource_datasource_Root_Team3(TournamentTeamVM newDataSource)
	{
		if (_datasource_Root_Team3 != null)
		{
			_widget_0_2.SetDataSource(null);
			_datasource_Root_Team3.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3 = null;
		}
		_datasource_Root_Team3 = newDataSource;
		_datasource_Root_Team3 = _datasource_Root.Team3;
		if (_datasource_Root_Team3 != null)
		{
			_datasource_Root_Team3.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team3;
			_datasource_Root_Team3.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team3;
			_widget_0_2.SetDataSource(_datasource_Root_Team3);
		}
	}

	private void RefreshDataSource_datasource_Root_Team4(TournamentTeamVM newDataSource)
	{
		if (_datasource_Root_Team4 != null)
		{
			_widget_0_3.SetDataSource(null);
			_datasource_Root_Team4.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4 = null;
		}
		_datasource_Root_Team4 = newDataSource;
		_datasource_Root_Team4 = _datasource_Root.Team4;
		if (_datasource_Root_Team4 != null)
		{
			_datasource_Root_Team4.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Team4;
			_datasource_Root_Team4.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Team4;
			_widget_0_3.SetDataSource(_datasource_Root_Team4);
		}
	}
}
