using System;
using System.Collections.Generic;
using System.Linq;
using MCM.Common;
using TaleWorlds.Library;
using AnimusForge.SiegeAftermathIntervention;

namespace AnimusForge;

public enum TerminalSettingType
{
	Bool,
	Integer,
	FloatingInteger,
	Dropdown,
	Text,
	Button,
	Hotkey
}

public sealed class TerminalSettingDef
{
	public string Id { get; }
	public string TabCategory { get; }
	public string GroupName { get; }
	public string DisplayName { get; }
	public string HintText { get; }
	public TerminalSettingType SettingType { get; }
	public float MinValue { get; }
	public float MaxValue { get; }
	public float StepValue { get; }
	public string FormatString { get; }
	public Func<DuelSettings, object> Getter { get; }
	public Action<DuelSettings, object> Setter { get; }
	public Action<DuelSettings> Invoker { get; }
	public Func<DuelSettings, Dropdown<string>> DropdownGetter { get; }

	public TerminalSettingDef(
		string id,
		string tabCategory,
		string groupName,
		string displayName,
		string hintText,
		TerminalSettingType settingType,
		float minValue,
		float maxValue,
		float stepValue,
		string formatString,
		Func<DuelSettings, object> getter,
		Action<DuelSettings, object> setter,
		Action<DuelSettings> invoker = null,
		Func<DuelSettings, Dropdown<string>> dropdownGetter = null)
	{
		Id = id ?? "";
		TabCategory = tabCategory ?? "";
		GroupName = groupName ?? "";
		DisplayName = displayName ?? "";
		HintText = hintText ?? "";
		SettingType = settingType;
		MinValue = minValue;
		MaxValue = maxValue;
		StepValue = stepValue;
		FormatString = formatString ?? "";
		Getter = getter;
		Setter = setter;
		Invoker = invoker;
		DropdownGetter = dropdownGetter;
	}
}

public static class TerminalSettingsRegistry
{
	private static readonly List<TerminalSettingDef> _allDefinitions = new List<TerminalSettingDef>(260);
	private static readonly Dictionary<string, List<TerminalSettingDef>> _byCategory = new Dictionary<string, List<TerminalSettingDef>>(StringComparer.Ordinal);
	private static readonly Dictionary<string, TerminalSettingDef> _byId = new Dictionary<string, TerminalSettingDef>(StringComparer.Ordinal);
	private static bool _initialized;

	static TerminalSettingsRegistry()
	{
		EnsureInitialized();
	}

	public static void EnsureInitialized()
	{
		if (_initialized) return;
		_initialized = true;
		RegisterDefinitions();
		foreach (var def in _allDefinitions)
		{
			_byId[def.Id] = def;
			if (!_byCategory.TryGetValue(def.TabCategory, out var list))
			{
				list = new List<TerminalSettingDef>();
				_byCategory[def.TabCategory] = list;
			}
			list.Add(def);
		}
	}

	public static IReadOnlyList<TerminalSettingDef> AllDefinitions => _allDefinitions;

	public static List<TerminalSettingDef> GetByCategory(string category)
	{
		EnsureInitialized();
		if (string.IsNullOrEmpty(category) || category == "全部") return _allDefinitions.ToList();
		return _byCategory.TryGetValue(category, out var list) ? list.ToList() : new List<TerminalSettingDef>();
	}

	public static TerminalSettingDef GetById(string id)
	{
		EnsureInitialized();
		return id != null && _byId.TryGetValue(id, out var def) ? def : null;
	}

	public static bool SaveSettings()
	{
		return DuelSettings.SaveCurrentSettings();
	}

	private static void RegisterDefinitions()
	{
		_allDefinitions.Add(new TerminalSettingDef("ApiUrl", "AI核心", "1. AI 核心配置/1. 主API（正文生成）", "API 地址（支持填写 Base URL）", "请填写你的接口地址，例如: https://api.openai.com/v1 或 https://api.openai.com/v1/chat/completions\\n当你填写到 /v1 时，本模组会自动请求 /v1/chat/completions。", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.ApiUrl ?? "", (s, v) => s.ApiUrl = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("ApiKey", "AI核心", "1. AI 核心配置/1. 主API（正文生成）", "API 密钥 (Key)", "填入你的 API 密钥", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.ApiKey ?? "", (s, v) => s.ApiKey = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("ModelName", "AI核心", "1. AI 核心配置/1. 主API（正文生成）", "模型名称", "例如: gpt-4o-mini。请填写你当前接口实际支持的模型名。", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.ModelName ?? "", (s, v) => s.ModelName = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("FetchMainModelList", "AI核心", "1. AI 核心配置/1. 主API（正文生成）", "拉取模型列表", "", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.FetchMainModelList?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("MainModelDropdown", "AI核心", "1. AI 核心配置/1. 主API（正文生成）", "模型名称（下拉）", "请先点击“拉取模型列表”，然后从下拉中选择模型。若选择“*手动填写*”，则使用上方文本框中的模型名。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.MainModelDropdown?.SelectedValue ?? "", (s, v) => { if (s.MainModelDropdown != null && v is int idx && idx >= 0 && idx < s.MainModelDropdown.Count) { var dd = s.MainModelDropdown; dd.SelectedIndex = idx; s.MainModelDropdown = dd; } }, null, s => s.MainModelDropdown));
		_allDefinitions.Add(new TerminalSettingDef("TestConnection", "AI核心", "1. AI 核心配置/1. 主API（正文生成）", "测试 API 连接", "", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.TestConnection?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("MainApiThinkingEnabled", "AI核心", "1. AI 核心配置/1. 主API（正文生成）", "开启思维链", "开启后，对 OpenAI 兼容思考接口写入 thinking.type=enabled，并写入 reasoning_effort；Anthropic/Claude 接口写入 thinking.type=enabled 与 output_config.effort。关闭后写入 thinking.type=disabled。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.MainApiThinkingEnabled, (s, v) => s.MainApiThinkingEnabled = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("MainApiReasoningEffortDropdown", "AI核心", "1. AI 核心配置/1. 主API（正文生成）", "思维链强度", "支持 minimal/low/medium/high/xhigh/max。关闭“开启思维链”即可关闭思考；YJ Gemini 使用原值发送。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.MainApiReasoningEffortDropdown?.SelectedValue ?? "", (s, v) => { if (s.MainApiReasoningEffortDropdown != null && v is int idx && idx >= 0 && idx < s.MainApiReasoningEffortDropdown.Count) { var dd = s.MainApiReasoningEffortDropdown; dd.SelectedIndex = idx; s.MainApiReasoningEffortDropdown = dd; } }, null, s => s.MainApiReasoningEffortDropdown));
		_allDefinitions.Add(new TerminalSettingDef("MainApiTemperature", "AI核心", "1. AI 核心配置/1. 主API（正文生成）", "温度", "控制正文生成随机性。0 更稳定，2 更发散。默认 0.80。", TerminalSettingType.FloatingInteger, 0f, 2f, 0.05f, "0.00", s => s.MainApiTemperature, (s, v) => s.MainApiTemperature = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("MainApiMaxTokens", "AI核心", "1. AI 核心配置/1. 主API（正文生成）", "最大输出Tokens", "主API正文生成调用的 max_tokens。默认 12000；如果接口不支持过高上限，可能会被接口拒绝。", TerminalSettingType.Integer, 512f, 64000f, 1f, "0", s => s.MainApiMaxTokens, (s, v) => s.MainApiMaxTokens = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("AuxiliaryApiUrl", "AI核心", "1. AI 核心配置/2. 前处理API（规则检索与简易对话链路）", "辅助API 地址（支持填写 Base URL）", "用于规则检索、规则路由与简易场景对话链路的低成本接口地址，例如: https://api.openai.com/v1。填写到 /v1 时会自动补全为 /v1/chat/completions。", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.AuxiliaryApiUrl ?? "", (s, v) => s.AuxiliaryApiUrl = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("AuxiliaryApiKey", "AI核心", "1. AI 核心配置/2. 前处理API（规则检索与简易对话链路）", "辅助API 密钥 (Key)", "填入辅助API的密钥。", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.AuxiliaryApiKey ?? "", (s, v) => s.AuxiliaryApiKey = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("AuxiliaryModelName", "AI核心", "1. AI 核心配置/2. 前处理API（规则检索与简易对话链路）", "辅助模型名称", "用于规则检索、规则路由与简易场景对话链路的低成本模型名称。", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.AuxiliaryModelName ?? "", (s, v) => s.AuxiliaryModelName = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("FetchAuxiliaryModelList", "AI核心", "1. AI 核心配置/2. 前处理API（规则检索与简易对话链路）", "拉取模型列表", "", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.FetchAuxiliaryModelList?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("AuxiliaryModelDropdown", "AI核心", "1. AI 核心配置/2. 前处理API（规则检索与简易对话链路）", "辅助模型名称（下拉）", "请先点击“拉取模型列表”，然后从下拉中选择模型。若选择“*手动填写*”，则使用上方文本框中的模型名。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.AuxiliaryModelDropdown?.SelectedValue ?? "", (s, v) => { if (s.AuxiliaryModelDropdown != null && v is int idx && idx >= 0 && idx < s.AuxiliaryModelDropdown.Count) { var dd = s.AuxiliaryModelDropdown; dd.SelectedIndex = idx; s.AuxiliaryModelDropdown = dd; } }, null, s => s.AuxiliaryModelDropdown));
		_allDefinitions.Add(new TerminalSettingDef("TestAuxiliaryConnection", "AI核心", "1. AI 核心配置/2. 前处理API（规则检索与简易对话链路）", "测试辅助API连接", "", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.TestAuxiliaryConnection?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("AuxiliaryApiThinkingEnabled", "AI核心", "1. AI 核心配置/2. 前处理API（规则检索与简易对话链路）", "开启思维链", "开启后，对 OpenAI 兼容思考接口写入 thinking.type=enabled，并写入 reasoning_effort；Anthropic/Claude 接口写入 thinking.type=enabled 与 output_config.effort。关闭后写入 thinking.type=disabled。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.AuxiliaryApiThinkingEnabled, (s, v) => s.AuxiliaryApiThinkingEnabled = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("AuxiliaryApiReasoningEffortDropdown", "AI核心", "1. AI 核心配置/2. 前处理API（规则检索与简易对话链路）", "思维链强度", "支持 minimal/low/medium/high/xhigh/max。关闭“开启思维链”即可关闭思考；YJ Gemini 使用原值发送。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.AuxiliaryApiReasoningEffortDropdown?.SelectedValue ?? "", (s, v) => { if (s.AuxiliaryApiReasoningEffortDropdown != null && v is int idx && idx >= 0 && idx < s.AuxiliaryApiReasoningEffortDropdown.Count) { var dd = s.AuxiliaryApiReasoningEffortDropdown; dd.SelectedIndex = idx; s.AuxiliaryApiReasoningEffortDropdown = dd; } }, null, s => s.AuxiliaryApiReasoningEffortDropdown));
		_allDefinitions.Add(new TerminalSettingDef("AuxiliaryApiTemperature", "AI核心", "1. AI 核心配置/2. 前处理API（规则检索与简易对话链路）", "温度", "控制前处理、规则路由和简易对话链路的随机性。0 更稳定，2 更发散。默认 0.00。", TerminalSettingType.FloatingInteger, 0f, 2f, 0.05f, "0.00", s => s.AuxiliaryApiTemperature, (s, v) => s.AuxiliaryApiTemperature = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("AuxiliaryApiMaxTokens", "AI核心", "1. AI 核心配置/2. 前处理API（规则检索与简易对话链路）", "最大输出Tokens", "前处理API规则检索、规则路由与简易对话链路调用的 max_tokens。默认 12000；如果接口不支持过高上限，可能会被接口拒绝。", TerminalSettingType.Integer, 512f, 64000f, 1f, "0", s => s.AuxiliaryApiMaxTokens, (s, v) => s.AuxiliaryApiMaxTokens = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ActionPostprocessApiUrl", "AI核心", "1. AI 核心配置/3. 后处理API（动作标签与情绪标签判定）", "后处理API 地址（支持填写 Base URL）", "用于标签后处理的独立接口地址，例如: https://api.openai.com/v1。填写到 /v1 时会自动补全为 /v1/chat/completions。留空时将继续回退使用主API。", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.ActionPostprocessApiUrl ?? "", (s, v) => s.ActionPostprocessApiUrl = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("ActionPostprocessApiKey", "AI核心", "1. AI 核心配置/3. 后处理API（动作标签与情绪标签判定）", "后处理API 密钥 (Key)", "填入后处理API的密钥。留空时将继续回退使用主API。", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.ActionPostprocessApiKey ?? "", (s, v) => s.ActionPostprocessApiKey = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("ActionPostprocessModelName", "AI核心", "1. AI 核心配置/3. 后处理API（动作标签与情绪标签判定）", "后处理模型名称", "用于标签后处理的模型名称。留空时将继续回退使用主API。后处理建议优先使用带思考/推理能力的模型（例如 OpenAI 的推理模型）或更高级模型，以提升标签判定稳定性。", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.ActionPostprocessModelName ?? "", (s, v) => s.ActionPostprocessModelName = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("FetchActionPostprocessModelList", "AI核心", "1. AI 核心配置/3. 后处理API（动作标签与情绪标签判定）", "拉取模型列表", "", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.FetchActionPostprocessModelList?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("ActionPostprocessModelDropdown", "AI核心", "1. AI 核心配置/3. 后处理API（动作标签与情绪标签判定）", "后处理模型名称（下拉）", "请先点击“拉取模型列表”，然后从下拉中选择模型。若选择“*手动填写*”，则使用上方文本框中的模型名。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.ActionPostprocessModelDropdown?.SelectedValue ?? "", (s, v) => { if (s.ActionPostprocessModelDropdown != null && v is int idx && idx >= 0 && idx < s.ActionPostprocessModelDropdown.Count) { var dd = s.ActionPostprocessModelDropdown; dd.SelectedIndex = idx; s.ActionPostprocessModelDropdown = dd; } }, null, s => s.ActionPostprocessModelDropdown));
		_allDefinitions.Add(new TerminalSettingDef("TestActionPostprocessConnection", "AI核心", "1. AI 核心配置/3. 后处理API（动作标签与情绪标签判定）", "测试后处理API连接", "", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.TestActionPostprocessConnection?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("ActionPostprocessApiThinkingEnabled", "AI核心", "1. AI 核心配置/3. 后处理API（动作标签与情绪标签判定）", "开启思维链", "开启后，对 OpenAI 兼容思考接口写入 thinking.type=enabled，并写入 reasoning_effort；Anthropic/Claude 接口写入 thinking.type=enabled 与 output_config.effort。关闭后写入 thinking.type=disabled。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.ActionPostprocessApiThinkingEnabled, (s, v) => s.ActionPostprocessApiThinkingEnabled = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("ActionPostprocessApiReasoningEffortDropdown", "AI核心", "1. AI 核心配置/3. 后处理API（动作标签与情绪标签判定）", "思维链强度", "支持 minimal/low/medium/high/xhigh/max。关闭“开启思维链”即可关闭思考；YJ Gemini 使用原值发送。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.ActionPostprocessApiReasoningEffortDropdown?.SelectedValue ?? "", (s, v) => { if (s.ActionPostprocessApiReasoningEffortDropdown != null && v is int idx && idx >= 0 && idx < s.ActionPostprocessApiReasoningEffortDropdown.Count) { var dd = s.ActionPostprocessApiReasoningEffortDropdown; dd.SelectedIndex = idx; s.ActionPostprocessApiReasoningEffortDropdown = dd; } }, null, s => s.ActionPostprocessApiReasoningEffortDropdown));
		_allDefinitions.Add(new TerminalSettingDef("ActionPostprocessApiTemperature", "AI核心", "1. AI 核心配置/3. 后处理API（动作标签与情绪标签判定）", "温度", "控制动作标签与情绪标签判定的随机性。建议保持较低。默认 0.00。", TerminalSettingType.FloatingInteger, 0f, 2f, 0.05f, "0.00", s => s.ActionPostprocessApiTemperature, (s, v) => s.ActionPostprocessApiTemperature = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("ActionPostprocessApiMaxTokens", "AI核心", "1. AI 核心配置/3. 后处理API（动作标签与情绪标签判定）", "最大输出Tokens", "后处理API动作标签与情绪标签判定调用的 max_tokens。默认 12000；如果接口不支持过高上限，可能会被接口拒绝。", TerminalSettingType.Integer, 512f, 64000f, 1f, "0", s => s.ActionPostprocessApiMaxTokens, (s, v) => s.ActionPostprocessApiMaxTokens = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ActionPostprocessHistoryEntryLimit", "AI核心", "1. AI 核心配置/3. 后处理API（动作标签与情绪标签判定）", "后处理历史条数上限", "控制动作后处理 <history> 最多携带多少条历史。本轮 <latest_reply> 独立保留，不占此额度。默认 100，最低 1，最高 100；数值越高，单次请求 token 与等待时间通常越高。", TerminalSettingType.Integer, 1f, 100f, 1f, "0", s => s.ActionPostprocessHistoryEntryLimit, (s, v) => s.ActionPostprocessHistoryEntryLimit = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("EventAndRebellionApiUrl", "AI核心", "1. AI 核心配置/4. 事件与王国叛乱API（周报生成与叛乱命名）", "事件/叛乱API 地址（支持填写 Base URL）", "用于事件系统周报与王国叛乱命名的独立接口地址，例如: https://api.openai.com/v1。填写到 /v1 时会自动补全为 /v1/chat/completions。留空时将继续回退使用主API。", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.EventAndRebellionApiUrl ?? "", (s, v) => s.EventAndRebellionApiUrl = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("EventAndRebellionApiKey", "AI核心", "1. AI 核心配置/4. 事件与王国叛乱API（周报生成与叛乱命名）", "事件/叛乱API 密钥 (Key)", "填入事件/叛乱专用API的密钥。留空时将继续回退使用主API。", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.EventAndRebellionApiKey ?? "", (s, v) => s.EventAndRebellionApiKey = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("EventAndRebellionModelName", "AI核心", "1. AI 核心配置/4. 事件与王国叛乱API（周报生成与叛乱命名）", "事件/叛乱模型名称", "用于事件周报与王国叛乱命名的模型名称。留空时将继续回退使用主API。", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.EventAndRebellionModelName ?? "", (s, v) => s.EventAndRebellionModelName = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("FetchEventAndRebellionModelList", "AI核心", "1. AI 核心配置/4. 事件与王国叛乱API（周报生成与叛乱命名）", "拉取模型列表", "", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.FetchEventAndRebellionModelList?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("EventAndRebellionModelDropdown", "AI核心", "1. AI 核心配置/4. 事件与王国叛乱API（周报生成与叛乱命名）", "事件/叛乱模型名称（下拉）", "请先点击“拉取模型列表”，然后从下拉中选择模型。若选择“*手动填写*”，则使用上方文本框中的模型名。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.EventAndRebellionModelDropdown?.SelectedValue ?? "", (s, v) => { if (s.EventAndRebellionModelDropdown != null && v is int idx && idx >= 0 && idx < s.EventAndRebellionModelDropdown.Count) { var dd = s.EventAndRebellionModelDropdown; dd.SelectedIndex = idx; s.EventAndRebellionModelDropdown = dd; } }, null, s => s.EventAndRebellionModelDropdown));
		_allDefinitions.Add(new TerminalSettingDef("TestEventAndRebellionConnection", "AI核心", "1. AI 核心配置/4. 事件与王国叛乱API（周报生成与叛乱命名）", "测试事件/叛乱API连接", "", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.TestEventAndRebellionConnection?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("EventAndRebellionApiThinkingEnabled", "AI核心", "1. AI 核心配置/4. 事件与王国叛乱API（周报生成与叛乱命名）", "开启思维链", "默认关闭。事件周报与王国叛乱命名是严格格式任务，建议只在确认接口会把最终答案稳定写入 content 时开启。开启后，对 OpenAI 兼容思考接口写入 thinking.type=enabled，并写入 reasoning_effort；Anthropic/Claude 接口写入 thinking.type=enabled 与 output_config.effort。关闭后写入 thinking.type=disabled。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EventAndRebellionApiThinkingEnabled, (s, v) => s.EventAndRebellionApiThinkingEnabled = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EventAndRebellionApiReasoningEffortDropdown", "AI核心", "1. AI 核心配置/4. 事件与王国叛乱API（周报生成与叛乱命名）", "思维链强度", "支持 minimal/low/medium/high/xhigh/max。关闭“开启思维链”即可关闭思考；YJ Gemini 使用原值发送。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.EventAndRebellionApiReasoningEffortDropdown?.SelectedValue ?? "", (s, v) => { if (s.EventAndRebellionApiReasoningEffortDropdown != null && v is int idx && idx >= 0 && idx < s.EventAndRebellionApiReasoningEffortDropdown.Count) { var dd = s.EventAndRebellionApiReasoningEffortDropdown; dd.SelectedIndex = idx; s.EventAndRebellionApiReasoningEffortDropdown = dd; } }, null, s => s.EventAndRebellionApiReasoningEffortDropdown));
		_allDefinitions.Add(new TerminalSettingDef("EventAndRebellionApiTemperature", "AI核心", "1. AI 核心配置/4. 事件与王国叛乱API（周报生成与叛乱命名）", "温度", "控制事件周报与王国叛乱命名的随机性。0 更稳定，2 更发散。默认 0.80。", TerminalSettingType.FloatingInteger, 0f, 2f, 0.05f, "0.00", s => s.EventAndRebellionApiTemperature, (s, v) => s.EventAndRebellionApiTemperature = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("EventAndRebellionApiMaxTokens", "AI核心", "1. AI 核心配置/4. 事件与王国叛乱API（周报生成与叛乱命名）", "最大输出Tokens", "事件周报、王国叛乱建国命名与统治者政策生成调用的 max_tokens。默认 12000；如果接口不支持过高上限，可能会被接口拒绝。", TerminalSettingType.Integer, 512f, 64000f, 1f, "0", s => s.EventAndRebellionApiMaxTokens, (s, v) => s.EventAndRebellionApiMaxTokens = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("GuardrailDirectTopN", "AI核心", "6. 规则触发（返回）", "规则返回上限", "控制每次对话最多向 AI 提供多少条附加规则。系统会自动推导召回和精排数量；若实际高相关规则不足，不会为了凑数硬塞。默认 4。", TerminalSettingType.Integer, 1f, 12f, 1f, "0", s => s.GuardrailDirectTopN, (s, v) => s.GuardrailDirectTopN = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("KnowledgeDirectTopN", "AI核心", "5. 知识检索（返回）", "知识返回上限", "控制每次对话最多向 AI 提供多少条相关知识。系统按重要性顺序取最靠前的同等数量名词，每个名词独立占一个知识槽；若最高分知识已被前面的名词占用，则顺延到第一条未占用知识。只有上限大于名词数时，才额外补充各名词的后续结果。默认 4。", TerminalSettingType.Integer, 1f, 12f, 1f, "0", s => s.KnowledgeDirectTopN, (s, v) => s.KnowledgeDirectTopN = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WorldEntityInjectMaxCount", "AI核心", "5. 知识检索（返回）", "实体注入上限", "控制每次对话最多向 AI 注入多少个人物、地点、家族和王国检索结果。系统按前处理的重要性顺序让每个名词先占一个最高分实体槽；重名人物会优先采用其他名词明确限定的家族、其次采用王国，再按其与当前聊天 NPC 的实际大地图距离获得最高 0.15 的微量加分，最终分允许超过 1.00；范围或位置不可用时回退原始得分。若最高分实体已被前面的名词占用，则顺延到第一条未占用实体。只有上限大于名词数时才补次要结果：先为最靠前名词补最多 3 条，再依次处理后续名词。默认 6。", TerminalSettingType.Integer, 1f, 20f, 1f, "0", s => s.WorldEntityInjectMaxCount, (s, v) => s.WorldEntityInjectMaxCount = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("PromptListCandidateMaxCount", "AI核心", "5. 知识检索（返回）", "清单候选显示上限", "控制每类物品、装备、部队、俘虏、固定资产和政策候选向 AI 注入多少条；候选足够时会补满到该数量，候选不足则显示全部。默认 10；不影响人物、地点、家族、王国的实体注入上限。", TerminalSettingType.Integer, 1f, 30f, 1f, "0", s => s.PromptListCandidateMaxCount, (s, v) => s.PromptListCandidateMaxCount = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("DailyConversationHistoryLineLimit", "AI核心", "5. 压缩记忆", "日内聊天上下文条数", "控制信使、自由对话和场景喊话每次请求最多直接携带多少条尚未日结压缩的普通聊天历史。AFEF 事实不占此额度；不会限制玩家继续聊天，也不会删除每日原始记忆。数值越高，单次请求 token 与等待时间通常越高。默认 100，最低 10，最高 500。", TerminalSettingType.Integer, 10f, 500f, 1f, "0", s => s.DailyConversationHistoryLineLimit, (s, v) => s.DailyConversationHistoryLineLimit = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("MemoryCompressionDenominator", "AI核心", "5. 压缩记忆", "记忆压缩比例分母", "日结摘要目标字数为当天有效对话总字数的 1/N，默认 5。AFEF 行不计入总字数且不会被压缩；摘要最少 80 字。", TerminalSettingType.Integer, 3f, 10f, 1f, "0", s => s.MemoryCompressionDenominator, (s, v) => s.MemoryCompressionDenominator = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("MemorySummaryRequestsPerMinute", "AI核心", "5. 压缩记忆", "记忆总结 RPM", "跨天后每分钟最多并发总结多少个 NPC/日记忆。默认 3，最高 20。", TerminalSettingType.Integer, 1f, 20f, 1f, "0", s => s.MemorySummaryRequestsPerMinute, (s, v) => s.MemorySummaryRequestsPerMinute = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("MemoryCandidateLimit", "AI核心", "5. 压缩记忆", "记忆候选上限", "进入前处理的压缩记忆候选块数量。默认 20；15-20 通常最合适。超过该数量时使用富标题语义检索。", TerminalSettingType.Integer, 5f, 40f, 1f, "0", s => s.MemoryCandidateLimit, (s, v) => s.MemoryCandidateLimit = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("MemoryFinalInjectCount", "AI核心", "5. 压缩记忆", "最终注入记忆数", "主链路最终注入的压缩记忆块数量。默认 4；运行时不会超过“记忆候选上限”。", TerminalSettingType.Integer, 2f, 20f, 1f, "0", s => s.MemoryFinalInjectCount, (s, v) => s.MemoryFinalInjectCount = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("MemoryPreprocessMode", "AI核心", "5. 压缩记忆", "前处理模式", "1=同体模式：规则 Code 与记忆编号放进同一个前处理 JSON 请求；2=并发模式：规则筛选与记忆筛选同时请求，全部成功解析后进入主链路。默认 1。", TerminalSettingType.Integer, 1f, 2f, 1f, "0", s => s.MemoryPreprocessMode, (s, v) => s.MemoryPreprocessMode = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("MemoryOverviewStartBlockCount", "AI核心", "5. 压缩记忆", "记忆大总结启动块数", "当某个 Hero NPC 的压缩记忆块达到该数量后，后台生成并滚动更新“过往记忆总览”。默认 5。", TerminalSettingType.Integer, 3f, 10f, 1f, "0", s => s.MemoryOverviewStartBlockCount, (s, v) => s.MemoryOverviewStartBlockCount = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("MemoryOverviewTargetChars", "AI核心", "5. 压缩记忆", "记忆大总结目标字数", "控制“过往记忆总览”的目标中文字符数。默认 200；越短越省 token，越长越保留细节。", TerminalSettingType.Integer, 100f, 1000f, 1f, "0", s => s.MemoryOverviewTargetChars, (s, v) => s.MemoryOverviewTargetChars = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableTtsSpeech", "AI核心", "7. 火山引擎 TTS（专用）", "启用TTS语音", "总开关。关闭后，NPC 不再播放 TTS 语音，并回退到纯文本气泡显示。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableTtsSpeech, (s, v) => s.EnableTtsSpeech = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("TtsVolcDedicatedEnabled", "AI核心", "7. 火山引擎 TTS（专用）", "启用火山专用模式", "开启后，TTS 请求将走火山 V1 HTTP 非流式原生协议（Authorization: Bearer;token + app/user/audio/request 结构）。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.TtsVolcDedicatedEnabled, (s, v) => s.TtsVolcDedicatedEnabled = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("TtsVolcDedicatedApiUrl", "AI核心", "7. 火山引擎 TTS（专用）", "火山专用 API 地址", "V1 非流式地址: https://openspeech.bytedance.com/api/v1/tts", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.TtsVolcDedicatedApiUrl ?? "", (s, v) => s.TtsVolcDedicatedApiUrl = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("TtsVolcDedicatedApiKey", "AI核心", "7. 火山引擎 TTS（专用）", "火山专用 Token (Authorization Bearer)", "请求头将按文档写入：Authorization: Bearer;{token}", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.TtsVolcDedicatedApiKey ?? "", (s, v) => s.TtsVolcDedicatedApiKey = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("TtsVolcDedicatedAppKey", "AI核心", "7. 火山引擎 TTS（专用）", "火山专用 AppID", "即 V1 请求体 app.appid。", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.TtsVolcDedicatedAppKey ?? "", (s, v) => s.TtsVolcDedicatedAppKey = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("TtsVolcDedicatedResourceId", "AI核心", "7. 火山引擎 TTS（专用）", "火山专用 Resource ID", "写入请求头 X-Api-Resource-Id。\\n可填：seed-tts-1.0 / seed-tts-1.0-concurr / seed-tts-2.0 / seed-icl-1.0 / seed-icl-1.0-concurr / seed-icl-2.0", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.TtsVolcDedicatedResourceId ?? "", (s, v) => s.TtsVolcDedicatedResourceId = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("TtsVolcDedicatedSpeaker", "AI核心", "7. 火山引擎 TTS（专用）", "火山专用 voice_type", "示例: zh_male_M392_conversation_wvae_bigtts", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.TtsVolcDedicatedSpeaker ?? "", (s, v) => s.TtsVolcDedicatedSpeaker = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("TtsVolcDedicatedAdditionsJson", "AI核心", "7. 火山引擎 TTS（专用）", "火山专用 extra_param(JSON对象)", "将原样写入 request.extra_param（字符串）。示例：{\\", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.TtsVolcDedicatedAdditionsJson ?? "", (s, v) => s.TtsVolcDedicatedAdditionsJson = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("TtsVolcDedicatedAudioFormat", "AI核心", "7. 火山引擎 TTS（专用）", "火山专用音频格式", "V1 encoding，当前播放器仅支持 wav 或 pcm。", TerminalSettingType.Text, 0f, 0f, 0f, "", s => s.TtsVolcDedicatedAudioFormat ?? "", (s, v) => s.TtsVolcDedicatedAudioFormat = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("TtsVolcDedicatedSampleRate", "AI核心", "7. 火山引擎 TTS（专用）", "火山专用采样率", "V1 rate 建议填 8000 / 16000 / 24000。", TerminalSettingType.Integer, 8000f, 24000f, 1f, "0", s => s.TtsVolcDedicatedSampleRate, (s, v) => s.TtsVolcDedicatedSampleRate = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("TtsVolcDedicatedVolume", "AI核心", "7. 火山引擎 TTS（专用）", "主语音音量(winmm)", "仅用于普通对话/测试语音（agentIndex<0）的主播放链路。场景喊话口型链路请调“口型链路音量”。", TerminalSettingType.FloatingInteger, 0f, 1f, 0.05f, "0.00", s => s.TtsVolcDedicatedVolume, (s, v) => s.TtsVolcDedicatedVolume = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("TtsVolcDedicatedSpeed", "AI核心", "7. 火山引擎 TTS（专用）", "火山专用语速", "V1 speed_ratio，范围 [0.1, 2.0]。", TerminalSettingType.FloatingInteger, 0.1f, 2f, 0.05f, "0.00", s => s.TtsVolcDedicatedSpeed, (s, v) => s.TtsVolcDedicatedSpeed = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("TtsSceneUseWinmmAudible", "AI核心", "7. 火山引擎 TTS（专用）", "场景发声走winmm(防回声)", "开启：场景NPC由winmm发声，口型链路仅驱动嘴型并静音。关闭：场景NPC改由口型链路发声，可调“口型链路音量”。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.TtsSceneUseWinmmAudible, (s, v) => s.TtsSceneUseWinmmAudible = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("TtsLipSyncSoundEventVolume", "AI核心", "7. 火山引擎 TTS（专用）", "口型链路音量", "用于 Rhubarb 口型驱动的 SoundEvent 音量。仅当“场景发声走winmm(防回声)”关闭时作为场景可听音量。", TerminalSettingType.FloatingInteger, 0f, 1f, 0.05f, "0.00", s => s.TtsLipSyncSoundEventVolume, (s, v) => s.TtsLipSyncSoundEventVolume = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("TestTtsVolcDedicatedVoice", "AI核心", "7. 火山引擎 TTS（专用）", "测试语音", "使用火山 V1 原生参数测试固定文本「为您服务，旅行者！」", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.TestTtsVolcDedicatedVoice?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("EnableDeepTrace", "AI核心", "4. 开发者选项", "【开发者】开启全代码截获", "⚠\\ufe0f 极其硬核的调试功能！\\n开启后将截获所有 UI 点击、状态切换和底层代码堆栈(Trace)。\\n日志量极大，仅供开发者排查问题使用。普通玩家请勿开启！", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableDeepTrace, (s, v) => s.EnableDeepTrace = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableDevEditHistory", "AI核心", "4. 开发者选项", "【开发者】启用数据管理（对话历史/赊账/个性/玩家履历）", "开启后，城镇主菜单中会出现【开发】数据管理入口，用于查看和修改任意 NPC 的历史对话记录、赊账/欠款、个性背景等数据；角色(C)中的玩家知名度/履历弹窗也会开放玩家履历编辑。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableDevEditHistory, (s, v) => s.EnableDevEditHistory = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableAdultHeroPersonaAutoGeneration", "AI核心", "4. 开发者选项", "新成年人物自动生成个性与背景", "开启后，当英雄子女成年时，自动使用前处理API为其生成个性与历史背景。已有个性或背景不会被覆盖。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableAdultHeroPersonaAutoGeneration, (s, v) => s.EnableAdultHeroPersonaAutoGeneration = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableModLogicLog", "AI核心", "4. 开发者选项", "【日志】写入 Mod_Logic.txt", "总逻辑日志开关。关闭后不再写入 Mod_Logic.txt。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableModLogicLog, (s, v) => s.EnableModLogicLog = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableVerboseModLogicLog", "AI核心", "4. 开发者选项", "【日志】写入详细调试日志", "只在排查问题时开启。开启后会写入更细的 Mod_Logic 诊断日志；大型剧本大地图可能产生较多日志。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableVerboseModLogicLog, (s, v) => s.EnableVerboseModLogicLog = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableObservabilityLog", "AI核心", "4. 开发者选项", "【日志】写入 Observability.jsonl", "结构化观测日志开关。关闭后不再写入 Observability.jsonl。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableObservabilityLog, (s, v) => s.EnableObservabilityLog = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableHitRateStatsLog", "AI核心", "4. 开发者选项", "【日志】写入 HitRate_Stats.txt", "命中率统计日志开关。关闭后不再写入 HitRate_Stats.txt。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableHitRateStatsLog, (s, v) => s.EnableHitRateStatsLog = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableTokenStatsLog", "AI核心", "4. 开发者选项", "【日志】写入 Token_Stats.txt", "Token 统计日志开关。关闭后不再写入 Token_Stats.txt。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableTokenStatsLog, (s, v) => s.EnableTokenStatsLog = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableEventLogs", "AI核心", "4. 开发者选项", "【日志】写入 Event_Logs.txt", "事件系统周报生成日志开关。关闭后不再写入 Event_Logs.txt。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableEventLogs, (s, v) => s.EnableEventLogs = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnablePerformanceMonitor", "AI核心", "4. 开发者选项", "【性能】启用性能监控", "开启后每30秒向 Mod_Logic.txt 写入 FPS、慢帧和帧总耗时。只有同时开启详细调试日志时才采集各 Tick/Scope 耗时；普通游玩不承担逐 Scope 统计成本。默认关闭。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnablePerformanceMonitor, (s, v) => s.EnablePerformanceMonitor = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableDeferredDailyMaintenance", "AI核心", "4. 开发者选项", "【性能】延后日结维护", "开启后，每日结算只登记 AnimusForge 维护任务，记忆总览、王国维护和周报准备会在后续大地图中按单帧预算分批执行。维护会在每个大地图 Tick 推进，不因行军暂停。默认开启。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableDeferredDailyMaintenance, (s, v) => s.EnableDeferredDailyMaintenance = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("DailyMaintenanceFrameBudgetMs", "AI核心", "4. 开发者选项", "【性能】日结维护每帧预算(ms)", "延后日结维护开启时，只有存在待办才按每帧预算推进；不会因玩家行军暂停。默认 3；调高会更快完成后台任务但更可能产生帧尖峰。", TerminalSettingType.Integer, 1f, 10f, 1f, "0", s => s.DailyMaintenanceFrameBudgetMs, (s, v) => s.DailyMaintenanceFrameBudgetMs = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableFreezeDumpCapture", "AI核心", "4. 开发者选项", "【诊断】AI聊天卡死时生成线程 Dump", "仅在 AnimusForge 自由对话的 AI 模式或场景喊话正在处理时，主线程连续 5 秒无心跳才生成紧凑线程 dump。普通对话、非 AI 游玩和原版保存期间自动停用。默认开启。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableFreezeDumpCapture, (s, v) => s.EnableFreezeDumpCapture = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("LogCleanupIntervalDropdown", "AI核心", "4. 开发者选项", "【日志】定时清理所有日志", "按真实时间定时清空 AnimusForge/Logs 下的所有当前日志文件。会保留文件本身与 UTF-8 BOM。默认每3天。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.LogCleanupIntervalDropdown?.SelectedValue ?? "", (s, v) => { if (s.LogCleanupIntervalDropdown != null && v is int idx && idx >= 0 && idx < s.LogCleanupIntervalDropdown.Count) { var dd = s.LogCleanupIntervalDropdown; dd.SelectedIndex = idx; s.LogCleanupIntervalDropdown = dd; } }, null, s => s.LogCleanupIntervalDropdown));
		_allDefinitions.Add(new TerminalSettingDef("OpenAfdianSupportLink", "AI核心", "0. 支持", "支持Animusforge制作组", "点击后会用系统默认浏览器打开爱发电页面。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.OpenAfdianSupportLink?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("ShoutKey", "场景互动", "3. 场景喊话", "喊话按键", "场景中按住此键预览并扩大喊话范围，松开后打开说话输入框。默认 T。", TerminalSettingType.Hotkey, 0f, 0f, 0f, "", s => s.ShoutKey ?? "", (s, v) => s.ShoutKey = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("ShoutSpecialMenuKey", "场景互动", "3. 场景喊话", "复杂交流按键", "场景中按住此键预览并扩大喊话范围，松开后打开复杂交流菜单。默认 Y。", TerminalSettingType.Hotkey, 0f, 0f, 0f, "", s => s.ShoutSpecialMenuKey ?? "", (s, v) => s.ShoutSpecialMenuKey = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("TerminalKey", "场景互动", "3. 场景喊话", "终端按键", "大地图上按此键打开 AnimusForge 终端。默认 U。", TerminalSettingType.Hotkey, 0f, 0f, 0f, "", s => s.TerminalKey ?? "", (s, v) => s.TerminalKey = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("SceneTauntGoldPickupKey", "场景互动", "3. 场景喊话", "倒地金币拾取键", "场景挑衅冲突中，NPC 倒地后靠近金币按此键拾取。默认 F。", TerminalSettingType.Hotkey, 0f, 0f, 0f, "", s => s.SceneTauntGoldPickupKey ?? "", (s, v) => s.SceneTauntGoldPickupKey = v?.ToString() ?? ""));
		_allDefinitions.Add(new TerminalSettingDef("ShoutInitialRangeMeters", "场景互动", "3. 场景喊话", "喊话起始范围(米)", "按下 T/Y 时使用的基础喊话范围。默认 4 米。", TerminalSettingType.FloatingInteger, 1f, 150f, 0.05f, "0.0", s => s.ShoutInitialRangeMeters, (s, v) => s.ShoutInitialRangeMeters = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("ShoutMaxRangeMeters", "场景互动", "3. 场景喊话", "喊话最大范围(米)", "按住 T/Y 时可扩大的最大喊话范围。上限 150 米。范围越大，预览标记越多。", TerminalSettingType.FloatingInteger, 1f, 150f, 0.05f, "0.0", s => s.ShoutMaxRangeMeters, (s, v) => s.ShoutMaxRangeMeters = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("ShoutMinTokens", "场景互动", "3. 场景喊话", "喊话回复最小字数", "场景喊话回复的最小字数。默认 40。", TerminalSettingType.Integer, 1f, 500f, 1f, "0", s => s.ShoutMinTokens, (s, v) => s.ShoutMinTokens = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ShoutMaxTokens", "场景互动", "3. 场景喊话", "喊话回复最大字数", "场景喊话回复的最大字数。默认 200；若小于最小字数，运行时会按最小字数处理。", TerminalSettingType.Integer, 1f, 500f, 1f, "0", s => s.ShoutMaxTokens, (s, v) => s.ShoutMaxTokens = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ShoutThoughtMinTokens", "场景互动", "3. 场景喊话", "内心思考最小字数", "场景喊话回复格式中，括号内心思考部分的最小字数。最低 40，默认 200。", TerminalSettingType.Integer, 40f, 2000f, 1f, "0", s => s.ShoutThoughtMinTokens, (s, v) => s.ShoutThoughtMinTokens = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("DisableShoutInnerThoughtPrompt", "场景互动", "3. 场景喊话", "关闭内心思考", "开启后，场景喊话请求体中不再要求输出“你的内心思考内容...”，只保留动作与实际发言格式。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.DisableShoutInnerThoughtPrompt, (s, v) => s.DisableShoutInnerThoughtPrompt = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("BubbleFontSize", "场景互动", "3. 场景喊话", "气泡字体大小", "设置场景喊话气泡中文字的字体大小", TerminalSettingType.Integer, 10f, 40f, 1f, "0", s => s.BubbleFontSize, (s, v) => s.BubbleFontSize = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("SceneConversationTimeoutSecondsPerVisibleCharacter", "场景互动", "3. 场景喊话", "对话超时每字秒数", "场景对话空闲解散时间按本轮玩家与 NPC 可见发言字数动态延长。默认每个字增加 1 秒。", TerminalSettingType.FloatingInteger, 0.5f, 3f, 0.05f, "0.0", s => s.SceneConversationTimeoutSecondsPerVisibleCharacter, (s, v) => s.SceneConversationTimeoutSecondsPerVisibleCharacter = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("PassiveStareTriggerSeconds", "场景互动", "3. 场景喊话", "盯着看触发时间(秒)", "玩家持续盯着同一个 NPC 多久后触发被动反应。默认 15 秒。", TerminalSettingType.Integer, 1f, 120f, 1f, "0", s => s.PassiveStareTriggerSeconds, (s, v) => s.PassiveStareTriggerSeconds = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnablePeaceSceneConflict", "场景互动", "3. 场景喊话", "允许玩家直接攻击触发场景冲突", "开启后，玩家直接攻击和平场景 NPC 可以触发本模组的场景冲突。关闭后，本模组不再把直接攻击转成场景冲突，伤害结算完全交回原版；对话中的吵架/挑衅仍然可以触发冲突升级。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnablePeaceSceneConflict, (s, v) => s.EnablePeaceSceneConflict = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("ShoutInputUiBackgroundDropdown", "场景互动", "3. 场景喊话", "喊话输入框底色", "只影响喊话输入框。默认黑色透明；也可选白色透明或粉色透明。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.ShoutInputUiBackgroundDropdown?.SelectedValue ?? "", (s, v) => { if (s.ShoutInputUiBackgroundDropdown != null && v is int idx && idx >= 0 && idx < s.ShoutInputUiBackgroundDropdown.Count) { var dd = s.ShoutInputUiBackgroundDropdown; dd.SelectedIndex = idx; s.ShoutInputUiBackgroundDropdown = dd; } }, null, s => s.ShoutInputUiBackgroundDropdown));
		_allDefinitions.Add(new TerminalSettingDef("MinimumClanTier", "决斗与部队", "2. 决斗规则", "最小家族等级", "", TerminalSettingType.Integer, 0f, 6f, 1f, "0", s => s.MinimumClanTier, (s, v) => s.MinimumClanTier = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("HealthThreshold", "决斗与部队", "2. 决斗规则", "战败血量阈值", "", TerminalSettingType.FloatingInteger, 0.1f, 0.5f, 0.1f, "#0%", s => s.HealthThreshold, (s, v) => s.HealthThreshold = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableDuelLoserClanRenownPenalty", "决斗与部队", "2. 决斗规则", "启用决斗家族声望转移", "正式决斗结算后，败者家族实际扣减多少声望，胜者家族就增加多少声望。双方同属一个家族，或任意一方没有家族时不结算。败者声望不会低于 0，也不会强制降低已经获得的家族等级。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableDuelLoserClanRenownPenalty, (s, v) => s.EnableDuelLoserClanRenownPenalty = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("DuelLoserClanRenownPenaltyMinimum", "决斗与部队", "2. 决斗规则", "声望最低扣减", "败者家族每次至少扣减的声望。默认 20；若家族剩余声望不足，则最多扣到 0。", TerminalSettingType.Integer, 0f, 1000f, 1f, "0", s => s.DuelLoserClanRenownPenaltyMinimum, (s, v) => s.DuelLoserClanRenownPenaltyMinimum = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("DuelLoserClanRenownPenaltyPercent", "决斗与部队", "2. 决斗规则", "按当前声望扣减（%）", "按败者家族结算前的当前声望计算比例扣减，并与最低扣减取较大值。默认 3%。", TerminalSettingType.Integer, 0f, 50f, 1f, "0", s => s.DuelLoserClanRenownPenaltyPercent, (s, v) => s.DuelLoserClanRenownPenaltyPercent = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("DuelLoserClanRenownPenaltyMaximum", "决斗与部队", "2. 决斗规则", "声望最高扣减", "单场决斗最多扣减的家族声望。默认 150；设为 0 表示不设上限。", TerminalSettingType.Integer, 0f, 5000f, 1f, "0", s => s.DuelLoserClanRenownPenaltyMaximum, (s, v) => s.DuelLoserClanRenownPenaltyMaximum = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableNpcBattleEquipmentRestore", "角色与同伴", "10. 物品与交易", "NPC 交出装备后自动补回", "开启后，NPC 因给予、交易或战后缴获失去已装备的装备时，满 3 天会恢复到原槽位；原槽位已有其他装备时不会覆盖。关闭后，NPC 仍可交出装备，但不会登记新的恢复任务，也不会执行已登记的恢复任务。重新开启后，已登记任务会继续处理。默认开启。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableNpcBattleEquipmentRestore, (s, v) => s.EnableNpcBattleEquipmentRestore = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableProactiveNpcRequests", "角色与同伴", "7. NPC主动接触", "启用 NPC 主动接触", "开启后，有明确需求的 NPC 队伍可以在大地图主动追上玩家并发起对话。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableProactiveNpcRequests, (s, v) => s.EnableProactiveNpcRequests = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestTestMode", "角色与同伴", "7. NPC主动接触", "测试模式", "开启后允许 Tier 0 玩家触发，并建议配合高概率、短冷却测试主动接触。正常游玩默认关闭。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.ProactiveNpcRequestTestMode, (s, v) => s.ProactiveNpcRequestTestMode = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestMinClanTier", "角色与同伴", "7. NPC主动接触", "最低家族等级", "测试模式关闭时生效；玩家家族等级低于该值则不会触发 NPC 主动接触。", TerminalSettingType.Integer, 0f, 6f, 1f, "0", s => s.ProactiveNpcRequestMinClanTier, (s, v) => s.ProactiveNpcRequestMinClanTier = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestChancePercent", "角色与同伴", "7. NPC主动接触", "每次扫描触发概率", "候选 NPC 的触发概率缩放值。正常游玩默认 35，测试时可拉到 100。", TerminalSettingType.Integer, 0f, 100f, 1f, "0", s => s.ProactiveNpcRequestChancePercent, (s, v) => s.ProactiveNpcRequestChancePercent = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestScanIntervalHours", "角色与同伴", "7. NPC主动接触", "扫描间隔(小时)", "每隔多少游戏小时扫描一次附近有需求的 NPC 队伍。正常游玩默认 6 小时。", TerminalSettingType.Integer, 1f, 24f, 1f, "0", s => s.ProactiveNpcRequestScanIntervalHours, (s, v) => s.ProactiveNpcRequestScanIntervalHours = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestGlobalCooldownHours", "角色与同伴", "7. NPC主动接触", "全局冷却(小时)", "任意一次主动接触启动后，多少小时内不再启动下一次。正常游玩默认 24 小时。", TerminalSettingType.Integer, 0f, 240f, 1f, "0", s => s.ProactiveNpcRequestGlobalCooldownHours, (s, v) => s.ProactiveNpcRequestGlobalCooldownHours = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestHeroCooldownDays", "角色与同伴", "7. NPC主动接触", "同 NPC 冷却(天)", "同一 NPC 主动接触玩家后，多少天内不会再次以同类需求来找玩家。正常游玩默认 14 天。", TerminalSettingType.Integer, 0f, 60f, 1f, "0", s => s.ProactiveNpcRequestHeroCooldownDays, (s, v) => s.ProactiveNpcRequestHeroCooldownDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestDistanceMultiplier", "角色与同伴", "7. NPC主动接触", "候选距离倍率", "候选 NPC 与玩家的最大距离为玩家视野范围乘以该倍率。正常游玩默认 1.0。", TerminalSettingType.FloatingInteger, 0.5f, 5f, 0.05f, "0.0", s => s.ProactiveNpcRequestDistanceMultiplier, (s, v) => s.ProactiveNpcRequestDistanceMultiplier = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestFoodDaysThreshold", "角色与同伴", "7. NPC主动接触", "缺粮阈值(天)", "NPC 队伍剩余粮食天数小于等于该值，或已经饥饿时，可以触发缺粮主动接触。正常游玩默认 2 天。", TerminalSettingType.Integer, 0f, 15f, 1f, "0", s => s.ProactiveNpcRequestFoodDaysThreshold, (s, v) => s.ProactiveNpcRequestFoodDaysThreshold = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestMoneyGoldThreshold", "角色与同伴", "7. NPC主动接触", "缺钱现金阈值", "NPC 领主可用现金低于该值时，可以触发缺钱主动接触。运行时不会低于原版队伍现金下限。默认 5000。", TerminalSettingType.Integer, 1f, 50000f, 1f, "0", s => s.ProactiveNpcRequestMoneyGoldThreshold, (s, v) => s.ProactiveNpcRequestMoneyGoldThreshold = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestMoneyWageDaysThreshold", "角色与同伴", "7. NPC主动接触", "缺钱军饷阈值(天)", "NPC 领主现金可支付军饷天数小于等于该值时，可以触发缺钱主动接触；0 表示只看现金阈值和未付军饷。正常游玩默认 2 天。", TerminalSettingType.Integer, 0f, 30f, 1f, "0", s => s.ProactiveNpcRequestMoneyWageDaysThreshold, (s, v) => s.ProactiveNpcRequestMoneyWageDaysThreshold = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestTroopRatioThresholdPercent", "角色与同伴", "7. NPC主动接触", "缺兵兵力比例阈值(%)", "NPC 领主当前人数低于队伍人数上限的该比例时，可以触发缺兵主动接触。正常游玩默认 45；测试时可调到 90 或 100。", TerminalSettingType.Integer, 1f, 100f, 1f, "0", s => s.ProactiveNpcRequestTroopRatioThresholdPercent, (s, v) => s.ProactiveNpcRequestTroopRatioThresholdPercent = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestPrisonerRatioThresholdPercent", "角色与同伴", "7. NPC主动接触", "俘虏容量阈值(%)", "NPC 领主当前俘虏数量达到俘虏上限的该比例时，可以触发俘虏过载或赎买主动接触。正常游玩默认 90；100 表示接近满员，超过 100 表示只在超载时触发。", TerminalSettingType.Integer, 1f, 150f, 1f, "0", s => s.ProactiveNpcRequestPrisonerRatioThresholdPercent, (s, v) => s.ProactiveNpcRequestPrisonerRatioThresholdPercent = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestLowMoraleThreshold", "角色与同伴", "7. NPC主动接触", "低士气阈值", "NPC 领主队伍士气低于或等于该值时，可以触发低士气主动接触；0 表示关闭该需求。正常游玩默认 35。", TerminalSettingType.Integer, 0f, 100f, 1f, "0", s => s.ProactiveNpcRequestLowMoraleThreshold, (s, v) => s.ProactiveNpcRequestLowMoraleThreshold = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestMountRatioThresholdPercent", "角色与同伴", "7. NPC主动接触", "缺马比例阈值(%)", "NPC 领主队伍坐骑数量低于队伍人数的该比例时，可以触发缺马/机动不足主动接触；0 表示关闭该需求。正常游玩默认 25。", TerminalSettingType.Integer, 0f, 100f, 1f, "0", s => s.ProactiveNpcRequestMountRatioThresholdPercent, (s, v) => s.ProactiveNpcRequestMountRatioThresholdPercent = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestOverburdenRatioThresholdPercent", "角色与同伴", "7. NPC主动接触", "负重压力阈值(%)", "NPC 领主队伍总负重达到库存容量的该比例时，可以触发负重压力主动接触。正常游玩默认 92。", TerminalSettingType.Integer, 50f, 150f, 1f, "0", s => s.ProactiveNpcRequestOverburdenRatioThresholdPercent, (s, v) => s.ProactiveNpcRequestOverburdenRatioThresholdPercent = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestClanGoldThreshold", "角色与同伴", "7. NPC主动接触", "家族金库阈值", "NPC 家族金库低于该值时，可以触发家族财政紧张主动接触；0 表示不看金库。正常游玩默认 15000。", TerminalSettingType.Integer, 0f, 200000f, 1f, "0", s => s.ProactiveNpcRequestClanGoldThreshold, (s, v) => s.ProactiveNpcRequestClanGoldThreshold = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestClanDebtThreshold", "角色与同伴", "7. NPC主动接触", "家族债务阈值", "NPC 家族欠王国债务高于该值时，可以触发家族财政紧张主动接触；0 表示不看债务。正常游玩默认 5000。", TerminalSettingType.Integer, 0f, 200000f, 1f, "0", s => s.ProactiveNpcRequestClanDebtThreshold, (s, v) => s.ProactiveNpcRequestClanDebtThreshold = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestMarriageAdultClanThreshold", "角色与同伴", "7. NPC主动接触", "联姻压力成人阈值", "NPC 家族成年核心成员数量小于或等于该值，且存在成年未婚家族成员时，可以触发继承/联姻压力主动接触。正常游玩默认 3。", TerminalSettingType.Integer, 1f, 12f, 1f, "0", s => s.ProactiveNpcRequestMarriageAdultClanThreshold, (s, v) => s.ProactiveNpcRequestMarriageAdultClanThreshold = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestFiefLoyaltyThreshold", "角色与同伴", "7. NPC主动接触", "封地忠诚阈值", "NPC 家族封地忠诚低于或等于该值时，可以触发封地治理焦虑主动接触；0 表示不看忠诚。正常游玩默认 35。", TerminalSettingType.Integer, 0f, 100f, 1f, "0", s => s.ProactiveNpcRequestFiefLoyaltyThreshold, (s, v) => s.ProactiveNpcRequestFiefLoyaltyThreshold = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestFiefSecurityThreshold", "角色与同伴", "7. NPC主动接触", "封地治安阈值", "NPC 家族封地治安低于或等于该值时，可以触发封地治理焦虑主动接触；0 表示不看治安。正常游玩默认 35。", TerminalSettingType.Integer, 0f, 100f, 1f, "0", s => s.ProactiveNpcRequestFiefSecurityThreshold, (s, v) => s.ProactiveNpcRequestFiefSecurityThreshold = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestFiefGarrisonThreshold", "角色与同伴", "7. NPC主动接触", "封地驻军阈值", "NPC 家族封地驻军低于或等于该值时，可以触发封地治理焦虑主动接触；0 表示不看驻军。正常游玩默认 80。", TerminalSettingType.Integer, 0f, 1000f, 1f, "0", s => s.ProactiveNpcRequestFiefGarrisonThreshold, (s, v) => s.ProactiveNpcRequestFiefGarrisonThreshold = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestIsolationInfluenceThreshold", "角色与同伴", "7. NPC主动接触", "孤立影响力阈值", "NPC 家族影响力低于或等于该值时，结合盟友数量可以触发缺少盟友主动接触；0 表示不看影响力。正常游玩默认 40。", TerminalSettingType.Integer, 0f, 500f, 1f, "0", s => s.ProactiveNpcRequestIsolationInfluenceThreshold, (s, v) => s.ProactiveNpcRequestIsolationInfluenceThreshold = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestIsolationMaxFriendlyClans", "角色与同伴", "7. NPC主动接触", "孤立友好家族上限", "同王国内与 NPC 家族关系达到 20 以上的友好家族数量小于或等于该值时，结合低影响力或敌对关系可以触发缺少盟友主动接触。正常游玩默认 1。", TerminalSettingType.Integer, 0f, 10f, 1f, "0", s => s.ProactiveNpcRequestIsolationMaxFriendlyClans, (s, v) => s.ProactiveNpcRequestIsolationMaxFriendlyClans = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcKnownMajorMultiplier", "角色与同伴", "7. NPC主动接触", "已知履历需求倍率", "NPC 已经知晓玩家重大履历时，需求驱动主动接触概率的倍率。默认 2.0。", TerminalSettingType.FloatingInteger, 1f, 5f, 0.05f, "0.0", s => s.ProactiveNpcKnownMajorMultiplier, (s, v) => s.ProactiveNpcKnownMajorMultiplier = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcNotorietyChanceMultiplier", "角色与同伴", "7. NPC主动接触", "知名度触发倍率", "玩家有效知名度转化为 NPC 主动接触额外概率的倍率。正常游玩默认 0.35。", TerminalSettingType.FloatingInteger, 0f, 3f, 0.05f, "0.0", s => s.ProactiveNpcNotorietyChanceMultiplier, (s, v) => s.ProactiveNpcNotorietyChanceMultiplier = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcMinNeedUrgency", "角色与同伴", "7. NPC主动接触", "最低需求紧急度", "NPC 主动接触必须达到的最低需求紧急度；测试模式下运行时按 0 处理。正常游玩默认 60。", TerminalSettingType.Integer, 0f, 100f, 1f, "0", s => s.ProactiveNpcMinNeedUrgency, (s, v) => s.ProactiveNpcMinNeedUrgency = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestTypeFatigueDays", "角色与同伴", "7. NPC主动接触", "请求类型疲劳(天)", "玩家收到某类主动请求后，该类型在多少游戏日内大幅降低触发概率；0 表示关闭类型疲劳。默认 10 天。", TerminalSettingType.Integer, 0f, 60f, 1f, "0", s => s.ProactiveNpcRequestTypeFatigueDays, (s, v) => s.ProactiveNpcRequestTypeFatigueDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestTypeFatigueMultiplier", "角色与同伴", "7. NPC主动接触", "疲劳类型概率倍率", "处于类型疲劳期的请求，其需求驱动和知名度驱动概率乘以该倍率，同时降低该需求在候选中的优先级。默认 0.20。", TerminalSettingType.FloatingInteger, 0f, 1f, 0.05f, "0.00", s => s.ProactiveNpcRequestTypeFatigueMultiplier, (s, v) => s.ProactiveNpcRequestTypeFatigueMultiplier = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestMountShortageWeight", "角色与同伴", "7. NPC主动接触", "缺马请求权重", "缺马/买马请求在地图主动接触和主动来信中的候选权重与触发概率倍率。默认 0.35；0 表示保留需求判定但不主动发起。测试模式下地图追踪仍按 1.00 计算。", TerminalSettingType.FloatingInteger, 0f, 1f, 0.05f, "0.00", s => s.ProactiveNpcRequestMountShortageWeight, (s, v) => s.ProactiveNpcRequestMountShortageWeight = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestRomanticInteractionGlobalCooldownDays", "角色与同伴", "7. NPC主动接触", "亲密互动全局冷却(天)", "异性且私人关系大于 30 的亲密互动，在地图追赶、主动来信和队内同伴聊天之间共享的硬冷却。默认 21 天。", TerminalSettingType.Integer, 1f, 120f, 1f, "0", s => s.ProactiveNpcRequestRomanticInteractionGlobalCooldownDays, (s, v) => s.ProactiveNpcRequestRomanticInteractionGlobalCooldownDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestGreetingGlobalCooldownDays", "角色与同伴", "7. NPC主动接触", "主动问候全局冷却(天)", "私人关系大于 20 的 NPC 主动追上玩家或主动来信问候后，共享的硬冷却。默认 42 天。", TerminalSettingType.Integer, 1f, 120f, 1f, "0", s => s.ProactiveNpcRequestGreetingGlobalCooldownDays, (s, v) => s.ProactiveNpcRequestGreetingGlobalCooldownDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestTerritorialInterrogationSettlementRangeMultiplier", "角色与同伴", "7. NPC主动接触", "领地盘问范围倍率", "玩家距某王国定居点不超过玩家视野乘该倍率时，该王国的异文化且未了解玩家履历的领主可主动盘问来历和目的。默认 3.0。", TerminalSettingType.FloatingInteger, 0.5f, 10f, 0.05f, "0.0", s => s.ProactiveNpcRequestTerritorialInterrogationSettlementRangeMultiplier, (s, v) => s.ProactiveNpcRequestTerritorialInterrogationSettlementRangeMultiplier = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("ProactiveNpcRequestTerritorialInterrogationGlobalCooldownDays", "角色与同伴", "7. NPC主动接触", "领地盘问全局冷却(天)", "领地盘问成功发起后共享的硬冷却。默认 42 天。", TerminalSettingType.Integer, 1f, 180f, 1f, "0", s => s.ProactiveNpcRequestTerritorialInterrogationGlobalCooldownDays, (s, v) => s.ProactiveNpcRequestTerritorialInterrogationGlobalCooldownDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableNpcInitiatedLetters", "角色与同伴", "7. NPC主动接触/NPC主动来信", "启用 NPC 主动来信", "允许已经认识玩家且具备足够亲密综合分的 NPC 主动派出真实信使。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableNpcInitiatedLetters, (s, v) => s.EnableNpcInitiatedLetters = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcInitiatedLetterTestMode", "角色与同伴", "7. NPC主动接触/NPC主动来信", "主动来信测试模式", "将触发概率提高到 100%，并取消主动来信冷却；仍要求 NPC 认识玩家、位置有效且动机真实。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.NpcInitiatedLetterTestMode, (s, v) => s.NpcInitiatedLetterTestMode = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcInitiatedLetterMinBondScore", "角色与同伴", "7. NPC主动接触/NPC主动来信", "最低亲密综合分", "私人关系与写信用信任值平均后的最低候选分。默认 10。", TerminalSettingType.Integer, 0f, 100f, 1f, "0", s => s.NpcInitiatedLetterMinBondScore, (s, v) => s.NpcInitiatedLetterMinBondScore = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcInitiatedLetterScanIntervalHours", "角色与同伴", "7. NPC主动接触/NPC主动来信", "扫描间隔(小时)", "每隔多少游戏小时扫描一次主动来信候选。默认 24 小时。", TerminalSettingType.Integer, 1f, 168f, 1f, "0", s => s.NpcInitiatedLetterScanIntervalHours, (s, v) => s.NpcInitiatedLetterScanIntervalHours = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcInitiatedLetterChanceMultiplier", "角色与同伴", "7. NPC主动接触/NPC主动来信", "写信概率倍率", "单次扫描概率=亲密综合分乘以该倍率。默认 0.25，即 100 分为 25%。", TerminalSettingType.FloatingInteger, 0f, 2f, 0.05f, "0.00", s => s.NpcInitiatedLetterChanceMultiplier, (s, v) => s.NpcInitiatedLetterChanceMultiplier = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcInitiatedLetterGlobalCooldownDays", "角色与同伴", "7. NPC主动接触/NPC主动来信", "全局冷却(天)", "任意 NPC 主动发信后，多少游戏日内不再启动下一封主动来信。默认 5 天。", TerminalSettingType.Integer, 0f, 60f, 1f, "0", s => s.NpcInitiatedLetterGlobalCooldownDays, (s, v) => s.NpcInitiatedLetterGlobalCooldownDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcInitiatedLetterLowScoreCooldownDays", "角色与同伴", "7. NPC主动接触/NPC主动来信", "低分 NPC 冷却(天)", "最低综合分 NPC 的发送者冷却。默认 45 天。", TerminalSettingType.Integer, 1f, 120f, 1f, "0", s => s.NpcInitiatedLetterLowScoreCooldownDays, (s, v) => s.NpcInitiatedLetterLowScoreCooldownDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcInitiatedLetterHighScoreCooldownDays", "角色与同伴", "7. NPC主动接触/NPC主动来信", "高分 NPC 冷却(天)", "100 综合分 NPC 的发送者冷却。默认 14 天。", TerminalSettingType.Integer, 1f, 60f, 1f, "0", s => s.NpcInitiatedLetterHighScoreCooldownDays, (s, v) => s.NpcInitiatedLetterHighScoreCooldownDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcInitiatedLetterQuietDays", "角色与同伴", "7. NPC主动接触/NPC主动来信", "最近交流静默期(天)", "任意渠道刚与该 NPC 交流后，至少等待多少游戏日再允许主动来信。默认 3 天。", TerminalSettingType.Integer, 0f, 30f, 1f, "0", s => s.NpcInitiatedLetterQuietDays, (s, v) => s.NpcInitiatedLetterQuietDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcInitiatedLetterPublicTrustCap", "角色与同伴", "7. NPC主动接触/NPC主动来信", "公共信任贡献上限", "公共信任对写信用信任值的正负贡献上限。默认 ±20。", TerminalSettingType.Integer, 0f, 100f, 1f, "0", s => s.NpcInitiatedLetterPublicTrustCap, (s, v) => s.NpcInitiatedLetterPublicTrustCap = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcInitiatedLetterMotiveFatigueDays", "角色与同伴", "7. NPC主动接触/NPC主动来信", "动机疲劳(天)", "同一 NPC 重复使用同类写信动机时降低权重的持续时间。默认 30 天。", TerminalSettingType.Integer, 0f, 120f, 1f, "0", s => s.NpcInitiatedLetterMotiveFatigueDays, (s, v) => s.NpcInitiatedLetterMotiveFatigueDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcInitiatedLetterMotiveFatigueMultiplier", "角色与同伴", "7. NPC主动接触/NPC主动来信", "疲劳动机权重倍率", "处于疲劳期的问候、近况、事件、情感、请求或外交动机权重倍率。默认 0.25。", TerminalSettingType.FloatingInteger, 0f, 1f, 0.05f, "0.00", s => s.NpcInitiatedLetterMotiveFatigueMultiplier, (s, v) => s.NpcInitiatedLetterMotiveFatigueMultiplier = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcInitiatedLetterTargetChars", "角色与同伴", "7. NPC主动接触/NPC主动来信", "主动来信目标字数", "NPC 主动来信正文的目标字数。默认 220 字。", TerminalSettingType.Integer, 80f, 1000f, 1f, "0", s => s.NpcInitiatedLetterTargetChars, (s, v) => s.NpcInitiatedLetterTargetChars = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcInitiatedLetterDebugLog", "角色与同伴", "7. NPC主动接触/NPC主动来信", "写入主动来信调试日志", "在 Mod_Logic.txt 中记录候选分数、概率、动机、冷却和跳过原因。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.NpcInitiatedLetterDebugLog, (s, v) => s.NpcInitiatedLetterDebugLog = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableCompanionProactiveChat", "角色与同伴", "7. NPC主动接触/队内同伴主动聊天", "启用队内 Hero 主动聊天", "允许玩家主队中的同伴、家人和其他 Hero 通过地图通知主动请求交谈。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableCompanionProactiveChat, (s, v) => s.EnableCompanionProactiveChat = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("CompanionProactiveChatTestMode", "角色与同伴", "7. NPC主动接触/队内同伴主动聊天", "队内主动聊天测试模式", "每游戏小时扫描、触发概率为 100% 且忽略冷却；仍要求 Hero 合法、玩家状态安全且存在有效动机。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.CompanionProactiveChatTestMode, (s, v) => s.CompanionProactiveChatTestMode = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("CompanionProactiveChatScanIntervalHours", "角色与同伴", "7. NPC主动接触/队内同伴主动聊天", "扫描间隔(小时)", "每隔多少游戏小时扫描一次队内 Hero。默认 24 小时。", TerminalSettingType.Integer, 1f, 168f, 1f, "0", s => s.CompanionProactiveChatScanIntervalHours, (s, v) => s.CompanionProactiveChatScanIntervalHours = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("CompanionProactiveChatGlobalCooldownDays", "角色与同伴", "7. NPC主动接触/队内同伴主动聊天", "全局冷却(天)", "生成一次队内主动聊天通知后，多少游戏日内不再生成下一条。默认 21 天。", TerminalSettingType.Integer, 0f, 120f, 1f, "0", s => s.CompanionProactiveChatGlobalCooldownDays, (s, v) => s.CompanionProactiveChatGlobalCooldownDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("CompanionProactiveChatHeroCooldownDays", "角色与同伴", "7. NPC主动接触/队内同伴主动聊天", "同 Hero 冷却(天)", "同一 Hero 主动请求交谈后，多少游戏日内不会再次发起。默认 48 天。", TerminalSettingType.Integer, 0f, 240f, 1f, "0", s => s.CompanionProactiveChatHeroCooldownDays, (s, v) => s.CompanionProactiveChatHeroCooldownDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("CompanionProactiveChatInteractionQuietDays", "角色与同伴", "7. NPC主动接触/队内同伴主动聊天", "任意交流静默期(天)", "任意渠道刚与该 Hero 交流后，至少等待多少游戏日再允许其主动聊天。默认 21 天。", TerminalSettingType.Integer, 0f, 120f, 1f, "0", s => s.CompanionProactiveChatInteractionQuietDays, (s, v) => s.CompanionProactiveChatInteractionQuietDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("CompanionProactiveChatNoticeLifetimeDays", "角色与同伴", "7. NPC主动接触/队内同伴主动聊天", "通知有效期(天)", "队内主动聊天通知可保留多少游戏日；过期视为婉拒。默认 3 天。", TerminalSettingType.Integer, 1f, 30f, 1f, "0", s => s.CompanionProactiveChatNoticeLifetimeDays, (s, v) => s.CompanionProactiveChatNoticeLifetimeDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("CompanionProactiveChatChanceMultiplier", "角色与同伴", "7. NPC主动接触/队内同伴主动聊天", "触发概率倍率", "队内主动聊天每日概率的总体倍率。默认 1.00。", TerminalSettingType.FloatingInteger, 0f, 5f, 0.05f, "0.00", s => s.CompanionProactiveChatChanceMultiplier, (s, v) => s.CompanionProactiveChatChanceMultiplier = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("CompanionProactiveChatMotiveFatigueDays", "角色与同伴", "7. NPC主动接触/队内同伴主动聊天", "动机疲劳(天)", "同类主动聊天动机被选中后降低权重的持续时间。默认 30 天。", TerminalSettingType.Integer, 0f, 120f, 1f, "0", s => s.CompanionProactiveChatMotiveFatigueDays, (s, v) => s.CompanionProactiveChatMotiveFatigueDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("CompanionProactiveChatMotiveFatigueMultiplier", "角色与同伴", "7. NPC主动接触/队内同伴主动聊天", "疲劳动机权重倍率", "处于疲劳期的动机候选权重倍率。默认 0.25。", TerminalSettingType.FloatingInteger, 0f, 1f, 0.05f, "0.00", s => s.CompanionProactiveChatMotiveFatigueMultiplier, (s, v) => s.CompanionProactiveChatMotiveFatigueMultiplier = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("CompanionProactiveChatRecentEventWindowDays", "角色与同伴", "7. NPC主动接触/队内同伴主动聊天", "近期事件窗口(天)", "Hero 或玩家近期真实事件可作为聊天动机的时间窗口。默认 10 天。", TerminalSettingType.Integer, 1f, 30f, 1f, "0", s => s.CompanionProactiveChatRecentEventWindowDays, (s, v) => s.CompanionProactiveChatRecentEventWindowDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("CompanionProactiveChatDebugLog", "角色与同伴", "7. NPC主动接触/队内同伴主动聊天", "写入队内主动聊天调试日志", "在 Mod_Logic.txt 中记录候选、概率、动机、冷却和通知状态。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.CompanionProactiveChatDebugLog, (s, v) => s.CompanionProactiveChatDebugLog = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("PlayerNotorietySummaryIntervalDays", "角色与同伴", "8. 玩家知名度", "玩家履历总结间隔(天)", "每隔多少游戏日尝试把玩家公开履历素材滚动总结一次。默认 3 天。", TerminalSettingType.Integer, 1f, 30f, 1f, "0", s => s.PlayerNotorietySummaryIntervalDays, (s, v) => s.PlayerNotorietySummaryIntervalDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("PlayerNotorietyMajorPromptChars", "角色与同伴", "8. 玩家知名度", "玩家履历字数", "玩家公开重大履历总结的目标字数和硬上限，也是NPC已知玩家重大履历时主链路注入的履历字数上限。AI 会整体重写旧摘要，而不是在末尾增量追加；未总结原始素材不会直接注入主链路。默认 300。", TerminalSettingType.Integer, 80f, 1000f, 1f, "0", s => s.PlayerNotorietyMajorPromptChars, (s, v) => s.PlayerNotorietyMajorPromptChars = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("PlayerNotorietyCourierRecentDistanceMultiplier", "角色与同伴", "8. 玩家知名度", "信使近期行动距离倍率", "玩家发信瞬间，目标 NPC 与玩家距离小于玩家视野范围乘以该倍率时，信使链路可让 NPC 知道玩家近期行动。默认 3.0。", TerminalSettingType.FloatingInteger, 0.5f, 10f, 0.05f, "0.0", s => s.PlayerNotorietyCourierRecentDistanceMultiplier, (s, v) => s.PlayerNotorietyCourierRecentDistanceMultiplier = Convert.ToSingle(v)));
		_allDefinitions.Add(new TerminalSettingDef("PlayerNotorietyDebugLogs", "角色与同伴", "8. 玩家知名度", "写入知名度调试日志", "开启后在 Mod_Logic.txt 中写入玩家知名度记录、知晓判定、总结与注入相关日志。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.PlayerNotorietyDebugLogs, (s, v) => s.PlayerNotorietyDebugLogs = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("MarriageCandidateMaxAge", "角色与同伴", "8. 婚姻规则", "可婚配最大年龄", "用于家族可婚配名单过滤。默认 55。", TerminalSettingType.Integer, 18f, 80f, 1f, "0", s => s.MarriageCandidateMaxAge, (s, v) => s.MarriageCandidateMaxAge = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("MarriageCandidateMaxAgeGap", "角色与同伴", "8. 婚姻规则", "与玩家最大年龄差", "用于家族可婚配名单过滤。默认 25。", TerminalSettingType.Integer, 0f, 60f, 1f, "0", s => s.MarriageCandidateMaxAgeGap, (s, v) => s.MarriageCandidateMaxAgeGap = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("MarriageRequireOppositeGender", "角色与同伴", "8. 婚姻规则", "婚配名单仅限异性（旧兼容）", "旧配置项保留用于兼容；当前婚姻机制允许同性婚配。默认关闭。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.MarriageRequireOppositeGender, (s, v) => s.MarriageRequireOppositeGender = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EditPlayerCustomPromptRule", "提示词与规则", "9. 提示词扩展", "玩家自定义规则文案", "点击这里使用大文本编辑器保存完整规则文案。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.EditPlayerCustomPromptRule?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("EditKingdomRebellionSystemPrompt", "提示词与规则", "9. 提示词扩展", "王国叛乱系统提示词", "点击这里使用大文本编辑器保存王国叛乱建国命名的完整 system prompt。默认内容为当前内置系统提示词，可按需要删减或改写。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.EditKingdomRebellionSystemPrompt?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("EditWeeklyReportWritingRequirements", "提示词与规则", "9. 提示词扩展", "周报写作要求文案", "点击这里使用大文本编辑器修改周报生成的写作要求。默认文本就是内置写作要求；留空保存后表示不注入写作要求。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.EditWeeklyReportWritingRequirements?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("EditNpcPersonaGenerationRequirements", "提示词与规则", "9. 提示词扩展", "NPC个性背景生成要求文案", "点击这里使用大文本编辑器保存 NPC 个性与历史背景生成的自定义要求。原始人设生成器提示词不会被覆盖，该文案会作为“玩家自定义生成要求”追加在其下方。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.EditNpcPersonaGenerationRequirements?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("EditDailyMemoryCompressionWritingRequirements", "提示词与规则", "9. 提示词扩展", "日结压缩写作要求", "修改日结压缩的文风和信息取舍。输出标签、公开性判断、AFEF 与身份事实规则不可覆盖。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.EditDailyMemoryCompressionWritingRequirements?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("EditMemoryOverviewCompressionWritingRequirements", "提示词与规则", "9. 提示词扩展", "记忆大压缩写作要求", "修改记忆大总结的文风和组织方式。输出标签、事实边界和长度范围不可覆盖。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.EditMemoryOverviewCompressionWritingRequirements?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("EditMajorActionCompressionWritingRequirements", "提示词与规则", "9. 提示词扩展", "重大履历压缩写作要求", "修改 NPC 重大履历滚动摘要的文风和取舍。输出标签、事实边界和长度范围不可覆盖。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.EditMajorActionCompressionWritingRequirements?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("EditPolicyPrompts", "外交与国家", "16. 政策系统", "政策提示词管理", "统一编辑玩家AI编写、玩家政策评议、NPC 统治者政策，以及当前可用政策效果的理解与判定要求。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.EditPolicyPrompts?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("ManagePolicyEffectModules", "外交与国家", "16. 政策系统", "政策效果模块管理", "分别设置玩家政策、地方政策、NPC 统治者政策和附庸国政策可检索的效果模块。只影响保存后新发起的政策。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.ManagePolicyEffectModules?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("OpenCustomPromptTextStoreFolderAction", "提示词与规则", "9. 提示词扩展", "自定义提示词JSON文件夹", "打开 CustomPrompts 文件夹，可直接编辑各套提示词 JSON。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.OpenCustomPromptTextStoreFolderAction?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("UseDetailedSceneSpeechPrompt", "提示词与规则", "9. 提示词扩展", "保留场景喊话动作/内心描写", "关闭：仍使用详细动作/内心文案，但输出时过滤动作描写、心理活动。开启：保留动作描写和内心活动。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.UseDetailedSceneSpeechPrompt, (s, v) => s.UseDetailedSceneSpeechPrompt = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("PreserveSceneAsteriskActions", "提示词与规则", "9. 提示词扩展", "保留星号动作描写", "开启后，即使关闭“保留场景喊话动作/内心描写”，也不会清洗被 **...** 或 *...* 包住的动作内容。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.PreserveSceneAsteriskActions, (s, v) => s.PreserveSceneAsteriskActions = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("DisableBuiltInSceneReplyFormatPrompt", "提示词与规则", "9. 提示词扩展", "自定义格式：不注入默认场景回复提示词", "开启后，不再注入单人交谈身份限制，以及“回复格式/动作/内心/字数”的默认要求。请在“玩家自定义规则文案”中自行提供完整格式。默认关闭。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.DisableBuiltInSceneReplyFormatPrompt, (s, v) => s.DisableBuiltInSceneReplyFormatPrompt = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("UseAiEvaluatedCustomPolicyCost", "外交与国家", "16. 政策系统/1. 玩家政策", "由AI评估政策消耗", "开启后，AI 会根据政策规模和执行难度评估所需第纳尔；第纳尔不足时，全部政策效果按实际投入比例折减。关闭后使用下面的固定第纳尔消耗。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.UseAiEvaluatedCustomPolicyCost, (s, v) => s.UseAiEvaluatedCustomPolicyCost = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("PlayerPolicyApiSourceDropdown", "外交与国家", "16. 政策系统/1. 玩家政策", "政策评议接口", "复用所选链路现有的 URL、Key、模型和地址解析规则；所选配置不完整时自动回退主 API。明确选择前处理时不受常规前处理 API 开关影响。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.PlayerPolicyApiSourceDropdown?.SelectedValue ?? "", (s, v) => { if (s.PlayerPolicyApiSourceDropdown != null && v is int idx && idx >= 0 && idx < s.PlayerPolicyApiSourceDropdown.Count) { var dd = s.PlayerPolicyApiSourceDropdown; dd.SelectedIndex = idx; s.PlayerPolicyApiSourceDropdown = dd; } }, null, s => s.PlayerPolicyApiSourceDropdown));
		_allDefinitions.Add(new TerminalSettingDef("PlayerPolicyAutoDraftApiSourceDropdown", "外交与国家", "16. 政策系统/1. 玩家政策", "AI编写接口", "只决定AI编写使用主链路、前处理或后处理；默认前处理。所选配置不完整时自动回退主接口，不影响政策评议接口。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.PlayerPolicyAutoDraftApiSourceDropdown?.SelectedValue ?? "", (s, v) => { if (s.PlayerPolicyAutoDraftApiSourceDropdown != null && v is int idx && idx >= 0 && idx < s.PlayerPolicyAutoDraftApiSourceDropdown.Count) { var dd = s.PlayerPolicyAutoDraftApiSourceDropdown; dd.SelectedIndex = idx; s.PlayerPolicyAutoDraftApiSourceDropdown = dd; } }, null, s => s.PlayerPolicyAutoDraftApiSourceDropdown));
		_allDefinitions.Add(new TerminalSettingDef("CustomPolicyGoldCost", "外交与国家", "16. 政策系统/1. 玩家政策", "固定第纳尔消耗", "仅在关闭“由AI评估政策消耗”后生效。玩家政策成功发布时扣除相应第纳尔；默认 50000，设置为 0 表示免费。", TerminalSettingType.Integer, 0f, 500000f, 1f, "0", s => s.CustomPolicyGoldCost, (s, v) => s.CustomPolicyGoldCost = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("CustomPolicyPublicFeedbackTargetChars", "外交与国家", "16. 政策系统/1. 玩家政策", "民众反馈篇幅", "设置玩家政策发布后民众反馈的目标篇幅。默认约 900 字，可在 100—1800 字之间调整；实际长度可能随模型输出略有浮动。", TerminalSettingType.Integer, 100f, 1800f, 1f, "0", s => s.CustomPolicyPublicFeedbackTargetChars, (s, v) => s.CustomPolicyPublicFeedbackTargetChars = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("PlayerPolicyFollowSelectedApiTokens", "外交与国家", "16. 政策系统/1. 玩家政策", "跟随所选API Token", "开启时使用实际生效 API 来源的最大输出 Tokens；若回退主 API，则改用主 API Token。关闭时始终使用下面的政策自定义值。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.PlayerPolicyFollowSelectedApiTokens, (s, v) => s.PlayerPolicyFollowSelectedApiTokens = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("PlayerPolicyCustomMaxTokens", "外交与国家", "16. 政策系统/1. 玩家政策", "自定义最大输出Tokens", "仅在关闭“跟随所选API Token”后使用。只影响玩家政策，允许 1000—100000；不修改其他 API 的全局上限。", TerminalSettingType.Integer, 1000f, 100000f, 1f, "0", s => s.PlayerPolicyCustomMaxTokens, (s, v) => s.PlayerPolicyCustomMaxTokens = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("PlayerPolicyEffectPostprocessMaxTokens", "外交与国家", "16. 政策系统/1. 玩家政策", "效果解析最大输出Tokens", "玩家政策第二阶段效果 JSON 的最大输出 Tokens。默认 5000；实际值不会超过上方玩家政策当前生效的 Token 上限。", TerminalSettingType.Integer, 512f, 12000f, 1f, "0", s => s.PlayerPolicyEffectPostprocessMaxTokens, (s, v) => s.PlayerPolicyEffectPostprocessMaxTokens = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("PlayerPolicyEffectModuleDetailCount", "外交与国家", "16. 政策系统/1. 玩家政策", "效果模块详规数量", "兼容旧配置，保存值仍可为 1—30，默认 6；最终最多向第二阶段注入 8 个详规，超过 8 的设置按 8 执行。该设置不限制 ONNX 内部候选池。数值越高，提示词和 Token 消耗越大。", TerminalSettingType.Integer, 1f, 30f, 1f, "0", s => s.PlayerPolicyEffectModuleDetailCount, (s, v) => s.PlayerPolicyEffectModuleDetailCount = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableNpcRulerPolicy", "外交与国家", "16. 政策系统/2. NPC统治者政策", "启用NPC统治者政策", "开启后，各 NPC 王国会按设定间隔制定并发布政策。关闭后不再生成新政策，已经生效的政策及其记录不受影响。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableNpcRulerPolicy, (s, v) => s.EnableNpcRulerPolicy = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcRulerPolicyApiSourceDropdown", "外交与国家", "16. 政策系统/2. NPC统治者政策", "API来源", "复用所选链路现有的 URL、Key、模型和地址解析规则；所选配置不完整时自动回退主 API。明确选择前处理时不受常规前处理 API 开关影响。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.NpcRulerPolicyApiSourceDropdown?.SelectedValue ?? "", (s, v) => { if (s.NpcRulerPolicyApiSourceDropdown != null && v is int idx && idx >= 0 && idx < s.NpcRulerPolicyApiSourceDropdown.Count) { var dd = s.NpcRulerPolicyApiSourceDropdown; dd.SelectedIndex = idx; s.NpcRulerPolicyApiSourceDropdown = dd; } }, null, s => s.NpcRulerPolicyApiSourceDropdown));
		_allDefinitions.Add(new TerminalSettingDef("NpcRulerPolicyCheckIntervalDays", "外交与国家", "16. 政策系统/2. NPC统治者政策", "政策检查间隔（天）", "每隔多少个游戏日检查一次是否需要生成新的 NPC 政策。默认 7 天，可在 1—30 天之间调整；没有符合条件的王国时，本轮不会生成政策。", TerminalSettingType.Integer, 1f, 30f, 1f, "0", s => s.NpcRulerPolicyCheckIntervalDays, (s, v) => s.NpcRulerPolicyCheckIntervalDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcRulerPolicyIntervalDays", "外交与国家", "16. 政策系统/2. NPC统治者政策", "同一王国政策冷却（天）", "同一 NPC 王国两次政策草案之间至少间隔多少个游戏日。默认 7 天，可在 1—30 天之间调整；待审、通过和否决的正常草案均参与冷却。玩家发布或续约附庸国政策不受冷却限制，但会从当天起按此天数压制目标附庸国的 NPC 统治者政策。", TerminalSettingType.Integer, 1f, 30f, 1f, "0", s => s.NpcRulerPolicyIntervalDays, (s, v) => s.NpcRulerPolicyIntervalDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcRulerPolicyFollowSelectedApiTokens", "外交与国家", "16. 政策系统/2. NPC统治者政策", "跟随所选API Token", "开启时使用实际生效 API 来源的最大输出 Tokens；若回退主 API，则改用主 API Token。关闭时始终使用下面的政策自定义值。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.NpcRulerPolicyFollowSelectedApiTokens, (s, v) => s.NpcRulerPolicyFollowSelectedApiTokens = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcRulerPolicyCustomMaxTokens", "外交与国家", "16. 政策系统/2. NPC统治者政策", "自定义最大输出Tokens", "仅在关闭“跟随所选API Token”后使用。只影响 NPC 统治者政策，允许 1000—100000；不修改其他 API 的全局上限。", TerminalSettingType.Integer, 1000f, 100000f, 1f, "0", s => s.NpcRulerPolicyCustomMaxTokens, (s, v) => s.NpcRulerPolicyCustomMaxTokens = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableWorldDiplomacy", "外交与国家", "17. AI外交（测试中）", "启用AI外交", "开启后，各国会自行发布外交宣言、展开交涉并采取外交行动。关闭后恢复原版王国外交决议。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableWorldDiplomacy, (s, v) => s.EnableWorldDiplomacy = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyStartNewGameAtPeace", "外交与国家", "17. AI外交（测试中）", "新游戏开局全大陆和平", "仅对新创建的存档生效。开局时结束王国之间已有的战争，让之后的战争与和平主要由AI外交推动。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.WorldDiplomacyStartNewGameAtPeace, (s, v) => s.WorldDiplomacyStartNewGameAtPeace = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableWorldDiplomacyMapNotifications", "外交与国家", "17. AI外交（测试中）", "启用右侧弹窗通知", "开启后，新发布的外交宣言会显示在屏幕右侧。关闭后仍可在王国公告中查看。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableWorldDiplomacyMapNotifications, (s, v) => s.EnableWorldDiplomacyMapNotifications = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyRoundIntervalDays", "外交与国家", "17. AI外交（测试中）", "两场外交事件的间隔（天）", "上一场外交事件结束后，通常等待多少天开始下一场。默认 3 天。", TerminalSettingType.Integer, 1f, 14f, 1f, "0", s => s.WorldDiplomacyRoundIntervalDays, (s, v) => s.WorldDiplomacyRoundIntervalDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyActivityDropdown", "外交与国家", "17. AI外交（测试中）", "参与国家规模", "决定一场外交事件最多有多少国家参加，发起国也计算在内。关系不足时不会强行凑满。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.WorldDiplomacyActivityDropdown?.SelectedValue ?? "", (s, v) => { if (s.WorldDiplomacyActivityDropdown != null && v is int idx && idx >= 0 && idx < s.WorldDiplomacyActivityDropdown.Count) { var dd = s.WorldDiplomacyActivityDropdown; dd.SelectedIndex = idx; s.WorldDiplomacyActivityDropdown = dd; } }, null, s => s.WorldDiplomacyActivityDropdown));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyCourtMaxDeliveryDays", "外交与国家", "17. AI外交（测试中）", "宣言送达最远王庭（天）", "决定外交宣言最迟多久传到大陆另一端的王庭。默认 7 天。", TerminalSettingType.Integer, 3f, 14f, 1f, "0", s => s.WorldDiplomacyCourtMaxDeliveryDays, (s, v) => s.WorldDiplomacyCourtMaxDeliveryDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyContinentSpreadDays", "外交与国家", "17. AI外交（测试中）", "宣言传遍大陆（天）", "决定地方贵族和平民多久能够得知一篇外交宣言。默认 21 天。", TerminalSettingType.Integer, 7f, 42f, 1f, "0", s => s.WorldDiplomacyContinentSpreadDays, (s, v) => s.WorldDiplomacyContinentSpreadDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyRoundLengthDropdown", "外交与国家", "17. AI外交（测试中）", "外交回合节奏", "决定一场外交事件通常持续多久。只影响新开始的事件。", TerminalSettingType.Dropdown, 0f, 0f, 1f, "", s => s.WorldDiplomacyRoundLengthDropdown?.SelectedValue ?? "", (s, v) => { if (s.WorldDiplomacyRoundLengthDropdown != null && v is int idx && idx >= 0 && idx < s.WorldDiplomacyRoundLengthDropdown.Count) { var dd = s.WorldDiplomacyRoundLengthDropdown; dd.SelectedIndex = idx; s.WorldDiplomacyRoundLengthDropdown = dd; } }, null, s => s.WorldDiplomacyRoundLengthDropdown));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyDeclarationMinCharacters", "外交与国家", "17. AI外交（测试中）", "外交宣言最小字数", "AI 生成的外交宣言正文最少使用多少个中文字符，标点计入。默认 40；可在 1—1000 之间调整。", TerminalSettingType.Integer, 1f, 1000f, 1f, "0", s => s.WorldDiplomacyDeclarationMinCharacters, (s, v) => s.WorldDiplomacyDeclarationMinCharacters = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyDeclarationMaxCharacters", "外交与国家", "17. AI外交（测试中）", "外交宣言最大字数", "AI 生成的外交宣言正文最多使用多少个中文字符，标点计入。默认 200；可在 1—1000 之间调整；若小于最小字数，运行时按最小字数处理。", TerminalSettingType.Integer, 1f, 1000f, 1f, "0", s => s.WorldDiplomacyDeclarationMaxCharacters, (s, v) => s.WorldDiplomacyDeclarationMaxCharacters = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyOffensiveWarCooldownDays", "外交与国家", "17. AI外交（测试中）", "再次主动开战间隔（天）", "一个国家主动发动战争后，至少等待多少天才能再次主动发动新战争。默认 42 天。", TerminalSettingType.Integer, 7f, 120f, 1f, "0", s => s.WorldDiplomacyOffensiveWarCooldownDays, (s, v) => s.WorldDiplomacyOffensiveWarCooldownDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyPeaceProtectionDays", "外交与国家", "17. AI外交（测试中）", "和平保护期（天）", "两国议和后，在这段时间内不会因为普通外交争端再次开战。默认 21 天。", TerminalSettingType.Integer, 0f, 60f, 1f, "0", s => s.WorldDiplomacyPeaceProtectionDays, (s, v) => s.WorldDiplomacyPeaceProtectionDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyTradeAllianceFailedProposalCooldownDays", "外交与国家", "17. AI外交（测试中）", "贸易/结盟失败冷却（天）", "贸易或结盟提议未达成后，同一提出国→同一对象国在这段时间内不能再次发起相同类型提议；反向提议和另一类型互不影响。默认 168 天；设为 0 关闭。", TerminalSettingType.Integer, 0f, 672f, 1f, "0", s => s.WorldDiplomacyTradeAllianceFailedProposalCooldownDays, (s, v) => s.WorldDiplomacyTradeAllianceFailedProposalCooldownDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyThreatComplianceIssuerRelationReward", "外交与国家", "17. AI外交（测试中）", "威慑退让国内关系奖励", "对象国明确服从谴责或最后通牒后，发出国每个正式、非雇佣兵封臣家族的族长与当前国王关系增加此数值。每次威慑只结算一次；设为 0 关闭。", TerminalSettingType.Integer, 0f, 50f, 1f, "0", s => s.WorldDiplomacyThreatComplianceIssuerRelationReward, (s, v) => s.WorldDiplomacyThreatComplianceIssuerRelationReward = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyHistoryCompressionTriggerThousands", "外交与国家", "17. AI外交（测试中）", "外交长期记忆压缩触发值（千估算 Tokens）", "长期外交历史达到该估算长度时开始压缩。默认 800，即约 800k Tokens；阈值越高，每次外交请求的延迟与费用通常越高。所选 API 模型必须有足够输入上下文，900k 仅适合上下文明显大于 1M 的模型。", TerminalSettingType.Integer, 64f, 900f, 1f, "0", s => s.WorldDiplomacyHistoryCompressionTriggerThousands, (s, v) => s.WorldDiplomacyHistoryCompressionTriggerThousands = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WorldDiplomacyHistoryCompressionTargetThousands", "外交与国家", "17. AI外交（测试中）", "外交长期记忆压缩后目标（千估算 Tokens）", "压缩完成后，长期外交快照与程序保留的近期硬事实合计目标长度。默认 48，即约 48k Tokens；上限 60k。实际摘要仍受所选 API 的“最大输出Tokens”限制，该上限较低时会生成更短快照。", TerminalSettingType.Integer, 8f, 60f, 1f, "0", s => s.WorldDiplomacyHistoryCompressionTargetThousands, (s, v) => s.WorldDiplomacyHistoryCompressionTargetThousands = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("EditWorldDiplomacyPrompt", "外交与国家", "17. AI外交（测试中）", "AI外交自定义偏好", "编辑利益判断、行动取向与文风偏好。留空表示不添加偏好；固定共同契约、事实边界和 MODE 输出规则不会被覆盖。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.EditWorldDiplomacyPrompt?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("RestoreDefaultWorldDiplomacyPrompt", "外交与国家", "17. AI外交（测试中）", "恢复默认AI外交偏好", "弹出确认后，将自定义偏好恢复为模组默认内容。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.RestoreDefaultWorldDiplomacyPrompt?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("EnableNobleGathering", "外交与国家", "18. 宴会功能", "启用宴会功能", "宴会系统总开关。关闭后停止创建新宴会，正在进行的宴会会在下一个安全的战役小时结算为取消，并安排主人和宾客返程；无需重启游戏。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableNobleGathering, (s, v) => s.EnableNobleGathering = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableNpcAutomaticNobleGatherings", "外交与国家", "18. 宴会功能", "启用NPC自动举办宴会", "开启后，符合条件的 NPC 会按王国自动举办宴会。关闭后不再自动创建 NPC 宴会，但玩家仍可主动举办。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableNpcAutomaticNobleGatherings, (s, v) => s.EnableNpcAutomaticNobleGatherings = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("AllowNpcNobleGatheringPlayerInvitations", "外交与国家", "18. 宴会功能", "允许NPC邀请玩家", "开启后，NPC 宴会可以邀请玩家并派信使送信。关闭后只阻止新邀请，已经发出的玩家邀请仍然有效。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.AllowNpcNobleGatheringPlayerInvitations, (s, v) => s.AllowNpcNobleGatheringPlayerInvitations = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("ShowNobleGatheringGuestArrivalMessages", "外交与国家", "18. 宴会功能", "显示宾客抵达提示", "控制玩家举办宴会时宾客抵达后的左下角彩色消息。关闭后只隐藏提示，不影响抵达判定、宴会状态或奖励。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.ShowNobleGatheringGuestArrivalMessages, (s, v) => s.ShowNobleGatheringGuestArrivalMessages = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("NpcNobleGatheringIntervalDays", "外交与国家", "18. 宴会功能", "NPC宴会间隔（天）", "同一王国两次自动宴会排期之间的游戏天数，默认 21 天。按王国分别计算；修改后用于下一次重新排期。", TerminalSettingType.Integer, 7f, 120f, 1f, "0", s => s.NpcNobleGatheringIntervalDays, (s, v) => s.NpcNobleGatheringIntervalDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("AllowNpcNobleGatheringGovernorInvitations", "外交与国家", "18. 宴会功能", "NPC可以邀请总督", "只影响 NPC 自动生成的宾客名单。关闭时 NPC 不会邀请正在治理定居点的总督；玩家举办宴会时仍可自由邀请总督。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.AllowNpcNobleGatheringGovernorInvitations, (s, v) => s.AllowNpcNobleGatheringGovernorInvitations = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("NobleGatheringDurationDays", "外交与国家", "18. 宴会功能", "宴会持续天数", "玩家与 NPC 宴会共用，默认 5 天。修改只影响之后新创建的宴会，已经开始的宴会保持原结束日期。", TerminalSettingType.Integer, 1f, 14f, 1f, "0", s => s.NobleGatheringDurationDays, (s, v) => s.NobleGatheringDurationDays = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("NobleGatheringCost", "外交与国家", "18. 宴会功能", "宴会举办费用", "玩家与 NPC 主人共用，费用从实际主人身上扣除。默认 50000 第纳尔；设为 0 表示免费。", TerminalSettingType.Integer, 0f, 500000f, 1f, "0", s => s.NobleGatheringCost, (s, v) => s.NobleGatheringCost = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("NobleGatheringInvitedClanRelationReward", "外交与国家", "18. 宴会功能", "每个受邀家族关系奖励", "玩家与 NPC 宴会共用；主人和每个受邀家族领袖每场只结算一次。默认 5；设为 0 表示不增加关系。修改只影响之后新创建的宴会。", TerminalSettingType.Integer, 0f, 20f, 1f, "0", s => s.NobleGatheringInvitedClanRelationReward, (s, v) => s.NobleGatheringInvitedClanRelationReward = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WeeklyReportLengthPreset", "外交与国家", "12. 事件系统（开发）", "周报篇幅档位", "1=200-400字；2=200-800字；3=200-1200字；4=200-1500字。世界周报和王国周报共用这一档位；默认 2。", TerminalSettingType.Integer, 1f, 4f, 1f, "0", s => s.WeeklyReportLengthPreset, (s, v) => s.WeeklyReportLengthPreset = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WeeklyReportRequestsPerMinute", "外交与国家", "12. 事件系统（开发）", "每分钟最多生成周报数", "限制开发态周报生成的请求速率。默认 5；最高 20。用于应对部分 API 渠道的 RPM 或并发限制。", TerminalSettingType.Integer, 1f, 20f, 1f, "0", s => s.WeeklyReportRequestsPerMinute, (s, v) => s.WeeklyReportRequestsPerMinute = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("AutoGenerateWeeklyReports", "外交与国家", "12. 事件系统（开发）", "每周自动生成周报", "开启后，系统会在每个新周开始时自动结算上一周，并生成世界周报与各王国周报。第0天会自动写入开局概要作为 week 0 事件。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.AutoGenerateWeeklyReports, (s, v) => s.AutoGenerateWeeklyReports = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("WeeklyReportPopupBodyFontSize", "外交与国家", "12. 事件系统（开发）", "周报弹窗正文字号", "仅影响最近王国周报的大弹窗正文，不影响别的界面。默认 18。", TerminalSettingType.Integer, 12f, 36f, 1f, "0", s => s.WeeklyReportPopupBodyFontSize, (s, v) => s.WeeklyReportPopupBodyFontSize = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableWeeklyReportMapNotifications", "外交与国家", "12. 事件系统（开发）", "周报右下角消息提示", "开启后，周报生成完成时会在大地图右下角显示可点击消息；关闭后不显示，且关闭期间新生成的周报不会排队提示。默认开启。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableWeeklyReportMapNotifications, (s, v) => s.EnableWeeklyReportMapNotifications = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableWeeklyReportReadingXpReward", "外交与国家", "12. 事件系统（开发）", "启用周报阅读经验奖励", "开启后，从地图通知打开周报并停留满 10 秒，会按三栏字数累计经验；每研读 20 篇后一次性给玩家魅力、统御和管理经验。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableWeeklyReportReadingXpReward, (s, v) => s.EnableWeeklyReportReadingXpReward = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("WeeklyReportReadingXpPerHundredChars", "外交与国家", "12. 事件系统（开发）", "周报每百字经验", "周报阅读奖励的字数倍率。默认 20，表示每栏每 100 个有效字/词给 20 点对应技能经验。", TerminalSettingType.Integer, 0f, 100f, 1f, "0", s => s.WeeklyReportReadingXpPerHundredChars, (s, v) => s.WeeklyReportReadingXpPerHundredChars = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("WeeklyReportReadingXpSkillCap", "外交与国家", "12. 事件系统（开发）", "周报单技能经验上限", "单份周报每个技能最多获得多少经验。默认 100；设置为 0 表示不发放周报阅读经验。", TerminalSettingType.Integer, 0f, 500f, 1f, "0", s => s.WeeklyReportReadingXpSkillCap, (s, v) => s.WeeklyReportReadingXpSkillCap = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableKingdomStabilityAndRebellion", "外交与国家", "12. 事件系统（开发）", "启用王国稳定度与叛乱", "关闭后，不再触发本模组的王国叛乱；王国稳定度不会再影响国王直辖领地忠诚度，也不会继续施加稳定度关系修正。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableKingdomStabilityAndRebellion, (s, v) => s.EnableKingdomStabilityAndRebellion = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnablePlayerKingdomRebellionImmunity", "外交与国家", "12. 事件系统（开发）", "玩家为国王时免疫稳定度叛乱", "开启后，当玩家家族是某个王国的执政家族或玩家本人是该王国领袖时，本模组的王国稳定度不会继续给该王国施加关系修正、国王直辖地忠诚修正或王国叛乱判定。原版城镇低忠诚叛乱仍按原版规则运行。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnablePlayerKingdomRebellionImmunity, (s, v) => s.EnablePlayerKingdomRebellionImmunity = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("GcczNpcResponseUnlimited", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "NPC Response Unlimited", "Removes the configured numeric cap in active GCCZ town scenes while retaining event deduplication and queue safety.", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.GcczNpcResponseUnlimited, (s, v) => s.GcczNpcResponseUnlimited = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("GcczNpcResponseLimit", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "NPC Response Limit", "Limits ambient NPC replies per player utterance, semantic action, or player attack event in an active GCCZ town scene.", TerminalSettingType.Integer, 1f, 20f, 1f, "0", s => s.GcczNpcResponseLimit, (s, v) => s.GcczNpcResponseLimit = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableGcczDiagnosticLog", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "写入 GCCZ 日志", "写入独立的 GCCZ_Debug.log。关闭后停止新增日志，但仍可导出或清空已有日志。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableGcczDiagnosticLog, (s, v) => s.EnableGcczDiagnosticLog = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableGcczVerboseDiagnosticLog", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "GCCZ 详细日志", "记录 NPC 回应限额等高频诊断。排查问题时再开启；关闭后仍保留阶段变化、处置结果和异常等关键日志。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableGcczVerboseDiagnosticLog, (s, v) => s.EnableGcczVerboseDiagnosticLog = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("GcczDiagnosticLogMaxSizeMegabytes", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "GCCZ 日志上限(MB)", "GCCZ_Debug.log 达到上限后自动轮转，上一份保留为 GCCZ_Debug.previous.log。默认 16 MB。", TerminalSettingType.Integer, 1f, 128f, 1f, "0", s => s.GcczDiagnosticLogMaxSizeMegabytes, (s, v) => s.GcczDiagnosticLogMaxSizeMegabytes = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ExportGcczDebugLog", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "导出 GCCZ_Debug.log", "将当前模块 Logs 文件夹里的 GCCZ_Debug.log 独立复制到桌面，文件名会带时间戳。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.ExportGcczDebugLog?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("ClearGcczDebugLog", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "清空 GCCZ_Debug.log", "只清空当前 GCCZ_Debug.log，不删除上一份轮转日志。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.ClearGcczDebugLog?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("EnableSetsDiagnosticLog", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "写入 SETS 日志", "写入独立的 SETS.log，用于进城随行与内部暴乱诊断。关闭后停止新增日志，但仍可导出或清空已有日志。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableSetsDiagnosticLog, (s, v) => s.EnableSetsDiagnosticLog = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("EnableSetsVerboseDiagnosticLog", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "SETS 详细日志", "记录逐帧保护、指挥刷新和刷兵进度等高频诊断。排查卡住时再开启；关闭后仍保留冲突开始、波次、胜利和异常等关键日志。", TerminalSettingType.Bool, 0f, 1f, 1f, "", s => s.EnableSetsVerboseDiagnosticLog, (s, v) => s.EnableSetsVerboseDiagnosticLog = Convert.ToBoolean(v)));
		_allDefinitions.Add(new TerminalSettingDef("SetsDiagnosticLogMaxSizeMegabytes", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "SETS 日志上限(MB)", "SETS.log 达到上限后自动轮转，上一份保留为 SETS.previous.log。默认 16 MB。", TerminalSettingType.Integer, 1f, 128f, 1f, "0", s => s.SetsDiagnosticLogMaxSizeMegabytes, (s, v) => s.SetsDiagnosticLogMaxSizeMegabytes = Convert.ToInt32(v)));
		_allDefinitions.Add(new TerminalSettingDef("ExportSetsDiagnosticLog", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "导出 SETS.log", "将当前模块 Logs 文件夹里的 SETS.log 独立复制到桌面，文件名会带时间戳。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.ExportSetsDiagnosticLog?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("ClearSetsDiagnosticLog", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "清空 SETS.log", "只清空当前 SETS.log，不删除上一份轮转日志。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.ClearSetsDiagnosticLog?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("ExportNoblePrisonerEscortLog", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "导出贵族俘虏随行日志", "将 NoblePrisonerEscort.log 独立复制到桌面，用于排查俘虏生成、场景处决与野外会面撤退。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.ExportNoblePrisonerEscortLog?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("ClearNoblePrisonerEscortLog", "决斗与部队", "战后与围城限制 (Siege & NPC Limits)", "清空贵族俘虏随行日志", "只清空当前 NoblePrisonerEscort.log，不删除上一份轮转日志。", TerminalSettingType.Button, 0f, 0f, 0f, "", s => null, null, s => s.ClearNoblePrisonerEscortLog?.Invoke()));
		_allDefinitions.Add(new TerminalSettingDef("IntimacyPregnancyChancePercent", "角色与同伴", "15. 亲密行为与怀孕", "怀孕几率（%）", "当亲密行为标签确认本轮已发生性行为和内射后，女方怀孕的概率。0 表示不会怀孕，100 表示必定怀孕。默认 50%。", TerminalSettingType.Integer, 0f, 100f, 1f, "0", s => s.IntimacyPregnancyChancePercent, (s, v) => s.IntimacyPregnancyChancePercent = Convert.ToInt32(v)));
	}
}
