<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TaleWorlds.MountAndBlade.Multiplayer.Test</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>