using AnimusForge;
using TaleWorlds.CampaignSystem;
int checks = 0;
void Check(bool value, string label) { checks++; if (!value) throw new Exception(label); }
Kingdom Realm(string id) => new() { StringId = id, RulingClan = new() { Leader = new Hero() } };
var player = Realm("player"); Hero.MainHero = player.RulingClan.Leader;
var subject = Realm("subject"); var other = Realm("other"); var enemy = Realm("enemy");
var owner = new VassalageBehavior { Player = player }; var first = owner.Sign(player, subject); var retained = owner.Sign(player, other);
Check(owner.GetPlayerSubjectReleaseToken(player, subject) == first.ReleaseIdentity, "direct subject token");
Check(owner.GetPlayerSubjectReleaseToken(subject, player) == "", "reverse direction denied");
Check(owner.GetPlayerSubjectReleaseToken(other, subject) == "", "third-country suzerain denied");
Check(!owner.TryReleasePlayerSubject(player, subject, "wrong", out _), "wrong token denied");
Check(!owner.TryReleasePlayerSubject(player, subject, "", out _), "empty token denied");
Check(owner.CapturePlayerSubjectReleaseTokens(player).Count == 2, "only current player subjects snapshotted");
var king = Hero.MainHero; Hero.MainHero = new Hero();
Check(owner.GetPlayerSubjectReleaseToken(player, subject) == "" && owner.CapturePlayerSubjectReleaseTokens(player).Count == 0,
    "non-ruling player has no token or snapshot");
Check(!owner.TryReleasePlayerSubject(player, subject, first.ReleaseIdentity, out _), "non-ruling player cannot release");
Hero.MainHero = king; king.IsAlive = false;
Check(!owner.TryReleasePlayerSubject(player, subject, first.ReleaseIdentity, out _), "dead player cannot release");
king.IsAlive = true; subject.IsEliminated = true;
Check(!owner.TryReleasePlayerSubject(player, subject, first.ReleaseIdentity, out _), "eliminated subject cannot release");
subject.IsEliminated = false;
owner.Wars.Add("subject:enemy"); owner.Wars.Add("other:enemy");
string source = "agreement_sync_subject_war@subject@" + first.ReleaseIdentity;
string otherSource = "agreement_sync_subject_war@other@" + retained.ReleaseIdentity;
Check(owner.PendingWarCurrent(source, player, enemy), "active source war is still eligible");
Check(owner.TryReleasePlayerSubject(player, subject, first.ReleaseIdentity, out var message) && message.Contains("恢复独立"), "release actual owner invokes break");
Check(owner.Breaks == 1 && !owner.HasAgreement(subject) && owner.HasAgreement(other), "release affects only selected agreement");
Check(owner.Wars.Contains("subject:enemy") && owner.Wars.Contains("other:enemy"), "release preserves existing native wars");
Check(!owner.PendingWarCurrent(source, player, enemy), "released source cannot pull suzerain into new war");
Check(owner.PendingWarCurrent(otherSource, player, enemy), "other subject pending war preserved");
Check(owner.PendingWarCurrent("agreement_sync_subject_war", player, enemy), "legacy war still valid when another active subject requires it");
Check(!owner.TryReleasePlayerSubject(player, subject, first.ReleaseIdentity, out _) && owner.Breaks == 1, "duplicate release is safe");
var second = owner.Sign(player, subject);
Check(first.ReleaseIdentity != second.ReleaseIdentity, "new treaty gets new incarnation");
Check(!owner.TryReleasePlayerSubject(player, subject, first.ReleaseIdentity, out _) && owner.HasAgreement(subject), "old result cannot release new treaty");
Check(!owner.PendingWarCurrent(source, player, enemy), "old queued war cannot bind to new treaty");
Check(owner.TryReleasePlayerSubject(player, subject, second.ReleaseIdentity, out _), "new token can release new treaty");
Check(owner.TryReleasePlayerSubject(player, other, retained.ReleaseIdentity, out _), "remaining direct subject can be released");
Check(!owner.PendingWarCurrent("agreement_sync_subject_war", player, enemy), "legacy pending war drops with no active subject source");
Check(owner.PendingWarCurrent("unrelated_reason", player, enemy), "unrelated pending tasks unaffected");
Check(!owner.PendingWarCurrent("agreement_sync_subject_war@subject@invalid@extra", player, enemy), "malformed source denied");
owner.Sign(other, subject);
Check(owner.GetPlayerSubjectReleaseToken(player, subject) == "", "foreign suzerain agreement denied");
owner.Sign(player, subject); var beforeRevision = owner.GetPlayerSubjectReleaseToken(player, subject);
var changed = owner.Sign(player, subject); // Simulate treaty owner rotating the incarnation on an approved amendment.
Check(!owner.TryReleasePlayerSubject(player, subject, beforeRevision, out _) && owner.HasAgreement(subject), "amended treaty rejects former token");
Console.WriteLine($"Vassalage release owner passed: {checks} assertions (linked production owner; campaign and BreakAgreement fakes).");
