<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\src\modules\AF.Module.Conversation\Channels\Scene\SceneSpeechQueueOwner.cs" Link="Production\SceneSpeechQueueOwner.cs" />
  </ItemGroup>
</Project>
