<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Refactor\Contracts\WorldDiplomacyIndependentClanPeaceContracts.cs" Link="WorldDiplomacyIndependentClanPeaceContracts.cs" />
    <Compile Include="..\..\Refactor\Domain\WorldDiplomacyOralIndependentClanPeaceRules.cs" Link="WorldDiplomacyOralIndependentClanPeaceRules.cs" />
    <Compile Include="..\..\Refactor\Modules\WorldDiplomacyIndependentClanPeaceCommandFacade.cs" Link="WorldDiplomacyIndependentClanPeaceCommandFacade.cs" />
    <Compile Include="..\..\src\modules\AF.Module.Diplomacy\Application\DiplomacyOralIndependentPeaceApplication.cs" Link="DiplomacyOralIndependentPeaceApplication.cs" />
  </ItemGroup>
</Project>
