using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using AnimusForge.SceneActions.Core;
using AnimusForge.SiegeAftermathIntervention;
using AnimusForge.XihaiAction;
using AnimusForge.Refactor.Adapters;
using AnimusForge.Refactor.Contracts;
using AnimusForge.Refactor.Modules;
using AnimusForge.Refactor.Runtime;
using RichExecutions.Core;
using RichExecutions.Scene;
using SandBox;
using SandBox.Missions.AgentBehaviors;
using SandBox.Missions.MissionLogics;
using SandBox.Missions.MissionLogics.Towns;
using SandBox.Objects.AnimationPoints;
using SandBox.Objects.Usables;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.ComponentInterfaces;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Encounters;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.CampaignSystem.Settlements.Locations;
using TaleWorlds.CampaignSystem.Siege;
using TaleWorlds.Core;
using TaleWorlds.Engine;
using TaleWorlds.InputSystem;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.MountAndBlade;
using TaleWorlds.MountAndBlade.Missions;

namespace AnimusForge;


using static AnimusForge.ShoutBehavior;

internal sealed class SceneMovementPorts
{
    internal delegate void AppendTargetedSceneNpcFactCapability(string factText, int targetAgentIndex, bool persistHeroPrivateHistory);
    internal AppendTargetedSceneNpcFactCapability AppendTargetedSceneNpcFact;
    internal delegate NpcDataPacket BuildSceneNpcDataFromLocationCharacterCapability(LocationCharacter locationCharacter);
    internal BuildSceneNpcDataFromLocationCharacterCapability BuildSceneNpcDataFromLocationCharacter;
    internal delegate void ClearAgentSceneConversationFocusCapability(Agent agent);
    internal ClearAgentSceneConversationFocusCapability ClearAgentSceneConversationFocus;
    internal delegate void ClearPendingSceneConversationAttentionReleaseCapability();
    internal ClearPendingSceneConversationAttentionReleaseCapability ClearPendingSceneConversationAttentionRelease;
    internal delegate void ForceAgentFacePlayerCapability(Agent agent);
    internal ForceAgentFacePlayerCapability ForceAgentFacePlayer;
    internal delegate Task<SceneCompactReactionInput> CaptureCompactSceneReactionInputAsyncCapability(NpcDataPacket targetNpc, Hero contextHero, List<NpcDataPacket> allNpcData, string extraFactLine, string singleReplyUserContent, Func<bool> isCurrent);
    internal CaptureCompactSceneReactionInputAsyncCapability CaptureCompactSceneReactionInputAsync;
    internal delegate void ReleaseAgentFromSceneConversationLocksCapability(Agent agent);
    internal ReleaseAgentFromSceneConversationLocksCapability ReleaseAgentFromSceneConversationLocks;
    internal delegate void ReleaseSceneConversationAttentionCapability(IEnumerable<int> participantAgentIndices, bool fullyRestoreAutonomy = true);
    internal ReleaseSceneConversationAttentionCapability ReleaseSceneConversationAttention;
    internal delegate void RemoveSceneMovementSuppressionAgentsCapability(IEnumerable<int> participantAgentIndices);
    internal RemoveSceneMovementSuppressionAgentsCapability RemoveSceneMovementSuppressionAgents;
    internal delegate Hero ResolveHeroFromAgentIndexCapability(int agentIndex);
    internal ResolveHeroFromAgentIndexCapability ResolveHeroFromAgentIndex;
    internal delegate void RestoreAgentAutonomyCapability(Agent agent);
    internal RestoreAgentAutonomyCapability RestoreAgentAutonomy;
    internal delegate void TrackPlayerInteractionCapability(NpcDataPacket primaryTarget, int participantCount, float timeoutSeconds);
    internal TrackPlayerInteractionCapability TrackPlayerInteraction;
    internal delegate void TryInterruptAgentSceneUseForStareCapability(Agent agent);
    internal TryInterruptAgentSceneUseForStareCapability TryInterruptAgentSceneUseForStare;
    internal delegate bool TriggerImmediateSceneBehaviorReactionCapability(string factText, int targetAgentIndex, bool persistHeroPrivateHistory, bool suppressStare, float postSpeechLeaveSeconds = -1f, bool skipSceneFactRecord = false, bool returnSceneSummonOnTimeout = false);
    internal TriggerImmediateSceneBehaviorReactionCapability TriggerImmediateSceneBehaviorReaction;
    internal delegate void EnqueueSpeechLineCapability(NpcDataPacket npc, string content, List<NpcDataPacket> allNpcData, bool skipHistory = false, bool suppressStare = false);
    internal EnqueueSpeechLineCapability EnqueueSpeechLine;
    internal delegate void CancelInteractionTimeoutArmCapability(int agentIndex);
    internal CancelInteractionTimeoutArmCapability CancelInteractionTimeoutArm;
    internal delegate void RemoveInteractionSessionCapability(int agentIndex);
    internal RemoveInteractionSessionCapability RemoveInteractionSession;
    internal delegate void CancelAutonomyRestoreCapability(int agentIndex);
    internal CancelAutonomyRestoreCapability CancelAutonomyRestore;
    internal delegate void DetachStareAgentCapability(int agentIndex);
    internal DetachStareAgentCapability DetachStareAgent;
    internal delegate bool ReleaseUseConversationSlotCapability(int agentIndex);
    internal ReleaseUseConversationSlotCapability ReleaseUseConversationSlot;
    internal delegate void ClearEmptyStareDeadlineCapability();
    internal ClearEmptyStareDeadlineCapability ClearEmptyStareDeadline;
    internal delegate void RemoveAttentionReleaseCapability(int agentIndex);
    internal RemoveAttentionReleaseCapability RemoveAttentionRelease;
}
