using System.Collections.Generic;
using System.Linq;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Siege;

public class BesiegerCamp : ISiegeEventSide
{
	[SaveableField(8)]
	private readonly MBList<MobileParty> _besiegerParties;

	[SaveableField(9)]
	private MobileParty _leaderParty;

	[SaveableField(14)]
	private IFaction _faction;

	[SaveableField(1)]
	private MBList<SiegeEvent.SiegeEngineMissile> _siegeEngineMissiles;

	[SaveableProperty(6)]
	public SiegeEvent SiegeEvent { get; private set; }

	[SaveableProperty(7)]
	public SiegeEvent.SiegeEnginesContainer SiegeEngines { get; private set; }

	public MobileParty LeaderParty => _leaderParty;

	public IFaction MapFaction => _faction;

	public BattleSideEnum BattleSide => BattleSideEnum.Attacker;

	public MBReadOnlyList<SiegeEvent.SiegeEngineMissile> SiegeEngineMissiles => _siegeEngineMissiles;

	[SaveableProperty(10)]
	public SiegeStrategy SiegeStrategy { get; private set; }

	[SaveableProperty(11)]
	public int NumberOfTroopsKilledOnSide { get; private set; }

	private float PreparationProgress => SiegeEngines?.SiegePreparations?.Progress ?? 0f;

	public bool IsPreparationComplete => PreparationProgress >= 1f;

	public bool IsReadyToBesiege
	{
		get
		{
			if (IsPreparationComplete)
			{
				return StartingAssaultOnBesiegedSettlementIsLogical();
			}
			return false;
		}
	}

	internal static void AutoGeneratedStaticCollectObjectsBesiegerCamp(object o, List<object> collectedObjects)
	{
		((BesiegerCamp)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		collectedObjects.Add(_besiegerParties);
		collectedObjects.Add(_leaderParty);
		collectedObjects.Add(_faction);
		collectedObjects.Add(_siegeEngineMissiles);
		collectedObjects.Add(SiegeEvent);
		collectedObjects.Add(SiegeEngines);
		collectedObjects.Add(SiegeStrategy);
	}

	internal static object AutoGeneratedGetMemberValueSiegeEvent(object o)
	{
		return ((BesiegerCamp)o).SiegeEvent;
	}

	internal static object AutoGeneratedGetMemberValueSiegeEngines(object o)
	{
		return ((BesiegerCamp)o).SiegeEngines;
	}

	internal static object AutoGeneratedGetMemberValueSiegeStrategy(object o)
	{
		return ((BesiegerCamp)o).SiegeStrategy;
	}

	internal static object AutoGeneratedGetMemberValueNumberOfTroopsKilledOnSide(object o)
	{
		return ((BesiegerCamp)o).NumberOfTroopsKilledOnSide;
	}

	internal static object AutoGeneratedGetMemberValue_besiegerParties(object o)
	{
		return ((BesiegerCamp)o)._besiegerParties;
	}

	internal static object AutoGeneratedGetMemberValue_leaderParty(object o)
	{
		return ((BesiegerCamp)o)._leaderParty;
	}

	internal static object AutoGeneratedGetMemberValue_faction(object o)
	{
		return ((BesiegerCamp)o)._faction;
	}

	internal static object AutoGeneratedGetMemberValue_siegeEngineMissiles(object o)
	{
		return ((BesiegerCamp)o)._siegeEngineMissiles;
	}

	public IEnumerable<PartyBase> GetInvolvedPartiesForEventType(MapEvent.BattleTypes mapEventType = MapEvent.BattleTypes.Siege)
	{
		foreach (MobileParty besiegerParty in _besiegerParties)
		{
			if (InvolveCondition(mapEventType, besiegerParty))
			{
				yield return besiegerParty.Party;
			}
		}
	}

	public PartyBase GetNextInvolvedPartyForEventType(ref int partyIndex, MapEvent.BattleTypes mapEventType = MapEvent.BattleTypes.Siege)
	{
		partyIndex++;
		for (int i = partyIndex; i < _besiegerParties.Count; i++)
		{
			MobileParty mobileParty = _besiegerParties[i];
			if (InvolveCondition(mapEventType, mobileParty))
			{
				partyIndex = i;
				return mobileParty.Party;
			}
		}
		return null;
	}

	public bool HasInvolvedPartyForEventType(PartyBase party, MapEvent.BattleTypes mapEventType = MapEvent.BattleTypes.Siege)
	{
		if (InvolveCondition(mapEventType, party.MobileParty))
		{
			foreach (MobileParty besiegerParty in _besiegerParties)
			{
				if (party == besiegerParty.Party)
				{
					return true;
				}
			}
		}
		return false;
	}

	private bool InvolveCondition(MapEvent.BattleTypes mapEventType, MobileParty besiegerParty)
	{
		if (mapEventType == MapEvent.BattleTypes.BlockadeBattle)
		{
			return besiegerParty.HasNavalNavigationCapability;
		}
		return true;
	}

	public BesiegerCamp(SiegeEvent siegeEvent, IFaction besiegerFaction)
	{
		_besiegerParties = new MBList<MobileParty>();
		SiegeEvent = siegeEvent;
		_faction = besiegerFaction;
	}

	public bool IsBesiegerSideParty(MobileParty mobileParty)
	{
		return GetInvolvedPartiesForEventType().Any((PartyBase t) => t == mobileParty.Party || t.MobileParty.AttachedParties.Any((MobileParty k) => k == mobileParty));
	}

	public void InitializeSiegeEventSide()
	{
		SiegeStrategy = DefaultSiegeStrategies.Custom;
		NumberOfTroopsKilledOnSide = 0;
		SiegeEvent.SiegeEngineConstructionProgress siegeEngineConstructionProgress = null;
		siegeEngineConstructionProgress = new SiegeEvent.SiegeEngineConstructionProgress(DefaultSiegeEngineTypes.Preparations, PreparationProgress, DefaultSiegeEngineTypes.Preparations.BaseHitPoints);
		SiegeEngines = new SiegeEvent.SiegeEnginesContainer(BattleSideEnum.Attacker, siegeEngineConstructionProgress);
		_siegeEngineMissiles = new MBList<SiegeEvent.SiegeEngineMissile>();
		SetPrebuiltSiegeEngines();
	}

	public void OnTroopsKilledOnSide(int killCount)
	{
		NumberOfTroopsKilledOnSide += killCount;
	}

	public void SetSiegeStrategy(SiegeStrategy strategy)
	{
		SiegeStrategy = strategy;
	}

	public void CheckBesiegerPartiesAndMakeThemLeave()
	{
		for (int num = _besiegerParties.Count - 1; num >= 0; num--)
		{
			MobileParty mobileParty = _besiegerParties[num];
			if (!mobileParty.IsMainParty && mobileParty.AttachedTo == null && mobileParty.DefaultBehavior != AiBehavior.BesiegeSettlement && mobileParty.DefaultBehavior != AiBehavior.EscortParty && mobileParty.DefaultBehavior != AiBehavior.AssaultSettlement)
			{
				mobileParty.BesiegerCamp = null;
			}
		}
	}

	internal void AddSiegePartyInternal(MobileParty mobileParty)
	{
		_besiegerParties.Add(mobileParty);
		if (_besiegerParties.Count == 1)
		{
			SiegeEvent.BesiegedSettlement.LastAttackerParty = mobileParty;
		}
		_leaderParty = Campaign.Current.Models.EncounterModel.GetLeaderOfSiegeEvent(SiegeEvent, BattleSideEnum.Attacker).PartyBelongedTo;
		_faction = _leaderParty.MapFaction;
		ChangeSiegeStrategyIfNeeded();
	}

	internal void RemoveSiegePartyInternal(MobileParty mobileParty)
	{
		_besiegerParties.Remove(mobileParty);
		if (mobileParty != null)
		{
			OnPartyLeftSiege(mobileParty);
		}
		if (_besiegerParties.All((MobileParty x) => !InvolveCondition(MapEvent.BattleTypes.BlockadeBattle, x) || !x.Ships.Any()))
		{
			if (SiegeEvent.IsBlockadeActive)
			{
				SiegeEvent.DeactivateBlockade();
			}
			else if (SiegeEvent.BlockadeShouldBeActivated)
			{
				SiegeEvent.DeactivatedBlockadeActivationOrder();
			}
		}
		if (_besiegerParties.Count == 0)
		{
			SiegeEvent.FinalizeSiegeEvent();
		}
		else if (_leaderParty == mobileParty && (_leaderParty == null || _leaderParty.MapEvent == null || _leaderParty.MapEvent.State != MapEventState.WaitingRemoval))
		{
			_leaderParty = Campaign.Current.Models.EncounterModel.GetLeaderOfSiegeEvent(SiegeEvent, BattleSideEnum.Attacker)?.PartyBelongedTo;
			_faction = _leaderParty?.MapFaction;
			ChangeSiegeStrategyIfNeeded();
		}
	}

	public void RemoveAllSiegeParties()
	{
		MapEvent mapEvent = SiegeEvent.BesiegedSettlement.Party.MapEvent;
		if (mapEvent != null && mapEvent.IsSiegeAssault && !mapEvent.IsFinalized)
		{
			Debug.FailedAssert("RemoveAllParties called before mapEvent is cleared", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Siege\\BesiegerCamp.cs", "RemoveAllSiegeParties", 231);
		}
		while (_besiegerParties.Count > 0)
		{
			_besiegerParties[0].BesiegerCamp = null;
		}
	}

	private void OnPartyLeftSiege(MobileParty mobileParty)
	{
		if (mobileParty == MobileParty.MainParty && PlayerSiege.PlayerSiegeEvent != null)
		{
			PlayerSiege.FinalizePlayerSiege();
		}
		if (Campaign.Current.Models.PartyImpairmentModel.CanGetDisorganized(mobileParty.Party))
		{
			mobileParty.SetDisorganized(isDisorganized: true);
		}
		if (_besiegerParties.Contains(MobileParty.MainParty) && (MobileParty.MainParty.MapEvent == null || !MobileParty.MainParty.MapEvent.HasWinner))
		{
			Campaign.Current.TimeControlMode = CampaignTimeControlMode.Stop;
			Campaign.Current.CurrentMenuContext?.Refresh();
		}
		mobileParty.SetMoveModeHold();
	}

	private void ChangeSiegeStrategyIfNeeded()
	{
		if (SiegeStrategy != DefaultSiegeStrategies.Custom || _leaderParty == null || _leaderParty.LeaderHero == Hero.MainHero)
		{
			return;
		}
		SiegeStrategy siegeStrategy = null;
		float num = float.MinValue;
		foreach (SiegeStrategy allAttackerStrategy in DefaultSiegeStrategies.AllAttackerStrategies)
		{
			float num2 = Campaign.Current.Models.SiegeEventModel.GetSiegeStrategyScore(SiegeEvent, BattleSideEnum.Attacker, allAttackerStrategy) * (0.5f + 0.5f * MBRandom.RandomFloat);
			if (num2 > num)
			{
				num = num2;
				siegeStrategy = allAttackerStrategy;
			}
		}
		SetSiegeStrategy(siegeStrategy);
	}

	internal CampaignVec2 GetSiegeCampPartyPosition(MobileParty mobileParty, MatrixFrame[] siegeCamp1GlobalFrames, MatrixFrame[] siegeCamp2GlobalFrames)
	{
		int num = 0;
		CampaignVec2 campaignVec;
		bool flag;
		do
		{
			int num2 = MBRandom.RandomInt(siegeCamp1GlobalFrames.Length);
			float randomFloat = MBRandom.RandomFloat;
			float randomFloat2 = MBRandom.RandomFloat;
			campaignVec = new CampaignVec2(siegeCamp1GlobalFrames[num2].origin.AsVec2 + randomFloat * siegeCamp1GlobalFrames[num2].rotation.s.AsVec2 + randomFloat2 * siegeCamp1GlobalFrames[num2].rotation.f.AsVec2, isOnLand: true);
			flag = false;
			if (!campaignVec.IsValid())
			{
				flag = true;
				num++;
				continue;
			}
			foreach (PartyBase item in SiegeEvent.BesiegerCamp.GetInvolvedPartiesForEventType())
			{
				if ((campaignVec - item.MobileParty.VisualPosition2DWithoutError).LengthSquared < 0.25f)
				{
					flag = true;
					break;
				}
			}
			num++;
		}
		while (flag && num < 20);
		if (num == 20 && siegeCamp2GlobalFrames != null && siegeCamp2GlobalFrames.Length != 0)
		{
			num = 0;
			do
			{
				int num3 = MBRandom.RandomInt(siegeCamp2GlobalFrames.Length);
				float randomFloat3 = MBRandom.RandomFloat;
				float randomFloat4 = MBRandom.RandomFloat;
				campaignVec = new CampaignVec2(siegeCamp2GlobalFrames[num3].origin.AsVec2 + randomFloat3 * siegeCamp2GlobalFrames[num3].rotation.s.AsVec2 + randomFloat4 * siegeCamp2GlobalFrames[num3].rotation.f.AsVec2, isOnLand: true);
				flag = false;
				if (!campaignVec.IsValid())
				{
					flag = true;
					num++;
					continue;
				}
				foreach (PartyBase item2 in SiegeEvent.BesiegerCamp.GetInvolvedPartiesForEventType())
				{
					if ((campaignVec - item2.MobileParty.VisualPosition2DWithoutError).LengthSquared < 0.25f)
					{
						flag = true;
						break;
					}
				}
				num++;
			}
			while (flag && num < 20);
		}
		return campaignVec;
	}

	public void AddSiegeEngineMissile(SiegeEvent.SiegeEngineMissile missile)
	{
		_siegeEngineMissiles.Add(missile);
	}

	public void RemoveDeprecatedMissiles()
	{
		_siegeEngineMissiles.RemoveAll((SiegeEvent.SiegeEngineMissile missile) => missile.CollisionTime.IsPast);
	}

	private bool StartingAssaultOnBesiegedSettlementIsLogical()
	{
		float num = 0f;
		float num2 = ((MobileParty.MainParty.CurrentSettlement == SiegeEvent.BesiegedSettlement) ? 0.5f : 1f);
		foreach (PartyBase item in SiegeEvent.BesiegedSettlement.GetInvolvedPartiesForEventType())
		{
			if (item.IsMobile && item.MobileParty.CurrentSettlement == SiegeEvent.BesiegedSettlement && (item.MobileParty.Aggressiveness > 0.01f || item.MobileParty.IsMilitia || item.MobileParty.IsGarrison))
			{
				num += num2 * item.CalculateCurrentStrength();
			}
		}
		float num3 = 0f;
		foreach (PartyBase item2 in SiegeEvent.BesiegerCamp.GetInvolvedPartiesForEventType())
		{
			num3 += item2.CalculateCurrentStrength();
		}
		bool flag = false;
		bool flag2 = false;
		foreach (SiegeEvent.SiegeEngineConstructionProgress item3 in SiegeEvent.GetSiegeEventSide(BattleSideEnum.Attacker).SiegeEngines.AllSiegeEngines())
		{
			if (item3.IsConstructed)
			{
				if (item3.SiegeEngine == DefaultSiegeEngineTypes.Ram || item3.SiegeEngine == DefaultSiegeEngineTypes.ImprovedRam)
				{
					flag = true;
				}
				else if (item3.SiegeEngine == DefaultSiegeEngineTypes.SiegeTower)
				{
					flag2 = true;
				}
			}
		}
		float settlementAdvantage = Campaign.Current.Models.CombatSimulationModel.GetSettlementAdvantage(SiegeEvent.BesiegedSettlement);
		float num4 = (float)CampaignTime.HoursInDay * 4f;
		float num5 = 0.8f - ((SiegeEvent.SiegeStartTime.ElapsedHoursUntilNow > num4) ? ((SiegeEvent.SiegeStartTime.ElapsedHoursUntilNow - num4) * 0.02f) : 0f);
		if (!flag)
		{
			num5 *= 1.25f;
		}
		if (!flag2)
		{
			num5 *= 1.25f;
		}
		float num6 = num3 / (num * MathF.Pow(settlementAdvantage, num5));
		bool result = false;
		float num7 = 1f;
		if (num6 > num7)
		{
			int numberOfEquipmentsBuilt = Campaign.Current.Models.CombatSimulationModel.GetNumberOfEquipmentsBuilt(SiegeEvent.BesiegedSettlement);
			num6 *= (float)MathF.Min(3, numberOfEquipmentsBuilt) / 3f;
			float num8 = Campaign.Current.Models.CombatSimulationModel.GetMaximumSiegeEquipmentProgress(SiegeEvent.BesiegedSettlement) + 0.25f * (float)(5 - numberOfEquipmentsBuilt);
			num6 *= 1f - 0.85f * (num8 * num8);
			float num9 = num6 * 0.1f;
			result = num == 0f || MBRandom.RandomFloat < num9;
		}
		return result;
	}

	private void SetPrebuiltSiegeEngines()
	{
		foreach (SiegeEngineType item in Campaign.Current.Models.SiegeEventModel.GetPrebuiltSiegeEnginesOfSiegeCamp(this))
		{
			float siegeEngineHitPoints = Campaign.Current.Models.SiegeEventModel.GetSiegeEngineHitPoints(SiegeEvent, item, BattleSideEnum.Attacker);
			SiegeEvent.SiegeEngineConstructionProgress siegeEngineConstructionProgress = new SiegeEvent.SiegeEngineConstructionProgress(item, 1f, siegeEngineHitPoints);
			SiegeEngines.AddPrebuiltEngineToReserve(siegeEngineConstructionProgress);
			SiegeEvent.CreateSiegeObject(siegeEngineConstructionProgress, SiegeEvent.GetSiegeEventSide(BattleSideEnum.Defender));
		}
	}

	private float GetDistanceBetweenRangedEngineAndWall(int rangedEngine, int wallIndex)
	{
		float num = (float)rangedEngine * 1f;
		float num2 = 0.5f + 2f * (float)wallIndex;
		return MathF.Abs(num - num2) + 2f;
	}

	private float PriorityCalculationForWalls(float distance)
	{
		return 5f - distance;
	}

	private void FindAttackableWallSectionWithHighestPriority(int attackerSlotIndex, SiegeEngineType siegeEngine, out int targetIndex, out float targetPriority)
	{
		targetIndex = -1;
		targetPriority = 0f;
		if (siegeEngine.IsAntiPersonnel)
		{
			return;
		}
		float num = float.MaxValue;
		MBReadOnlyList<float> settlementWallSectionHitPointsRatioList = SiegeEvent.BesiegedSettlement.SettlementWallSectionHitPointsRatioList;
		for (int i = 0; i < settlementWallSectionHitPointsRatioList.Count; i++)
		{
			if (settlementWallSectionHitPointsRatioList[i] > 0f)
			{
				float distanceBetweenRangedEngineAndWall = GetDistanceBetweenRangedEngineAndWall(attackerSlotIndex, i);
				float num2 = PriorityCalculationForWalls(distanceBetweenRangedEngineAndWall);
				if (num2 > targetPriority || (MathF.Abs(num2 - targetPriority) < float.Epsilon && num > distanceBetweenRangedEngineAndWall))
				{
					targetIndex = i;
					targetPriority = num2;
					num = distanceBetweenRangedEngineAndWall;
				}
			}
		}
	}

	public void BombardHitWalls(SiegeEngineType attackerEngineType, int wallIndex)
	{
		MBReadOnlyList<float> settlementWallSectionHitPointsRatioList = SiegeEvent.BesiegedSettlement.SettlementWallSectionHitPointsRatioList;
		if (settlementWallSectionHitPointsRatioList[wallIndex] > 0f)
		{
			float num = Campaign.Current.Models.SiegeEventModel.GetSiegeEngineDamage(SiegeEvent, BattleSideEnum.Attacker, attackerEngineType, SiegeBombardTargets.Wall) / SiegeEvent.BesiegedSettlement.MaxHitPointsOfOneWallSection;
			SiegeEvent.BesiegedSettlement.SetWallSectionHitPointsRatioAtIndex(wallIndex, MBMath.ClampFloat(settlementWallSectionHitPointsRatioList[wallIndex] - num, 0f, 1f));
			bool flag = settlementWallSectionHitPointsRatioList[wallIndex] <= 0f;
			if (flag)
			{
				SiegeEvent.BesiegedSettlement.Party.SetVisualAsDirty();
			}
			CampaignEventDispatcher.Instance.OnSiegeBombardmentWallHit(LeaderParty, SiegeEvent.BesiegedSettlement, BattleSideEnum.Attacker, attackerEngineType, flag);
		}
	}

	public void GetAttackTarget(ISiegeEventSide siegeEventSide, SiegeEngineType siegeEngine, int siegeEngineSlot, out SiegeBombardTargets targetType, out int targetIndex)
	{
		targetType = SiegeBombardTargets.None;
		targetIndex = -1;
		siegeEventSide.SiegeEvent.FindAttackableRangedEngineWithHighestPriority(this, siegeEngineSlot, out var targetIndex2, out var targetPriority);
		FindAttackableWallSectionWithHighestPriority(siegeEngineSlot, siegeEngine, out var targetIndex3, out var targetPriority2);
		if (targetIndex2 == -1 && targetIndex3 == -1)
		{
			return;
		}
		if (targetIndex2 == -1)
		{
			targetIndex = targetIndex3;
			targetType = SiegeBombardTargets.Wall;
			return;
		}
		if (targetIndex3 == -1)
		{
			targetIndex = targetIndex2;
			targetType = SiegeBombardTargets.RangedEngines;
			return;
		}
		float num = targetPriority + targetPriority2;
		if (MBRandom.RandomFloat * num < targetPriority)
		{
			targetIndex = targetIndex2;
			targetType = SiegeBombardTargets.RangedEngines;
		}
		else
		{
			targetIndex = targetIndex3;
			targetType = SiegeBombardTargets.Wall;
		}
	}

	public void FinalizeSiegeEvent()
	{
		if (!GetInvolvedPartiesForEventType().IsEmpty())
		{
			RemoveAllSiegeParties();
		}
	}

	public void OnAfterLoad()
	{
		if (!MBSaveLoad.LastLoadedGameVersion.IsOlderThan(ApplicationVersion.FromString("v1.3.0")))
		{
			return;
		}
		if (_leaderParty == null)
		{
			_leaderParty = ((_besiegerParties.Count > 0) ? _besiegerParties[0] : null);
		}
		if (_faction == null || _leaderParty.MapFaction != _faction)
		{
			if (_leaderParty != null)
			{
				_faction = _leaderParty.MapFaction;
			}
			else if (_besiegerParties.Any())
			{
				_faction = _besiegerParties[0]?.MapFaction;
			}
		}
	}

	public void SetPositionAfterMapChange(CampaignVec2 newPosition)
	{
		Campaign.Current.MapSceneWrapper.GetSiegeCampFrames(SiegeEvent.BesiegedSettlement, out var siegeCamp1GlobalFrames, out var siegeCamp2GlobalFrames);
		foreach (MobileParty besiegerParty in _besiegerParties)
		{
			bool flag = false;
			foreach (MatrixFrame item in siegeCamp1GlobalFrames)
			{
				CampaignVec2 position = besiegerParty.Position;
				Vec3 origin = item.origin;
				if (position.DistanceSquared(origin.AsVec2) < 2f)
				{
					flag = true;
					break;
				}
			}
			if (!flag)
			{
				foreach (MatrixFrame item2 in siegeCamp2GlobalFrames)
				{
					CampaignVec2 position = besiegerParty.Position;
					Vec3 origin = item2.origin;
					if (position.DistanceSquared(origin.AsVec2) < 2f)
					{
						flag = true;
						break;
					}
				}
			}
			if (!flag)
			{
				CampaignVec2 siegeCampPartyPosition = GetSiegeCampPartyPosition(besiegerParty, siegeCamp1GlobalFrames.ToArray(), siegeCamp2GlobalFrames.ToArray());
				besiegerParty.SetPositionAfterMapChange(siegeCampPartyPosition);
			}
		}
	}
}
