<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TaleWorlds.MountAndBlade</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="TaleWorlds.Core">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.Core.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.DotNet">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.DotNet.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade.Diamond">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Diamond.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Library">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.Library.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.PlayerServices">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.PlayerServices.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Engine">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.Engine.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Localization">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.Localization.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.InputSystem">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.PlatformService">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.PlatformService.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.ObjectSystem">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.ObjectSystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.PSAI">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.PSAI.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.ModuleManager">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.ModuleManager.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.SaveSystem">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.SaveSystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.ScreenSystem">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.ScreenSystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade.Helpers">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Helpers.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.LinQuick">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.LinQuick.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Diamond">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.Diamond.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.AchievementSystem">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.AchievementSystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.ActivitySystem">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.ActivitySystem.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>