using AnimusForge;using Newtonsoft.Json;using TaleWorlds.Library;using static AnimusForge.MyBehavior;
int n=0;void Check(bool ok,string label){if(!ok)throw new Exception(label);n++;}
var root=Path.GetFullPath("artifacts/af2-host-terminal-closeout/line-d/packageimport/fixtures/"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
void Write(string folder,string name,string json){Directory.CreateDirectory(Path.Combine(root,folder));File.WriteAllText(Path.Combine(root,folder,name),json);}
Write("personality_background","hero__export.json","{\"HeroId\":\"hero\",\"Personality\":\"prepared\"}");Write("personality_background","bad__export.json","badJSON");Write("dialogue_history","hero__export.json","[{\"GameDayIndex\":1}]");Write("debt","hero__export.json","{\"Amount\":9}");Write("voice_mapping","VoiceMapping.json","{}");
long generation=1;Action overwrite=null,skip=null,cancel=null;Dictionary<string,NpcPersonaProfile> prepared=null;Dictionary<string,List<DialogueDay>> history=null;int storageRefreshes=0,unnamedRefreshes=0;bool personaAccepted=true,knowledgeValid=true;
var execution=new DeveloperImportController(()=>generation,g=>g==generation);
var port=new DeveloperPackageImportPort {
 CaptureGeneration=()=>generation,IsCurrent=g=>g==generation,HasPersonaAuthority=()=>true,ContainsPersona=id=>id=="hero",HasHistoryAuthority=()=>true,ContainsHistory=id=>id=="hero",HasKingdomSummaryAuthority=()=>true,ContainsKingdomSummary=id=>true,WorldOpeningSummary=()=>"existing",EventRecords=()=>new(){new(){EventId="event"}},ReadUnnamedPersonaKey=file=>null,
 TryResolveNpcDataFileHeroIdForImport=(string file,out string id,out string warning)=>{id=NpcDataFileName.TryParseHeroId(file);warning="";return true;},StampNpcPersonaProfile=(id,p)=>p.HeroId=id,NormalizeMemoryHeroId=id=>id.ToLowerInvariant(),HasCompressedMemoryDataForHero=id=>true,
 ValidateUnnamedPersonaKeysForImport=(string dir,out string error)=>{error="";return true;},ValidateKnowledgeKeywordsForImport=(string dir,bool overwriteExisting,out string error)=>{error="invalid knowledge";return knowledgeValid;},
 ApplyImportedPersonaProfiles=(data,o,g)=>{TestState.Order.Add("persona");prepared=data;return personaAccepted;},ApplyImportedDialogueHistory=(data,o,g)=>{TestState.Order.Add("history");history=data;return true;},ApplyCompressedMemoryExportBundle=(id,b,o)=>{TestState.Order.Add("compressed");return true;},
 TryLoadEventDataFromImportDir=(string dir,out EventImportPayload payload,out string error)=>{payload=new(){HasWorldSummaryFile=true,HasKingdomSummariesFile=true,HasEventRecordsFile=true,KingdomSummaries=new(){{"k","summary"}},EventRecords=new(){new(){EventId="event"}}};error="";return true;},ApplyImportedEventData=(p,o)=>TestState.Order.Add("weekly"),
 ImportKnowledgeFromDir=(string dir,bool overwriteExisting,out string detail)=>{TestState.Order.Add("knowledge");detail="fixture partial failure";return false;},RefreshVoiceStorage=()=>storageRefreshes++,RefreshUnnamedStorage=()=>unnamedRefreshes++,
 ShowDuplicateImportInquiry=(title,text,yes,no,stop)=>{var choices=execution.BeginConfirmation(yes,no,stop);overwrite=choices[0];skip=choices[1];cancel=choices[2];}
};
var package=new DeveloperPackageImportController(port,execution);
package.ImportAllData(root);Check(TestState.Order.Count==0,"package preoverwrite preparation has no domain commits");cancel();overwrite();Check(TestState.Order.Count==0,"package cancel retires detached plan");
package.ImportAllData(root);var oldOverwrite=overwrite;generation++;oldOverwrite();Check(TestState.Order.Count==0,"load retires prepared package");
package.ImportAllData(root);Write("personality_background","hero__export.json","{\"Personality\":\"changed-after-prepare\"}");VoiceMapper.Fail=true;overwrite();Check(string.Join(",",TestState.Order)=="persona,history,debt,voice,weekly,kingdom,unnamed,knowledge","complete original domain order despite voice/kingdom/knowledge failures");
Check(prepared.Count==1&&prepared["hero"].Personality=="prepared","bad JSON skipped and prepared profile unaffected by later file writes");Check(prepared.Comparer.Equals(EqualityComparer<string>.Default)&&history.Comparer.Equals(EqualityComparer<string>.Default),"original profile/history prepared dictionary comparers");
Check(storageRefreshes==0&&unnamedRefreshes==1,"failed voice does not persist fake success; unnamed still commits in order");Check(InformationManager.Messages.Any(m=>m.StartsWith("导入完成：")),"partial failures preserve completion message");var count=TestState.Order.Count;overwrite();Check(TestState.Order.Count==count,"duplicate overwrite does not replay package");
TestState.Order.Clear();personaAccepted=false;package.ImportAllData(root);overwrite();Check(TestState.Order.SequenceEqual(new[]{"persona"}),"retired persona capability stops remaining domains");personaAccepted=true;
TestState.Order.Clear();port.ApplyImportedDialogueHistory=(d,o,g)=>{TestState.Order.Add("history");return false;};package.ImportAllData(root);skip();Check(TestState.Order.SequenceEqual(new[]{"persona","history"}),"retired memory capability stops downstream commits");
Write("compressed_memory","hero__export.json","{\"Blocks\":[]}");Write("compressed_memory","invalid__export.json","notJSON");Write("compressed_memory","persona__export.json","{\"HeroId\":\"persona\",\"Personality\":\"synthetic\",\"Background\":\"synthetic\"}");TestState.Order.Clear();knowledgeValid=false;package.ImportHeroNpcAllData(root);overwrite();Check(TestState.Order.Count==0,"hero package validation failure prevents any domain mutation");
knowledgeValid=true;Dictionary<string,CompressedMemoryExportBundle> bundles=new();bool lastOverwrite=true;port.ApplyCompressedMemoryExportBundle=(id,b,o)=>{TestState.Order.Add("compressed");bundles[id]=b;lastOverwrite=o;return true;};package.ImportHeroNpcAllData(root);skip();Check(TestState.Order.SequenceEqual(new[]{"persona","compressed","debt"})&&bundles.Count==1&&!lastOverwrite,"hero package original order and skip flag with invalid bundle excluded");Check(InformationManager.Messages.Any(m=>m.Contains("跳过 2 个无效压缩记忆文件")),"invalid JSON and wrong persona schema partial success warning preserved");Check(!bundles.ContainsKey("persona"),"persona schema never reaches package memory commit");
TestState.Order.Clear();package.ImportHeroNpcAllData(root);oldOverwrite=overwrite;generation++;oldOverwrite();Check(TestState.Order.Count==0,"late hero package rejected");

var debtHost=new MyBehavior {FixtureConfirmation=execution};var reward=RewardSystemBehavior.Instance;
reward.Snapshot=new(){{"hero",new(){Amount=5}}};TestState.Order.Clear();debtHost.RunSingleDebt(root,"hero");Check(!reward.Snapshot.ContainsKey("hero")&&ReferenceEquals(reward.LastExport,reward.LastCommit),"actual single Debt missing file removes from same exported snapshot before canonical commit");
reward.Snapshot=new(){{"hero",new(){Amount=5}}};var nullFile=Path.Combine(root,"single-null.json");File.WriteAllText(nullFile,"null");debtHost.RunSingleDebt(nullFile,"hero");Check(!reward.Snapshot.ContainsKey("hero")&&ReferenceEquals(reward.LastExport,reward.LastCommit),"actual single Debt null JSON delete retains snapshot reference");
var entryFile=Path.Combine(root,"single-valid.json");File.WriteAllText(entryFile,"{\"Amount\":17}");reward.Snapshot=new(){{"hero",new(){Amount=5}}};TestState.Order.Clear();debtHost.RunSingleDebt(entryFile,"hero");Check(TestState.Order.Count==0&&reward.Snapshot["hero"].Amount==5,"actual single Debt duplicate waits for UI overwrite confirmation");debtHost.FixtureChoices[2]();debtHost.FixtureChoices[0]();Check(reward.Snapshot["hero"].Amount==5,"actual single Debt cancel preserves authoritative entry");
debtHost.RunSingleDebt(entryFile,"hero");debtHost.FixtureChoices[0]();Check(reward.Snapshot["hero"].Amount==17&&ReferenceEquals(reward.LastExport,reward.LastCommit),"actual single Debt nonnull direct assign delegates policy then commits same snapshot");
Console.WriteLine($"PASS: {n} actual package import preparation / confirmation / partial-success assertions (isolated synthetic JSON, stubbed game/domain capabilities, production tolerant reader body).");
