using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Election;
using TaleWorlds.CampaignSystem.Map;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.SaveSystem;

namespace AnimusForge;

// Instant bulletin mode: campaign events are scored locally on arrival (O(1) append, capped list),
// the hourly tick advances one collect window, and each publish issues one LLM request.
// Kingdoms get a local template brief once per week (no LLM); NPCs read live facts instead.
public partial class MyBehavior
{
	private const string WorldBulletinStorageKey = "_af_worldBulletin_v1";

	private const string WorldBulletinBulletinIdMarker = ":bulletin:";

	private WorldBulletinSaveState _worldBulletinState { get => _worldBulletinOwner.State; set => _worldBulletinOwner.State = value; }

	private ConcurrentQueue<Action> _worldBulletinMainThreadActions { get => _worldBulletinOwner.MainThreadActions; }

	private bool _worldBulletinInFlight { get => _worldBulletinOwner.InFlight; set => _worldBulletinOwner.InFlight = value; }

	// Rank captured in BeforeHeroKilledEvent; consumed by the matching HeroKilledEvent in the same call stack.
	private Dictionary<string, WorldBulletinDeathSnapshot> _worldBulletinDeathSnapshots => _worldBulletinEventCapture.DeathSnapshots;

	// Unreadable raw JSON is carried verbatim, then retained inside any newly initialized state.
	private string _worldBulletinCorruptRaw { get => _worldBulletinOwner.CorruptRaw; set => _worldBulletinOwner.CorruptRaw = value; }

	// Id of the newest published bulletin, for the per-prompt NPC lookup (MyBehavior.WorldBulletinNpc.cs).
	private string _worldBulletinLatestEventId { get => _worldBulletinOwner.LatestEventId; set => _worldBulletinOwner.LatestEventId = value; }

	private int _worldBulletinLastPruneDay { get => _worldBulletinOwner.LastPruneDay; set => _worldBulletinOwner.LastPruneDay = value; }

	private WorldBulletinFocus _worldBulletinFocus { get => _worldBulletinEventCapture.Focus; set => _worldBulletinEventCapture.Focus=value; }

	private int _worldBulletinFocusDay { get => _worldBulletinEventCapture.FocusDay; set => _worldBulletinEventCapture.FocusDay=value; }

	private string _worldBulletinFocusOwnKingdomId { get => _worldBulletinEventCapture.FocusOwnKingdomId; set => _worldBulletinEventCapture.FocusOwnKingdomId=value; }

	internal static bool IsWorldBulletinEnabled() => WorldBulletinStateOwner.IsWorldBulletinEnabled();

	private static bool IsWorldBulletinPublishingEnabled() => WorldBulletinStateOwner.IsWorldBulletinPublishingEnabled();

	private static bool IsWorldBulletinEventId(string eventId) => WorldBulletinStateOwner.IsWorldBulletinEventId(eventId);

	private readonly WorldBulletinStateOwner _worldBulletinOwner = new WorldBulletinStateOwner();
 private WorldBulletinPort _worldBulletinPort;
 private WorldBulletinStateOwner WorldBulletinState { get { _worldBulletinOwner.Bind(_worldBulletinPort ??= new WorldBulletinPort { ResolveKingdom=ResolveKingdomDisplay,NoticeTitle=BuildWeeklyReportNoticeTitle,PopupSubtitle=BuildWeeklyReportPopupSubtitle,PopupBody=BuildWeeklyReportPopupBodyText,AutoWeek=()=>_lastAutoGeneratedWeeklyReportWeek,SetAutoWeek=week=>_lastAutoGeneratedWeeklyReportWeek=week,Enabled=IsWorldBulletinEnabled,PublishingEnabled=IsWorldBulletinPublishingEnabled,WritingRequirements=()=>DuelSettings.GetSettings()?.WorldBulletinWritingRequirements,CurrentDay=GetCurrentGameDayIndexSafe,CurrentHour=GetCurrentCampaignHourSafe,CurrentDate=GetCurrentGameDateTextSafe,Focus=GetWorldBulletinFocus,Render=PlayerNotorietyBehavior.RenderPlayerNamedReferenceForExternal,CapturePromptFacts=CaptureWorldBulletinPromptFacts,PrepareSelection=plan=>WorldBulletinPanelIllustrationBridge.PrepareSelection?.Invoke(plan),AwaitIllustration=(plan,release)=>WorldBulletinPanelIllustrationBridge.AwaitSelection?.Invoke(plan,release)==true,CancelIllustration=CancelWorldBulletinIllustration,PrepareIssue=PrepareWorldBulletinIssue,QueueNotice=QueueWeeklyReportMapNotice,Records=()=>_eventRecordEntries??=new List<EventRecordEntry>(),FindRecord=FindWeeklyReportRecordById,ProductState=BuildPublishedWorldWeeklyProductState,NotifyProductChanged=NotifyPublishedWorldWeeklyProductChanged,NotifyTimeline=NotifyWorldMessageWeeklyTimelineChanged,EligibleKingdoms=()=>GetDevEditableKingdoms().Where(IsKingdomEligibleForWeeklyReport).Select(k=>new KeyValuePair<string,string>(GetKingdomId(k),GetKingdomDisplayName(k))).ToList(),CallApi=CallWeeklyReportApiDetailed,Log=Logger.Log });return _worldBulletinOwner; } }
 private WorldBulletinPromptFacts CaptureWorldBulletinPromptFacts(WorldBulletinSelection selection,WorldBulletinFocus focus) => _worldBulletinEventCapture.CaptureWorldBulletinPromptFacts(selection, focus);
 private void PrepareWorldBulletinIssue(string eventId) {var prepare=WorldBulletinPanelIllustrationBridge.PrepareIssue;if(prepare==null)return;var published=FindWeeklyReportRecordById(eventId);if(published!=null)prepare(eventId,BuildWeeklyReportNoticeTitle(published),BuildWeeklyReportPopupSubtitle(published),BuildWeeklyReportPopupBodyText(published));}
 private WorldBulletinSaveState EnsureWorldBulletinState() => WorldBulletinState.EnsureWorldBulletinState();

	private void RegisterWorldBulletinEvents()
	{
		CampaignEvents.HourlyTickEvent.AddNonSerializedListener(this, OnWorldBulletinHourlyTick);
		CampaignEvents.WarDeclared.AddNonSerializedListener(this, OnWorldBulletinWarDeclared);
		CampaignEvents.MakePeace.AddNonSerializedListener(this, OnWorldBulletinMakePeace);
		CampaignEvents.OnSettlementOwnerChangedEvent.AddNonSerializedListener(this, OnWorldBulletinSettlementOwnerChanged);
		CampaignEvents.BeforeHeroKilledEvent.AddNonSerializedListener(this, OnWorldBulletinBeforeHeroKilled);
		CampaignEvents.HeroKilledEvent.AddNonSerializedListener(this, OnWorldBulletinHeroKilled);
		CampaignEvents.HeroPrisonerTaken.AddNonSerializedListener(this, OnWorldBulletinHeroPrisonerTaken);
		CampaignEvents.MapEventEnded.AddNonSerializedListener(this, OnWorldBulletinMapEventEnded);
		CampaignEvents.KingdomDestroyedEvent.AddNonSerializedListener(this, OnWorldBulletinKingdomDestroyed);
		CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, OnWorldBulletinClanChangedKingdom);
		CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, RememberDiscontinuedKingdomRuler);
		CampaignEvents.RaidCompletedEvent.AddNonSerializedListener(this, OnWorldBulletinRaidCompleted);
		CampaignEvents.OnAllianceStartedEvent.AddNonSerializedListener(this, OnWorldBulletinAllianceStarted);
		CampaignEvents.OnAllianceEndedEvent.AddNonSerializedListener(this, OnWorldBulletinAllianceEnded);
		CampaignEvents.RulingClanChanged.AddNonSerializedListener(this, OnWorldBulletinRulingClanChanged);
		CampaignEvents.BeforeHeroesMarried.AddNonSerializedListener(this, OnWorldBulletinHeroesMarried);
		CampaignEvents.OnClanDefectedEvent.AddNonSerializedListener(this, OnWorldBulletinClanDefected);
		CampaignEvents.OnClanDestroyedEvent.AddNonSerializedListener(this, OnWorldBulletinClanDestroyed);
		CampaignEvents.ArmyGathered.AddNonSerializedListener(this, OnWorldBulletinArmyGathered);
		CampaignEvents.TownRebelliosStateChanged.AddNonSerializedListener(this, OnWorldBulletinTownRebelliousStateChanged);
		CampaignEvents.RebellionFinished.AddNonSerializedListener(this, OnWorldBulletinTownRebellion);
	}

	// ---------- event capture ----------

	private static double GetCurrentCampaignHourSafe()
	{
		try
		{
			return CampaignTime.Now.ToHours;
		}
		catch
		{
			return GetCurrentGameDayIndexSafe() * 24.0;
		}
	}

	// Home kingdom (the player's, else the nearest, like the legacy report) plus the 3 nearest kingdoms.
	// The proximity scan walks Settlement.All, so the focus is cached for one campaign day;
	// a change of the player's own kingdom refreshes it at once.
	private WorldBulletinFocus GetWorldBulletinFocus() => _worldBulletinEventCapture.GetWorldBulletinFocus();

	private static bool IsWorldBulletinPlayerHero(Hero hero) => WorldBulletinEventCaptureAdapter.IsWorldBulletinPlayerHero(hero);

	// Returns true only for a newly recorded fact, so callers apply stability once per fact.
	private bool CaptureWorldBulletinEvent(string kind, string key, int score, string sentence, bool involvesPlayer, string group, string detail, params string[] kingdomIds) => WorldBulletinState.CaptureWorldBulletinEvent(kind, key, score, sentence, involvesPlayer, group, detail, kingdomIds);

internal static void RecordDiplomacyBulletinMaterial(string documentId, string sentence, string detail,
        string authorKingdomId, string targetKingdomId, string authorHeroId, int day)
    {
        var owner = Instance ?? Campaign.Current?.GetCampaignBehavior<MyBehavior>();
        if (owner == null || !IsWorldBulletinEnabled() || day != GetCurrentGameDayIndexSafe() || string.IsNullOrWhiteSpace(documentId)) return;
        try
        {
            owner.WorldBulletinState.CaptureCivilNewsMaterial("diplomatic_declaration", "declaration:" + documentId,
                sentence, detail, authorHeroId == Hero.MainHero?.StringId, authorKingdomId, targetKingdomId);
        }
        catch (Exception ex) { Logger.Log("WorldBulletin", "[WARN] declaration capture: " + ex.Message); }
    }

	private static WorldBulletinParticipant[] BulletinParticipants(params (Hero Hero, string Role)[] people) => WorldBulletinEventCaptureAdapter.BulletinParticipants(people);

	private bool CaptureWorldBulletinEvent(string kind, string key, int score, string sentence, bool involvesPlayer, string group, string detail, WorldBulletinParticipant[] participants, params string[] kingdomIds) => WorldBulletinState.CaptureWorldBulletinEvent(kind,key,score,sentence,involvesPlayer,group,detail,participants,kingdomIds);

	// Final Coup facts arrive only after political/casualty settlement. True means handled,
	// including an explicit settings-off skip; disabling news must not block gameplay settlement.
	internal bool TryRecordCoupOutcomeForBulletin(string coupId, bool success, string sentence, string detail, string kingdomId, string actorKingdomId) => WorldBulletinState.TryRecordCoupOutcomeForBulletin(coupId, success, sentence, detail, kingdomId, actorKingdomId);

	internal bool TryRecordCoupOutcomeWithParticipantsForBulletin(string coupId, bool success, string sentence, string detail, string kingdomId, string actorKingdomId, string actorId, string formerKingId) => WorldBulletinState.TryRecordCoupOutcomeWithParticipantsForBulletin(coupId, success, sentence, detail, kingdomId, actorKingdomId, actorId, formerKingId);

	// Bulletin stability replaces the legacy weekly STAB tags, so it runs only when bulletins actually publish;
	// with auto weekly reports off, stability stays as untouched as it was before.
	private void ApplyWorldBulletinStability(string kingdomId,int delta) => _kingdomStabilityGameAdapter.ApplyWorldBulletinStability(kingdomId,delta,() => WorldBulletinState,WorldBulletinStateOwner.IsWorldBulletinPublishingEnabled);

	private void OnWorldBulletinWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail) => _worldBulletinEventCapture.OnWorldBulletinWarDeclared(faction1, faction2, detail);

	private void OnWorldBulletinMakePeace(IFaction side1, IFaction side2, MakePeaceAction.MakePeaceDetail detail) => _worldBulletinEventCapture.OnWorldBulletinMakePeace(side1, side2, detail);

    private static string GetWorldBulletinWarReason(DeclareWarAction.DeclareWarDetail detail)
        => WorldBulletinCampaignMaterialPolicy.WarReason(detail.ToString());

	// Order-independent, so A-vs-B war and B-vs-A peace land in one story.
	private static string WorldBulletinPairKey(IFaction a, IFaction b) => WorldBulletinEventCaptureAdapter.WorldBulletinPairKey(a, b);

	private static string WorldBulletinHeroTitle(Hero hero) => WorldBulletinEventCaptureAdapter.WorldBulletinHeroTitle(hero);

	private void OnWorldBulletinSettlementOwnerChanged(Settlement settlement, bool openToClaim, Hero newOwner, Hero oldOwner, Hero capturerHero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail detail) => _worldBulletinEventCapture.OnWorldBulletinSettlementOwnerChanged(settlement, openToClaim, newOwner, oldOwner, capturerHero, detail);

	private static bool IsWorldBulletinRuler(Hero hero) => WorldBulletinEventCaptureAdapter.IsWorldBulletinRuler(hero);

	// KillCharacterAction hands the clan and throne to the heir (and may detach a heirless clan from its kingdom)
	// before HeroKilledEvent fires, in both 1.3.x and 1.4.x. Rank and realm are therefore read here, one event earlier.
	private void OnWorldBulletinBeforeHeroKilled(Hero victim, Hero killer, KillCharacterAction.KillCharacterActionDetail detail, bool showNotification) => _worldBulletinEventCapture.OnWorldBulletinBeforeHeroKilled(victim,killer,detail,showNotification);

	internal sealed class WorldBulletinDeathSnapshot
	{
		public Hero Hero;

		public bool Ruler;

		public string KingdomId = "";

		public string Title = "";
	}

	private void OnWorldBulletinHeroKilled(Hero victim, Hero killer, KillCharacterAction.KillCharacterActionDetail detail, bool showNotification) => _worldBulletinEventCapture.OnWorldBulletinHeroKilled(victim,killer,detail,showNotification);

	private void OnWorldBulletinHeroPrisonerTaken(PartyBase capturer, Hero prisoner) => _worldBulletinEventCapture.OnWorldBulletinHeroPrisonerTaken(capturer, prisoner);

	private void OnWorldBulletinMapEventEnded(MapEvent mapEvent) => _worldBulletinEventCapture.OnWorldBulletinMapEventEnded(mapEvent);

	private void OnWorldBulletinKingdomDestroyed(Kingdom kingdom) => _worldBulletinEventCapture.OnWorldBulletinKingdomDestroyed(kingdom);

	private void OnWorldBulletinClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification) => _worldBulletinEventCapture.OnWorldBulletinClanChangedKingdom(clan, oldKingdom, newKingdom, detail, showNotification);

	private void OnWorldBulletinRaidCompleted(BattleSideEnum winnerSide, RaidEventComponent raidEvent) => _worldBulletinEventCapture.OnWorldBulletinRaidCompleted(winnerSide, raidEvent);

	internal void CaptureWorldBulletinCivilWar(string kingdomId, string stableKey) => _worldBulletinEventCapture.CaptureWorldBulletinCivilWar(kingdomId, stableKey);

	private void OnWorldBulletinAllianceStarted(Kingdom k1, Kingdom k2) => _worldBulletinEventCapture.OnWorldBulletinAllianceStarted(k1, k2);

private void OnWorldBulletinAllianceEnded(Kingdom k1, Kingdom k2) => _worldBulletinEventCapture.OnWorldBulletinAllianceEnded(k1, k2);

private void OnWorldBulletinRulingClanChanged(Kingdom kingdom, Clan eventRulingClan) => _worldBulletinEventCapture.OnWorldBulletinRulingClanChanged(kingdom, eventRulingClan);

private void OnWorldBulletinHeroesMarried(Hero first, Hero second, bool showNotification) => _worldBulletinEventCapture.OnWorldBulletinHeroesMarried(first, second, showNotification);

private void OnWorldBulletinClanDefected(Clan clan, Kingdom oldKingdom, Kingdom newKingdom) => _worldBulletinEventCapture.OnWorldBulletinClanDefected(clan, oldKingdom, newKingdom);

private void OnWorldBulletinClanDestroyed(Clan clan) => _worldBulletinEventCapture.OnWorldBulletinClanDestroyed(clan);

private void OnWorldBulletinArmyGathered(Army army, IMapPoint gatheringPoint) => _worldBulletinEventCapture.OnWorldBulletinArmyGathered(army, gatheringPoint);

private void OnWorldBulletinTownRebelliousStateChanged(Town town, bool rebellious) => _worldBulletinEventCapture.OnWorldBulletinTownRebelliousStateChanged(town, rebellious);

private void OnWorldBulletinTownRebellion(Settlement settlement, Clan oldOwnerClan) => _worldBulletinEventCapture.OnWorldBulletinTownRebellion(settlement, oldOwnerClan);

internal void CaptureWorldBulletinAnnexation(Kingdom receiving, Kingdom annexed, Hero formerRuler, int transferredClans) => _worldBulletinEventCapture.CaptureWorldBulletinAnnexation(receiving, annexed, formerRuler, transferredClans);

internal void CaptureWorldBulletinVassalage(Kingdom suzerain, Kingdom vassal, string typeName, bool established) => _worldBulletinEventCapture.CaptureWorldBulletinVassalage(suzerain, vassal, typeName, established);

internal static bool SuppressWorldBulletinRulerChange { get => WorldBulletinEventCaptureAdapter.SuppressWorldBulletinRulerChange; set => WorldBulletinEventCaptureAdapter.SuppressWorldBulletinRulerChange = value; }

private void RememberDiscontinuedKingdomRuler(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification) => _worldBulletinEventCapture.RememberDiscontinuedKingdomRuler(clan, oldKingdom, newKingdom, detail, showNotification);

	// ---------- hourly scheduling ----------

	private void OnWorldBulletinHourlyTick() => WorldBulletinState.OnWorldBulletinHourlyTick();

	private static void PruneWorldBulletinWeeklyStability(WorldBulletinSaveState state, int currentWeek) => WorldBulletinStateOwner.PruneWorldBulletinWeeklyStability(state, currentWeek);

	private void AdvanceWorldBulletinScope(WorldBulletinSaveState state, double now) => WorldBulletinState.AdvanceWorldBulletinScope(state, now);

	// Main thread, once per publish: at most four kingdoms, each checked against the others for war.
	private List<string> BuildWorldBulletinKingdomContext(WorldBulletinSelection selection) => _worldBulletinEventCapture.BuildWorldBulletinKingdomContext(selection);

	private async Task RunWorldBulletinRequestAsync(double windowEndHour, long generation, WorldBulletinSelection selection, WorldBulletinText template, string systemPrompt, string userPrompt, WorldBulletinIllustrationPlan illustrationPlan) => await WorldBulletinState.RunWorldBulletinRequestAsync(windowEndHour, generation, selection, template, systemPrompt, userPrompt, illustrationPlan);

	private void ProcessWorldBulletinMainThreadActions() => WorldBulletinState.ProcessWorldBulletinMainThreadActions();

	private void CompleteWorldBulletin(double windowEndHour, long generation, WorldBulletinSelection selection, WorldBulletinText template, WorldBulletinText generated, WorldBulletinIllustrationPlan illustrationPlan) => WorldBulletinState.CompleteWorldBulletin(windowEndHour, generation, selection, template, generated, illustrationPlan);

	private static void CancelWorldBulletinIllustration(WorldBulletinIllustrationPlan plan)
	{
		try { if (plan != null) WorldBulletinPanelIllustrationBridge.CancelSelection?.Invoke(plan); }
		catch (Exception ex) { Logger.Log("WorldBulletin", "[Illustration] cancel failed: " + ex.Message); }
	}

	private void PublishWorldBulletin(WorldBulletinScopeState scope, WorldBulletinSelection selection, WorldBulletinText template, WorldBulletinText generated, WorldBulletinIllustrationPlan illustrationPlan) => WorldBulletinState.PublishWorldBulletin(scope, selection, template, generated, illustrationPlan);

	private void UpsertWorldBulletinRecord(string eventId, string eventKind, string scopeKingdomId, string title, string shortSummary, string summary, int day) => WorldBulletinState.UpsertWorldBulletinRecord(eventId, eventKind, scopeKingdomId, title, shortSummary, summary, day);

	// ---------- weekly kingdom briefs ----------

	// Local template only: an archive line per kingdom for the browser and the stability history.
	// NPCs read live facts (MyBehavior.WorldBulletinNpc.cs), so no LLM polish is spent here.

	// ---------- persistence / lifecycle ----------

	private void SyncWorldBulletinData(IDataStore dataStore) => CampaignWorldBulletinPersistenceAdapter.Sync(dataStore, WorldBulletinState, ResetWorldBulletinTransientState);

	private void ResetWorldBulletinTransientState(){WorldBulletinState.ResetTransient();_worldBulletinFocus=null;_worldBulletinFocusDay=-1;_worldBulletinFocusOwnKingdomId="";_worldBulletinDeathSnapshots.Clear();}

	private void ResetWorldBulletinForRuntime(string reason){ResetWorldBulletinTransientState();WorldBulletinState.ResetRuntime(reason);}
}
