using System;
using System.Collections.Generic;
using System.Threading;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Core;
using TaleWorlds.Library;

namespace AnimusForge;

public partial class MyBehavior
{
    private int _newsCollectionEpoch;
    private int _newsMaterialEndSequence = -1;
    private double _newsMaterialEndHour = -1;
    private bool _newsCollectionNewGame;
    private bool HasRestartedWeeklyCollection => _worldBulletinState?.WeeklyCollectionStartHour >= 0;

    // Main thread, O(1) on the existing engine tick. No history or NPC scan.
    private void SynchronizeNewsCollectionMode()
    {
        if (Campaign.Current == null || !ReferenceEquals(Instance, this) || !TWParallel.IsMainThread()) return;
        bool bulletin = IsWorldBulletinEnabled();
        var state = EnsureWorldBulletinState();
        if (!state.CollectionBulletinMode.HasValue && !_newsCollectionNewGame) { state.CollectionBulletinMode = bulletin; return; }
        if (state.CollectionBulletinMode == bulletin && !_newsCollectionNewGame) return;
        bool newGame = _newsCollectionNewGame;
        _newsCollectionNewGame = false;
        Interlocked.Increment(ref _newsCollectionEpoch);
        state.CollectionBulletinMode = bulletin;
        state.WeeklyCollectionStartHour = GetCurrentCampaignHourSafe();
        state.WeeklyCollectionStartSequence = _npcActionGlobalOrderCounter;
        _newsMaterialEndSequence = -1; _newsMaterialEndHour = -1;
        _weeklyRuntime = null;
        _weeklyReportMaterialRevisions.MarkAll();
        _weeklyEditor?.CancelForNewsModeChange();
        _pendingAutoWeeklyReportBuild = null;
        _weeklyReportGenerationInProgress = false;
        _weeklyAutoSchedule.Clear();
        _weeklyPromptPreparationQueue.CancelAll();
        _weeklyWaveLaunchQueue.CancelAll();
        _weeklyBatchApiAttemptQueue.CancelAll();
        _weeklyReportCommitQueue.CancelAll();
        // Remove only weekly generation jobs; keep other daily maintenance intact.
        int count = _dailyMaintenanceQueue.Count;
        for (int i = 0; i < count; i++)
        {
            var job = _dailyMaintenanceQueue.Dequeue();
            if (job.Kind == DailyMaintenanceTaskKind.PrepareAutoWeeklyReports)
                _dailyMaintenanceJobKeys.Remove(BuildDailyMaintenanceJobKey(job.Kind, job.DayIndex, job.WeekIndex, job.StartDay, job.EndDay));
            else _dailyMaintenanceQueue.Enqueue(job);
        }
        _lastAutoGeneratedWeeklyReportWeek = Math.Max(_lastAutoGeneratedWeeklyReportWeek, GetCurrentGameDayIndexSafe() / 7);
        WorldBulletinState.RestartCollection(state.WeeklyCollectionStartHour);
        InformationManager.DisplayMessage(new InformationMessage(newGame
            ? (bulletin ? "快报已从本次开局开始收集事件。" : "周报已从本次开局开始收集，累计7个游戏日后生成第一期。")
            : bulletin
            ? "已切换快报：从现在重新收集事件，历史档案保留。"
            : "已切换周报：从现在重新收集，累计7个游戏日后生成第一期；旧重试已取消。"));
        Logger.Log("EventWeeklyReport", "[ModeRestart] bulletin=" + bulletin + " hour=" + state.WeeklyCollectionStartHour + " sequence=" + state.WeeklyCollectionStartSequence);
    }

    // Hourly only; preparation reuses the existing frame-budgeted weekly collector.
    private void TryStartRestartedWeeklyCollection()
    {
        var state = _worldBulletinState;
        if (!HasRestartedWeeklyCollection || IsWorldBulletinEnabled() || _weeklyReportGenerationInProgress
            || _weeklyEditor?.RetryContext != null || !(DuelSettings.GetSettings()?.IsLegacyWeeklyAutoGenerationActive() ?? false)
            || AutomaticKingdomRebellions.FlowActive || !NewsCollectionPolicy.IsWeeklyDue(state.WeeklyCollectionStartHour, GetCurrentCampaignHourSafe())) return;
        int day = GetCurrentGameDayIndexSafe();
        _newsMaterialEndSequence = _npcActionGlobalOrderCounter;
        _newsMaterialEndHour = GetCurrentCampaignHourSafe();
        int startDay = Math.Max(0, (int)Math.Floor(state.WeeklyCollectionStartHour / 24.0));
        int week = Math.Max(_lastAutoGeneratedWeeklyReportWeek + 1, day / 7);
        TryInitializePendingAutoWeeklyReportBuild(new DailyMaintenanceJob {
            Kind = DailyMaintenanceTaskKind.PrepareAutoWeeklyReports, DayIndex = day, WeekIndex = week,
            StartDay = startDay, EndDay = day, Reason = "news_mode_fresh_seven_days"
        });
    }

    private bool IsAfterNewsCollectionStart(int sequence) => NewsCollectionPolicy.Includes(sequence,
        _worldBulletinState?.WeeklyCollectionStartSequence ?? -1, _newsMaterialEndSequence);

    private void CompleteRestartedWeeklyCollection()
    {
        if (!HasRestartedWeeklyCollection || _newsMaterialEndHour < 0) return;
        _worldBulletinState.WeeklyCollectionStartHour = _newsMaterialEndHour;
        _worldBulletinState.WeeklyCollectionStartSequence = _newsMaterialEndSequence;
        _newsMaterialEndHour = -1; _newsMaterialEndSequence = -1;
    }
}
