using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.SaveSystem;

namespace AnimusForge;

// Instant bulletin mode: campaign events are scored locally on arrival (O(1) append, capped list),
// the hourly tick advances one collect window, and each publish issues one LLM request.
// Kingdoms get a local template brief once per week (no LLM); NPCs read live facts instead.
public partial class MyBehavior
{
	private const string WorldBulletinStorageKey = "_af_worldBulletin_v1";

	private const string WorldBulletinBulletinIdMarker = ":bulletin:";

	private WorldBulletinSaveState _worldBulletinState { get => _worldBulletinOwner.State; set => _worldBulletinOwner.State = value; }

	private ConcurrentQueue<Action> _worldBulletinMainThreadActions { get => _worldBulletinOwner.MainThreadActions; }

	private bool _worldBulletinInFlight { get => _worldBulletinOwner.InFlight; set => _worldBulletinOwner.InFlight = value; }

	// Rank captured in BeforeHeroKilledEvent; consumed by the matching HeroKilledEvent in the same call stack.
	private readonly Dictionary<string, WorldBulletinDeathSnapshot> _worldBulletinDeathSnapshots = new Dictionary<string, WorldBulletinDeathSnapshot>(StringComparer.Ordinal);

	// Unreadable raw JSON is carried verbatim, then retained inside any newly initialized state.
	private string _worldBulletinCorruptRaw { get => _worldBulletinOwner.CorruptRaw; set => _worldBulletinOwner.CorruptRaw = value; }

	// Id of the newest published bulletin, for the per-prompt NPC lookup (MyBehavior.WorldBulletinNpc.cs).
	private string _worldBulletinLatestEventId { get => _worldBulletinOwner.LatestEventId; set => _worldBulletinOwner.LatestEventId = value; }

	private int _worldBulletinLastPruneDay { get => _worldBulletinOwner.LastPruneDay; set => _worldBulletinOwner.LastPruneDay = value; }

	private WorldBulletinFocus _worldBulletinFocus;

	private int _worldBulletinFocusDay = -1;

	private string _worldBulletinFocusOwnKingdomId = "";

	internal static bool IsWorldBulletinEnabled()
	{
		try
		{
			return DuelSettings.GetSettings()?.UseWorldBulletin ?? true;
		}
		catch
		{
			return true;
		}
	}

	private static bool IsWorldBulletinPublishingEnabled()
	{
		try
		{
			DuelSettings settings = DuelSettings.GetSettings();
			return settings == null || (settings.UseWorldBulletin && settings.AutoGenerateWeeklyReports);
		}
		catch
		{
			return true;
		}
	}

	private static bool IsWorldBulletinEventId(string eventId) => WorldBulletinStateOwner.IsWorldBulletinEventId(eventId);

	private readonly WorldBulletinStateOwner _worldBulletinOwner = new WorldBulletinStateOwner();
 private WorldBulletinPort _worldBulletinPort;
 private WorldBulletinStateOwner WorldBulletinState { get { _worldBulletinOwner.Bind(_worldBulletinPort ??= new WorldBulletinPort { ResolveKingdom=ResolveKingdomDisplay,NoticeTitle=BuildWeeklyReportNoticeTitle,PopupSubtitle=BuildWeeklyReportPopupSubtitle,PopupBody=BuildWeeklyReportPopupBodyText,AutoWeek=()=>_lastAutoGeneratedWeeklyReportWeek,SetAutoWeek=week=>_lastAutoGeneratedWeeklyReportWeek=week,Enabled=IsWorldBulletinEnabled,PublishingEnabled=IsWorldBulletinPublishingEnabled,CurrentDay=GetCurrentGameDayIndexSafe,CurrentHour=GetCurrentCampaignHourSafe,CurrentDate=GetCurrentGameDateTextSafe,Focus=GetWorldBulletinFocus,Render=PlayerNotorietyBehavior.RenderPlayerNamedReferenceForExternal,CapturePromptFacts=CaptureWorldBulletinPromptFacts,PrepareSelection=plan=>WorldBulletinPanelIllustrationBridge.PrepareSelection?.Invoke(plan),AwaitIllustration=(plan,release)=>WorldBulletinPanelIllustrationBridge.AwaitSelection?.Invoke(plan,release)==true,CancelIllustration=CancelWorldBulletinIllustration,PrepareIssue=PrepareWorldBulletinIssue,QueueNotice=QueueWeeklyReportMapNotice,Records=()=>_eventRecordEntries??=new List<EventRecordEntry>(),FindRecord=FindWeeklyReportRecordById,ProductState=BuildPublishedWorldWeeklyProductState,NotifyProductChanged=NotifyPublishedWorldWeeklyProductChanged,NotifyTimeline=NotifyWorldMessageWeeklyTimelineChanged,EligibleKingdoms=()=>GetDevEditableKingdoms().Where(IsKingdomEligibleForWeeklyReport).Select(k=>new KeyValuePair<string,string>(GetKingdomId(k),GetKingdomDisplayName(k))).ToList(),CallApi=CallWeeklyReportApiDetailed,Log=Logger.Log });return _worldBulletinOwner; } }
 private WorldBulletinPromptFacts CaptureWorldBulletinPromptFacts(WorldBulletinSelection selection,WorldBulletinFocus focus) { Kingdom home=FindKingdomById(focus.PlayerKingdomId);return new WorldBulletinPromptFacts {ScopeLine="快报视角：天下大事，但以"+(home!=null?GetKingdomDisplayName(home):"玩家所在地区")+"读者关心的角度组织；与玩家本人或该国相关的事实优先交代",Date=GetCurrentGameDateTextSafe(),KingdomContext=BuildWorldBulletinKingdomContext(selection)}; }
 private void PrepareWorldBulletinIssue(string eventId) {var prepare=WorldBulletinPanelIllustrationBridge.PrepareIssue;if(prepare==null)return;var published=FindWeeklyReportRecordById(eventId);if(published!=null)prepare(eventId,BuildWeeklyReportNoticeTitle(published),BuildWeeklyReportPopupSubtitle(published),BuildWeeklyReportPopupBodyText(published));}
 private WorldBulletinSaveState EnsureWorldBulletinState() => WorldBulletinState.EnsureWorldBulletinState();

	private void RegisterWorldBulletinEvents()
	{
		CampaignEvents.HourlyTickEvent.AddNonSerializedListener(this, OnWorldBulletinHourlyTick);
		CampaignEvents.WarDeclared.AddNonSerializedListener(this, OnWorldBulletinWarDeclared);
		CampaignEvents.MakePeace.AddNonSerializedListener(this, OnWorldBulletinMakePeace);
		CampaignEvents.OnSettlementOwnerChangedEvent.AddNonSerializedListener(this, OnWorldBulletinSettlementOwnerChanged);
		CampaignEvents.BeforeHeroKilledEvent.AddNonSerializedListener(this, OnWorldBulletinBeforeHeroKilled);
		CampaignEvents.HeroKilledEvent.AddNonSerializedListener(this, OnWorldBulletinHeroKilled);
		CampaignEvents.HeroPrisonerTaken.AddNonSerializedListener(this, OnWorldBulletinHeroPrisonerTaken);
		CampaignEvents.MapEventEnded.AddNonSerializedListener(this, OnWorldBulletinMapEventEnded);
		CampaignEvents.KingdomDestroyedEvent.AddNonSerializedListener(this, OnWorldBulletinKingdomDestroyed);
		CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, OnWorldBulletinClanChangedKingdom);
		CampaignEvents.RaidCompletedEvent.AddNonSerializedListener(this, OnWorldBulletinRaidCompleted);
	}

	// ---------- event capture ----------

	private static double GetCurrentCampaignHourSafe()
	{
		try
		{
			return CampaignTime.Now.ToHours;
		}
		catch
		{
			return GetCurrentGameDayIndexSafe() * 24.0;
		}
	}

	// Home kingdom (the player's, else the nearest, like the legacy report) plus the 3 nearest kingdoms.
	// The proximity scan walks Settlement.All, so the focus is cached for one campaign day;
	// a change of the player's own kingdom refreshes it at once.
	private WorldBulletinFocus GetWorldBulletinFocus()
	{
		try
		{
			string own = GetKingdomId(Clan.PlayerClan?.Kingdom);
			int day = GetCurrentGameDayIndexSafe();
			if (_worldBulletinFocus == null || day != _worldBulletinFocusDay || !string.Equals(own, _worldBulletinFocusOwnKingdomId, StringComparison.OrdinalIgnoreCase))
			{
				List<string> nearest = GetKingdomIdsByPlayerProximity(GetDevEditableKingdoms().Where(IsKingdomEligibleForWeeklyReport).Select(k => GetKingdomId(k)))
					.Where(x => !string.IsNullOrWhiteSpace(x)).Take(3).ToList();
				_worldBulletinFocus = new WorldBulletinFocus
				{
					PlayerKingdomId = own.Length > 0 ? own : nearest.FirstOrDefault() ?? "",
					NearbyKingdomIds = new HashSet<string>(nearest, StringComparer.OrdinalIgnoreCase)
				};
				_worldBulletinFocusDay = day;
				_worldBulletinFocusOwnKingdomId = own;
			}
			return _worldBulletinFocus;
		}
		catch
		{
			return new WorldBulletinFocus();
		}
	}

	private static bool IsWorldBulletinPlayerHero(Hero hero)
	{
		return hero != null && (hero == Hero.MainHero || (hero.Clan != null && hero.Clan == Clan.PlayerClan));
	}

	// Returns true only for a newly recorded fact, so callers apply stability once per fact.
	private bool CaptureWorldBulletinEvent(string kind, string key, int score, string sentence, bool involvesPlayer, string group, string detail, params string[] kingdomIds) => WorldBulletinState.CaptureWorldBulletinEvent(kind, key, score, sentence, involvesPlayer, group, detail, kingdomIds);

	private static WorldBulletinParticipant[] BulletinParticipants(params (Hero Hero, string Role)[] people)
	{
		return people.Where(x => x.Hero != null).GroupBy(x => x.Hero.StringId).Take(4)
			.Select(x => new WorldBulletinParticipant { HeroId = x.Key, Name = x.First().Hero.Name?.ToString() ?? "", Role = x.First().Role }).ToArray();
	}

	private bool CaptureWorldBulletinEvent(string kind, string key, int score, string sentence, bool involvesPlayer, string group, string detail, WorldBulletinParticipant[] participants, params string[] kingdomIds) => WorldBulletinState.CaptureWorldBulletinEvent(kind,key,score,sentence,involvesPlayer,group,detail,participants,kingdomIds);

	// Final Coup facts arrive only after political/casualty settlement. True means handled,
	// including an explicit settings-off skip; disabling news must not block gameplay settlement.
	internal bool TryRecordCoupOutcomeForBulletin(string coupId, bool success, string sentence, string detail, string kingdomId, string actorKingdomId) => WorldBulletinState.TryRecordCoupOutcomeForBulletin(coupId, success, sentence, detail, kingdomId, actorKingdomId);

	internal bool TryRecordCoupOutcomeWithParticipantsForBulletin(string coupId, bool success, string sentence, string detail, string kingdomId, string actorKingdomId, string actorId, string formerKingId) => WorldBulletinState.TryRecordCoupOutcomeWithParticipantsForBulletin(coupId, success, sentence, detail, kingdomId, actorKingdomId, actorId, formerKingId);

	// Bulletin stability replaces the legacy weekly STAB tags, so it runs only when bulletins actually publish;
	// with auto weekly reports off, stability stays as untouched as it was before.
	private void ApplyWorldBulletinStability(string kingdomId,int delta) { if(delta==0||!IsWorldBulletinPublishingEnabled()||!DuelSettings.IsKingdomStabilityAndRebellionEnabled())return;Kingdom kingdom=FindKingdomById(kingdomId);if(kingdom==null||kingdom.IsEliminated)return;string id=GetKingdomId(kingdom);WorldBulletinState.ApplyStability(id,delta,GetCurrentGameDayIndexSafe(),GetKingdomStabilityValue(kingdom),value=>KingdomStability.Set(id,value));}

	private void OnWorldBulletinWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
	{
		try
		{
			if (!(faction1 is Kingdom k1) || !(faction2 is Kingdom k2))
			{
				return;
			}
			string sentence = WorldBulletinCampaignMaterialPolicy.WarSentence(GetKingdomDisplayName(k1), GetKingdomDisplayName(k2));
			string detailText = WorldBulletinCampaignMaterialPolicy.WarDetail(GetHeroDisplayName(k1.Leader), GetHeroDisplayName(k2.Leader), GetWorldBulletinWarReason(detail));
			CaptureWorldBulletinEvent("war_declared", "war:" + GetKingdomId(k1) + ":" + GetKingdomId(k2) + ":" + GetCurrentGameDayIndexSafe(), WorldBulletinCampaignMaterialPolicy.EventPriority("war_declared"), sentence, false,
				"diplomacy:" + WorldBulletinPairKey(k1, k2), detailText, BulletinParticipants((k1.Leader, "宣战方君主，未证实亲临现场"), (k2.Leader, "被宣战方君主，未证实亲临现场")), GetKingdomId(k1), GetKingdomId(k2));
		}
		catch (Exception ex)
		{
			Logger.Log("WorldBulletin", "[ERROR] war declared: " + ex.Message);
		}
	}

	private void OnWorldBulletinMakePeace(IFaction side1, IFaction side2, MakePeaceAction.MakePeaceDetail detail)
	{
		try
		{
			if (!(side1 is Kingdom k1) || !(side2 is Kingdom k2))
			{
				return;
			}
			string sentence = WorldBulletinCampaignMaterialPolicy.PeaceSentence(GetKingdomDisplayName(k1), GetKingdomDisplayName(k2));
			string detailText = WorldBulletinCampaignMaterialPolicy.PeaceDetail(GetKingdomDisplayName(k1), GetHeroDisplayName(k1.Leader), GetKingdomDisplayName(k2), GetHeroDisplayName(k2.Leader), detail == MakePeaceAction.MakePeaceDetail.ByKingdomDecision);
			if (CaptureWorldBulletinEvent("peace_made", "peace:" + GetKingdomId(k1) + ":" + GetKingdomId(k2) + ":" + GetCurrentGameDayIndexSafe(), WorldBulletinCampaignMaterialPolicy.EventPriority("peace_made"), sentence, false,
				"diplomacy:" + WorldBulletinPairKey(k1, k2), detailText, BulletinParticipants((k1.Leader, "议和一方君主，未证实亲临现场"), (k2.Leader, "议和另一方君主，未证实亲临现场")), GetKingdomId(k1), GetKingdomId(k2)))
			{
				ApplyWorldBulletinStability(GetKingdomId(k1), 2);
				ApplyWorldBulletinStability(GetKingdomId(k2), 2);
			}
		}
		catch (Exception ex)
		{
			Logger.Log("WorldBulletin", "[ERROR] make peace: " + ex.Message);
		}
	}

    private static string GetWorldBulletinWarReason(DeclareWarAction.DeclareWarDetail detail)
        => WorldBulletinCampaignMaterialPolicy.WarReason(detail.ToString());

	// Order-independent, so A-vs-B war and B-vs-A peace land in one story.
	private static string WorldBulletinPairKey(IFaction a, IFaction b)
	{
		string x = GetKingdomId(a);
		string y = GetKingdomId(b);
		return WorldBulletinCampaignMaterialPolicy.PairKey(x, y);
	}

	private static string WorldBulletinHeroTitle(Hero hero)
	{
		if (hero == null)
		{
			return "";
		}
		if (IsWorldBulletinRuler(hero))
		{
			return WorldBulletinCampaignMaterialPolicy.HeroTitle(true, GetKingdomDisplayName(hero.Clan?.Kingdom), "", false);
		}
		string clan = GetClanDisplayName(hero.Clan);
		string kingdom = hero.Clan?.Kingdom != null ? GetKingdomDisplayName(hero.Clan.Kingdom) : "";
		bool clanLeader = hero.Clan != null && hero.Clan.Leader == hero;
		return WorldBulletinCampaignMaterialPolicy.HeroTitle(false, kingdom, clan, clanLeader);
	}

	private void OnWorldBulletinSettlementOwnerChanged(Settlement settlement, bool openToClaim, Hero newOwner, Hero oldOwner, Hero capturerHero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail detail)
	{
		try
		{
			if (settlement == null || settlement.IsVillage || (!settlement.IsTown && !settlement.IsCastle))
			{
				return;
			}
			Kingdom newKingdom = newOwner?.Clan?.Kingdom;
			Kingdom oldKingdom = oldOwner?.Clan?.Kingdom;
			string newId = GetKingdomId(newKingdom);
			string oldId = GetKingdomId(oldKingdom);
			string name = GetSettlementDisplayName(settlement);
			bool involvesPlayer = IsWorldBulletinPlayerHero(newOwner) || IsWorldBulletinPlayerHero(oldOwner) || IsWorldBulletinPlayerHero(capturerHero);
			string key = "settlement:" + GetSettlementId(settlement) + ":" + GetHeroId(newOwner) + ":" + GetCurrentGameDayIndexSafe();
			string oldName = GetKingdomDisplayName(oldKingdom, GetClanDisplayName(oldOwner?.Clan) + "家族");
			string newName = GetKingdomDisplayName(newKingdom, GetClanDisplayName(newOwner?.Clan) + "家族");
			string settlementGroup = "siege:" + GetSettlementId(settlement);
			string ownerDetail = WorldBulletinCampaignMaterialPolicy.OwnerDetail(settlement.IsTown, oldOwner != null, GetHeroDisplayName(oldOwner), WorldBulletinHeroTitle(oldOwner), newOwner != null, GetHeroDisplayName(newOwner), WorldBulletinHeroTitle(newOwner));
			if (detail == ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail.BySiege)
			{
				Hero actor = capturerHero ?? newOwner;
				string sentence = WorldBulletinCampaignMaterialPolicy.SiegeSentence(GetHeroDisplayName(actor), name, oldName, newName);
			if (CaptureWorldBulletinEvent("settlement_siege", key, WorldBulletinCampaignMaterialPolicy.SiegePriority(settlement.IsTown), sentence, involvesPlayer, settlementGroup, ownerDetail + "；攻城统帅：" + GetHeroDisplayName(actor), BulletinParticipants((actor, "攻城统帅"), (oldOwner, "原领主，未证实在场"), (newOwner, "新领主，未证实在场")), newId, oldId))
				{
					ApplyWorldBulletinStability(newId, WorldBulletinCampaignMaterialPolicy.SiegeStability(settlement.IsTown, true));
					ApplyWorldBulletinStability(oldId, WorldBulletinCampaignMaterialPolicy.SiegeStability(settlement.IsTown, false));
				}
				return;
			}
			string label = GetSettlementOwnerChangeDetailLabel(detail);
			if (WorldBulletinCampaignMaterialPolicy.SameKingdom(newId, oldId))
			{
				string grant = WorldBulletinCampaignMaterialPolicy.GrantSentence(name, GetHeroDisplayName(newOwner), label);
				CaptureWorldBulletinEvent("fief_grant", key, WorldBulletinCampaignMaterialPolicy.EventPriority("fief_grant"), grant, involvesPlayer, "fief_grant:" + newId + ":" + GetCurrentGameDayIndexSafe(), ownerDetail, BulletinParticipants((newOwner, "获授封地者")), newId);
				return;
			}
			string transfer = WorldBulletinCampaignMaterialPolicy.TransferSentence(name, oldName, newName, label);
			CaptureWorldBulletinEvent("settlement_transfer", key, WorldBulletinCampaignMaterialPolicy.EventPriority("settlement_transfer"), transfer, involvesPlayer, settlementGroup, ownerDetail, BulletinParticipants((newOwner, "新领主"), (oldOwner, "原领主")), newId, oldId);
		}
		catch (Exception ex)
		{
			Logger.Log("WorldBulletin", "[ERROR] settlement owner changed: " + ex.Message);
		}
	}

	private static bool IsWorldBulletinRuler(Hero hero)
	{
		try
		{
			Kingdom kingdom = hero?.Clan?.Kingdom;
			return kingdom != null && (kingdom.Leader == hero || (kingdom.RulingClan == hero.Clan && hero.Clan.Leader == hero));
		}
		catch
		{
			return false;
		}
	}

	// KillCharacterAction hands the clan and throne to the heir (and may detach a heirless clan from its kingdom)
	// before HeroKilledEvent fires, in both 1.3.x and 1.4.x. Rank and realm are therefore read here, one event earlier.
	private void OnWorldBulletinBeforeHeroKilled(Hero victim, Hero killer, KillCharacterAction.KillCharacterActionDetail detail, bool showNotification)
	{
		try
		{
			if (victim == null || victim == Hero.MainHero || !victim.IsLord || !IsWorldBulletinEnabled())
			{
				return;
			}
			_worldBulletinDeathSnapshots[GetHeroId(victim)] = new WorldBulletinDeathSnapshot
			{
				Ruler = IsWorldBulletinRuler(victim),
				KingdomId = GetKingdomId(victim.Clan?.Kingdom),
				Title = WorldBulletinHeroTitle(victim)
			};
		}
		catch (Exception ex)
		{
			Logger.Log("WorldBulletin", "[ERROR] before hero killed: " + ex.Message);
		}
	}

	private sealed class WorldBulletinDeathSnapshot
	{
		public bool Ruler;

		public string KingdomId = "";

		public string Title = "";
	}

	private void OnWorldBulletinHeroKilled(Hero victim, Hero killer, KillCharacterAction.KillCharacterActionDetail detail, bool showNotification)
	{
		try
		{
			if (victim == null || victim == Hero.MainHero || !victim.IsLord)
			{
				return;
			}
			string victimId = GetHeroId(victim);
			_worldBulletinDeathSnapshots.TryGetValue(victimId, out WorldBulletinDeathSnapshot snapshot);
			_worldBulletinDeathSnapshots.Remove(victimId);
			bool ruler = snapshot?.Ruler ?? IsWorldBulletinRuler(victim);
			Kingdom kingdom = (snapshot != null ? FindKingdomById(snapshot.KingdomId) : null) ?? victim.Clan?.Kingdom;
			string victimTitle = snapshot?.Title ?? WorldBulletinHeroTitle(victim);
            string deathDetail = detail.ToString();
            string who = WorldBulletinCampaignMaterialPolicy.KilledWho(ruler,
                kingdom != null || ruler ? GetKingdomDisplayName(kingdom) : "", GetClanDisplayName(victim.Clan), GetHeroDisplayName(victim));
            bool natural = WorldBulletinCampaignMaterialPolicy.IsNaturalDeath(deathDetail);
            string killerName = killer != null ? GetHeroDisplayName(killer) : "";
            VengeanceExecutionFacts executionFacts = ResolvePublicExecutionFacts(victim, detail);
            bool execution = executionFacts != null || IsExecutionKillDetail(detail);
            var material = new WorldBulletinDeathMaterialCapture {
                Who = who, VictimTitle = victimTitle, Age = (int)victim.Age,
                HasKiller = killer != null, KillerName = killerName, KillerTitle = killer != null ? WorldBulletinHeroTitle(killer) : "",
                Detail = deathDetail, Execution = execution, HasPublicExecutionFacts = executionFacts != null,
                Venue = executionFacts != null ? BuildPublicExecutionVenueText(executionFacts) : "",
                Method = executionFacts != null ? BuildPublicExecutionMethodText(executionFacts) : "",
                Charge = executionFacts != null ? BuildPublicExecutionChargeText(executionFacts) : "",
                ToneLabel = executionFacts?.ToneLabel, LegitimacyLabel = executionFacts?.LegitimacyLabel,
                PlayerStruck = executionFacts?.PlayerStruck ?? false,
                ExecutionPlace = execution && executionFacts == null ? ResolveHeroExecutionLocationText(ResolveHeroExecutionSettlement(victim, killer), victim, killer) : ""
            };
            string sentence = WorldBulletinCampaignMaterialPolicy.DeathSentence(material);
            int score = WorldBulletinCampaignMaterialPolicy.DeathPriority(ruler, natural);
            string kind = WorldBulletinCampaignMaterialPolicy.DeathKind(ruler);
            string kingdomId = GetKingdomId(kingdom);
            string group = WorldBulletinCampaignMaterialPolicy.DeathGroup(execution, deathDetail, GetHeroId(killer), GetHeroId(victim), GetCurrentGameDayIndexSafe(),
                deathDetail == "DiedInBattle" ? WorldBulletinPairKey(killer?.MapFaction, victim.MapFaction) : "");
            string detailText = WorldBulletinCampaignMaterialPolicy.DeathDetail(material);
			if (CaptureWorldBulletinEvent(kind, "killed:" + victimId, score, sentence, IsWorldBulletinPlayerHero(killer) || IsWorldBulletinPlayerHero(victim), group, detailText, BulletinParticipants((victim, "死者"), (natural ? null : killer, "致死方，是否亲自行刑依事实")), kingdomId, GetKingdomId(killer?.Clan?.Kingdom)))
			{
				ApplyWorldBulletinStability(kingdomId, WorldBulletinCampaignMaterialPolicy.DeathStability(ruler, natural));
			}
		}
		catch (Exception ex)
		{
			Logger.Log("WorldBulletin", "[ERROR] hero killed: " + ex.Message);
		}
	}

	private void OnWorldBulletinHeroPrisonerTaken(PartyBase capturer, Hero prisoner)
	{
		try
		{
			if (prisoner == null || prisoner == Hero.MainHero || !prisoner.IsLord)
			{
				return;
			}
			Hero captor = capturer?.LeaderHero ?? capturer?.MobileParty?.LeaderHero;
			bool ruler = IsWorldBulletinRuler(prisoner);
			Kingdom kingdom = prisoner.Clan?.Kingdom;
			string who = WorldBulletinCampaignMaterialPolicy.CapturedWho(ruler, GetKingdomDisplayName(kingdom), GetHeroDisplayName(prisoner), GetKingdomDisplayName(kingdom, GetClanDisplayName(prisoner.Clan) + "家族"));
			string sentence = WorldBulletinCampaignMaterialPolicy.CapturedSentence(who, captor != null, GetHeroDisplayName(captor));
			string kingdomId = GetKingdomId(kingdom);
			// Same group as the day's clashes between these realms, so a battle and its captives read as one story.
			string group = "clash:" + GetCurrentGameDayIndexSafe() + ":" + WorldBulletinPairKey(captor?.MapFaction, prisoner.MapFaction);
			string detailText = WorldBulletinCampaignMaterialPolicy.CapturedDetail(WorldBulletinHeroTitle(prisoner), captor != null, GetHeroDisplayName(captor), WorldBulletinHeroTitle(captor));
			if (CaptureWorldBulletinEvent(ruler ? "ruler_captured" : "lord_captured", "captured:" + GetHeroId(prisoner) + ":" + GetCurrentGameDayIndexSafe(), WorldBulletinCampaignMaterialPolicy.CapturedPriority(ruler), sentence, IsWorldBulletinPlayerHero(captor),
				group, detailText, BulletinParticipants((prisoner, "被俘者"), (captor, "俘获方")), kingdomId, GetKingdomId(captor?.Clan?.Kingdom)))
			{
				ApplyWorldBulletinStability(kingdomId, WorldBulletinCampaignMaterialPolicy.CapturedStability(ruler));
			}
		}
		catch (Exception ex)
		{
			Logger.Log("WorldBulletin", "[ERROR] prisoner taken: " + ex.Message);
		}
	}

	private void OnWorldBulletinMapEventEnded(MapEvent mapEvent)
	{
		try
		{
			if (mapEvent == null || !mapEvent.HasWinner || mapEvent.IsHideoutBattle || IsBanditOrMonsterMapEvent(mapEvent))
			{
				return;
			}
			MapEventSide winner = mapEvent.WinningSide == BattleSideEnum.Attacker ? mapEvent.AttackerSide : mapEvent.DefenderSide;
			MapEventSide loser = GetMapEventDefeatedSide(mapEvent);
			if (winner == null || loser == null)
			{
				return;
			}
			bool involvesPlayer = mapEvent.IsPlayerMapEvent;
			bool winnerLord = ShouldMentionBattleHero(winner.LeaderParty?.LeaderHero);
			bool loserLord = ShouldMentionBattleHero(loser.LeaderParty?.LeaderHero);
			if (!involvesPlayer && !winnerLord && !loserLord)
			{
				return;
			}
			int troops = GetMapEventTroopCount(mapEvent);
			bool sallyOut = mapEvent.IsSallyOut || mapEvent.IsSiegeOutside;
			bool siege = mapEvent.IsSiegeAssault || sallyOut;
			// Raid fights are covered by the raid event; a lord running down villagers or caravans is not news.
			bool lordVsLord = winnerLord && loserLord;
			if (!WorldBulletinCampaignMaterialPolicy.ShouldIncludeBattle(involvesPlayer, winnerLord, loserLord, mapEvent.IsRaid, siege, troops, MajorNpcBattleTroopThreshold))
			{
				return;
			}
			int score = WorldBulletinCampaignMaterialPolicy.BattlePriority(troops, MajorNpcBattleTroopThreshold, lordVsLord, siege);
			string location = GetMapEventLocationLabel(mapEvent);
			string winnerFaction = GetFactionDisplayName(winner.MapFaction, "一方");
			string loserFaction = GetFactionDisplayName(loser.MapFaction, "另一方");
			string sentence = WorldBulletinCampaignMaterialPolicy.BattleSentence(location, sallyOut, siege, GetPrimaryOtherSideLabel(winner), winnerFaction, GetPrimaryOtherSideLabel(loser), loserFaction, troops);
			string winnerId = GetKingdomId(winner.MapFaction);
			string loserId = GetKingdomId(loser.MapFaction);
			string group = siege && mapEvent.MapEventSettlement != null
				? "siege:" + GetSettlementId(mapEvent.MapEventSettlement)
				: "clash:" + GetCurrentGameDayIndexSafe() + ":" + WorldBulletinPairKey(winner.MapFaction, loser.MapFaction);
			string detailText = WorldBulletinCampaignMaterialPolicy.BattleDetail(GetMapEventSideCommittedTroopCount(winner), BuildMapEventCasualtyText(winner), GetMapEventSideCommittedTroopCount(loser), BuildMapEventCasualtyText(loser), sallyOut, winnerLord, winnerLord ? WorldBulletinHeroTitle(winner.LeaderParty.LeaderHero) : "", loserLord, loserLord ? WorldBulletinHeroTitle(loser.LeaderParty.LeaderHero) : "");
			if (CaptureWorldBulletinEvent(sallyOut ? "sally_out_battle" : siege ? "siege_battle" : "battle", "battle:" + BuildMapEventStableKey(mapEvent, location), score, sentence, involvesPlayer, group, detailText, BulletinParticipants((winner.LeaderParty?.LeaderHero, "胜方统帅"), (loser.LeaderParty?.LeaderHero, "败方统帅")), winnerId, loserId))
			{
				int swing = WorldBulletinCampaignMaterialPolicy.BattleStability(troops, MajorNpcBattleTroopThreshold);
				ApplyWorldBulletinStability(winnerId, swing);
				ApplyWorldBulletinStability(loserId, -swing);
			}
		}
		catch (Exception ex)
		{
			Logger.Log("WorldBulletin", "[ERROR] map event ended: " + ex.Message);
		}
	}

	private void OnWorldBulletinKingdomDestroyed(Kingdom kingdom)
	{
		try
		{
			if (kingdom == null)
			{
				return;
			}
			CaptureWorldBulletinEvent("kingdom_destroyed", "kingdom_destroyed:" + GetKingdomId(kingdom), WorldBulletinCampaignMaterialPolicy.EventPriority("kingdom_destroyed"), WorldBulletinCampaignMaterialPolicy.DestroyedSentence(GetKingdomDisplayName(kingdom)), false,
				"realm:" + GetKingdomId(kingdom), WorldBulletinCampaignMaterialPolicy.DestroyedDetail(GetHeroDisplayName(kingdom.Leader)), BulletinParticipants((kingdom.Leader, "事件相关君主，是否亲临现场依事实")), GetKingdomId(kingdom));
		}
		catch (Exception ex)
		{
			Logger.Log("WorldBulletin", "[ERROR] kingdom destroyed: " + ex.Message);
		}
	}

	private void OnWorldBulletinClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification)
	{
		try
		{
			if (clan == null)
			{
				return;
			}
			bool involvesPlayer = clan == Clan.PlayerClan;
			if (detail == ChangeKingdomAction.ChangeKingdomActionDetail.LeaveWithRebellion && oldKingdom != null)
			{
				string sentence = WorldBulletinCampaignMaterialPolicy.RebellionSentence(GetClanDisplayName(clan), GetKingdomDisplayName(oldKingdom));
				if (CaptureWorldBulletinEvent("kingdom_rebellion", "rebellion:" + GetClanId(clan) + ":" + GetKingdomId(oldKingdom), WorldBulletinCampaignMaterialPolicy.EventPriority("kingdom_rebellion"), sentence, involvesPlayer,
					"realm:" + GetKingdomId(oldKingdom), WorldBulletinCampaignMaterialPolicy.RebellionDetail(GetHeroDisplayName(clan.Leader), GetHeroDisplayName(oldKingdom.Leader)), BulletinParticipants((clan.Leader, "反叛家族族长"), (oldKingdom.Leader, "原王国君主，未证实在场")), GetKingdomId(oldKingdom)))
				{
					ApplyWorldBulletinStability(GetKingdomId(oldKingdom), -8);
				}
			}
			else if (detail == ChangeKingdomAction.ChangeKingdomActionDetail.CreateKingdom && newKingdom != null)
			{
				string sentence = WorldBulletinCampaignMaterialPolicy.CreatedSentence(GetClanDisplayName(clan), GetKingdomDisplayName(newKingdom));
				CaptureWorldBulletinEvent("kingdom_created", "kingdom_created:" + GetKingdomId(newKingdom), WorldBulletinCampaignMaterialPolicy.EventPriority("kingdom_created"), sentence, involvesPlayer,
					"realm:" + GetKingdomId(oldKingdom ?? newKingdom), WorldBulletinCampaignMaterialPolicy.CreatedDetail(GetHeroDisplayName(clan.Leader), oldKingdom != null, GetKingdomDisplayName(oldKingdom)), BulletinParticipants((clan.Leader, "开国者")), GetKingdomId(newKingdom), GetKingdomId(oldKingdom));
			}
		}
		catch (Exception ex)
		{
			Logger.Log("WorldBulletin", "[ERROR] clan changed kingdom: " + ex.Message);
		}
	}

	private void OnWorldBulletinRaidCompleted(BattleSideEnum winnerSide, RaidEventComponent raidEvent)
	{
		try
		{
			if (winnerSide != BattleSideEnum.Attacker)
			{
				return;
			}
			Settlement settlement = raidEvent?.MapEventSettlement;
			Hero raider = raidEvent?.AttackerSide?.LeaderParty?.LeaderHero;
			if (settlement == null || raider == null || !raider.IsLord)
			{
				return;
			}
			string victimId = GetKingdomId(settlement.MapFaction);
			string sentence = WorldBulletinCampaignMaterialPolicy.RaidSentence(settlement.Name?.ToString(), GetHeroDisplayName(raider), GetFactionDisplayName(raider.MapFaction, "敌军"));
			// A realm's raids on one day collapse into a single "等N起" line.
			string owner = settlement.Village?.Bound != null ? GetSettlementDisplayName(settlement.Village.Bound) : "";
			if (CaptureWorldBulletinEvent("raid", "raid:" + GetSettlementId(settlement) + ":" + GetCurrentGameDayIndexSafe(), WorldBulletinCampaignMaterialPolicy.EventPriority("raid"), sentence, IsWorldBulletinPlayerHero(raider),
				"raid:" + GetCurrentGameDayIndexSafe() + ":" + GetKingdomId(raider.MapFaction) + ">" + victimId, WorldBulletinCampaignMaterialPolicy.RaidDetail(owner), BulletinParticipants((raider, "劫掠方统帅")), victimId, GetKingdomId(raider.MapFaction)))
			{
				ApplyWorldBulletinStability(victimId, -1);
			}
		}
		catch (Exception ex)
		{
			Logger.Log("WorldBulletin", "[ERROR] raid completed: " + ex.Message);
		}
	}

	internal void CaptureWorldBulletinCivilWar(string kingdomId, string stableKey)
	{
		try
		{
			Kingdom kingdom = FindKingdomById(kingdomId);
			if (kingdom == null)
			{
				return;
			}
			CaptureWorldBulletinEvent("civil_war", "civil_war:" + (stableKey ?? GetKingdomId(kingdom)), WorldBulletinCampaignMaterialPolicy.EventPriority("civil_war"), WorldBulletinCampaignMaterialPolicy.CivilWarSentence(GetKingdomDisplayName(kingdom)), Clan.PlayerClan?.Kingdom == kingdom,
				"realm:" + GetKingdomId(kingdom), WorldBulletinCampaignMaterialPolicy.CivilWarDetail(GetHeroDisplayName(kingdom.Leader)), BulletinParticipants((kingdom.Leader, "事件相关君主，是否亲临现场依事实")), GetKingdomId(kingdom));
		}
		catch (Exception ex)
		{
			Logger.Log("WorldBulletin", "[ERROR] civil war: " + ex.Message);
		}
	}

	// ---------- hourly scheduling ----------

	private void OnWorldBulletinHourlyTick() => WorldBulletinState.OnWorldBulletinHourlyTick();

	private static void PruneWorldBulletinWeeklyStability(WorldBulletinSaveState state, int currentWeek) => WorldBulletinStateOwner.PruneWorldBulletinWeeklyStability(state, currentWeek);

	private void AdvanceWorldBulletinScope(WorldBulletinSaveState state, double now) => WorldBulletinState.AdvanceWorldBulletinScope(state, now);

	// Main thread, once per publish: at most four kingdoms, each checked against the others for war.
	private List<string> BuildWorldBulletinKingdomContext(WorldBulletinSelection selection)
	{
		List<string> lines = new List<string>();
		try
		{
			List<string> ids = selection.MajorFacts.SelectMany(e => e.KingdomIds ?? new List<string>())
				.Where(x => !string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).Take(4).ToList();
			List<Kingdom> all = GetDevEditableKingdoms().Where(IsKingdomEligibleForWeeklyReport).ToList();
			foreach (string id in ids)
			{
				Kingdom kingdom = FindKingdomById(id);
				if (kingdom == null || kingdom.IsEliminated)
				{
					continue;
				}
				int towns = 0;
				int castles = 0;
				foreach (Settlement settlement in kingdom.Settlements)
				{
					if (settlement.IsTown)
					{
						towns++;
					}
					else if (settlement.IsCastle)
					{
						castles++;
					}
				}
				List<string> enemies = all.Where(k => k != kingdom && kingdom.IsAtWarWith(k)).Select(k => GetKingdomDisplayName(k)).Take(4).ToList();
				bool stabilityEnabled = DuelSettings.IsKingdomStabilityAndRebellionEnabled();
                string line = WorldBulletinCampaignMaterialPolicy.KingdomContextLine(GetKingdomDisplayName(kingdom), GetHeroDisplayName(kingdom.Leader), towns, castles, stabilityEnabled,
                    stabilityEnabled ? GetKingdomStabilityValue(kingdom) : 0, enemies);
				lines.Add(line);
			}
		}
		catch (Exception ex)
		{
			Logger.Log("WorldBulletin", "[WARN] kingdom context skipped: " + ex.Message);
		}
		return lines;
	}

	private async Task RunWorldBulletinRequestAsync(double windowEndHour, long generation, WorldBulletinSelection selection, WorldBulletinText template, string systemPrompt, string userPrompt, WorldBulletinIllustrationPlan illustrationPlan) => await WorldBulletinState.RunWorldBulletinRequestAsync(windowEndHour, generation, selection, template, systemPrompt, userPrompt, illustrationPlan);

	private void ProcessWorldBulletinMainThreadActions() => WorldBulletinState.ProcessWorldBulletinMainThreadActions();

	private void CompleteWorldBulletin(double windowEndHour, long generation, WorldBulletinSelection selection, WorldBulletinText template, WorldBulletinText generated, WorldBulletinIllustrationPlan illustrationPlan) => WorldBulletinState.CompleteWorldBulletin(windowEndHour, generation, selection, template, generated, illustrationPlan);

	private static void CancelWorldBulletinIllustration(WorldBulletinIllustrationPlan plan)
	{
		try { if (plan != null) WorldBulletinPanelIllustrationBridge.CancelSelection?.Invoke(plan); }
		catch (Exception ex) { Logger.Log("WorldBulletin", "[Illustration] cancel failed: " + ex.Message); }
	}

	private void PublishWorldBulletin(WorldBulletinScopeState scope, WorldBulletinSelection selection, WorldBulletinText template, WorldBulletinText generated, WorldBulletinIllustrationPlan illustrationPlan) => WorldBulletinState.PublishWorldBulletin(scope, selection, template, generated, illustrationPlan);

	private void UpsertWorldBulletinRecord(string eventId, string eventKind, string scopeKingdomId, string title, string shortSummary, string summary, int day) => WorldBulletinState.UpsertWorldBulletinRecord(eventId, eventKind, scopeKingdomId, title, shortSummary, summary, day);

	// ---------- weekly kingdom briefs ----------

	// Local template only: an archive line per kingdom for the browser and the stability history.
	// NPCs read live facts (MyBehavior.WorldBulletinNpc.cs), so no LLM polish is spent here.

	// ---------- persistence / lifecycle ----------

	private void SyncWorldBulletinData(IDataStore dataStore)
	{
		try
		{
			if (dataStore.IsSaving)
			{
                string json = WorldBulletinState.ExportJson();
				CampaignSaveChunkHelper.SaveChunkedString(dataStore, WorldBulletinStorageKey, json, "WorldBulletin");
				return;
			}
			_worldBulletinCorruptRaw = null;
			string loaded = CampaignSaveChunkHelper.LoadChunkedString(dataStore, WorldBulletinStorageKey, "WorldBulletin") ?? "";
            WorldBulletinState.ImportJson(loaded);
			ResetWorldBulletinTransientState();
		}
		catch (Exception ex)
		{
			// Save-path failures keep the in-memory state; only the load path may reset it.
			if (!dataStore.IsSaving)
			{
				_worldBulletinState = null;
				ResetWorldBulletinTransientState();
			}
			Logger.Log("WorldBulletin", "[ERROR] SyncData isolated (saving=" + dataStore.IsSaving + "): " + ex.Message);
		}
	}

	private void ResetWorldBulletinTransientState(){WorldBulletinState.ResetTransient();_worldBulletinFocus=null;_worldBulletinFocusDay=-1;_worldBulletinFocusOwnKingdomId="";_worldBulletinDeathSnapshots.Clear();}

	private void ResetWorldBulletinForRuntime(string reason){ResetWorldBulletinTransientState();WorldBulletinState.ResetRuntime(reason);}
}
