using System;
using System.Collections.Generic;
using System.Linq;
using AnimusForge.Refactor.Contracts;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Core;
using TaleWorlds.MountAndBlade;
using static AnimusForge.ShoutBehavior;
namespace AnimusForge;
// Request-scoped leaf capabilities; no host, scene, history or lifecycle state is owned here.
internal sealed class SceneExternalPromptCapturePorts
{
    internal delegate string StripScenePersonaBlocksQuery(string text);
    internal StripScenePersonaBlocksQuery StripScenePersonaBlocks;
    internal delegate string ExtractTrustPromptBlockQuery(string text, out string remaining);
    internal ExtractTrustPromptBlockQuery ExtractTrustPromptBlock;
    internal delegate string GetSceneNpcHistoryNameForPromptQuery(NpcDataPacket npc);
    internal GetSceneNpcHistoryNameForPromptQuery GetSceneNpcHistoryNameForPrompt;
    internal delegate string BuildScenePresentNpcListBlockForPromptQuery(IEnumerable<NpcDataPacket> presentNpcs, NpcDataPacket selfNpc, Dictionary<int, Hero> resolvedHeroes = null, bool useAllegianceLabel = false);
    internal BuildScenePresentNpcListBlockForPromptQuery BuildScenePresentNpcListBlockForPrompt;
    internal delegate string BuildSceneMechanismPromptSectionQuery(List<SceneSummonPromptTarget> sceneSummonTargets = null, List<SceneGuidePromptTarget> sceneGuideTargets = null, string sceneSummonClosureInstruction = null, string sceneFollowControlInstruction = null, NpcDataPacket publicActionTarget = null);
    internal BuildSceneMechanismPromptSectionQuery BuildSceneMechanismPromptSection;
    internal delegate bool HasPartyTransferRuleContextQuery(string extras);
    internal HasPartyTransferRuleContextQuery HasPartyTransferRuleContext;
    internal delegate string AppendPlayerCustomPromptRuleToSystemPromptQuery(string systemPrompt);
    internal AppendPlayerCustomPromptRuleToSystemPromptQuery AppendPlayerCustomPromptRuleToSystemPrompt;
    internal delegate string BuildSceneSystemTopPromptIntroForSingleQuery(NpcDataPacket npc, Hero hero, IEnumerable<NpcDataPacket> presentNpcs = null, bool includeInventorySummary = false, bool includeTradePricing = false, bool partyTransferTopicSelected = false, MentionedWorldEntities promptMentions = null);
    internal BuildSceneSystemTopPromptIntroForSingleQuery BuildSceneSystemTopPromptIntroForSingle;
    internal delegate string BuildSceneUserRuntimeContextForSingleQuery(NpcDataPacket npc, Hero hero, IEnumerable<NpcDataPacket> presentNpcs = null, bool includeInventorySummary = false, bool includeTradePricing = false, bool partyTransferTopicSelected = false, MentionedWorldEntities promptMentions = null);
    internal BuildSceneUserRuntimeContextForSingleQuery BuildSceneUserRuntimeContextForSingle;
    internal delegate string BuildScenePublicHistorySectionQuery(List<string> sceneHistoryLines);
    internal BuildScenePublicHistorySectionQuery BuildScenePublicHistorySection;
    internal delegate void SplitSceneExtraSectionsQuery(string text, out string miscSection, out string ruleSection, out string knowledgeSection);
    internal SplitSceneExtraSectionsQuery SplitSceneExtraSections;
    internal delegate string BuildSceneSystemRuleBlockQuery(string ruleSection, string sceneMechanismPromptSection);
    internal BuildSceneSystemRuleBlockQuery BuildSceneSystemRuleBlock;
    internal delegate string BuildSceneSingleNpcTaskSystemBlockQuery(string npcName, bool hasMultiplePresentNpcs, int minTokens, int maxTokens, string playerNameForLength);
    internal BuildSceneSingleNpcTaskSystemBlockQuery BuildSceneSingleNpcTaskSystemBlock;
    internal delegate void GetSceneReplyLengthLimitsQuery(DuelSettings settings, out int minTokens, out int maxTokens);
    internal GetSceneReplyLengthLimitsQuery GetSceneReplyLengthLimits;
    internal delegate void SplitPersistedHeroHistorySectionsQuery(string persistedHeroHistory, out string privateRecentWindowSection, out string persistedWithoutRecentWindow);
    internal SplitPersistedHeroHistorySectionsQuery SplitPersistedHeroHistorySections;
    internal delegate string TryGetKingdomIdOverrideFromAgentQuery(Agent agent);
    internal TryGetKingdomIdOverrideFromAgentQuery TryGetKingdomIdOverrideFromAgent;
    internal delegate List<string> BuildPreprocessExcludedRuleIdsForCurrentInteractionQuery(Hero targetHero, CharacterObject targetCharacter, int targetAgentIndex, bool hasAnyHero, List<SceneSummonPromptTarget> sceneSummonTargets = null, List<SceneGuidePromptTarget> sceneGuideTargets = null, NpcDataPacket sceneSpeakerNpc = null, List<NpcDataPacket> sceneCandidates = null, string currentPlayerText = null);
    internal BuildPreprocessExcludedRuleIdsForCurrentInteractionQuery BuildPreprocessExcludedRuleIdsForCurrentInteraction;
    internal delegate string GetPlayerDisplayNameForShoutQuery();
    internal GetPlayerDisplayNameForShoutQuery GetPlayerDisplayNameForShout;
    internal delegate string BuildSceneActionPostprocessUserPromptQuery(string userPromptTemplate, string tagRules, string npcName, string historyText, string latestReplyBlock, string sharedItemList = null, string playerItemList = null, string debtHint = null, string marriagePlayerCandidates = null, string marriageTargetCandidates = null, string runtimeContext = null);
    internal BuildSceneActionPostprocessUserPromptQuery BuildSceneActionPostprocessUserPrompt;
    internal delegate string BuildStrictSceneMessagesSystemPromptQuery(string systemPrompt, bool suppressReplyFormatInstruction = false);
    internal BuildStrictSceneMessagesSystemPromptQuery BuildStrictSceneMessagesSystemPrompt;
    internal delegate string BuildPersistedHeroHistoryContextQuery(int agentIndex, string currentInput, Dictionary<int, Hero> resolvedHeroes);
    internal BuildPersistedHeroHistoryContextQuery BuildPersistedHeroHistoryContext;
    internal delegate List<string> CaptureVisibleSceneHistoryLinesForPromptQuery(int viewerAgentIndex, string viewerName, bool useDistanceLabels);
    internal CaptureVisibleSceneHistoryLinesForPromptQuery CaptureVisibleSceneHistoryLinesForPrompt;
    internal Func<List<NpcDataPacket>, Dictionary<int, Hero>, List<SceneSummonPromptTarget>> SummonTargets;
    internal Func<Agent, int, List<SceneGuidePromptTarget>> GuideTargets;
    internal Func<List<NpcDataPacket>, string> SummonClosure;
    internal Func<NpcDataPacket, string> FollowControl;
}
