using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.ComponentInterfaces;
using TaleWorlds.CampaignSystem.Encounters;
using TaleWorlds.CampaignSystem.Naval;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;
using TaleWorlds.SaveSystem.Load;

namespace TaleWorlds.CampaignSystem.MapEvents;

public class MapEventParty
{
	[SaveableField(2)]
	private FlattenedTroopRoster _roster;

	[SaveableField(3)]
	private int _contributionToBattle = 1;

	[SaveableField(14)]
	private int _healthyManCountAtStart = 1;

	[SaveableField(16)]
	private int _participatingTroopCount = -1;

	[SaveableField(7)]
	private TroopRoster _woundedInBattle = TroopRoster.CreateDummyTroopRoster();

	[SaveableField(8)]
	private TroopRoster _diedInBattle = TroopRoster.CreateDummyTroopRoster();

	[SaveableField(15)]
	private TroopRoster _routedInBattle = TroopRoster.CreateDummyTroopRoster();

	[SaveableProperty(1)]
	public PartyBase Party { get; private set; }

	[SaveableProperty(10)]
	public int PlunderedGold { get; set; }

	[SaveableProperty(11)]
	public int GoldLost { get; set; }

	public float GainedRenown => GainedRenownExplained.ResultNumber;

	public float GainedInfluence => GainedInfluenceExplained.ResultNumber;

	public float GainedMorale => GainedMoraleExplained.ResultNumber;

	public ExplainedNumber GainedRenownExplained { get; private set; }

	public ExplainedNumber GainedInfluenceExplained { get; private set; }

	public ExplainedNumber GainedMoraleExplained { get; private set; }

	public int HealthyManCountAtStart => _healthyManCountAtStart;

	public TroopRoster DiedInBattle => _diedInBattle;

	public TroopRoster WoundedInBattle => _woundedInBattle;

	public TroopRoster RoutedInBattle => _routedInBattle;

	public int ContributionToBattle => _contributionToBattle;

	public bool IsNpcParty => Party != PartyBase.MainParty;

	public TroopRoster RosterToReceiveLootMembers
	{
		get
		{
			if (!IsNpcParty)
			{
				return PlayerEncounter.Current.RosterToReceiveLootMembers;
			}
			return Party.MemberRoster;
		}
	}

	public TroopRoster RosterToReceiveLootPrisoners
	{
		get
		{
			if (!IsNpcParty)
			{
				return PlayerEncounter.Current.RosterToReceiveLootPrisoners;
			}
			if (Party.IsMobile && (Party.MobileParty.IsMilitia || Party.MobileParty.IsGarrison))
			{
				return Party.MobileParty.HomeSettlement.Party.PrisonRoster;
			}
			return Party.PrisonRoster;
		}
	}

	public ItemRoster RosterToReceiveLootItems
	{
		get
		{
			if (!IsNpcParty)
			{
				return PlayerEncounter.Current.RosterToReceiveLootItems;
			}
			return Party.ItemRoster;
		}
	}

	public FlattenedTroopRoster Troops => _roster;

	public int ParticipatingTroopCount => _participatingTroopCount;

	public bool HasTroopLimit
	{
		get
		{
			if (_participatingTroopCount >= 0)
			{
				return _participatingTroopCount < _healthyManCountAtStart;
			}
			return false;
		}
	}

	public MBReadOnlyList<Ship> Ships => Party.Ships;

	internal static void AutoGeneratedStaticCollectObjectsMapEventParty(object o, List<object> collectedObjects)
	{
		((MapEventParty)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		collectedObjects.Add(_roster);
		collectedObjects.Add(_woundedInBattle);
		collectedObjects.Add(_diedInBattle);
		collectedObjects.Add(_routedInBattle);
		collectedObjects.Add(Party);
	}

	internal static object AutoGeneratedGetMemberValueParty(object o)
	{
		return ((MapEventParty)o).Party;
	}

	internal static object AutoGeneratedGetMemberValuePlunderedGold(object o)
	{
		return ((MapEventParty)o).PlunderedGold;
	}

	internal static object AutoGeneratedGetMemberValueGoldLost(object o)
	{
		return ((MapEventParty)o).GoldLost;
	}

	internal static object AutoGeneratedGetMemberValue_roster(object o)
	{
		return ((MapEventParty)o)._roster;
	}

	internal static object AutoGeneratedGetMemberValue_contributionToBattle(object o)
	{
		return ((MapEventParty)o)._contributionToBattle;
	}

	internal static object AutoGeneratedGetMemberValue_healthyManCountAtStart(object o)
	{
		return ((MapEventParty)o)._healthyManCountAtStart;
	}

	internal static object AutoGeneratedGetMemberValue_participatingTroopCount(object o)
	{
		return ((MapEventParty)o)._participatingTroopCount;
	}

	internal static object AutoGeneratedGetMemberValue_woundedInBattle(object o)
	{
		return ((MapEventParty)o)._woundedInBattle;
	}

	internal static object AutoGeneratedGetMemberValue_diedInBattle(object o)
	{
		return ((MapEventParty)o)._diedInBattle;
	}

	internal static object AutoGeneratedGetMemberValue_routedInBattle(object o)
	{
		return ((MapEventParty)o)._routedInBattle;
	}

	public override string ToString()
	{
		return Party.Name.ToString();
	}

	internal MapEventParty(PartyBase party)
	{
		Party = party;
		Update();
		_healthyManCountAtStart = party.NumberOfHealthyMembers;
		_participatingTroopCount = -1;
	}

	internal void SetParticipatingTroopCount(int count)
	{
		_participatingTroopCount = count;
	}

	internal void TrimRosterToAllocatedTroops(Dictionary<UniqueTroopDescriptor, MapEventParty> allocatedTroops)
	{
		if (!HasTroopLimit)
		{
			return;
		}
		List<UniqueTroopDescriptor> list = new List<UniqueTroopDescriptor>();
		foreach (FlattenedTroopRosterElement item in _roster)
		{
			if (!allocatedTroops.ContainsKey(item.Descriptor))
			{
				list.Add(item.Descriptor);
			}
		}
		foreach (UniqueTroopDescriptor item2 in list)
		{
			_roster.Remove(item2);
		}
	}

	[LoadInitializationCallback]
	private void OnLoad(MetaData metaData, ObjectLoadData objectLoadData)
	{
		if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion.IsOlderThan(ApplicationVersion.FromString("v1.3.0")))
		{
			_routedInBattle = TroopRoster.CreateDummyTroopRoster();
			object fieldValueBySaveId = objectLoadData.GetFieldValueBySaveId(9);
			if (fieldValueBySaveId != null)
			{
				_healthyManCountAtStart = (int)fieldValueBySaveId;
			}
		}
		if (MBSaveLoad.LastLoadedGameVersion.IsOlderThan(ApplicationVersion.FromString("v1.3.14.108208")))
		{
			object propertyValueBySaveId = objectLoadData.GetPropertyValueBySaveId(7);
			object propertyValueBySaveId2 = objectLoadData.GetPropertyValueBySaveId(8);
			object propertyValueBySaveId3 = objectLoadData.GetPropertyValueBySaveId(9);
			if (propertyValueBySaveId != null)
			{
				GainedRenownExplained = new ExplainedNumber((float)propertyValueBySaveId);
			}
			if (propertyValueBySaveId2 != null)
			{
				GainedInfluenceExplained = new ExplainedNumber((float)propertyValueBySaveId2);
			}
			if (propertyValueBySaveId3 != null)
			{
				GainedMoraleExplained = new ExplainedNumber((float)propertyValueBySaveId3);
			}
		}
	}

	public void Update()
	{
		if (_roster == null)
		{
			_roster = new FlattenedTroopRoster(Party.MemberRoster.TotalManCount);
		}
		else
		{
			_roster.Clear();
		}
		foreach (TroopRosterElement item in Party.MemberRoster.GetTroopRoster())
		{
			if (item.Character.IsHero)
			{
				if (!_woundedInBattle.Contains(item.Character) && !_diedInBattle.Contains(item.Character))
				{
					_roster.Add(item.Character, item.Character.HeroObject.IsWounded, item.Xp);
				}
			}
			else
			{
				_roster.Add(item.Character, item.Number, item.WoundedNumber);
			}
		}
	}

	internal void ResetContributionToBattleToStrength()
	{
		_contributionToBattle = (int)TaleWorlds.Library.MathF.Sqrt(Party.GetCustomStrength(Party.Side, Party.MapEvent.SimulationContext));
	}

	public void OnTroopKilled(UniqueTroopDescriptor troopSeed)
	{
		CharacterObject troop = _roster[troopSeed].Troop;
		if (!troop.IsHero && Party.IsActive)
		{
			Party.MemberRoster.RemoveTroop(troop, 1, troopSeed);
		}
		_roster.OnTroopKilled(troopSeed);
		DiedInBattle.AddToCounts(_roster[troopSeed].Troop, 1);
	}

	public void OnTroopWounded(UniqueTroopDescriptor troopSeed)
	{
		Party.MemberRoster.WoundTroop(_roster[troopSeed].Troop, 1, troopSeed);
		_roster.OnTroopWounded(troopSeed);
		WoundedInBattle.AddToCounts(_roster[troopSeed].Troop, 1, insertAtFront: false, 1);
	}

	public void OnTroopRouted(UniqueTroopDescriptor troopSeed)
	{
		if (!_roster[troopSeed].Troop.IsHero)
		{
			Party.MemberRoster.AddToCounts(_roster[troopSeed].Troop, -1);
			_roster.OnTroopRouted(troopSeed);
			RoutedInBattle.AddToCounts(_roster[troopSeed].Troop, 1);
		}
		else if (!_roster[troopSeed].Troop.HeroObject.IsWounded)
		{
			Party.MemberRoster.WoundTroop(_roster[troopSeed].Troop, 1, troopSeed);
		}
	}

	public void OnShipSunk(Ship ship)
	{
		if (Party.IsMobile)
		{
			Party.MobileParty.RecentEventsMorale += Campaign.Current.Models.BattleRewardModel.GetSunkenShipMoraleEffect(Party, ship);
		}
	}

	public void OnShipDamaged(Ship ship, SiegeEngineType siegeEngine, int damage)
	{
		if (Party.IsMobile)
		{
			Party.MobileParty.RecentEventsMorale += Campaign.Current.Models.BattleRewardModel.GetShipSiegeEngineHitMoraleEffect(ship, siegeEngine);
		}
		ship.OnShipDamaged(damage, null, out var _);
	}

	public void OnShipScoreHit(Ship ship, Ship struckShip, SiegeEngineType siegeEngine, int damage, bool isFinishingStrike)
	{
		float num = (float)damage / struckShip.MaxHitPoints;
		_contributionToBattle += TaleWorlds.Library.MathF.Ceiling(num * (float)struckShip.TotalCrewCapacity);
	}

	public CharacterObject GetTroop(UniqueTroopDescriptor troopSeed)
	{
		return _roster[troopSeed].Troop;
	}

	public RosterTroopState GetTroopState(UniqueTroopDescriptor troopSeed)
	{
		return _roster[troopSeed].State;
	}

	public void OnRoundEnd(MapEventSide partySide, BattleSideEnum roundWinner)
	{
		if (Party.IsMobile)
		{
			float num = Campaign.Current.Models.BattleRewardModel.CalculateMoraleChangeOnRoundVictory(Party, partySide, roundWinner);
			if (!num.ApproximatelyEqualsTo(0f))
			{
				Party.MobileParty.RecentEventsMorale += num;
			}
		}
	}

	public void OnTroopScoreHit(UniqueTroopDescriptor attackerTroopDesc, CharacterObject attackedTroop, int damage, bool isFatal, bool isTeamKill, WeaponComponentData attackerWeapon, bool isSimulatedHit)
	{
		if (isTeamKill)
		{
			return;
		}
		CharacterObject troop = _roster[attackerTroopDesc].Troop;
		ExplainedNumber xpFromHit = Campaign.Current.Models.CombatXpModel.GetXpFromHit(troop, null, attackedTroop, Party, damage, isFatal, isSimulatedHit ? CombatXpModel.MissionTypeEnum.SimulationBattle : CombatXpModel.MissionTypeEnum.Battle);
		if (!troop.IsHero)
		{
			if (xpFromHit.RoundedResultNumber > 0)
			{
				_roster.OnTroopGainXp(attackerTroopDesc, xpFromHit.RoundedResultNumber);
			}
		}
		else
		{
			CampaignEventDispatcher.Instance.OnHeroCombatHit(troop, attackedTroop, Party, attackerWeapon, isFatal, xpFromHit.RoundedResultNumber);
		}
		_contributionToBattle += xpFromHit.RoundedResultNumber;
	}

	public void SetRenownInfluenceAndMoraleOnBattleEnd(ExplainedNumber renown, ExplainedNumber influence, ExplainedNumber morale)
	{
		GainedRenownExplained = renown;
		GainedInfluenceExplained = influence;
		GainedMoraleExplained = morale;
	}

	internal void CommitXpGain()
	{
		if (Party.MobileParty == null)
		{
			return;
		}
		int num = 0;
		bool flag = (Party.LeaderHero ?? Party.Owner)?.IsAlive ?? false;
		Dictionary<CharacterObject, int> dictionary = new Dictionary<CharacterObject, int>();
		foreach (FlattenedTroopRosterElement item in _roster)
		{
			if (!item.IsKilled && item.XpGained > 0)
			{
				CharacterObject troop = item.Troop;
				int num2 = TaleWorlds.Library.MathF.Round(Campaign.Current.Models.PartyTrainingModel.CalculateXpGainFromBattles(item, Party).ResultNumber);
				if (!dictionary.TryGetValue(troop, out var value))
				{
					dictionary.Add(troop, num2);
				}
				else
				{
					dictionary[troop] = value + num2;
				}
			}
		}
		_roster.ResetTroopXP();
		foreach (KeyValuePair<CharacterObject, int> item2 in dictionary)
		{
			CharacterObject key = item2.Key;
			int value2 = item2.Value;
			MobilePartyHelper.CanTroopGainXp(Party, key, out var gainableMaxXp);
			gainableMaxXp = Math.Min(gainableMaxXp, value2);
			int num3 = value2 - gainableMaxXp;
			if (gainableMaxXp > 0)
			{
				int num4 = Campaign.Current.Models.PartyTrainingModel.GenerateSharedXp(key, gainableMaxXp, Party.MobileParty);
				if (num4 > 0)
				{
					num += num4;
					if (num3 > 0)
					{
						int num5 = Math.Min(num4, num3);
						num3 -= num5;
						num4 -= num5;
					}
					gainableMaxXp -= num4;
				}
				if (!key.IsHero)
				{
					Party.MemberRoster.AddXpToTroop(key, gainableMaxXp);
				}
			}
			if (flag && num3 > 0)
			{
				SkillLevelingManager.OnBattleEnded(Party, key, num3);
			}
		}
		if (num > 0)
		{
			MobilePartyHelper.PartyAddSharedXp(Party.MobileParty, num);
		}
	}

	internal void CommitRenownChanges()
	{
		if (GainedRenown > 0f)
		{
			Hero leaderHero = Party.LeaderHero;
			if (leaderHero != null)
			{
				GainRenownAction.Apply(leaderHero, GainedRenown, doNotNotify: true);
			}
		}
	}

	internal void CommitInfluenceChanges()
	{
		if (!GainedInfluence.ApproximatelyEqualsTo(0f))
		{
			Hero leaderHero = Party.LeaderHero;
			if (leaderHero != null)
			{
				GainKingdomInfluenceAction.ApplyForBattle(leaderHero, GainedInfluence);
			}
		}
	}

	internal void CommitMoraleChanges()
	{
		if (!GainedMorale.ApproximatelyEqualsTo(0f) && Party.MobileParty != null)
		{
			Party.MobileParty.RecentEventsMorale += GainedMorale;
		}
	}

	internal void CommitGoldChanges()
	{
		PartyBase party = Party;
		Hero leaderHero = party.LeaderHero;
		if (leaderHero != null)
		{
			if (PlunderedGold > 0)
			{
				if (leaderHero == Hero.MainHero)
				{
					MBTextManager.SetTextVariable("GOLD", PlunderedGold);
					MBInformationManager.AddQuickInformation(GameTexts.FindText("str_plunder_gain_message"));
				}
				GiveGoldAction.ApplyBetweenCharacters(null, leaderHero, PlunderedGold, disableNotification: true);
			}
			if (GoldLost > 0)
			{
				GiveGoldAction.ApplyBetweenCharacters(leaderHero, null, GoldLost, disableNotification: true);
			}
		}
		else if (party.IsMobile && party.MobileParty.IsPartyTradeActive)
		{
			party.MobileParty.PartyTradeGold += PlunderedGold - GoldLost;
		}
		PlunderedGold = 0;
		GoldLost = 0;
	}
}
