using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;
using HarmonyLib;
using SandBox.GauntletUI.Encyclopedia;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.ViewModelCollection.Encyclopedia.Pages;
using TaleWorlds.Core;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.Library;
using TaleWorlds.ScreenSystem;
using TaleWorlds.TwoDimension;
using AnimusForge.Illustrator.Context;
using AnimusForge.Illustrator.Core;
using AnimusForge.Illustrator.Engine;
using AnimusForge.Illustrator.UI.Gallery;
using AnimusForge.Illustrator.UI.Overlays;

namespace AnimusForge.Illustrator.UI.Patches
{
    public static class EncyclopediaHeroIllustrationPatch
    {
        private const string ButtonId = "AnimusForgeHeroIllustrateButton";
        private static readonly ConditionalWeakTable<object, EncyclopediaHeroPageVM> RootDataSources = new ConditionalWeakTable<object, EncyclopediaHeroPageVM>();
        private static readonly List<WeakReference<ButtonWidget>> InjectedButtons = new List<WeakReference<ButtonWidget>>();
        private static bool _patched;

        public static void EnsurePatched(Harmony harmony)
        {
            if (_patched) return;
            _patched = true;

            try
            {
                Harmony activeHarmony = harmony ?? new Harmony("AnimusForge.Illustrator.Encyclopedia");

                MethodInfo loadMovie = AccessTools.Method(typeof(GauntletMovie), nameof(GauntletMovie.Load));
                if (loadMovie != null)
                {
                    activeHarmony.Patch(loadMovie, postfix: new HarmonyMethod(typeof(EncyclopediaHeroIllustrationPatch), nameof(LoadMoviePostfix)));
                }

                MethodInfo encyclopediaTick = AccessTools.Method(typeof(EncyclopediaData), "OnTick");
                if (encyclopediaTick != null)
                {
                    activeHarmony.Patch(encyclopediaTick, prefix: new HarmonyMethod(typeof(EncyclopediaHeroIllustrationPatch), nameof(EncyclopediaDataOnTickPrefix)));
                }

                Type generatedRootType = AccessTools.TypeByName("SandBox.GauntletUI.AutoGenerated1.EncyclopediaHeroPage__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_Pages_EncyclopediaHeroPageVM");
                if (generatedRootType != null)
                {
                    MethodInfo setDataSource = AccessTools.Method(generatedRootType, "SetDataSource");
                    if (setDataSource != null)
                    {
                        activeHarmony.Patch(setDataSource, postfix: new HarmonyMethod(typeof(EncyclopediaHeroIllustrationPatch), nameof(SetDataSourcePostfix)));
                    }
                    MethodInfo createWidgets = AccessTools.Method(generatedRootType, "CreateWidgets");
                    if (createWidgets != null)
                    {
                        activeHarmony.Patch(createWidgets, postfix: new HarmonyMethod(typeof(EncyclopediaHeroIllustrationPatch), nameof(CreateWidgetsPostfix)));
                    }
                }
            }
            catch (Exception ex)
            {
                TaleWorlds.Library.Debug.Print($"[Illustrator] Failed to patch encyclopedia: {ex.Message}");
            }
        }

        public static bool EncyclopediaDataOnTickPrefix()
        {
            return !IllustratorGalleryPopup.IsOpen && !IllustrationCardPopup.IsOpen;
        }

        public static void LoadMoviePostfix(string movieName, IViewModel datasource, IGauntletMovie __result)
        {
            try
            {
                if (!string.Equals(movieName, "EncyclopediaHeroPage", StringComparison.Ordinal) || !(datasource is EncyclopediaHeroPageVM vm))
                {
                    return;
                }

                Widget root = __result?.RootWidget;
                TrackRoot(root, vm);
                EnsureButton(root);
            }
            catch (Exception ex)
            {
                TaleWorlds.Library.Debug.Print($"[Illustrator] Encyclopedia LoadMoviePostfix error: {ex.Message}");
            }
        }

        public static void SetDataSourcePostfix(object __instance, EncyclopediaHeroPageVM dataSource)
        {
            try
            {
                TrackRoot(__instance, dataSource);
                EnsureButton(__instance);
            }
            catch
            {
            }
        }

        public static void CreateWidgetsPostfix(object __instance)
        {
            try
            {
                EnsureButton(__instance);
            }
            catch
            {
            }
        }

        private static void TrackRoot(object root, EncyclopediaHeroPageVM vm)
        {
            if (root == null || vm == null) return;
            RootDataSources.Remove(root);
            RootDataSources.Add(root, vm);
        }

        private static EncyclopediaHeroPageVM GetDataSource(object root)
        {
            if (root == null) return null;
            var reflected = AccessTools.Field(root.GetType(), "_datasource_Root")?.GetValue(root) as EncyclopediaHeroPageVM;
            if (reflected != null) return reflected;
            return RootDataSources.TryGetValue(root, out var cached) ? cached : null;
        }

        private static Hero ResolveHero(EncyclopediaHeroPageVM vm)
        {
            if (vm == null) return null;
            return AccessTools.Field(typeof(EncyclopediaHeroPageVM), "_hero")?.GetValue(vm) as Hero;
        }

        private static void EnsureButton(object root)
        {
            var existing = GetExistingButton(root);
            if (existing != null) TrackButton(existing);
            if (!IllustratorRuntime.IsEnabled("encyclopedia"))
            {
                if (existing != null) existing.IsVisible = false;
                return;
            }
            if (existing != null)
            {
                existing.IsVisible = true;
                return;
            }

            Widget parent = GetButtonParent(root);
            if (parent == null)
            {
                return;
            }

            ButtonWidget button = new ButtonWidget(parent.Context)
            {
                Id = ButtonId,
                WidthSizePolicy = SizePolicy.Fixed,
                HeightSizePolicy = SizePolicy.Fixed,
                SuggestedWidth = 180f,
                SuggestedHeight = 38f,
                HorizontalAlignment = HorizontalAlignment.Right,
                VerticalAlignment = VerticalAlignment.Top,
                MarginTop = 8f,
                MarginRight = 44f,
                MarginBottom = 8f,
                Brush = parent.Context.GetBrush("Popup.Done.Button.NineGrid") ?? parent.Context.GetBrush("ButtonBrush2"),
                IsEnabled = true,
                DoNotAcceptEvents = false,
                DoNotPassEventsToChildren = true,
                IsVisible = true
            };

            button.ClickEventHandlers.Add(delegate
            {
                HandleIllustrateClicked(root);
            });
            TrackButton(button);

            TextWidget textWidget = new TextWidget(parent.Context)
            {
                WidthSizePolicy = SizePolicy.StretchToParent,
                HeightSizePolicy = SizePolicy.StretchToParent,
                Text = "【纪事插画】",
                Brush = parent.Context.GetBrush("Popup.Button.Text") ?? parent.Context.GetBrush("Encyclopedia.SubPage.Info.Text"),
                DoNotAcceptEvents = true
            };

            if (textWidget.Brush != null)
            {
                textWidget.Brush.FontSize = 18;
                textWidget.Brush.TextHorizontalAlignment = TextHorizontalAlignment.Center;
                textWidget.Brush.TextVerticalAlignment = TextVerticalAlignment.Center;
            }

            button.AddChild(textWidget);

            Widget contentList = GetRightSideContentList(root);
            if (ReferenceEquals(parent, contentList))
            {
                parent.AddChildAtIndex(button, 0);
            }
            else
            {
                parent.AddChild(button);
            }
        }

        private static void TrackButton(ButtonWidget button)
        {
            if (button == null) return;
            for (int i = InjectedButtons.Count - 1; i >= 0; i--)
            {
                if (!InjectedButtons[i].TryGetTarget(out var existing) || ReferenceEquals(existing, button))
                {
                    if (ReferenceEquals(existing, button)) return;
                    InjectedButtons.RemoveAt(i);
                }
            }
            InjectedButtons.Add(new WeakReference<ButtonWidget>(button));
        }

        public static void RefreshInjectedButtons()
        {
            IllustratorRuntime.AssertMainThread();
            bool visible = IllustratorRuntime.IsEnabled("encyclopedia");
            for (int i = InjectedButtons.Count - 1; i >= 0; i--)
            {
                if (!InjectedButtons[i].TryGetTarget(out var button))
                {
                    InjectedButtons.RemoveAt(i);
                    continue;
                }
                button.IsVisible = visible;
            }
        }

        private static void HandleIllustrateClicked(object root)
        {
            if (!IllustratorRuntime.IsEnabled("encyclopedia")) return;
            EncyclopediaHeroPageVM vm = GetDataSource(root);
            Hero hero = ResolveHero(vm);
            if (hero == null)
            {
                InformationManager.DisplayMessage(new InformationMessage("无法获取当前英雄信息。"));
                return;
            }

            Widget tableauWidget = FindTableauWidget(root as Widget);
            IllustrationCardPopup.ShowForEncyclopedia(hero, tableauWidget);
        }

        private static Widget FindTableauWidget(Widget root)
        {
            if (root == null) return null;

            Widget byId = root.FindChild("CharacterTableau", includeAllChildren: true);
            if (byId != null) return byId;

            return FindChildByType(root);
        }

        private static Widget FindChildByType(Widget current)
        {
            if (current == null) return null;
            string typeName = current.GetType().Name;
            if (typeName.IndexOf("Tableau", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                TaleWorlds.Library.Debug.Print($"[Illustrator] Found character tableau by type: {typeName}, size={current.Size}");
                return current;
            }

            for (int i = 0; i < current.ChildCount; i++)
            {
                Widget found = FindChildByType(current.GetChild(i));
                if (found != null) return found;
            }
            return null;
        }

        private static ButtonWidget GetExistingButton(object root)
        {
            Widget widget = root as Widget;
            return widget?.FindChild(ButtonId, includeAllChildren: true) as ButtonWidget;
        }

        private static Widget GetButtonParent(object root)
        {
            return GetRightSideContentList(root) ?? GetRightSideRoot(root);
        }

        private static Widget GetRightSideContentList(object root)
        {
            if (root == null) return null;
            Widget reflected = AccessTools.Field(root.GetType(), "_widget_0_0_1_0_0_0_0_0")?.GetValue(root) as Widget;
            if (reflected != null) return reflected;
            Widget widget = root as Widget;
            Widget clanDivider = widget?.FindChild("ClanDivider", includeAllChildren: true);
            if (clanDivider?.ParentWidget != null) return clanDivider.ParentWidget;
            return widget?.FindChild("RightSideList", includeAllChildren: true);
        }

        private static Widget GetRightSideRoot(object root)
        {
            if (root == null) return null;
            Widget reflected = AccessTools.Field(root.GetType(), "_widget_0_0_1")?.GetValue(root) as Widget;
            if (reflected != null) return reflected;
            Widget widget = root as Widget;
            return widget?.FindChild("RightSideScrollablePanel", includeAllChildren: true);
        }
    }
}
