using AnimusForge;using Newtonsoft.Json;
int n=0;void Check(bool ok,string text){if(!ok)throw new Exception(text);n++;}
var kb=new KnowledgeLibraryBehavior();var kingdom=new KingdomStrategicProfileBehavior();KnowledgeLibraryBehavior.Instance=kb;KingdomStrategicProfileBehavior.Instance=kingdom;
var profiles=new Dictionary<string,MyBehavior.NpcPersonaProfile>{{"h",new()}};var events=new List<MyBehavior.EventRecordEntry>{new()};string world="old",voiceStorage="old";var calls=new List<string>();bool throwVoice=false;
var port=new DatabaseReloadPort {ExportPersonaProfilesJson=()=>JsonConvert.SerializeObject(profiles),GetWorldOpeningSummary=()=>world,ExportEventRecordsJson=()=>JsonConvert.SerializeObject(events),CaptureWorldWeeklyProductsFingerprint=()=>world,GetKingdomOpeningSummaries=()=>new(){{"k","old"}},RestorePersonaProfiles=p=>{calls.Add("persona-restore");profiles=p;},RestoreWeeklyData=(w,k,e,previous)=>{calls.Add("weekly-restore");world=w;events=e;},ReplaceOpeningKnowledge=p=>{calls.Add("opening-write");world="new";},SetVoiceMappingStorage=s=>voiceStorage=s,ReplaceNpcVoiceAssignments=(Dictionary<string,string> source,out int applied)=>{calls.Add("persona-write");applied=1;if(throwVoice)throw new InvalidOperationException("fixture apply failure");profiles["h"].VoiceId="new";return 1;}};
var owner=new DatabaseReloadController(port);var plan=new MyBehavior.DatabaseReloadPlan {KnowledgeRules=new(){new(){Id="nonplayer"}}};
Check(!owner.ApplyDatabaseReloadPlan(null,out var detail)&&kb.Calls.Count==0,"invalid plan no commit");kb.SnapshotFailure=true;Check(!owner.ApplyDatabaseReloadPlan(plan,out detail)&&kb.Calls.Count==0,"snapshot failure no commit");kb.SnapshotFailure=false;kb.RejectReplace=true;Check(!owner.ApplyDatabaseReloadPlan(plan,out detail)&&!kb.Calls.Contains("knowledge-restore")&&calls.Count==0,"knowledge rejection no later commits/no new rollback");kb.RejectReplace=false;kb.Calls.Clear();
VoiceMapper.Results=new(new[]{false,true});Check(!owner.ApplyDatabaseReloadPlan(plan,out detail)&&kb.State=="old"&&kingdom.State=="old"&&VoiceMapper.State=="old","voice failure restores domain state");Check(calls.SequenceEqual(new[]{"persona-restore","weekly-restore"})&&detail.Contains("已自动回滚"),"rollback sequence includes untouched snapshot domains");calls.Clear();kb.Calls.Clear();kingdom.Calls.Clear();
kingdom.RejectApply=true;Check(!owner.ApplyDatabaseReloadPlan(plan,out detail)&&profiles["h"].VoiceId=="old"&&world=="old"&&voiceStorage=="old","late kingdom failure restores earlier commits");Check(calls.SequenceEqual(new[]{"persona-write","opening-write","persona-restore","weekly-restore"}),"original apply then restore order");calls.Clear();kingdom.RejectApply=false;
throwVoice=true;Check(!owner.ApplyDatabaseReloadPlan(plan,out detail)&&kb.State=="old"&&detail.Contains("fixture apply failure"),"throw after earlier mutation restores snapshot");throwVoice=false;calls.Clear();
kingdom.RejectApply=true;kb.RejectRestore=true;kingdom.RejectRestore=true;Check(!owner.ApplyDatabaseReloadPlan(plan,out detail)&&detail.Contains("自动回滚不完整")&&detail.Contains("知识库")&&detail.Contains("王国性格"),"rollback failure reported honestly");Check(calls.Contains("persona-restore")&&calls.Contains("weekly-restore"),"one domain rollback rejection continues other restores");kb.RejectRestore=false;kingdom.RejectRestore=false;kingdom.RejectApply=false;kb.State="old";calls.Clear();
Check(owner.ApplyDatabaseReloadPlan(plan,out detail)&&kb.State=="new"&&world=="new"&&profiles["h"].VoiceId=="new","successful real coordinator commits domains");Check(calls.SequenceEqual(new[]{"persona-write","opening-write"})&&!detail.Contains("回滚"),"success no rollback");

var playerProfile=new MyBehavior.NpcPersonaProfile{VoiceId="player",Personality="player persona"};var retainedProfile=new MyBehavior.NpcPersonaProfile{VoiceId="before",Personality="exact persona",Background="exact background",HeroName="keep"};var voiceAuthority=new Dictionary<string,MyBehavior.NpcPersonaProfile>{{"player",playerProfile},{"h",retainedProfile},{"voiceonly",new(){VoiceId="remove"}}};var originalVoiceAuthority=voiceAuthority;int stamps=0;
int cleared=PersonaImportOwner.ReplaceVoiceAssignments(ref voiceAuthority,new(){{"h","replacement"},{"player","not applied"},{"new","newvoice"}},"player",(id,p)=>{stamps++;p.HeroId=id;},out int assigned);
Check(ReferenceEquals(voiceAuthority,originalVoiceAuthority)&&ReferenceEquals(voiceAuthority["player"],playerProfile)&&playerProfile.VoiceId=="player","voice replacement keeps authority/player identity");Check(ReferenceEquals(voiceAuthority["h"],retainedProfile)&&retainedProfile.Personality=="exact persona"&&retainedProfile.Background=="exact background"&&retainedProfile.HeroName=="keep","voice replacement preserves unrelated persona metadata");Check(cleared==2&&assigned==2&&stamps==1&&!voiceAuthority.ContainsKey("voiceonly"),"voice-only removal/count and only newly created profile stamped");
var fixture=Path.Combine(Environment.GetEnvironmentVariable("AF_H7_FIXTURE_ROOT") ?? "artifacts/af2-host-terminal-closeout/line-d/reload/fixtures",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(fixture);var bad=Path.Combine(fixture,"bad.json");File.WriteAllBytes(bad,new byte[]{0xC3,0x28});Check(!DatabaseReloadPreflight.TryReadDatabaseReloadUtf8Text(bad,out _,out detail)&&detail.Contains("UTF-8"),"strict invalid UTF8 rejected");File.WriteAllText(Path.Combine(fixture,"null.json"),"null");Check(!DatabaseReloadPreflight.TryReadDatabaseReloadJson(Path.Combine(fixture,"null.json"),out MyBehavior.NpcPersonaProfile nullProfile,out detail),"null JSON cannot become destructive default");File.WriteAllText(Path.Combine(fixture,"broken.json"),"{");Check(!DatabaseReloadPreflight.TryReadDatabaseReloadJson(Path.Combine(fixture,"broken.json"),out nullProfile,out detail),"malformed JSON rejected");
Check(!DatabaseReloadPreflight.TryValidateDatabaseReloadVoiceMapping("{\"male_young\":[\"v\",\"v\"],\"fallback\":\"\"}",out detail),"duplicate voice key rejected");Check(DatabaseReloadPreflight.TryValidateDatabaseReloadVoiceMapping("{\"male_young\":[\"v\"],\"fallback\":\"v\"}",out detail),"valid voice mapping accepted");
var ruleids=new HashSet<string>(StringComparer.OrdinalIgnoreCase);var keywordowners=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);var preparedRules=new List<KnowledgeLibraryBehavior.LoreRule>();int disambiguated=0,dedup=0;
Check(KnowledgeImportValidationOwner.TryAddDatabaseReloadKnowledgeRule(new(){Id="lore",Keywords=new(){"shared"}},"first.json",ruleids,keywordowners,preparedRules,ref disambiguated,ref dedup,out detail),"first knowledge rule prepared");var splitRule=new KnowledgeLibraryBehavior.LoreRule{Id="lore",Keywords=new(){"shared","unique"}};Check(KnowledgeImportValidationOwner.TryAddDatabaseReloadKnowledgeRule(splitRule,"lore__second.json",ruleids,keywordowners,preparedRules,ref disambiguated,ref dedup,out detail)&&splitRule.Id=="lore__second"&&splitRule.Keywords.SequenceEqual(new[]{"unique"})&&disambiguated==1&&dedup==1,"duplicate rule stable filename ID and keyword authority preserved");Check(KnowledgeImportValidationOwner.TryAddDatabaseReloadKnowledgeRule(new(){Id="player"},"player.json",ruleids,keywordowners,preparedRules,ref disambiguated,ref dedup,out detail)&&preparedRules.Count==2,"player knowledge not converted to ordinary lore");
Console.WriteLine($"PASS: {n} actual DatabaseReloadController transaction lifecycle assertions (domain/game declaration fixtures; no file or live-save operations).");
