<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TaleWorlds.MountAndBlade.Launcher.Library</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="TaleWorlds.Library">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.Library.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.TwoDimension">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.TwoDimension.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.TwoDimension.Standalone">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.TwoDimension.Standalone.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.ModuleManager">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.ModuleManager.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI.Data">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.Data.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI.PrefabSystem">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.PrefabSystem.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics.Vectors">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\System.Numerics.Vectors.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.InputSystem">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.Starter.Library">
      <HintPath>..\..\..\snapshot\bin\Win64_Shipping_Client\TaleWorlds.Starter.Library.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>