<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TaleWorlds.CampaignSystem.ViewModelCollection.BirthAndDeath</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>..\..\dependencies\TaleWorlds.MountAndBlade.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.CampaignSystem.ViewModelCollection">
      <HintPath>..\..\dependencies\TaleWorlds.CampaignSystem.ViewModelCollection.dll</HintPath>
    </Reference>
    <Reference Include="TaleWorlds.CampaignSystem">
      <HintPath>..\..\dependencies\TaleWorlds.CampaignSystem.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>