from pathlib import Path
import importlib.util, os, subprocess, sys, argparse, json, hashlib
ROOT = Path(__file__).resolve().parents[4]
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "tests"))
from output_isolation import minimal_test_environment
s=importlib.util.spec_from_file_location('extract', ROOT/'tests/modules/AF.Module.Conversation/ChannelCutoverBoundaryTests/run.py')
m=importlib.util.module_from_spec(s); s.loader.exec_module(m)
parser=argparse.ArgumentParser();parser.add_argument('--run-root',type=Path);parser.add_argument('--wilderness-current',action='store_true');parser.add_argument('--native-history-current',action='store_true');parser.add_argument('--lore-current',action='store_true');parser.add_argument('--public-targeted-current',action='store_true');parser.add_argument('--uncompressed-family-current',action='store_true');parser.add_argument('--uncompressed-family-host-current',action='store_true');parser.add_argument('--uncompressed-family-original',action='store_true');parser.add_argument('--uncompressed-family-mutate-inclusion',action='store_true');parser.add_argument('--strict-capture-current',action='store_true');parser.add_argument('--pure-message-current',action='store_true');parser.add_argument('--persisted-history-current',action='store_true');parser.add_argument('--api-line',choices=['1.3','1.4'],default='1.3');args=parser.parse_args()
out=(args.run_root or ROOT/'artifacts/af2-host-terminal-closeout/line-b/scene-history-tests').resolve()
out.mkdir(parents=True,exist_ok=True)
if args.persisted_history_current:
    receipts=[]
    def read(path):
        text=(ROOT/path).read_text(encoding='utf-8-sig');receipts.append(dict(path=path,rawSha256=hashlib.sha256((ROOT/path).read_bytes()).hexdigest()));return text
    path='src/AF.GameAdapter.Bannerlord/Prompt/SceneHistoryPromptCaptureAdapter.cs'
    text=read(path);cluster=text[text.index('    internal sealed class PersistedHistoryCapturePorts'):text.rfind('}')]
    header='using System;using System.Collections.Generic;using System.Linq;using System.Threading;using System.Threading.Tasks;using System.Diagnostics;using System.Runtime.CompilerServices;using TaleWorlds.CampaignSystem;using TaleWorlds.MountAndBlade;using TaleWorlds.Library;using AnimusForge.SiegeAftermathIntervention;namespace AnimusForge.Refactor.Adapters;internal sealed class SceneHistoryPromptCaptureAdapter {private readonly Func<SceneConversationHistoryOwner> _history; internal SceneHistoryPromptCaptureAdapter(Func<SceneConversationHistoryOwner> history,PersistedHistoryCapturePorts ports){_history=history;_persisted=ports;}'
    (out/'CurrentHistory.cs').write_text(header+cluster+'}',encoding='utf-8')
    baseline_path=ROOT/'artifacts/j17-host-implementation-20261004/c/precomputed-history-original-unsafe-baseline.json'
    baseline=json.loads(baseline_path.read_text(encoding='utf-8'))
    old_build=baseline['capture'];old_start=baseline['unsafe'].replace('private Task<string> StartPrecomputedPersistedHistoryContextTask(', 'internal Task<string> StartPrecomputedPersistedHistoryContextTask(')
    original='using System;using System.Collections.Generic;using System.Linq;using System.Threading.Tasks;using TaleWorlds.CampaignSystem;using TaleWorlds.MountAndBlade;using AnimusForge.SiegeAftermathIntervention;using PrecomputedShoutRagContext=AnimusForge.ShoutBehavior.PrecomputedShoutRagContext;namespace AnimusForge;internal class OriginalUnsafeHistoryBaseline {'+old_build+old_start+'private string GetLatestSceneNpcUtterance(int index)=>"secondary";private string BuildWildernessNonHeroHistoryContextForPrompt(NpcDataPacket npc,Hero hero,CharacterObject character,int index,string input,string secondary)=>npc.Id+":"+input+":"+secondary;}'
    (out/'OriginalUnsafe.cs').write_text(original,encoding='utf-8')
    receipts.append(dict(path=str(baseline_path.relative_to(ROOT)).replace('\\','/'),rawSha256=hashlib.sha256(baseline_path.read_bytes()).hexdigest()))
    harness=(HERE/'Harness.cs.txt').read_text(encoding='utf-8').split('// @@PERSISTED_HISTORY_CURRENT_CASES@@')[1].split('// @@STRICT_CAPTURE_CURRENT@@')[0]
    (out/'Program.cs').write_text(harness,encoding='utf-8')
    paths=['src/modules/AF.Module.Conversation/Channels/Native/ConversationGameThreadDispatcher.cs','src/AF.Foundation.Runtime/Scheduling/PendingOperationRegistry.cs','src/AF.Foundation.Runtime/Lifecycle/SaveRuntimeGuard.cs','src/modules/AF.Module.Prompt/Composition/PreprocessFormatException.cs']
    for path in paths: read(path)
    (out/'Tests.csproj').write_text('<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><Nullable>disable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup>'+''.join('<Compile Include="'+str(ROOT/path)+'" />' for path in paths)+'</ItemGroup></Project>',encoding='utf-8')
    (out/'NuGet.Config').write_text('<configuration><packageSources><clear/></packageSources></configuration>',encoding='utf-8')
    dotnet=ROOT/'local/dotnet/8.0.425/dotnet.exe';env=minimal_test_environment(dotnet,out)
    run=subprocess.run([str(dotnet),'run','--project',str(out/'Tests.csproj'),'-c','Release']+(['-p:DefineConstants=BANNERLORD_1_4_OR_GREATER'] if args.api_line=='1.4' else []),cwd=out,env=env,capture_output=True,text=True,encoding='utf-8',errors='replace',timeout=90)
    (out/'run.log').write_text(run.stdout+run.stderr,encoding='utf-8')
    after=[dict(path=x['path'],rawSha256=hashlib.sha256((ROOT/x['path']).read_bytes()).hexdigest()) for x in receipts]
    assert receipts==after,'source changed during test'
    (out/'receipt.json').write_text(json.dumps(dict(api=args.api_line,exitCode=run.returncode,inputs=receipts,after=after,sourceClass='current exact persisted-history orchestration and whole real dispatcher/registry/generation',controlledLeaves=['game Mission/Hero/Agent','history capture/render leaf; not whole SharedHistoryWork proof']),indent=2),encoding='utf-8')
    print(run.stdout+run.stderr,end='');raise SystemExit(run.returncode)
create=m.declaration((ROOT/'src/modules/AF.Module.Prompt/Composition/MainPromptMessageAssemblyOwner.cs').read_text(encoding='utf-8-sig'),'internal static object CreateCourierChatMessage(')
metadata=m.declaration((ROOT/'src/modules/AF.Module.Conversation/Channels/Scene/ShoutUtils.cs').read_text(encoding='utf-8-sig'),'public static string StripConversationMetadataPrefix(')
harness=(HERE/'Harness.cs.txt').read_text(encoding='utf-8').split('// @@PERSISTED_HISTORY_CURRENT_CASES@@')[0].split('// @@PURE_MESSAGE_CURRENT_CASES@@')
program=harness[0].split('// @@STRICT_CAPTURE_CURRENT@@')[0].replace('@@CREATE@@',create).replace('@@METADATA@@',metadata)
source_receipts=[]
if args.pure_message_current:
    def extract(path,signature):
        source=(ROOT/path).read_text(encoding='utf-8-sig');body=m.declaration(source,signature)
        source_receipts.append(dict(path=path,signature=signature,rawSha256=hashlib.sha256((ROOT/path).read_bytes()).hexdigest(),bodySha256=hashlib.sha256(body.encode('utf-8')).hexdigest()))
        return body
    names=['HasPartyTransferRuleContext','BuildNpcInitiatedOpeningPersistentFactText','BuildRecentSceneLoreQueryText','FilterScenePublicHistoryLines','ComposeScenePublicHistorySection','PrepareSceneMainReplySpeechText','IsAuxiliaryPureDialogueSceneMessage','BuildProactiveSceneOpeningFactText','BuildNpcInitiatedOpeningUserText','StripAfefPrefixForPromptSection','BuildScopedAfefFactLinesForPrompt','BuildCurrentAfefFactPromptBlock','StripScenePersonaBlocks','ExtractTrustPromptBlock','InjectTrustBlockBeforeGroupRules','BuildAutoGroupRelayInfoDisplayName','ContainsLiteralKeywordHit','ContainsAutoGroupEndSignal','TryParseAutoGroupRelayTargetAgentIndex','BuildAutoGroupChatReplyInstruction','NormalizeSceneHistoryLineForLoreQuery','CreateEmptyNativeConversationPromptContext','IsNativeConversationPreprocessUnavailableTextForExternal','HasInjectedRuleBlockForPostprocess','BuildNearbyPresentNpcLineForPrompt']
    import re
    composer_path='src/modules/AF.Module.Prompt/Composition/ScenePromptMessageProjectionComposer.cs'
    source=(ROOT/composer_path).read_text(encoding='utf-8-sig')
    bodies=[extract(composer_path,re.search(r'internal static [^\n{};]+ '+name+r'\(',source).group(0)) for name in names]
    (out/'CurrentComposer.cs').write_text('using System;using System.Collections.Generic;using System.Linq;using System.Text;using System.Text.RegularExpressions;using AnimusForge.Refactor.Adapters;namespace AnimusForge.Refactor.Modules;internal static class ScenePromptMessageProjectionComposer {'+'\n'.join(bodies)+'}',encoding='utf-8')
    c2_host_path='src/modules/AF.Module.Conversation/Channels/Scene/ShoutBehavior.cs'
    c2_host='\n'.join(extract(c2_host_path,signature) for signature in ['internal static bool HasPartyTransferRuleContext(','internal static string BuildNpcInitiatedOpeningPersistentFactText(','private static string StripAfefPrefixForPromptSection('])
    (out/'CurrentC2Host.cs').write_text('using System;using AnimusForge.Refactor.Modules;namespace AnimusForge;internal static class ShoutBehavior {'+c2_host+'}',encoding='utf-8')
    helpers='\n'.join(extract('src/modules/AF.Module.Conversation/Internal/Postprocess/ConversationActionPostprocessOwner.cs','internal static string '+name+'(') for name in ['GetSceneNpcGivenNameForPrompt','GetSceneNpcIdentityNameForPrompt','GetSceneNpcListIdentityForPrompt','ExtractDeferredSceneActionTags','StripDeferredSceneMoodTags'])
    helpers+='\n'+extract('src/modules/AF.Module.Conversation/Internal/Postprocess/ConversationActionPostprocessOwner.cs','internal static bool HasNonMoodDeferredSceneActionTag(')
    program=program.replace('internal static class ConversationActionPostprocessOwner {','internal static class ConversationActionPostprocessOwner {'+helpers,1)
    strip=extract('src/modules/AF.Module.Conversation/Internal/Postprocess/ConversationActionPostprocessOwner.cs','internal static string StripActionTagsForSceneSpeech(')
    program=program.replace('internal static string StripActionTagsForSceneSpeech(string text) => text;',strip,1)
    program=program.replace('public static string StripNamePrefixedLineSafely','public static string GetPromptListName(NpcDataPacket n)=>n?.PromptGivenName; public static string GetPromptIdentityName(NpcDataPacket n)=>n?.PromptDisplayName??n?.Name; public static string GetPromptHistoryName(NpcDataPacket n)=>n?.Name; public static string StripNamePrefixedLineSafely',1)
    program=program.replace('static void Main()','static void OriginalMain()',1)+harness[1]
    history_name='\n'.join(extract('src/AF.GameAdapter.Bannerlord/Prompt/SceneAgentIdentityPromptCaptureAdapter.cs','internal static '+kind+' '+name+'(') for kind,name in [('string','GetSceneNpcHistoryNameForPrompt'),('string','NormalizeSceneNpcMatchValue'),('bool','IsSameSceneNpcForPrompt')])
    (out/'CurrentIdentity.cs').write_text('using System;namespace AnimusForge.Refactor.Adapters;internal static class SceneAgentIdentityPromptCaptureAdapter {'+history_name+'}',encoding='utf-8')
    recent=extract('src/AF.GameAdapter.Bannerlord/Prompt/PromptRuleCaptureBannerlordAdapter.cs','internal static string BuildRecentNpcFactContext(')
    program=program.replace('internal sealed class MyBehavior {','internal sealed class MyBehavior { internal class DialogueDay {internal List<string> Lines;}',1)
    (out/'CurrentRecentFacts.cs').write_text('using System;using System.Collections.Generic;using System.Linq;using Hero=TaleWorlds.CampaignSystem.Hero;using DialogueDay=AnimusForge.MyBehavior.DialogueDay;namespace TaleWorlds.CampaignSystem {internal class Hero {}} namespace AnimusForge.Refactor.Adapters {internal static class PromptRuleCaptureBannerlordAdapter {'+recent+'}}',encoding='utf-8')
    text_methods='\n'.join(extract('src/AF.GameAdapter.Bannerlord/Prompt/PersonaIdentityPromptCaptureAdapter.cs','internal static string '+name+'(') for name in ['MergeUserHistoryAndInput','NormalizePlayerHistoryLineForPrompt'])
    prefix=extract('src/AF.GameAdapter.Bannerlord/Prompt/MemoryRecallInputCaptureAdapter.cs','internal static bool TryStripPlayerSpeechPrefix(')
    (out/'CurrentIdentityText.cs').write_text('using System;namespace AnimusForge.Refactor.Adapters {internal static class PersonaIdentityPromptCaptureAdapter {internal static int NameCaptures;internal static string BuildPlayerPublicDisplayNameForPrompt(){NameCaptures++;return \"Player\";}'+text_methods+'}internal static class MemoryRecallInputCaptureAdapter {'+prefix+'}internal static class MemoryHistoryCommitBannerlordAdapter {internal static string FirstMeetingFact;internal static string NormalizeFirstMeetingNpcFactForPrompt(string line)=>FirstMeetingFact??\"\";}}',encoding='utf-8')
if args.strict_capture_current:
    def extract(path,signature):
        source=(ROOT/path).read_text(encoding='utf-8-sig');start=source.index(signature);brace=source.find('{',start);arrow=source.find('=>',start);body=source[start:source.index(';',arrow)+1] if arrow>=0 and (brace<0 or arrow<brace) else m.declaration(source,signature)
        source_receipts.append(dict(path=path,signature=signature,rawSha256=hashlib.sha256((ROOT/path).read_bytes()).hexdigest(),bodySha256=hashlib.sha256(body.encode('utf-8')).hexdigest()))
        return body
    cp='src/AF.GameAdapter.Bannerlord/Prompt/SceneHistoryPromptCaptureAdapter.cs'
    signatures=['internal static bool HasNativeConversationSceneDialogueHistoryForPrompt(', 'internal static bool ShouldIncludeCurrentSceneSessionInNativePersistedHistory(', 'internal static int ClampMemoryPromptHour(', 'internal static bool TryConvertAfefFactToStrictChatMessage(', 'internal static bool ShouldDeferExtraFactPersistenceUntilAfterSceneReply(', 'internal static bool IsDetailedSceneSpeechPromptEnabled(', 'internal static bool ShouldPreserveSceneAsteriskActions(', 'internal static string GetStrictScenePlayerDisplayName(', 'internal static string BuildStrictSceneMessagesSystemPrompt(', 'internal static SceneHistoryMessageContext CaptureSceneHistoryMessageContext(', 'internal List<string> CaptureVisibleSceneHistoryLinesForPrompt(', 'internal SceneHistoryMessageAssemblyInput CaptureStrictSceneMessageInputForNpc(', 'internal List<ConversationMessage> CaptureNpcConversationHistory(', 'internal static ConversationMessage StampConversationMessageWithCurrentMemoryContext(']
    if args.native_history_current: signatures += ['internal static Func<string> CaptureNativeConversationPersistedHistoryWork(', 'internal static string GetLatestNativeConversationNpcUtteranceForExternal(', 'internal static void TryRecordNativeConversationCurrentDialogLine(', 'internal static void AppendNativeConversationSessionHistoryCaptured(', 'internal void AppendNativeConversationSessionLineToSceneHistoryCaptured(', 'internal static List<string> BuildNativeConversationUnifiedSceneHistoryLinesForPrompt(', 'internal static List<ConversationMessage> BuildNativeConversationSessionHistoryMessagesForAgent(', 'internal static List<string> BuildNativeConversationSceneHistoryLinesForPrompt(', 'internal static List<ConversationMessage> BuildNativeConversationSessionHistoryMessages(', 'internal static List<AnimusForgeDialogueHistoryEntry> GetNativeConversationSessionHistorySnapshot(', 'internal static string CaptureNativeConversationHistoryKey(', 'internal static string CaptureNativeConversationNonHeroUnnamedKey(']
    if args.public_targeted_current:
        assert args.native_history_current
        signatures += ['internal void AppendTargetedScenePlayerFact(', 'internal void AppendTargetedSceneNpcFact(', 'internal void RecordExtraFactToSceneHistoryCaptured(', 'internal static List<int> BuildVisibleAgentSnapshot(', 'internal void AppendSceneEventToNativeSharedHistory(', 'internal void AppendSceneEventToNativeSharedHistoryForTargets(', 'internal static List<string> GetAuxiliarySceneDialogueHistoryLinesForExternal(', 'internal static List<string> GetNativeConversationAuxiliaryHistoryLinesForExternal(', 'internal List<string> CaptureAuxiliarySceneDialogueHistoryLines(']
    if args.lore_current:
        assert args.native_history_current
        signatures.append('internal string BuildAutoGroupLoreContextForSpeaker(')
    family_bodies=[]
    if args.uncompressed_family_current:
        assert args.native_history_current and args.wilderness_current and not args.public_targeted_current
        family_source='src/modules/AF.Module.Conversation/Channels/Scene/ShoutBehavior.cs' if args.uncompressed_family_original else cp
        family_signatures=['internal static List<ConversationMessage> BuildUncompressedMemoryRoleMessagesForPrompt(Hero hero, int targetAgentIndex)', 'internal static List<ConversationMessage> BuildUncompressedMemoryRoleMessagesForPrompt(Hero hero, CharacterObject targetCharacter, NpcDataPacket npc, int targetAgentIndex)', 'internal static List<ConversationMessage> BuildUncompressedMemoryRoleMessagesForPrompt(int targetAgentIndex, Dictionary<int, Hero> resolvedHeroes)']
        for sig in family_signatures:
            body=extract(family_source,sig)
            if args.uncompressed_family_original:
                assert 'return SceneHistoryPromptCaptureAdapter.BuildUncompressedMemoryRoleMessagesForPrompt(' not in body, 'Original TDD mode requires pre-migration body; preserved original002/mutant003 evidence must not be refreshed from thin current facade'
                body=body.replace('if (TryResolveWildernessNonHeroMemory(', 'if (SceneAgentIdentityPromptCaptureAdapter.TryResolveWildernessNonHeroMemory(').replace('LogNonHeroMemoryTrace(', 'SceneAgentIdentityPromptCaptureAdapter.LogNonHeroMemoryTrace(')
            if args.uncompressed_family_mutate_inclusion:body=body.replace('includeCurrentActiveSceneSession: false','includeCurrentActiveSceneSession: true')
            family_bodies.append(body)
    header='using AnimusForge.Refactor.Modules;using System;using System.Linq;using System.Collections.Generic;using TaleWorlds.CampaignSystem.Party;using TaleWorlds.MountAndBlade;using TaleWorlds.CampaignSystem;namespace AnimusForge.Refactor.Adapters;internal sealed class SceneHistoryPromptCaptureAdapter {private readonly Func<SceneConversationHistoryOwner> _history;private readonly ScenePendingAfefFactsOwner _pendingFacts;internal SceneHistoryPromptCaptureAdapter(SceneConversationHistoryOwner h,ScenePendingAfefFactsOwner p){_history=()=>h;_pendingFacts=p;}'
    if args.public_targeted_current:
        header=header.replace('private readonly Func<SceneConversationHistoryOwner> _history;','private readonly NativeConversationSessionOwner _nativeSessions;private readonly Func<SceneHistoryPromptCaptureAdapter> _ownCapture;private readonly Func<SceneConversationHistoryOwner> _history;').replace('_history=()=>h;_pendingFacts=p;','_history=()=>h;_pendingFacts=p;_nativeSessions=new NativeConversationSessionOwner(SceneConversationHistoryOwner.NextEventSequence,100);_ownCapture=()=>this;')
        header+='internal NativeConversationSessionOwner FixtureSession=>_nativeSessions;'
    (out/'CurrentStrictCapture.cs').write_text(header+'\n'.join(extract(cp,x) for x in signatures)+'\n'+''.join(family_bodies)+'}',encoding='utf-8')
    (out/'GameCaptureLeaves.cs').write_text('using System;using AnimusForge;using TaleWorlds.CampaignSystem;namespace TaleWorlds.CampaignSystem {internal struct CampaignTime {internal static CampaignTime Now=>new();internal double ToDays=>11;public override string ToString()=>"Autumn 11";}} namespace AnimusForge.Refactor.Adapters {internal static class SceneTradeBannerlordAdapter {internal static string GetPlayerDisplayNameForShout()=>"Player";}internal static class SceneAgentIdentityPromptCaptureAdapter {internal static int CustomReads;internal static string ResolveSceneHeroIdFromAgentIndex(int i)=>i==7?"ada":"";internal static void FillSceneMessageHeroIdentity(ConversationMessage m){}internal static float GetPlayerDistanceToAgentForScenePrompt(int i)=>3;internal static string BuildPlayerCustomPromptRuleBlock(){CustomReads++;return "custom";}internal static string JoinPromptSections(params string[] x)=>string.Join("\\n",x);}internal static class PersonaIdentityPromptCaptureAdapter {internal static int GetCurrentMemoryGameHourForExternal()=>9;}internal static class SceneLocationPromptCaptureAdapter {internal static string ResolveCurrentMemorySceneLabel()=>"square";}internal static class LlmRequestConfigurationCaptureAdapter {internal static ConversationSpeechTextOptions CaptureSceneSpeechTextOptions()=>new(SceneHistoryPromptCaptureAdapter.IsDetailedSceneSpeechPromptEnabled(),SceneHistoryPromptCaptureAdapter.ShouldPreserveSceneAsteriskActions());}}',encoding='utf-8')
    compose=extract('src/modules/AF.Module.Prompt/Composition/ScenePromptMessageProjectionComposer.cs','internal static bool TryExtractReplyFormatInstruction(')
    if args.public_targeted_current: compose+=extract('src/modules/AF.Module.Prompt/Composition/ScenePromptMessageProjectionComposer.cs','internal static string NormalizeSceneExtraFactForHistory(')
    (out/'CurrentStrictComposer.cs').write_text('using System;using System.Linq;using System.Collections.Generic;namespace AnimusForge.Refactor.Modules;internal static class ScenePromptMessageProjectionComposer {'+compose+((''.join(extract('src/modules/AF.Module.Prompt/Composition/ScenePromptMessageProjectionComposer.cs','internal static string '+n+'(') for n in ['BuildRecentSceneLoreQueryText','NormalizeSceneHistoryLineForLoreQuery'])) if args.lore_current else '')+'}',encoding='utf-8')
    native=extract('src/modules/AF.Module.Conversation/Channels/Native/NativeConversationSessionOwner.cs','internal static int ResolveHistoryLineLimit(')
    if not args.native_history_current: (out/'CurrentNativeLimit.cs').write_text('using System;namespace AnimusForge;internal static class NativeConversationSessionOwner {'+native+'}',encoding='utf-8')
    if args.native_history_current:
        program=program.replace('internal static class ConversationActionPostprocessOwner {','internal static class ConversationActionPostprocessOwner {'+extract('src/modules/AF.Module.Conversation/Internal/Postprocess/ConversationActionPostprocessOwner.cs','internal static string GetSceneNpcIdentityNameForPrompt('),1)
        name=extract('src/AF.GameAdapter.Bannerlord/Prompt/SceneAgentIdentityPromptCaptureAdapter.cs','internal static string GetSceneNpcHistoryNameForPrompt(')
        name+=extract('src/AF.GameAdapter.Bannerlord/Prompt/SceneAgentIdentityPromptCaptureAdapter.cs','internal static int TryResolveNativeConversationAgentIndex(')
        for kind,method in [('int','GetShoutThoughtMinTokens'),('bool','IsShoutInnerThoughtPromptDisabled'),('void','GetSceneReplyLengthLimits'),('bool','HasGcczImmediatePromptExtras'),('string','BuildGcczImmediateIdentityOverrideBlock')]: name+=extract('src/AF.GameAdapter.Bannerlord/Prompt/SceneAgentIdentityPromptCaptureAdapter.cs','internal static '+kind+' '+method+'(')
        (out/'IndependentGcczBoundaryLeaf.cs').write_text('using System;using TaleWorlds.CampaignSystem;namespace AnimusForge;internal static class AfGcczShoutBridge {internal static bool Active,Injected,Throw;internal static int ActiveReads,BlockReads,IdentityReads;internal static string Identity;internal static bool IsActive(){ActiveReads++;if(Throw)throw new Exception("bridge");return Active;}internal static bool HasInjectedRuleBlock(string x){BlockReads++;return Injected;}internal static string BuildImmediateReactionIdentityOverride(Hero h,CharacterObject c,int i){IdentityReads++;if(Throw)throw new Exception("bridge");return Identity;}}',encoding='utf-8')
        if args.lore_current: name+=extract('src/AF.GameAdapter.Bannerlord/Prompt/SceneAgentIdentityPromptCaptureAdapter.cs','internal static void LogShoutLorePrequery(')
        if args.public_targeted_current:
            methods=['internal static bool TryGetNativeConversationLinkTargetForExternal(', 'internal static bool TryGetNativeConversationHistoryTargetForExternal(', 'internal bool TryGetNativeConversationPersistentHistoryTargetForExternal(', 'internal static string FormatNativeConversationDisplayTextForExternal(string rawVisibleText, Hero', 'internal static string FormatNativeConversationDisplayTextForExternal(string rawVisibleText)', 'internal static bool TryResolveNativeConversationTarget(', 'internal static bool IsNativeConversationSelfTarget(', 'internal static bool TryResolveNativeConversationTargetFromAgent(', 'internal static Hero ResolveHeroFromAgentIndex(']
            name+=''.join(extract('src/AF.GameAdapter.Bannerlord/Prompt/SceneAgentIdentityPromptCaptureAdapter.cs',x) for x in methods)
            selector=extract('src/AF.GameAdapter.Bannerlord/Prompt/PromptRuleCaptureBannerlordAdapter.cs','internal static LegacyDetachedRuleSelector CreateNativeConversationDetachedRuleSelectorForExternal(')
            (out/'CurrentNativePublicSelector.cs').write_text('using System;using System.Collections.Generic;namespace AnimusForge.Refactor.Adapters;internal static class PromptRuleCaptureBannerlordAdapter {'+selector+'}',encoding='utf-8')
        name+='internal NpcDataPacket BuildNativeConversationNpcData(Hero h,CharacterObject c)=>throw new Exception("UNVISITED nonHero packet capture");internal static void LogNonHeroMemoryTrace(string x){}'
        (out/'HistoryWorkBoundaryLeaf.cs').write_text('using System;namespace AnimusForge;internal sealed class MyBehavior {internal static int WorkCaptures;internal static string CapturedSecondary;internal static Func<string> CapturedWork;internal static Func<string> CaptureHistoryContextWorkForHero(TaleWorlds.CampaignSystem.Hero h,string p,string secondary,bool include,long generation){WorkCaptures++;CapturedSecondary=secondary;return CapturedWork;}internal static Func<string> CaptureHistoryContextWorkById(string id,string name,string p,string secondary,bool include,long generation)=>throw new Exception("UNVISITED nonHero work");}',encoding='utf-8')
        guard=extract('src/modules/AF.Module.Conversation/Channels/Scene/ShoutBehavior.cs','internal static bool IsBannerlordMainThreadForNativeActions(')
        (out/'CurrentNativeThreadGuard.cs').write_text('using System;using TaleWorlds.Library;namespace AnimusForge {internal static class ShoutBehavior {'+guard+'}}namespace TaleWorlds.Library {internal static class TWParallel {internal static bool Main=true;internal static bool IsMainThread()=>Main;}}',encoding='utf-8')
        input_path='src/AF.GameAdapter.Bannerlord/Scene/SceneShoutInputController.cs'
        resolver='\n'.join(extract(input_path,'internal static '+kind+' '+name+'(') for kind,name in [('int','TryResolveNativeConversationAgentIndex'),('bool','IsUsableNativeConversationFallbackAgent'),('bool','IsValidNativeConversationTargetAgent')])
        (out/'CurrentNativeAgentResolver.cs').write_text('using System;using System.Linq;using TaleWorlds.CampaignSystem;using TaleWorlds.CampaignSystem.Party;using TaleWorlds.CampaignSystem.Encounters;using TaleWorlds.MountAndBlade;namespace AnimusForge.Refactor.Adapters;internal static class SceneShoutInputController {'+resolver+'}',encoding='utf-8')
        leaves=(out/'GameCaptureLeaves.cs').read_text(encoding='utf-8').replace('internal static class SceneAgentIdentityPromptCaptureAdapter {', 'internal sealed class SceneAgentIdentityPromptCaptureAdapter {'+name+'internal static bool TryResolveWildernessNonHeroMemory(AnimusForge.NpcDataPacket n,TaleWorlds.CampaignSystem.Hero h,TaleWorlds.CampaignSystem.CharacterObject c,int i,out string id,out string name){id=name="";throw new Exception("UNVISITED wilderness identity capability");}internal static TaleWorlds.CampaignSystem.Party.MobileParty TryResolveWildernessNonHeroMobileParty(int i)=>throw new Exception("UNVISITED wilderness game capability");',1)
        leaves+='namespace TaleWorlds.CampaignSystem {internal class Hero {internal string StringId;internal object Name;internal CharacterObject CharacterObject;}internal class CharacterObject {internal Hero HeroObject;internal string StringId;internal object Name;internal bool IsSoldier;internal Culture Culture;}internal class Culture {internal string StringId;}}namespace TaleWorlds.CampaignSystem.Party {internal class MobileParty {internal static MobileParty MainParty;internal TaleWorlds.CampaignSystem.Hero LeaderHero;internal Faction MapFaction;}internal class Faction{internal string StringId;}}'
        leaves+='namespace AnimusForge {internal static class Logger {internal static void Log(string area,string text){Console.WriteLine("DIAG "+area+":"+text);}}}namespace TaleWorlds.CampaignSystem {internal class Campaign {internal static Campaign Current;internal ConversationManager ConversationManager;}internal class ConversationManager {internal object OneToOneConversationAgent;internal bool IsConversationInProgress;}}namespace TaleWorlds.CampaignSystem.Party {internal class PartyBase {}}namespace TaleWorlds.CampaignSystem.Encounters {internal static class PlayerEncounter {internal static TaleWorlds.CampaignSystem.Party.PartyBase EncounteredParty;}}'
        if args.lore_current:
            leaves='using TaleWorlds.MountAndBlade;'+leaves
            leaves=leaves.replace('internal bool IsSoldier;','internal bool IsSoldier;internal string Occupation;')
            leaves+='namespace AnimusForge {internal static partial class AIConfigHandler {internal static int LoreReads;internal static bool Throw;internal static string Input,Secondary,Kind,Kingdom;internal static string Read(string input,string secondary,string kind,string kingdom){LoreReads++;Input=input;Secondary=secondary;Kind=kind;Kingdom=kingdom;if(Throw)throw new Exception("lore leaf");return "captured lore";}internal static string GetLoreContext(string input,TaleWorlds.CampaignSystem.Hero h,string secondary)=>Read(input,secondary,"hero",null);internal static string GetLoreContext(string input,TaleWorlds.CampaignSystem.CharacterObject c,string kingdom,string secondary)=>Read(input,secondary,"character",kingdom);}}'
        if args.public_targeted_current:
            leaves='using TaleWorlds.MountAndBlade;using TaleWorlds.CampaignSystem.Encounters;'+leaves
            leaves=leaves.replace('internal class Hero {','internal class Hero {internal static Hero MainHero,OneToOneConversationHero;').replace('internal class CharacterObject {','internal class BasicCharacterObject {internal bool IsHero;}internal class CharacterObject:BasicCharacterObject {internal static CharacterObject PlayerCharacter,OneToOneConversationCharacter;').replace('internal class PartyBase {}','internal class PartyBase {internal Hero LeaderHero;}').replace('internal static void Log(string area,string text)', 'internal static void LogTrace(string area,string text)=>Log(area,text);internal static void Log(string area,string text)')
            leaves+='namespace TaleWorlds.CampaignSystem.Conversation {internal static class ConversationHelper {internal static TaleWorlds.CampaignSystem.CharacterObject GetConversationCharacterPartyLeader(TaleWorlds.CampaignSystem.Party.PartyBase p)=>p?.LeaderHero?.CharacterObject;}}namespace AnimusForge {internal static class EncyclopediaEntityLinkFormatter {internal static bool Throw;internal static Hero Hero;internal static string FormatNativeConversationText(string text,Hero h,CharacterObject c){Hero=h;if(Throw)throw new Exception("display leaf");return "formatted:"+text;}internal static string SanitizeUntrustedRichText(string text)=>"sanitized:"+text;}internal static class PlayerEncounterCompat {internal static bool PostBattle;internal static bool IsInPostBattleResultFlow()=>PostBattle;}}'
            boundary=out/'HistoryWorkBoundaryLeaf.cs';b=boundary.read_text(encoding='utf-8');b=b.replace('internal sealed class MyBehavior {','internal sealed class MyBehavior {internal static List<string> PrivateFacts=new();internal static void AppendExternalDialogueHistory(Hero h,string player,string reply,string fact)=>PrivateFacts.Add(fact);');boundary.write_text('using System.Collections.Generic;using TaleWorlds.CampaignSystem;'+b,encoding='utf-8')
            gccz=out/'IndependentGcczBoundaryLeaf.cs';b=gccz.read_text(encoding='utf-8').replace('internal static bool Active,','internal static bool Persistent;internal static bool ShouldUsePersistentPersonalMemory(Hero h,CharacterObject c,int i)=>Persistent;internal static bool Active,');gccz.write_text(b,encoding='utf-8')
            (out/'NativePublicLookupLeaf.cs').write_text('using System;using System.Collections.Generic;namespace AnimusForge;internal static class NativePublicLookupProbe {internal static bool Success=true;internal static string Error;internal static int Cap,Calls;internal static string User,Secondary,Runtime;internal static List<string> Ids=new(){" Duel ","duel","trust"};internal static IEnumerable<string> Excluded;}internal static partial class AIConfigHandler {internal static bool TryCallAuxiliaryRuleCodesForExternal(string user,string secondary,string runtime,int cap,out List<string> ids,out string error,IEnumerable<string> excluded){NativePublicLookupProbe.Calls++;NativePublicLookupProbe.User=user;NativePublicLookupProbe.Secondary=secondary;NativePublicLookupProbe.Runtime=runtime;NativePublicLookupProbe.Cap=cap;NativePublicLookupProbe.Excluded=excluded;ids=NativePublicLookupProbe.Ids;error=NativePublicLookupProbe.Error;return NativePublicLookupProbe.Success;}}',encoding='utf-8')
        (out/'GameCaptureLeaves.cs').write_text(leaves,encoding='utf-8')
    program=program.replace('internal static class ShoutUtils {', 'internal static class ShoutUtils { internal static bool IsInValidScene()=>TaleWorlds.MountAndBlade.Mission.Valid; internal static NpcDataPacket ExtractNpcData(TaleWorlds.MountAndBlade.Agent a)=>a?.Npc; internal static string GetPromptHistoryName(NpcDataPacket n)=>n?.Name; internal static string GetPromptIdentityName(NpcDataPacket n)=>n?.Name;',1)
    (out/'MissionCaptureLeaf.cs').write_text('namespace TaleWorlds.MountAndBlade;internal class Mission {internal static Mission Current;internal static bool Valid=true;internal object Scene;internal System.Collections.Generic.List<Agent> Agents;}internal class Agent {internal bool IsMainAgent;internal Origin Origin;internal int Index;internal bool Active=true;internal bool IsActive()=>Active;internal object Character;internal AnimusForge.NpcDataPacket Npc;}internal class Origin {internal object BattleCombatant;}',encoding='utf-8')
    if args.public_targeted_current:
        f=out/'MissionCaptureLeaf.cs';b=f.read_text(encoding='utf-8').replace('internal class Agent {','internal enum AgentState {Active,Inactive}internal class Agent {internal bool IsHuman=true;internal AgentState State=AgentState.Active;internal float Health=100;internal string Name;').replace('internal object Character;','internal TaleWorlds.CampaignSystem.BasicCharacterObject Character;');f.write_text(b,encoding='utf-8')
        b=out/'CurrentNativeAgentResolver.cs';code=b.read_text(encoding='utf-8');extra=extract(input_path,'internal static bool CanAgentParticipateInSceneSpeech(')+extract(input_path,'internal static bool IsNativeConversationInputOpenForExternal(')+extract('src/modules/AF.Module.Conversation/Channels/Scene/ShoutBehavior.cs','internal static string ResolveCurrentNativeConversationTargetKey(')
        code=code[:code.rfind('}')]+'internal static bool _nativeConversationInputOpen;internal static string _nativeConversationInputTargetKey;internal static object CurrentInstance;internal static bool TryResolveNativeConversationTarget(out Hero h,out CharacterObject c,out string n)=>SceneAgentIdentityPromptCaptureAdapter.TryResolveNativeConversationTarget(out h,out c,out n);'+extra+'}';b.write_text(code,encoding='utf-8')
    if args.wilderness_current:
        assert args.native_history_current
        ap='src/AF.GameAdapter.Bannerlord/Prompt/SceneAgentIdentityPromptCaptureAdapter.cs'
        agent='\n'.join(extract(ap,'internal static '+kind+' '+method+'(') for kind,method in [('bool','TryResolveWildernessNonHeroMemory'),('MobileParty','TryResolveWildernessNonHeroMobileParty'),('bool','IsWildernessNonHeroMemoryScope'),('string','BuildWildernessNonHeroCharacterMemoryKey'),('string','BuildWildernessNonHeroPartyMemoryKey'),('string','BuildWildernessNonHeroPartyTrace'),('string','BuildWildernessNonHeroPartyRepresentativePrompt'),('PartyBase','ResolveWildernessNonHeroPartyBaseForPrompt'),('bool','TryResolveWildernessNonHeroRewardParty')])
        leaf=out/'GameCaptureLeaves.cs';text=leaf.read_text(encoding='utf-8')
        old='internal static bool TryResolveWildernessNonHeroMemory(AnimusForge.NpcDataPacket n,TaleWorlds.CampaignSystem.Hero h,TaleWorlds.CampaignSystem.CharacterObject c,int i,out string id,out string name){id=name="";throw new Exception("UNVISITED wilderness identity capability");}internal static TaleWorlds.CampaignSystem.Party.MobileParty TryResolveWildernessNonHeroMobileParty(int i)=>throw new Exception("UNVISITED wilderness game capability");'
        assert old in text;text=text.replace(old,agent,1).replace('using TaleWorlds.CampaignSystem;','using TaleWorlds.CampaignSystem;using TaleWorlds.CampaignSystem.Party;using TaleWorlds.CampaignSystem.Settlements;using TaleWorlds.CampaignSystem.Encounters;using TaleWorlds.MountAndBlade;',1)
        text=text.replace('internal class MobileParty {internal static MobileParty MainParty;','internal class MobileParty {internal object Name;internal string StringId;internal PartyBase Party;internal TaleWorlds.CampaignSystem.Settlements.Settlement CurrentSettlement;internal static MobileParty MainParty;',1).replace('internal class Faction{internal string StringId;}','internal class Faction{internal string StringId;internal object Name;}',1).replace('internal class PartyBase {}','internal class PartyBase {internal static PartyBase MainParty;internal bool IsMobile;internal MobileParty MobileParty;internal object ItemRoster;internal int Index;}',1)
        text+='namespace TaleWorlds.CampaignSystem.Settlements {internal class Settlement {internal static Settlement CurrentSettlement;}}namespace TaleWorlds.Core {internal class Game {internal static Game Current;internal GameStateManager GameStateManager;}internal class GameStateManager {internal object ActiveState;}}namespace TaleWorlds.MountAndBlade {internal class MissionState {}}'
        leaf.write_text(text,encoding='utf-8')
        world=extract('src/AF.GameAdapter.Bannerlord/Conversation/ConversationActionBoundaryBannerlordAdapter.cs','internal static bool IsNativeConversationWorldMapContext(')
        (out/'CurrentWorldMapGuard.cs').write_text('using System;using TaleWorlds.Core;using TaleWorlds.MountAndBlade;namespace AnimusForge.Refactor.Adapters;internal static class ConversationActionBoundaryBannerlordAdapter {'+world+'}',encoding='utf-8')
        identifier=extract('src/AF.GameAdapter.Bannerlord/Records/CampaignCharacterRecordCaptureAdapter.cs','internal static string BuildNonHeroMemoryId(')
        normalize=extract('src/modules/AF.Module.Memory/Records/MemoryPersistenceModels.cs','internal static string NormalizeMemoryHeroId(')
        state_source=(ROOT/'src/modules/AF.Module.Memory/Summary/MemoryBusinessStateOwner.cs').read_text(encoding='utf-8-sig');prefix=state_source[state_source.index('internal const string NonHeroMemoryIdPrefix'):];prefix=prefix[:prefix.index(';')+1]
        state_path='src/modules/AF.Module.Memory/Summary/MemoryBusinessStateOwner.cs';source_receipts.append(dict(path=state_path,signature='NonHeroMemoryIdPrefix actual constant',rawSha256=hashlib.sha256((ROOT/state_path).read_bytes()).hexdigest(),bodySha256=hashlib.sha256(prefix.encode('utf-8')).hexdigest()))
        (out/'CurrentNonHeroIdentifier.cs').write_text('using System;namespace AnimusForge;internal static class CampaignCharacterRecordCaptureAdapter {'+identifier+'}internal static class MemoryRecordRules {'+normalize+'}internal static class MemoryBusinessStateOwner {'+prefix+'}',encoding='utf-8')
        boundary=out/'HistoryWorkBoundaryLeaf.cs';text=boundary.read_text(encoding='utf-8');extra='internal static string HistoryResult;internal static readonly System.Collections.Generic.List<string> Appends=new(),Migrations=new();internal static TaleWorlds.CampaignSystem.Party.PartyBase Counterparty;internal static TaleWorlds.CampaignSystem.Party.PartyBase ResolvePartyTransferCounterpartyForExternal(TaleWorlds.CampaignSystem.Hero h,TaleWorlds.CampaignSystem.CharacterObject c,int i)=>Counterparty;internal static string BuildNonHeroMemoryIdForExternal(string key)=>CampaignCharacterRecordCaptureAdapter.BuildNonHeroMemoryId(key);internal static string GetOrCreateWildernessNonHeroPartyMemoryKeyForExternal(TaleWorlds.CampaignSystem.Party.MobileParty p)=>"";internal static string GetExistingWildernessNonHeroPartyMemoryKeyForExternal(TaleWorlds.CampaignSystem.Party.MobileParty p)=>"";internal static void MigrateNonHeroPartyScopedMemoryForExternal(string id,string key)=>Migrations.Add(id+":"+key);internal static string BuildNonHeroHistoryContextForExternal(string id,string name,int cap,string input,string secondary,bool include)=>HistoryResult;internal static void AppendExternalNonHeroSceneDialogueHistory(string id,string name,string player,string reply,string fact,int session)=>Appends.Add(id+":"+session);internal static void AppendExternalNonHeroDialogueHistory(string id,string name,string player,string reply,string fact)=>Appends.Add(id+":default");'
        text=text.replace('internal sealed class MyBehavior {','internal sealed class MyBehavior {'+extra,1);boundary.write_text(text,encoding='utf-8')
        capture=out/'CurrentStrictCapture.cs';text=capture.read_text(encoding='utf-8');text=text[:text.rfind('}')]+'\n'+extract(cp,'internal static string BuildWildernessNonHeroHistoryContextForPrompt(')+extract(cp,'internal static void AppendWildernessNonHeroMemory(')+'}';capture.write_text(text,encoding='utf-8')
    if args.uncompressed_family_current:
        f=out/'HistoryWorkBoundaryLeaf.cs';b=f.read_text(encoding='utf-8');extra='internal static int UncompressedReads;internal static string UncompressedId,UncompressedName;internal static Hero UncompressedHero;internal static int UncompressedIndex;internal static bool UncompressedInclude,UncompressedThrow;internal static List<ConversationMessage> UncompressedResult=new(){new(){Role="user",Content="player"},new(){Role="assistant",Content="NPC"}};internal static List<ConversationMessage> ReadUncompressed(Hero hero,string id,string name,int index,bool include){UncompressedReads++;UncompressedHero=hero;UncompressedId=id;UncompressedName=name;UncompressedIndex=index;UncompressedInclude=include;if(UncompressedThrow)throw new Exception("controlled actual memory boundary exception");return UncompressedResult;}internal static List<ConversationMessage> BuildUncompressedMemoryRoleMessagesForExternal(Hero h,int i,bool includeCurrentActiveSceneSession)=>ReadUncompressed(h,null,null,i,includeCurrentActiveSceneSession);internal static List<ConversationMessage> BuildNonHeroUncompressedMemoryRoleMessagesForExternal(string id,string name,int i,bool includeCurrentActiveSceneSession)=>ReadUncompressed(null,id,name,i,includeCurrentActiveSceneSession);'
        b=b.replace('internal sealed class MyBehavior {','internal sealed class MyBehavior {'+extra,1);f.write_text('using System.Collections.Generic;using TaleWorlds.CampaignSystem;'+b,encoding='utf-8')
        f=out/'IndependentGcczBoundaryLeaf.cs';b=f.read_text(encoding='utf-8');b=b.replace('internal static bool Active,','internal static bool Persistent=true;internal static int PersistentReads;internal static bool ShouldUsePersistentPersonalMemory(Hero h,CharacterObject c,int i){PersistentReads++;return Persistent;}internal static bool Active,',1);f.write_text(b,encoding='utf-8')
        f=out/'MissionCaptureLeaf.cs';b=f.read_text(encoding='utf-8');b=b.replace('internal static Mission Current;','private static Mission _current;internal static bool Throw;internal static int Reads;internal static Mission Current {get{Reads++;if(Throw)throw new System.Exception("mission");if(!TaleWorlds.Library.TWParallel.Main)throw new System.Exception("BACKGROUND LIVE READ");return _current;}set{_current=value;}}');f.write_text(b,encoding='utf-8')
    if args.uncompressed_family_host_current:
        assert args.uncompressed_family_current and not args.uncompressed_family_original
        wrappers=''.join(extract('src/modules/AF.Module.Conversation/Channels/Scene/ShoutBehavior.cs',sig) for sig in family_signatures)
        assert wrappers.count('return SceneHistoryPromptCaptureAdapter.BuildUncompressedMemoryRoleMessagesForPrompt(')==3
        (out/'CurrentUncompressedHostFacade.cs').write_text('using System;using System.Collections.Generic;using TaleWorlds.CampaignSystem;using AnimusForge.Refactor.Adapters;namespace AnimusForge;internal static partial class ShoutBehavior {'+wrappers+'}',encoding='utf-8')
        f=out/'CurrentNativeThreadGuard.cs';b=f.read_text(encoding='utf-8').replace('internal static class ShoutBehavior {','internal static partial class ShoutBehavior {');f.write_text(b,encoding='utf-8')
    program=program.replace('static void Main()','static void OriginalMain()',1)+(HERE/'Harness.cs.txt').read_text(encoding='utf-8').split('// @@STRICT_CAPTURE_CURRENT@@')[1].split('// @@LORE_CURRENT_CASES@@')[0].split('// @@PUBLIC_TARGETED_CURRENT_CASES@@')[0].split('// @@UNCOMPRESSED_FAMILY_CURRENT_CASES@@')[0]
    if not args.wilderness_current:
        program=program.split('// @@WILDERNESS_CURRENT_CASES@@')[0]+program.split('// @@WILDERNESS_CURRENT_END@@')[-1] if '// @@WILDERNESS_CURRENT_CASES@@' in program else program

    if not args.native_history_current: program=program.split('// @@NATIVE_HISTORY_CURRENT_CASES@@')[0]+' Console.WriteLine("PASS strict capture current "+Count);}}'
    else: program=program.replace('Console.WriteLine("PASS strict capture current "+Count);','')
if args.lore_current:
    cases=(HERE/'Harness.cs.txt').read_text(encoding='utf-8').split('// @@LORE_CURRENT_CASES@@')[1].split('// @@PUBLIC_TARGETED_CURRENT_CASES@@')[0].split('// @@UNCOMPRESSED_FAMILY_CURRENT_CASES@@')[0]
    program=program.replace('var hero=new TaleWorlds.CampaignSystem.Hero{StringId="ada"',cases+'var hero=new TaleWorlds.CampaignSystem.Hero{StringId="ada"',1)
if args.public_targeted_current:
    cases=(HERE/'Harness.cs.txt').read_text(encoding='utf-8').split('// @@PUBLIC_TARGETED_CURRENT_CASES@@')[1].split('// @@UNCOMPRESSED_FAMILY_CURRENT_CASES@@')[0]
    program=program.replace('Console.WriteLine("PASS strict/native history current "+Count);',cases+'Console.WriteLine("PASS strict/native history current "+Count);')
if args.uncompressed_family_current:
    cases=(HERE/'Harness.cs.txt').read_text(encoding='utf-8').split('// @@UNCOMPRESSED_FAMILY_CURRENT_CASES@@')[1]
    if args.uncompressed_family_host_current:cases=cases.replace('AnimusForge.Refactor.Adapters.SceneHistoryPromptCaptureAdapter.BuildUncompressedMemoryRoleMessagesForPrompt(', 'AnimusForge.ShoutBehavior.BuildUncompressedMemoryRoleMessagesForPrompt(')
    program=program.replace('Console.WriteLine("PASS strict/native history current "+Count);',cases+'Console.WriteLine("PASS strict/native history current "+Count);')
(out/'Program.cs').write_text(program,encoding='utf-8')
paths=['src/modules/AF.Module.Prompt/Composition/SceneHistoryMessageAssemblyOwner.cs','src/modules/AF.Module.Prompt/Composition/ConversationRoleClassificationOwner.cs','src/modules/AF.Module.Conversation/Internal/History/ConversationMessage.cs','src/modules/AF.Module.Conversation/Internal/History/ConversationSpeechTextRules.cs']
paths += ['src/modules/AF.Module.Conversation/Internal/History/SceneHistoryProjectionOwner.cs']
if args.public_targeted_current: paths += ['src/AF.Contracts/Internal/InteractionContracts.cs','src/AF.Contracts/Internal/LlmContracts.cs','src/modules/AF.Module.Prompt/Configuration/LegacyDetachedRuleSelector.cs']
if args.native_history_current: paths += ['src/modules/AF.Module.Conversation/Channels/Native/NativeConversationSessionOwner.cs','src/modules/AF.Module.Memory/Records/AnimusForgeDialogueHistoryEntry.cs','src/modules/AF.Module.Conversation/Internal/History/NativeHistoryIdentityProjectionOwner.cs']
if args.strict_capture_current: paths += ['src/modules/AF.Module.Conversation/Internal/History/SceneConversationHistoryOwner.cs','src/modules/AF.Module.Prompt/Composition/HistorySectionProjectionOwner.cs','src/modules/AF.Module.Conversation/Channels/Scene/ScenePendingAfefFactsOwner.cs']
if args.pure_message_current: paths.append('src/modules/AF.Module.Memory/Records/DialogueHistoryLedger.cs')
if args.pure_message_current:
    paths.append('src/modules/AF.Module.Economy/Host/GiveAssetTagCodec.cs')
    source_receipts.extend(dict(path=x,signature='FULL_CURRENT_SOURCE',rawSha256=hashlib.sha256((ROOT/x).read_bytes()).hexdigest()) for x in paths)
if args.strict_capture_current: source_receipts.extend(dict(path=x,signature='FULL_CURRENT_SOURCE',rawSha256=hashlib.sha256((ROOT/x).read_bytes()).hexdigest()) for x in paths)
if args.strict_capture_current and not (args.native_history_current or args.wilderness_current):
    (out/'EmptyPartyNamespace.cs').write_text('namespace TaleWorlds.CampaignSystem.Party {}',encoding='utf-8')
(out/'Tests.csproj').write_text('<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><Nullable>disable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup>'+''.join('<Compile Include="'+str(ROOT/p)+'" />' for p in paths)+'</ItemGroup></Project>',encoding='utf-8')
(out/'NuGet.Config').write_text('<configuration><packageSources><clear/></packageSources></configuration>',encoding='utf-8')
dotnet=ROOT/'local/dotnet/8.0.425/dotnet.exe'
env=minimal_test_environment(dotnet,out)
r=subprocess.run([str(dotnet),'run','--project',str(out/'Tests.csproj'),'-c','Release']+(['-p:DefineConstants=BANNERLORD_1_4_OR_GREATER'] if args.api_line=='1.4' else []),cwd=out,env=env,capture_output=True,text=True,encoding='utf-8',errors='replace',timeout=90)
(out/'run.log').write_text(r.stdout+r.stderr,encoding='utf-8')
if args.pure_message_current or args.strict_capture_current:
    after=[dict(path=x['path'],rawSha256=hashlib.sha256((ROOT/x['path']).read_bytes()).hexdigest()) for x in source_receipts]
    assert all(x['rawSha256']==y['rawSha256'] for x,y in zip(source_receipts,after)), 'current source changed during test'
    (out/'receipt.json').write_text(json.dumps(dict(sourceClass=('current-production-exact-strict-capture + whole history/pending/assembly owners' if args.strict_capture_current else 'current-production-exact-pure-declarations'),controlledLeaves=(['game date/hour/location/identity/distance and settings access','named player custom-rule capture (not its algorithm)','independent ShoutUtils and visible normalizer leaves'] if args.strict_capture_current else ['ShoutUtils independent name selection','detached DTO','public player name scalar capture and A first-meeting capability (not their algorithms)']),api=args.api_line,exitCode=r.returncode,inputs=source_receipts,after=after),indent=2),encoding='utf-8')
print(r.stdout+r.stderr,end=''); raise SystemExit(r.returncode)
