using AnimusForge;
using AnimusForge.Refactor.Runtime;
namespace AnimusForge { public static class Logger { public static void Log(string area,string message){} } }
namespace TaleWorlds.Library { public static class TWParallel { public static bool IsMainThread()=>true; } public static class MBMath { public static int ClampInt(int x,int min,int max)=>Math.Clamp(x,min,max); } }
internal static class Program
{
 sealed class Scope:IDisposable { public void Dispose(){} }
 static int count; static void Check(bool ok,string name) { if(!ok)throw new Exception(name);count++; }
 static MemorySummaryJob Job()=>new(){HeroId="hero",HeroName="Hero",GameDayIndex=2};
 static DailyMemoryDraft Draft(string id="hero")=>new(){HeroId=id,GameDayIndex=2,HasLlmDialogue=true,Lines=new(){new(){Text="fact",Speaker="NPC"}}};
 static CompressedMemoryBlock Block()=>new(){HeroId="hero",GameDayIndex=2,RichTitle="Title",Summary="summary",PlayerHistoryMaterial="public"};
 static MemoryBusinessStateOwner Owner(){var o=new MemoryBusinessStateOwner();o.Drafts["hero"]=new(){Draft()};o.DailyQueue.Add(Job());return o;}
 static MemoryDailyCommitEffects Effects(List<string> seq,string fail="")=>new(){
  MarkOverviewDirty=id=>seq.Add("dirty"),ClearNativeHistory=day=>{seq.Add("native");if(fail=="native")throw new Exception("native");},
  LogSuccess=()=>seq.Add("log"),RecordPublicMemory=b=>{seq.Add("social");if(fail=="social")throw new Exception("social");},
  RecordPublicWeeklyMaterial=b=>seq.Add("public-weekly"),RecordWeeklyMaterial=b=>seq.Add("weekly"),EnqueueOverview=(id,name,b)=>seq.Add("overview")};
 static void Main(){
  var o=Owner();var seq=new List<string>();Check(o.ApplyDaily(Job(),Block(),"hero",Effects(seq)),"daily accepted");
  Check(seq.SequenceEqual(new[]{"dirty","native","log","social","public-weekly","weekly","overview"}),"cross-domain order");
  Check(o.DailyQueue.Count==0&&!o.Drafts.ContainsKey("hero")&&o.Blocks["hero"].Count==1,"daily persisted states");
  foreach(var boundary in new[]{"native","social"}) {o=Owner();seq=new();try{o.ApplyDaily(Job(),Block(),"hero",Effects(seq,boundary));throw new Exception("failure swallowed");}catch(Exception e){Check(e.Message==boundary,"original failure propagated");}
   Check(o.Blocks["hero"].Count==1&&!o.Drafts.ContainsKey("hero"),"partial block/draft success");
   Check(o.DailyQueue.Count==(boundary=="native"?1:0),"partial queue order");Check(!seq.Contains("weekly")&&!seq.Contains("overview"),"later effects suppressed");}
  o=Owner();o.Drafts["hero"]=new(){Draft("wrong")};o.FailDaily(Job()," fail ");Check(o.DailyQueue[0].RetryCount==3&&o.DailyQueue[0].LastError=="fail","daily terminal queue");Check(o.Drafts["hero"][0].SummaryRetryCount==0,"mismatched old-json identity untouched");
  o=Owner();o.FailDaily(Job(),"fail");Check(o.Drafts["hero"][0].SummaryRetryCount==3,"daily terminal draft");
  var overview=new MemoryOverviewState{HeroId="hero",Summary="old",IncludedBlockIds=new(){"b"}};o.Overviews["hero"]=overview;o.OverviewQueue.Add(new(){HeroId="hero"});o.FailOverview(new(){HeroId="hero"},"error");
  Check(o.OverviewQueue[0].RetryCount==3&&o.Overviews["hero"].LastError=="error","overview terminal");Check(overview.LastError==""&&!ReferenceEquals(overview,o.Overviews["hero"]),"overview failure detaches copy");
  Check(o.ApplyOverview(new(){HeroId="hero"},new(){Summary="new"},"hero",()=>{}),"overview success");Check(o.OverviewQueue.Count==0&&o.Overviews["hero"].Summary=="new","overview remove queue");
  o.MajorQueue.Add(new(){HeroId="hero"});o.FailMajor(new(){HeroId="hero"},"err");Check(o.MajorQueue[0].RetryCount==3&&o.MajorSummaries["hero"].LastError=="err","major terminal");
  Check(o.ApplyMajor(new(){HeroId="hero"},new(){Summary="major",LastSummarizedDay=4,LastSummarizedSequence=8},"hero",()=>{}),"major accepted");Check(o.MajorQueue.Count==0&&o.MajorSummaries["hero"].LastSummarizedSequence==8,"major cursor preserved");
  o=Owner();o.DailyQueue.Add(new(){HeroId="target",GameDayIndex=2});o.OverviewQueue.Add(new(){HeroId="hero"});o.MajorQueue.Add(new(){HeroId="hero"});o.PendingWeeklyTriggers.Add(new(){MemoryId="hero",GameDayIndex=2,StableKey="key"});o.DirtyOverviewIds.Add("hero");o.OverviewCandidateIdSet.Add("hero");o.OverviewCandidateIds.Enqueue("hero");
  o.RetargetMemoryQueues("hero","target");Check(o.DailyQueue.Count==1&&o.DailyQueue[0].HeroId=="target","identity daily queue dedup");Check(o.OverviewQueue[0].HeroId=="target"&&o.MajorQueue[0].HeroId=="target","identity other queues");
  o.RetargetMemoryOverviewCandidateScanIds("hero","target");Check(o.DirtyOverviewIds.Contains("target")&&!o.DirtyOverviewIds.Contains("hero")&&o.OverviewCandidateIds.Dequeue()=="target","identity candidate indexes");
  o.Overviews["hero"]=new(){HeroId="hero",Summary="source",IncludedBlockIds=new(){"a"},UpdatedUtcTicks=9};o.Overviews["target"]=new(){HeroId="target",Summary="target",IncludedBlockIds=new(){"b"},UpdatedUtcTicks=4};o.MergeMemoryOverviewStateById("hero","target");Check(o.Overviews["target"].Summary=="target\nsource"&&o.Overviews["target"].IncludedBlockIds.SequenceEqual(new[]{"b","a"})&&o.Overviews["target"].UpdatedUtcTicks==9,"identity overview merge");
  var d=Draft();var merged=MemoryBusinessStateOwner.MergeDailyMemoryDraftLists(new[]{d},new[]{Draft("source")},"target");Check(merged.Count==1&&d.HeroId=="target","identity daily live alias retained");
  var b1=Block();var b2=Block();b2.Summary="second";b2.StartHour=1;b2.EndHour=8;var mergedB=MemoryBusinessStateOwner.MergeCompressedMemoryBlockLists(new[]{b1},new[]{b2},"target");Check(mergedB.Count==1&&mergedB[0].HeroId=="target"&&mergedB[0].Summary=="summary\nsecond","identity blocks order");
  o=Owner();o.DailyQueue.Add(new(){HeroId="hero",GameDayIndex=2});o.DailyQueue.Add(new(){HeroId="invalid",GameDayIndex=3});o.DailyQueue.Add(null);o.OverviewQueue.Add(new(){HeroId="hero"});o.OverviewQueue.Add(new(){HeroId="other",TriggerGameDayIndex=3});int phases=0;
  var port=new MemorySummaryPlanningPort{MaxJobs=2,GetBudgetMilliseconds=()=>0,ElapsedTicks=()=>0,IsEntityEligible=id=>id!="invalid",IsDailyPending=j=>j.HeroId!="invalid",IsMajorPending=j=>true,IsOverviewPending=j=>true,CancelUnavailable=(id,reason)=>{},RunPhaseAsync=async(run,gen,apply)=>{await Task.Yield();phases++;return apply();}};
  var plan=new MemorySummaryPlanningOwner(o,port).BuildMemorySummaryPlanAsync(1).GetAwaiter().GetResult();Check(plan.DailyCount==1&&plan.OverviewCount==1&&plan.Items.Count==2,"planner dedup daily before overview");Check(o.DailyQueue.Count==2&&o.DailyQueue.All(x=>x!=null&&x.HeroId!="invalid"),"planner filters invalid and null before compact");Check(phases>=7,"planner bounded job slices");
  o=Owner();o.QueuePort=new(){IsEntityEligible=id=>id!="dead",OverviewStartCount=()=>1,CurrentDay=()=>4,Log=(tag,text)=>{}};
  Check(o.HasMemorySummaryJobStillPending(Job()),"daily live pending");o.Drafts["hero"][0].SummaryRetryCount=3;Check(!o.HasMemorySummaryJobStillPending(Job()),"terminal draft suppresses queue recreation");
  o.Blocks["hero"]=new(){Block()};o.TryEnqueueMemoryOverviewForMemoryId("hero","Hero");Check(o.OverviewQueue.Count==1,"overview queue state owner");o.Overviews["hero"]=new(){HeroId="hero",LastError="terminal"};Check(!o.HasMemoryOverviewJobStillPending(new(){HeroId="hero"}),"overview terminal query");
  o.MajorActions["hero"]=new(){new(){Day=2,Sequence=1,Text="action"}};o.TryEnqueueMajorActionSummaryForDraft(Draft(),new(),true);Check(o.MajorQueue.Count==1,"major queue state owner");o.MajorSummaries["hero"]=new(){HeroId="hero",LastError="terminal"};Check(!o.HasMajorActionSummaryJobStillPending(new(){HeroId="hero"}),"major terminal query");
  o.OverviewStorage["hero"]="persist";o.MajorStorage["hero"]="persist";o.PendingWeeklyTriggers.Add(new(){MemoryId="hero",GameDayIndex=2,StableKey="key"});o.Sealing.Queued=new(){"hero|2"};o.Sealing.QueuedMajor=new(){"hero"};
  Check(o.CancelUnavailableHeroCompressionWorkById("hero","dead"),"unavailable cancels work");Check(o.DailyQueue.Count==0&&o.OverviewQueue.Count==0&&o.MajorQueue.Count==0&&o.OverviewStorage.Count==0&&o.MajorStorage.Count==0,"unavailable cancels derived stores");Check(o.Drafts.ContainsKey("hero")&&o.Blocks.ContainsKey("hero")&&o.PendingWeeklyTriggers.Count==1&&o.MajorActions.ContainsKey("hero"),"unavailable retains weekly fact sources");Check(o.Sealing.Queued.Count==0&&o.Sealing.QueuedMajor.Count==0,"unavailable clears seal dedup");
  o=new();var history=new Dictionary<string,List<MyBehavior.DialogueDay>>();var recovery=new MemoryRecoveryStateOwner(o);int publishes=0;
  recovery.Bind(new(){IsEntityEligible=id=>true,CurrentDay=()=>4,CurrentDate=()=>"day4",History=()=>history,LoadHistory=id=>history.TryGetValue(id,out var h)?h:new(),SaveHistory=(id,h)=>{history[id]=h;publishes++;},RemoveExpiredFacts=h=>false,Log=(area,text)=>{},TickScope=()=>new Scope()});
  var seed=new InteractionMemoryRecoverySeed{CommitId="commit",Channel=0,SessionId="s",SubjectId="hero",NpcName="NPC",OriginGameDay=2,OriginGameDate="day2",OriginGameHour=3,Components=new[]{new InteractionMemoryRecoveryComponentSeed{Part="user",DailySpeaker="player",DailyText="daily",RecentText="recent",IsLlmDialogue=true},new InteractionMemoryRecoveryComponentSeed{Part="fact",DailySpeaker="AFEF",DailyText="fact",RecentText="fact",IsAfef=true}}};
  Check(recovery.Ledger.Begin(seed,out var rid,out var err)==InteractionMemoryRecoveryBeginStatus.Began,"recovery begins");recovery.ProcessInteractionMemoryRecoveryEntry(rid);Check(recovery.Ledger.IsCompleted(rid)&&o.Drafts["hero"][0].Lines.Count==2&&history["hero"][0].Lines.Count==2,"recovery publishes both parts and projections");recovery.ProcessInteractionMemoryRecoveryEntry(rid);Check(publishes==2,"recovery duplicate never republishes");
  var line=o.Drafts["hero"][0].Lines[0];line.MemoryCommitPart="assistant";recovery.ReconcilePersistedInteractionMemoryRecoveryMarkers();Check(recovery.Ledger.QuarantineCount==1,"recovery wrong part missing mask quarantines");
  recovery.ResetInteractionMemoryRecoveryTransientState("sync_load");Check(recovery.LoadConfirmed==0&&recovery.LoadedGeneration==0,"recovery sync clears stamp");recovery.ResetInteractionMemoryRecoveryTransientState("game_loaded");Check(recovery.LoadedGeneration==0,"recovery event cannot manufacture import proof");recovery.ActivateInteractionMemoryRecoveryAfterLoad();Check(recovery.Ledger.IsDisabled,"recovery unconfirmed save disabled");
  var store=new ExecutionTranscriptStore();var record=store.Ensure(new(){SessionId="s"});Check(store.Complete("missing",true,"a")==null,"execution missing");Check(ReferenceEquals(record,store.Complete("s",false,"a"))&&record.Outcome=="cancelled"&&record.Actor=="a","execution cancel state");Check(store.Complete("s",true,"b")==null&&record.Actor=="a","execution repeated no rewrite");record=store.Ensure(new(){SessionId="e"});Check(store.Complete("e",true,"Player")==record&&record.Outcome=="executed","execution death state");
  bool main=false,campaign=true;long gen=SaveRuntimeGuard.CurrentGeneration;int shown=0,observed=0;Action callback=null;
  var notices=new MemoryFailureNoticeOwner();notices.Bind(new(){IsCurrentOwner=g=>g==SaveRuntimeGuard.CurrentGeneration,IsCurrentCampaign=()=>campaign,IsMainThread=()=>main,Observe=(a,b)=>observed++,Show=(a,b,c)=>{shown++;callback=c;}});
  notices.PublishMemoryFailureNotice("first","one",gen);notices.PublishMemoryFailureNotice("second","two",gen);Check(shown==0&&observed==2,"failure background never UI");main=true;notices.ProcessPendingMemoryFailureNotice();Check(shown==1&&notices.Active,"first pending failure shown");var oldCallback=callback;notices.ResetMemoryFailureNotices();notices.PublishMemoryFailureNotice("new","three",gen);oldCallback();Check(notices.Active&&shown==2,"obsolete revision cannot close replacement");callback();Check(!notices.Active,"current callback releases active");
  main=false;notices.PublishMemoryFailureNotice("stale","x",gen);SaveRuntimeGuard.AdvanceGeneration("notice test");main=true;notices.ProcessPendingMemoryFailureNotice();Check(shown==2&&!notices.Active,"stale save never shown");notices.Bind(new(){IsCurrentOwner=g=>true,IsCurrentCampaign=()=>true,IsMainThread=()=>true,Observe=(a,b)=>{},Show=(a,b,c)=>throw new Exception("UI")});notices.PublishMemoryFailureNotice("throw","x",SaveRuntimeGuard.CurrentGeneration);Check(!notices.Active,"UI failure releases own revision");
  Check(!MemoryRecoveryStateOwner.ShouldCompleteInitialInteractionMemoryNotoriety(InteractionMemoryRecoveryBeginStatus.ExistingPending,true,"id","id")&&!MemoryRecoveryStateOwner.ShouldCompleteInitialInteractionMemoryNotoriety(InteractionMemoryRecoveryBeginStatus.Began,true,"id","other")&&MemoryRecoveryStateOwner.ShouldCompleteInitialInteractionMemoryNotoriety(InteractionMemoryRecoveryBeginStatus.Began,true,"id","id"),"aux completion new matching commit only");
  Console.WriteLine("F3_MEMORY_BUSINESS_RESULT pass="+count+" fail=0 LIVE=NOT_RUN SAVE=NOT_RUN");
 }
}
