using System;
using System.Collections.Generic;
using TaleWorlds.LinQuick;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;

namespace TaleWorlds.CampaignSystem.Incidents;

public class Incident : MBObjectBase
{
	public delegate bool IncidentOptionConditionDelegate(TextObject text);

	public delegate void IncidentOptionConsequenceDelegate();

	public class IncidentTrigger
	{
		private HashSet<string> _triggers = new HashSet<string>();

		public IncidentTrigger(params string[] ids)
		{
			foreach (string item in ids)
			{
				_triggers.Add(item);
			}
		}

		public bool HasTrigger(string id)
		{
			return _triggers.Contains(id);
		}

		public bool HasTrigger(IncidentTrigger triggers)
		{
			foreach (string trigger in triggers._triggers)
			{
				if (_triggers.Contains(trigger))
				{
					return true;
				}
			}
			return false;
		}

		public void AddTrigger(string id)
		{
			_triggers.Add(id);
		}
	}

	private readonly struct IncidentOption
	{
		public readonly TextObject Text;

		public readonly IncidentOptionConditionDelegate Condition;

		public readonly IncidentOptionConsequenceDelegate Consequence;

		private readonly List<IncidentEffect> _effects;

		public IReadOnlyList<IncidentEffect> Effects => _effects;

		public IncidentOption(TextObject text, List<IncidentEffect> effects, IncidentOptionConditionDelegate condition, IncidentOptionConsequenceDelegate consequence)
		{
			Text = text;
			_effects = effects;
			Condition = condition;
			Consequence = consequence;
		}
	}

	private Func<TextObject, bool> _condition;

	private List<IncidentOption> _options;

	public TextObject Title { get; private set; }

	public TextObject Description { get; private set; }

	public IncidentTrigger Trigger { get; private set; }

	public string TypeId { get; private set; }

	public CampaignTime Cooldown { get; private set; }

	public int NumOfOptions => _options.Count;

	internal static void AutoGeneratedStaticCollectObjectsIncident(object o, List<object> collectedObjects)
	{
		((Incident)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		base.AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	public void Initialize(string title, string description, IncidentTrigger trigger, string type, CampaignTime cooldown, Func<TextObject, bool> condition)
	{
		Title = new TextObject(title);
		Description = new TextObject(description);
		Trigger = trigger;
		TypeId = type;
		Cooldown = cooldown;
		_condition = condition;
		_options = new List<IncidentOption>();
		base.IsReady = true;
	}

	public Incident(string id)
		: base(id)
	{
	}

	public void AddOption(string text, List<IncidentEffect> effects, IncidentOptionConditionDelegate condition = null, IncidentOptionConsequenceDelegate consequence = null)
	{
		IncidentOption item = new IncidentOption(new TextObject(text), effects, condition, consequence);
		_options.Add(item);
	}

	public bool CanIncidentBeInvoked()
	{
		if (_condition(Description))
		{
			foreach (IncidentOption option in _options)
			{
				if (option.Condition != null && !option.Condition(option.Text))
				{
					return false;
				}
				foreach (IncidentEffect effect in option.Effects)
				{
					if (!effect.Condition())
					{
						return false;
					}
				}
			}
			return true;
		}
		return false;
	}

	public TextObject GetOptionText(int index)
	{
		return _options[index].Text;
	}

	public IncidentHint GetOptionHint(int index)
	{
		IReadOnlyList<IncidentEffect> effects = _options[index].Effects;
		if (effects.Count == 0)
		{
			return new IncidentHint(new TextObject("{=lobJVVWT}Nothing happens"));
		}
		return new IncidentHint(null, IncidentHintType.Root, effects.SelectQ((IncidentEffect x) => x.GetHint()).ToArrayQ());
	}

	public List<TextObject> InvokeOption(int index)
	{
		IncidentOption incidentOption = _options[index];
		List<TextObject> list = new List<TextObject>();
		foreach (IncidentEffect effect in incidentOption.Effects)
		{
			list.AddRange(effect.Consequence());
		}
		incidentOption.Consequence?.Invoke();
		Campaign.Current.IncidentManager.IncidentResolved(this);
		return list;
	}
}
