<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyHistoryCaptureApplication.cs" Link="WorldDiplomacyHistoryCaptureApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyCampaignApplication.cs" Link="WorldDiplomacyCampaignApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyInitialPeaceApplication.cs" Link="WorldDiplomacyInitialPeaceApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyPrestigeApplication.cs" Link="WorldDiplomacyPrestigeApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyThreatSettlementApplication.cs" Link="WorldDiplomacyThreatSettlementApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/IWorldDiplomacyThreatSettlementPort.cs" Link="IWorldDiplomacyThreatSettlementPort.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyWarAdmissionApplication.cs" Link="WorldDiplomacyWarAdmissionApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyImmediateActionApplication.cs" Link="WorldDiplomacyImmediateActionApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/IWorldDiplomacyPublicationPort.cs" Link="IWorldDiplomacyPublicationPort.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyPublicationRoutingApplication.cs" Link="WorldDiplomacyPublicationRoutingApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyDocumentPublicationApplication.cs" Link="WorldDiplomacyDocumentPublicationApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/IWorldDiplomacyDocumentExecutionPort.cs" Link="IWorldDiplomacyDocumentExecutionPort.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyDocumentExecutionApplication.cs" Link="WorldDiplomacyDocumentExecutionApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyLlmDispatchApplication.cs" Link="WorldDiplomacyLlmDispatchApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyCompletionApplication.cs" Link="WorldDiplomacyCompletionApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyCompletionCallbacks.cs" Link="WorldDiplomacyCompletionCallbacks.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyLlmResult.cs" Link="WorldDiplomacyLlmResult.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/World/WorldDiplomacyJobRuntimeCoordinator.cs" Link="WorldDiplomacyJobRuntimeCoordinator.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/World/WorldDiplomacyRequestLeaseCoordinator.cs" Link="WorldDiplomacyRequestLeaseCoordinator.cs" />

    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyPresentationQueries.cs" Link="WorldDiplomacyPresentationQueries.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyTimelineApplication.cs" Link="WorldDiplomacyTimelineApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyProactiveDiscussionApplication.cs" Link="WorldDiplomacyProactiveDiscussionApplication.cs" />
    <Compile Include="../../WorldDiplomacyProactiveSpeakerEligibilityRules.cs" Link="WorldDiplomacyProactiveSpeakerEligibilityRules.cs" />
    <Compile Include="../../WorldDiplomacyProactiveDocumentSelectionRules.cs" Link="WorldDiplomacyProactiveDocumentSelectionRules.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyPlayerApplication.cs" Link="WorldDiplomacyPlayerApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyNotificationApplication.cs" Link="WorldDiplomacyNotificationApplication.cs" />
    <Compile Include="../../Refactor/Contracts/WorldDiplomacyPresentationContracts.cs" Link="WorldDiplomacyPresentationContracts.cs" />
    <Compile Include="../../Refactor/Contracts/WorldDiplomacyTimelineDocumentQueryContracts.cs" Link="WorldDiplomacyTimelineDocumentQueryContracts.cs" />

    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/IWorldDiplomacyDraftRepairWorld.cs" Link="IWorldDiplomacyDraftRepairWorld.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyDraftRepairApplication.cs" Link="WorldDiplomacyDraftRepairApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/IWorldDiplomacyPromptWorld.cs" Link="IWorldDiplomacyPromptWorld.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyPromptComposer.cs" Link="WorldDiplomacyPromptComposer.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyPropagationApplication.cs" Link="WorldDiplomacyPropagationApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyOfferApplication.cs" Link="WorldDiplomacyOfferApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyCourtResponseApplication.cs" Link="WorldDiplomacyCourtResponseApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyDocumentApplication.cs" Link="WorldDiplomacyDocumentApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyThreatApplication.cs" Link="WorldDiplomacyThreatApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyRoundApplication.cs" Link="WorldDiplomacyRoundApplication.cs" />
    <Compile Include="../../src/modules/AF.Module.Diplomacy/Application/WorldDiplomacyPolicyRoundApplication.cs" Link="WorldDiplomacyPolicyRoundApplication.cs" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\Refactor\Contracts\WorldDiplomacyRoundLifecycleContracts.cs" Link="WorldDiplomacyRoundLifecycleContracts.cs" />
    <Compile Include="..\..\Refactor\Domain\WorldDiplomacyIntentVocabulary.cs" Link="WorldDiplomacyIntentVocabulary.cs" />
    <Compile Include="..\..\Refactor\Domain\WorldDiplomacyRoundLifecycleRules.cs" Link="WorldDiplomacyRoundLifecycleRules.cs" />
    <Compile Include="..\..\Refactor\Domain\WorldDiplomacyEnvelopeJsonRules.cs" Link="WorldDiplomacyEnvelopeJsonRules.cs" />
    <Compile Include="..\..\Refactor\Domain\WorldDiplomacyTextRules.cs" Link="WorldDiplomacyTextRules.cs" />
    <Compile Include="..\..\Refactor\Domain\WorldDiplomacyReputationRules.cs" Link="WorldDiplomacyReputationRules.cs" />
    <Compile Include="..\..\Refactor\Domain\WorldDiplomacyOfferContractRules.cs" Link="WorldDiplomacyOfferContractRules.cs" />
    <Compile Include="..\..\Refactor\Domain\WorldDiplomacyPromptContractRules.cs" Link="WorldDiplomacyPromptContractRules.cs" />
    <Compile Include="..\..\Refactor\Domain\WorldDiplomacyStructureRules.cs" Link="Refactor\Domain\WorldDiplomacyStructureRules.cs" />
    <Compile Include="..\..\Refactor\Domain\WorldDiplomacyDocumentFactRules.cs" Link="Refactor\Domain\WorldDiplomacyDocumentFactRules.cs" />
    <Compile Include="..\..\Refactor\Domain\WorldDiplomacyCanonicalRenderRules.cs" Link="Refactor\Domain\WorldDiplomacyCanonicalRenderRules.cs" />
<Compile Include="..\..\Refactor\Domain\WorldDiplomacyCanonicalHistoryRules.cs" Link="Refactor\Domain\WorldDiplomacyCanonicalHistoryRules.cs" />
    <Compile Include="..\..\Refactor\Persistence\WorldDiplomacyActivityRecords.cs" Link="WorldDiplomacyActivityRecords.cs" />
    <Compile Include="..\..\Refactor\Persistence\WorldDiplomacyCanonicalHistoryRecords.cs" Link="WorldDiplomacyCanonicalHistoryRecords.cs" />
    <Compile Include="..\..\Refactor\Persistence\WorldDiplomacyDocumentRecords.cs" Link="WorldDiplomacyDocumentRecords.cs" />
    <Compile Include="..\..\Refactor\Persistence\WorldDiplomacyRoundRecords.cs" Link="WorldDiplomacyRoundRecords.cs" />
    <Compile Include="..\..\Refactor\Persistence\WorldDiplomacySummaryRecords.cs" Link="WorldDiplomacySummaryRecords.cs" />
    <Compile Include="..\..\Refactor\Persistence\WorldDiplomacyPropagationRecords.cs" Link="WorldDiplomacyPropagationRecords.cs" />
    <Compile Include="..\..\Refactor\Persistence\WorldDiplomacyStorageRecord.cs" Link="WorldDiplomacyStorageRecord.cs" />
    <Compile Include="..\..\Refactor\Persistence\WorldDiplomacyOfferCooldownRecord.cs" Link="WorldDiplomacyOfferCooldownRecord.cs" />
    <Compile Include="..\..\Refactor\Persistence\WorldDiplomacyOfferCooldownStorageNormalizer.cs" Link="WorldDiplomacyOfferCooldownStorageNormalizer.cs" />
<Compile Include="..\..\Refactor\Persistence\WorldDiplomacyThreatStorageMigration.cs" Link="WorldDiplomacyThreatStorageMigration.cs" />
<Compile Include="..\..\Refactor\Persistence\WorldDiplomacyStorageMigration.cs" Link="WorldDiplomacyStorageMigration.cs" />
    <Compile Include="..\..\src\modules\AF.Module.Diplomacy\Rules\WorldDiplomacyPolicyHistoryRules.cs" Link="WorldDiplomacyPolicyHistoryRules.cs" />
<Compile Include="..\..\Refactor\Domain\WorldDiplomacyGenerationValidationRules.cs" Link="WorldDiplomacyGenerationValidationRules.cs" />
    <Compile Include="..\..\src\modules\AF.Module.Diplomacy\Rules\WorldDiplomacyThreatStateRules.cs" Link="WorldDiplomacyThreatStateRules.cs" />
    <Compile Include="..\..\Refactor\Persistence\WorldDiplomacyThreatRecords.cs" Link="WorldDiplomacyThreatRecords.cs" />
    <Compile Include="..\..\Refactor\Persistence\WorldDiplomacyWarPeaceRecords.cs" Link="WorldDiplomacyWarPeaceRecords.cs" />
    <Compile Include="..\..\Refactor\Persistence\WorldDiplomacyWarSnapshotRecords.cs" Link="WorldDiplomacyWarSnapshotRecords.cs" />
    <Compile Include="..\..\Refactor\Persistence\WorldDiplomacyWorkRecords.cs" Link="WorldDiplomacyWorkRecords.cs" />
    <Compile Include="..\..\src\modules\AF.Module.Diplomacy\Rules\WorldDiplomacyResultSettlementRules.cs" Link="WorldDiplomacyResultSettlementRules.cs" />
    <Compile Include="..\..\src\modules\AF.Module.Diplomacy\Rules\WorldDiplomacyOfferCooldownRules.cs" Link="WorldDiplomacyOfferCooldownRules.cs" />
    <Compile Include="..\..\Refactor\Domain\WorldDiplomacyWarPressureRules.cs" Link="WorldDiplomacyWarPressureRules.cs" />
  </ItemGroup>
</Project>
