using System.Collections.Generic;
using NavalDLC.ViewModelCollection.Port;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.PrefabSystem;

namespace NavalDLC.GauntletUI.AutoGenerated;

public class GeneratedUIPrefabCreator : IGeneratedUIPrefabCreator
{
	public GeneratedPrefabInstantiationResult CreatePortScreen__NavalDLC_ViewModelCollection_Port_PortVM(UIContext context, Dictionary<string, object> data)
	{
		PortScreen__NavalDLC_ViewModelCollection_Port_PortVM portScreen__NavalDLC_ViewModelCollection_Port_PortVM = new PortScreen__NavalDLC_ViewModelCollection_Port_PortVM(context);
		portScreen__NavalDLC_ViewModelCollection_Port_PortVM.CreateWidgets();
		portScreen__NavalDLC_ViewModelCollection_Port_PortVM.SetIds();
		portScreen__NavalDLC_ViewModelCollection_Port_PortVM.SetAttributes();
		GeneratedPrefabInstantiationResult generatedPrefabInstantiationResult = new GeneratedPrefabInstantiationResult(portScreen__NavalDLC_ViewModelCollection_Port_PortVM);
		GeneratedGauntletMovie data2 = new GeneratedGauntletMovie("PortScreen", portScreen__NavalDLC_ViewModelCollection_Port_PortVM);
		object obj = data["DataSource"];
		portScreen__NavalDLC_ViewModelCollection_Port_PortVM.SetDataSource((PortVM)obj);
		generatedPrefabInstantiationResult.AddData("Movie", data2);
		return generatedPrefabInstantiationResult;
	}

	public void CollectGeneratedPrefabDefinitions(GeneratedPrefabContext generatedPrefabContext)
	{
		generatedPrefabContext.AddGeneratedPrefab("PortScreen", "NavalDLC.ViewModelCollection.Port.PortVM", CreatePortScreen__NavalDLC_ViewModelCollection_Port_PortVM);
	}
}
