using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.GameMenu.TroopSelection;
using TaleWorlds.Core.ViewModelCollection.Generic;
using TaleWorlds.Core.ViewModelCollection.ImageIdentifiers;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.GauntletUI.GamepadNavigation;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.GameMenu;
using TaleWorlds.TwoDimension;

namespace SandBox.GauntletUI.AutoGenerated1;

public class GameMenuTroopSelection__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_TroopSelection_GameMenuTroopSelectionVM_Dependency_1_ItemTemplate : ButtonWidget
{
	private ButtonWidget _widget;

	private GameMenuTroopSelectionItemButtonWidget _widget_0;

	private NavigationAutoScrollWidget _widget_0_0;

	private NavigationScopeTargeter _widget_0_1;

	private ImageIdentifierWidget _widget_0_2;

	private DefaultLayerSpriteChangerBrushWidget _widget_0_2_0;

	private DefaultLayerSpriteChangerBrushWidget _widget_0_2_1;

	private TextWidget _widget_0_3;

	private Widget _widget_0_4;

	private Widget _widget_0_5;

	private FillBarVerticalClipTierColorsWidget _widget_0_5_0;

	private Widget _widget_0_5_0_0;

	private NavigationAutoScrollWidget _widget_0_6;

	private NavigationAutoScrollWidget _widget_0_7;

	private ListPanel _widget_0_8;

	private ButtonWidget _widget_0_8_0;

	private ListPanel _widget_0_8_1;

	private TextWidget _widget_0_8_1_0;

	private TextWidget _widget_0_8_1_1;

	private TextWidget _widget_0_8_1_2;

	private ButtonWidget _widget_0_8_2;

	private Widget _widget_0_9;

	private TroopSelectionItemVM _datasource_Root;

	private CharacterImageIdentifierVM _datasource_Root_Visual;

	private StringItemWithHintVM _datasource_Root_TierIconData;

	private StringItemWithHintVM _datasource_Root_TypeIconData;

	public GameMenuTroopSelection__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_TroopSelection_GameMenuTroopSelectionVM_Dependency_1_ItemTemplate(UIContext context)
		: base(context)
	{
	}

	public void CreateWidgets()
	{
		_widget = this;
		_widget_0 = new GameMenuTroopSelectionItemButtonWidget(base.Context);
		_widget.AddChild(_widget_0);
		_widget_0_0 = new NavigationAutoScrollWidget(base.Context);
		_widget_0.AddChild(_widget_0_0);
		_widget_0_1 = new NavigationScopeTargeter(base.Context);
		_widget_0.AddChild(_widget_0_1);
		_widget_0_2 = new ImageIdentifierWidget(base.Context);
		_widget_0.AddChild(_widget_0_2);
		_widget_0_2_0 = new DefaultLayerSpriteChangerBrushWidget(base.Context);
		_widget_0_2.AddChild(_widget_0_2_0);
		_widget_0_2_1 = new DefaultLayerSpriteChangerBrushWidget(base.Context);
		_widget_0_2.AddChild(_widget_0_2_1);
		_widget_0_3 = new TextWidget(base.Context);
		_widget_0.AddChild(_widget_0_3);
		_widget_0_4 = new Widget(base.Context);
		_widget_0.AddChild(_widget_0_4);
		_widget_0_5 = new Widget(base.Context);
		_widget_0.AddChild(_widget_0_5);
		_widget_0_5_0 = new FillBarVerticalClipTierColorsWidget(base.Context);
		_widget_0_5.AddChild(_widget_0_5_0);
		_widget_0_5_0_0 = new Widget(base.Context);
		_widget_0_5_0.AddChild(_widget_0_5_0_0);
		_widget_0_6 = new NavigationAutoScrollWidget(base.Context);
		_widget_0.AddChild(_widget_0_6);
		_widget_0_7 = new NavigationAutoScrollWidget(base.Context);
		_widget_0.AddChild(_widget_0_7);
		_widget_0_8 = new ListPanel(base.Context);
		_widget_0.AddChild(_widget_0_8);
		_widget_0_8_0 = new ButtonWidget(base.Context);
		_widget_0_8.AddChild(_widget_0_8_0);
		_widget_0_8_1 = new ListPanel(base.Context);
		_widget_0_8.AddChild(_widget_0_8_1);
		_widget_0_8_1_0 = new TextWidget(base.Context);
		_widget_0_8_1.AddChild(_widget_0_8_1_0);
		_widget_0_8_1_1 = new TextWidget(base.Context);
		_widget_0_8_1.AddChild(_widget_0_8_1_1);
		_widget_0_8_1_2 = new TextWidget(base.Context);
		_widget_0_8_1.AddChild(_widget_0_8_1_2);
		_widget_0_8_2 = new ButtonWidget(base.Context);
		_widget_0_8.AddChild(_widget_0_8_2);
		_widget_0_9 = new Widget(base.Context);
		_widget_0.AddChild(_widget_0_9);
	}

	public void SetIds()
	{
		_widget_0_4.Id = "CheckmarkVisualWidget";
		_widget_0_5.Id = "HeroHealthParent";
		_widget_0_5_0_0.Id = "FillWidget";
		_widget_0_8.Id = "AddRemoveControls";
		_widget_0_8_0.Id = "AddButtonWidget";
		_widget_0_8_1.Id = "AddRemoveControlsChild";
		_widget_0_8_1_0.Id = "CurrentAmountTextWidget";
		_widget_0_8_1_1.Id = "SeperatorTextWidget";
		_widget_0_8_1_2.Id = "MaxAmountTextWidget";
		_widget_0_8_2.Id = "RemoveButtonWidget";
	}

	public void SetAttributes()
	{
		base.WidthSizePolicy = SizePolicy.Fixed;
		base.HeightSizePolicy = SizePolicy.Fixed;
		base.SuggestedWidth = 220f;
		base.SuggestedHeight = 140f;
		base.HorizontalAlignment = HorizontalAlignment.Center;
		base.HoveredCursorState = "RightClickLink";
		_widget_0.UpdateChildrenStates = true;
		_widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0.Brush = base.Context.GetBrush("TroopSelection.Card");
		_widget_0.AddButtonWidget = _widget_0_8_0;
		_widget_0.HeroHealthParent = _widget_0_5;
		_widget_0.RemoveButtonWidget = _widget_0_8_2;
		_widget_0.CheckmarkVisualWidget = _widget_0_4;
		_widget_0.AddRemoveControls = _widget_0_8;
		_widget_0.HoveredCursorState = "RightClickLink";
		_widget_0_0.TrackedWidget = _widget_0;
		_widget_0_1.ScopeID = "ManageTroopsItemScope";
		_widget_0_1.ScopeParent = _widget_0;
		_widget_0_1.ScopeMovements = GamepadNavigationTypes.Vertical;
		_widget_0_2.UpdateChildrenStates = true;
		_widget_0_2.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_2.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_2.SuggestedHeight = 67f;
		_widget_0_2.SuggestedWidth = 100f;
		_widget_0_2.MarginLeft = 20f;
		_widget_0_2.MarginTop = 10f;
		_widget_0_2.DoNotAcceptEvents = true;
		_widget_0_2_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_2_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_2_0.SuggestedWidth = 20f;
		_widget_0_2_0.SuggestedHeight = 20f;
		_widget_0_2_0.HorizontalAlignment = HorizontalAlignment.Right;
		_widget_0_2_0.VerticalAlignment = VerticalAlignment.Top;
		_widget_0_2_0.PositionXOffset = 0f;
		_widget_0_2_0.PositionYOffset = 2f;
		_widget_0_2_0.Brush = base.Context.GetBrush("GameMenu.ManageHideoutTroops.TierTypeSelectionBrush");
		_widget_0_2_0.SpriteBrush = base.Context.GetBrush("GameMenu.ManageHideoutTroops.TierIconsBrush");
		_widget_0_2_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_2_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_2_1.SuggestedWidth = 20f;
		_widget_0_2_1.SuggestedHeight = 20f;
		_widget_0_2_1.HorizontalAlignment = HorizontalAlignment.Left;
		_widget_0_2_1.VerticalAlignment = VerticalAlignment.Top;
		_widget_0_2_1.PositionXOffset = 0f;
		_widget_0_2_1.PositionYOffset = 2f;
		_widget_0_2_1.Brush = base.Context.GetBrush("GameMenu.ManageHideoutTroops.TierTypeSelectionBrush");
		_widget_0_2_1.SpriteBrush = base.Context.GetBrush("GameMenu.ManageHideoutTroops.TypeIconsBrush");
		_widget_0_3.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_3.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_3.SuggestedWidth = 135f;
		_widget_0_3.SuggestedHeight = 55f;
		_widget_0_3.Brush = base.Context.GetBrush("GameMenu.ManageHideoutTroops.NameText");
		_widget_0_3.MarginLeft = 20f;
		_widget_0_3.MarginTop = 80f;
		_widget_0_3.DoNotAcceptEvents = true;
		_widget_0_4.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_4.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_4.SuggestedWidth = 47f;
		_widget_0_4.SuggestedHeight = 38f;
		_widget_0_4.HorizontalAlignment = HorizontalAlignment.Right;
		_widget_0_4.MarginTop = 20f;
		_widget_0_4.MarginRight = 20f;
		_widget_0_4.Sprite = base.Context.SpriteData.GetSprite("SPGeneral\\GameMenu\\companion_selected_check");
		_widget_0_4.Color = new Color(0.9568628f, 0.882353f, 0.7686275f);
		_widget_0_4.DoNotAcceptEvents = true;
		_widget_0_5.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_5.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_5.SuggestedHeight = 65f;
		_widget_0_5.SuggestedWidth = 15f;
		_widget_0_5.MarginTop = 15f;
		_widget_0_5.MarginLeft = 15f;
		_widget_0_5.IsEnabled = false;
		_widget_0_5_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_5_0.SuggestedWidth = 7f;
		_widget_0_5_0.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0_5_0.MaxAmount = 100;
		_widget_0_5_0.FillWidget = _widget_0_5_0_0;
		_widget_0_5_0.IsDirectionUpward = true;
		_widget_0_5_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
		_widget_0_5_0.MaxedColor = "#00FF10FF";
		_widget_0_5_0.HighColor = "#63C90DFF";
		_widget_0_5_0.MediumColor = "#F76F0DFF";
		_widget_0_5_0.LowColor = "#DE0000FF";
		_widget_0_5_0.MarginTop = 4f;
		_widget_0_5_0.MarginBottom = 4f;
		_widget_0_5_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0_5_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0_5_0_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_5_0_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
		_widget_0_6.TrackedWidget = _widget_0_8_0;
		_widget_0_6.AutoScrollTopOffset = 100;
		_widget_0_6.AutoScrollBottomOffset = 100;
		_widget_0_7.TrackedWidget = _widget_0_8_2;
		_widget_0_7.AutoScrollTopOffset = 100;
		_widget_0_7.AutoScrollBottomOffset = 100;
		_widget_0_8.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_0_8.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0_8.HorizontalAlignment = HorizontalAlignment.Right;
		_widget_0_8.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_8.StackLayout.LayoutMethod = LayoutMethod.VerticalTopToBottom;
		_widget_0_8_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_8_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_8_0.SuggestedWidth = 35f;
		_widget_0_8_0.SuggestedHeight = 35f;
		_widget_0_8_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0_8_0.Brush = base.Context.GetBrush("GameMenu.ManageHideoutTroops.PlusButton");
		_widget_0_8_0.GamepadNavigationIndex = 0;
		_widget_0_8_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_8_1.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0_8_1.SuggestedWidth = 80f;
		_widget_0_8_1.MarginRight = 15f;
		_widget_0_8_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0_8_1_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_8_1_0.SuggestedHeight = 45f;
		_widget_0_8_1_0.Brush = base.Context.GetBrush("GameMenu.ManageHideoutTroops.CountText");
		_widget_0_8_1_0.DoNotAcceptEvents = true;
		_widget_0_8_1_1.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0_8_1_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_8_1_1.SuggestedHeight = 45f;
		_widget_0_8_1_1.Brush = base.Context.GetBrush("GameMenu.ManageHideoutTroops.CountText");
		_widget_0_8_1_1.Text = "\\";
		_widget_0_8_1_1.Brush.TextHorizontalAlignment = TextHorizontalAlignment.Center;
		_widget_0_8_1_1.DoNotAcceptEvents = true;
		_widget_0_8_1_2.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_8_1_2.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_8_1_2.SuggestedWidth = 30f;
		_widget_0_8_1_2.SuggestedHeight = 45f;
		_widget_0_8_1_2.Brush = base.Context.GetBrush("GameMenu.ManageHideoutTroops.TotalCountText");
		_widget_0_8_1_2.Brush.FontSize = 20;
		_widget_0_8_1_2.DoNotAcceptEvents = true;
		_widget_0_8_2.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_8_2.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_8_2.SuggestedWidth = 35f;
		_widget_0_8_2.SuggestedHeight = 35f;
		_widget_0_8_2.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0_8_2.Brush = base.Context.GetBrush("GameMenu.ManageHideoutTroops.MinusButton");
		_widget_0_8_2.GamepadNavigationIndex = 1;
		_widget_0_9.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_9.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_9.SuggestedWidth = 30f;
		_widget_0_9.SuggestedHeight = 30f;
		_widget_0_9.HorizontalAlignment = HorizontalAlignment.Right;
		_widget_0_9.VerticalAlignment = VerticalAlignment.Bottom;
		_widget_0_9.PositionXOffset = -10f;
		_widget_0_9.PositionYOffset = -10f;
		_widget_0_9.Sprite = base.Context.SpriteData.GetSprite("StdAssets\\lock_closed");
		_widget_0_9.ColorFactor = 1.3f;
		_widget_0_9.DoNotAcceptEvents = true;
	}

	public void DestroyDataSource()
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.EventFire -= EventListenerOf_widget;
			_widget_0.EventFire -= EventListenerOf_widget_0;
			_widget_0.PropertyChanged -= PropertyChangedListenerOf_widget_0;
			_widget_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0;
			_widget_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0;
			_widget_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0;
			_widget_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0;
			_widget_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0;
			_widget_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0;
			_widget_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0;
			_widget_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0;
			_widget_0_3.PropertyChanged -= PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_3;
			_widget_0_3.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_3;
			_widget_0_5_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_8_1_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_2.PropertyChanged -= PropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_9.PropertyChanged -= PropertyChangedListenerOf_widget_0_9;
			_widget_0_9.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_9;
			_widget_0_9.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_9;
			_widget_0_9.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_9;
			_widget_0_9.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_9;
			_widget_0_9.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_9;
			_widget_0_9.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_9;
			_widget_0_9.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_9;
			_widget_0_9.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_9;
			if (_datasource_Root_Visual != null)
			{
				_datasource_Root_Visual.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
				_widget_0_2.PropertyChanged -= PropertyChangedListenerOf_widget_0_2;
				_widget_0_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2;
				_widget_0_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2;
				_widget_0_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2;
				_widget_0_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2;
				_datasource_Root_Visual = null;
			}
			if (_datasource_Root_TierIconData != null)
			{
				_datasource_Root_TierIconData.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TierIconData;
				_widget_0_2_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2_0;
				_datasource_Root_TierIconData = null;
			}
			if (_datasource_Root_TypeIconData != null)
			{
				_datasource_Root_TypeIconData.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TypeIconData;
				_widget_0_2_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2_1;
				_datasource_Root_TypeIconData = null;
			}
			_datasource_Root = null;
		}
	}

	public void SetDataSource(TroopSelectionItemVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void EventListenerOf_widget(Widget widget, string commandName, object[] args)
	{
		if (commandName == "AlternateClick")
		{
			_datasource_Root.ExecuteLink();
		}
	}

	private void EventListenerOf_widget_0(Widget widget, string commandName, object[] args)
	{
		if (commandName == "Add")
		{
			_datasource_Root.ExecuteAdd();
		}
		if (commandName == "Remove")
		{
			_datasource_Root.ExecuteRemove();
		}
		if (commandName == "AlternateClick")
		{
			_datasource_Root.ExecuteLink();
		}
	}

	private void PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0(string propertyName)
	{
		switch (propertyName)
		{
		case "IsSelected":
			_datasource_Root.IsSelected = _widget_0.IsSelected;
			break;
		case "IsTroopHero":
			_datasource_Root.IsTroopHero = _widget_0.IsTroopHero;
			break;
		case "MaxAmount":
			_datasource_Root.MaxAmount = _widget_0.MaxAmount;
			break;
		case "CurrentAmount":
			_datasource_Root.CurrentAmount = _widget_0.CurrentAmount;
			break;
		case "IsRosterFull":
			_datasource_Root.IsRosterFull = _widget_0.IsRosterFull;
			break;
		case "IsLocked":
			_datasource_Root.IsLocked = _widget_0.IsLocked;
			break;
		}
	}

	private void PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_3(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.Name = _widget_0_3.Text;
		}
	}

	private void PropertyChangedListenerOf_widget_0_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_5_0(string propertyName)
	{
		if (propertyName == "InitialAmount")
		{
			_datasource_Root.HeroHealthPercent = _widget_0_5_0.InitialAmount;
		}
	}

	private void PropertyChangedListenerOf_widget_0_8_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_8_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_8_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_8_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_8_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_8_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_8_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_8_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_8_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_8_1_0(string propertyName)
	{
		if (propertyName == "IntText")
		{
			_datasource_Root.CurrentAmount = _widget_0_8_1_0.IntText;
		}
	}

	private void PropertyChangedListenerOf_widget_0_8_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_8_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_8_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_8_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_8_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_8_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_8_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_8_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_8_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_8_1_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_8_1_2(string propertyName)
	{
		if (propertyName == "IntText")
		{
			_datasource_Root.MaxAmount = _widget_0_8_1_2.IntText;
		}
	}

	private void PropertyChangedListenerOf_widget_0_9(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_9(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_9(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_9(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_9(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_9(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_9(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_9(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_9(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_9(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_9(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_9(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_9(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_9(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_9(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_9(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_9(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_9(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_9(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsLocked = _widget_0_9.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_2(string propertyName)
	{
		switch (propertyName)
		{
		case "AdditionalArgs":
			_datasource_Root_Visual.AdditionalArgs = _widget_0_2.AdditionalArgs;
			break;
		case "ImageId":
			_datasource_Root_Visual.Id = _widget_0_2.ImageId;
			break;
		case "TextureProviderName":
			_datasource_Root_Visual.TextureProviderName = _widget_0_2.TextureProviderName;
			break;
		}
	}

	private void PropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_2_0(string propertyName)
	{
		if (propertyName == "SpriteBrushLayerName")
		{
			_datasource_Root_TierIconData.Text = _widget_0_2_0.SpriteBrushLayerName;
		}
	}

	private void PropertyChangedListenerOf_widget_0_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_2_1(string propertyName)
	{
		if (propertyName == "SpriteBrushLayerName")
		{
			_datasource_Root_TypeIconData.Text = _widget_0_2_1.SpriteBrushLayerName;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		switch (propertyName)
		{
		case "Visual":
			RefreshDataSource_datasource_Root_Visual(_datasource_Root.Visual);
			break;
		case "TierIconData":
			RefreshDataSource_datasource_Root_TierIconData(_datasource_Root.TierIconData);
			break;
		case "TypeIconData":
			RefreshDataSource_datasource_Root_TypeIconData(_datasource_Root.TypeIconData);
			break;
		case "IsSelected":
			_widget_0.IsSelected = _datasource_Root.IsSelected;
			break;
		case "IsTroopHero":
			_widget_0.IsTroopHero = _datasource_Root.IsTroopHero;
			break;
		case "MaxAmount":
			_widget_0.MaxAmount = _datasource_Root.MaxAmount;
			_widget_0_8_1_2.IntText = _datasource_Root.MaxAmount;
			break;
		case "CurrentAmount":
			_widget_0.CurrentAmount = _datasource_Root.CurrentAmount;
			_widget_0_8_1_0.IntText = _datasource_Root.CurrentAmount;
			break;
		case "IsRosterFull":
			_widget_0.IsRosterFull = _datasource_Root.IsRosterFull;
			break;
		case "IsLocked":
			_widget_0.IsLocked = _datasource_Root.IsLocked;
			_widget_0_9.IsVisible = _datasource_Root.IsLocked;
			break;
		case "Name":
			_widget_0_3.Text = _datasource_Root.Name;
			break;
		case "HeroHealthPercent":
			_widget_0_5_0.InitialAmount = _datasource_Root.HeroHealthPercent;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_Visual(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_Visual(string propertyName)
	{
		switch (propertyName)
		{
		case "AdditionalArgs":
			_widget_0_2.AdditionalArgs = _datasource_Root_Visual.AdditionalArgs;
			break;
		case "Id":
			_widget_0_2.ImageId = _datasource_Root_Visual.Id;
			break;
		case "TextureProviderName":
			_widget_0_2.TextureProviderName = _datasource_Root_Visual.TextureProviderName;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_TierIconData(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TierIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TierIconData(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TierIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TierIconData(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TierIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TierIconData(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TierIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TierIconData(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TierIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TierIconData(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TierIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TierIconData(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TierIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TierIconData(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TierIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TierIconData(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TierIconData(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_TierIconData(string propertyName)
	{
		if (propertyName == "Text")
		{
			_widget_0_2_0.SpriteBrushLayerName = _datasource_Root_TierIconData.Text;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_TypeIconData(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TypeIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TypeIconData(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TypeIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TypeIconData(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TypeIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TypeIconData(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TypeIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TypeIconData(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TypeIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TypeIconData(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TypeIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TypeIconData(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TypeIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TypeIconData(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TypeIconData(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TypeIconData(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_TypeIconData(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_TypeIconData(string propertyName)
	{
		if (propertyName == "Text")
		{
			_widget_0_2_1.SpriteBrushLayerName = _datasource_Root_TypeIconData.Text;
		}
	}

	private void RefreshDataSource_datasource_Root(TroopSelectionItemVM newDataSource)
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.EventFire -= EventListenerOf_widget;
			_widget_0.EventFire -= EventListenerOf_widget_0;
			_widget_0.PropertyChanged -= PropertyChangedListenerOf_widget_0;
			_widget_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0;
			_widget_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0;
			_widget_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0;
			_widget_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0;
			_widget_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0;
			_widget_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0;
			_widget_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0;
			_widget_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0;
			_widget_0_3.PropertyChanged -= PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_3;
			_widget_0_3.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_3;
			_widget_0_5_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_8_1_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_2.PropertyChanged -= PropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_9.PropertyChanged -= PropertyChangedListenerOf_widget_0_9;
			_widget_0_9.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_9;
			_widget_0_9.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_9;
			_widget_0_9.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_9;
			_widget_0_9.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_9;
			_widget_0_9.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_9;
			_widget_0_9.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_9;
			_widget_0_9.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_9;
			_widget_0_9.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_9;
			if (_datasource_Root_Visual != null)
			{
				_datasource_Root_Visual.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
				_widget_0_2.PropertyChanged -= PropertyChangedListenerOf_widget_0_2;
				_widget_0_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2;
				_widget_0_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2;
				_widget_0_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2;
				_widget_0_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2;
				_datasource_Root_Visual = null;
			}
			if (_datasource_Root_TierIconData != null)
			{
				_datasource_Root_TierIconData.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TierIconData;
				_widget_0_2_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2_0;
				_datasource_Root_TierIconData = null;
			}
			if (_datasource_Root_TypeIconData != null)
			{
				_datasource_Root_TypeIconData.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TypeIconData;
				_widget_0_2_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2_1;
				_datasource_Root_TypeIconData = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.EventFire += EventListenerOf_widget;
			_widget_0.IsSelected = _datasource_Root.IsSelected;
			_widget_0.IsTroopHero = _datasource_Root.IsTroopHero;
			_widget_0.MaxAmount = _datasource_Root.MaxAmount;
			_widget_0.CurrentAmount = _datasource_Root.CurrentAmount;
			_widget_0.IsRosterFull = _datasource_Root.IsRosterFull;
			_widget_0.IsLocked = _datasource_Root.IsLocked;
			_widget_0.EventFire += EventListenerOf_widget_0;
			_widget_0.PropertyChanged += PropertyChangedListenerOf_widget_0;
			_widget_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0;
			_widget_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0;
			_widget_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0;
			_widget_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0;
			_widget_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0;
			_widget_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0;
			_widget_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0;
			_widget_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0;
			_widget_0_3.Text = _datasource_Root.Name;
			_widget_0_3.PropertyChanged += PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_3;
			_widget_0_3.intPropertyChanged += intPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_3;
			_widget_0_5_0.InitialAmount = _datasource_Root.HeroHealthPercent;
			_widget_0_5_0.PropertyChanged += PropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_5_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_5_0;
			_widget_0_8_1_0.IntText = _datasource_Root.CurrentAmount;
			_widget_0_8_1_0.PropertyChanged += PropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_8_1_0;
			_widget_0_8_1_2.IntText = _datasource_Root.MaxAmount;
			_widget_0_8_1_2.PropertyChanged += PropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.intPropertyChanged += intPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_8_1_2.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_8_1_2;
			_widget_0_9.IsVisible = _datasource_Root.IsLocked;
			_widget_0_9.PropertyChanged += PropertyChangedListenerOf_widget_0_9;
			_widget_0_9.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_9;
			_widget_0_9.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_9;
			_widget_0_9.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_9;
			_widget_0_9.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_9;
			_widget_0_9.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_9;
			_widget_0_9.intPropertyChanged += intPropertyChangedListenerOf_widget_0_9;
			_widget_0_9.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_9;
			_widget_0_9.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_9;
			_datasource_Root_Visual = _datasource_Root.Visual;
			if (_datasource_Root_Visual != null)
			{
				_datasource_Root_Visual.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
				_widget_0_2.AdditionalArgs = _datasource_Root_Visual.AdditionalArgs;
				_widget_0_2.ImageId = _datasource_Root_Visual.Id;
				_widget_0_2.TextureProviderName = _datasource_Root_Visual.TextureProviderName;
				_widget_0_2.PropertyChanged += PropertyChangedListenerOf_widget_0_2;
				_widget_0_2.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_2;
				_widget_0_2.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_2;
				_widget_0_2.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_2;
				_widget_0_2.intPropertyChanged += intPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_2;
			}
			_datasource_Root_TierIconData = _datasource_Root.TierIconData;
			if (_datasource_Root_TierIconData != null)
			{
				_datasource_Root_TierIconData.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TierIconData;
				_datasource_Root_TierIconData.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TierIconData;
				_widget_0_2_0.SpriteBrushLayerName = _datasource_Root_TierIconData.Text;
				_widget_0_2_0.PropertyChanged += PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_2_0;
			}
			_datasource_Root_TypeIconData = _datasource_Root.TypeIconData;
			if (_datasource_Root_TypeIconData != null)
			{
				_datasource_Root_TypeIconData.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TypeIconData;
				_datasource_Root_TypeIconData.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TypeIconData;
				_widget_0_2_1.SpriteBrushLayerName = _datasource_Root_TypeIconData.Text;
				_widget_0_2_1.PropertyChanged += PropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.intPropertyChanged += intPropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_2_1;
				_widget_0_2_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_2_1;
			}
		}
	}

	private void RefreshDataSource_datasource_Root_Visual(CharacterImageIdentifierVM newDataSource)
	{
		if (_datasource_Root_Visual != null)
		{
			_datasource_Root_Visual.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
			_widget_0_2.PropertyChanged -= PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2;
			_widget_0_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2;
			_datasource_Root_Visual = null;
		}
		_datasource_Root_Visual = newDataSource;
		_datasource_Root_Visual = _datasource_Root.Visual;
		if (_datasource_Root_Visual != null)
		{
			_datasource_Root_Visual.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
			_widget_0_2.AdditionalArgs = _datasource_Root_Visual.AdditionalArgs;
			_widget_0_2.ImageId = _datasource_Root_Visual.Id;
			_widget_0_2.TextureProviderName = _datasource_Root_Visual.TextureProviderName;
			_widget_0_2.PropertyChanged += PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_2;
			_widget_0_2.intPropertyChanged += intPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_2;
		}
	}

	private void RefreshDataSource_datasource_Root_TierIconData(StringItemWithHintVM newDataSource)
	{
		if (_datasource_Root_TierIconData != null)
		{
			_datasource_Root_TierIconData.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TierIconData;
			_widget_0_2_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2_0;
			_datasource_Root_TierIconData = null;
		}
		_datasource_Root_TierIconData = newDataSource;
		_datasource_Root_TierIconData = _datasource_Root.TierIconData;
		if (_datasource_Root_TierIconData != null)
		{
			_datasource_Root_TierIconData.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TierIconData;
			_datasource_Root_TierIconData.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TierIconData;
			_widget_0_2_0.SpriteBrushLayerName = _datasource_Root_TierIconData.Text;
			_widget_0_2_0.PropertyChanged += PropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_2_0;
		}
	}

	private void RefreshDataSource_datasource_Root_TypeIconData(StringItemWithHintVM newDataSource)
	{
		if (_datasource_Root_TypeIconData != null)
		{
			_datasource_Root_TypeIconData.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TypeIconData;
			_widget_0_2_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2_1;
			_datasource_Root_TypeIconData = null;
		}
		_datasource_Root_TypeIconData = newDataSource;
		_datasource_Root_TypeIconData = _datasource_Root.TypeIconData;
		if (_datasource_Root_TypeIconData != null)
		{
			_datasource_Root_TypeIconData.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TypeIconData;
			_datasource_Root_TypeIconData.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TypeIconData;
			_widget_0_2_1.SpriteBrushLayerName = _datasource_Root_TypeIconData.Text;
			_widget_0_2_1.PropertyChanged += PropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.intPropertyChanged += intPropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_2_1;
			_widget_0_2_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_2_1;
		}
	}
}
