using System.Collections.Generic;
using TaleWorlds.Localization;

namespace TaleWorlds.Core;

public class CharacterAttribute : PropertyObject
{
	public TextObject Abbreviation { get; private set; }

	public CharacterAttribute(string stringId)
		: base(stringId)
	{
	}

	public void Initialize(TextObject name, TextObject description, TextObject abbreviation)
	{
		Initialize(name, description);
		Abbreviation = abbreviation;
		AfterInitialized();
	}

	internal static void AutoGeneratedStaticCollectObjectsCharacterAttribute(object o, List<object> collectedObjects)
	{
		((CharacterAttribute)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		base.AutoGeneratedInstanceCollectObjects(collectedObjects);
	}
}
