using System.Collections.Generic;
using System.Xml;
using TaleWorlds.ObjectSystem;

namespace TaleWorlds.Core;

public abstract class ItemComponent : MBObjectBase
{
	public ItemObject Item { get; set; }

	public ItemModifierGroup ItemModifierGroup { get; protected set; }

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		base.AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	public override void Deserialize(MBObjectManager objectManager, XmlNode node)
	{
		Initialize();
		string text = node.Attributes["modifier_group"]?.Value;
		if (text != null)
		{
			ItemModifierGroup = Game.Current.ObjectManager.GetObject<ItemModifierGroup>(text);
		}
	}

	public abstract ItemComponent GetCopy();
}
