using System.Collections.Generic;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;

namespace TaleWorlds.Core;

public class PropertyObject : MBObjectBase
{
	private TextObject _name;

	private TextObject _description;

	public TextObject Name => _name;

	public TextObject Description => _description;

	internal static void AutoGeneratedStaticCollectObjectsPropertyObject(object o, List<object> collectedObjects)
	{
		((PropertyObject)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		base.AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	public override TextObject GetName()
	{
		return Name;
	}

	public PropertyObject(string stringId)
		: base(stringId)
	{
	}

	public void Initialize(TextObject name, TextObject description)
	{
		base.Initialize();
		_name = name;
		_description = description;
	}
}
