using System;
using System.Collections.Generic;
using System.Xml;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;

namespace TaleWorlds.Core;

public class ShipUpgradePiece : MBObjectBase
{
	private MBList<ShipSlot> _targetSlots;

	public TextObject Name { get; private set; }

	public TextObject Description { get; private set; }

	public MBReadOnlyList<ShipSlot> TargetSlots => _targetSlots;

	public int LightValue { get; private set; }

	public int MediumValue { get; private set; }

	public int HeavyValue { get; private set; }

	public string SlotPrefabChildTagId { get; private set; }

	public bool NotMerchandise { get; private set; }

	public float CombatFactor { get; private set; }

	public float CrewCapacityBonusMultiplier { get; private set; }

	public int RequiredPortLevel { get; private set; }

	public float ShipWeightBonusMultiplier { get; private set; }

	public BasicCultureObject RequiredCulture1 { get; private set; }

	public float DecreaseForwardDragMultiplier { get; private set; }

	public float CampaignSpeedBonusMultiplier { get; private set; }

	public float MaxHitPointsBonusMultiplier { get; private set; }

	public float MaxSailHitPointsBonusMultiplier { get; private set; }

	public int SeaWorthinessBonus { get; private set; }

	public float CrewShieldHitPointsBonusMultiplier { get; private set; }

	public float InventoryCapacityBonusMultiplier { get; private set; }

	public int AdditionalAmmoBonus { get; private set; }

	public float MaxOarPowerBonusMultiplier { get; private set; }

	public float MaxOarForceBonusMultiplier { get; private set; }

	public float SailForceBonusMultiplier { get; private set; }

	public float CrewMeleeDamageBonusMultiplier { get; private set; }

	public int ArcherQuiverBonus { get; private set; }

	public int ThrowingWeaponStackBonus { get; private set; }

	public float SailRotationSpeedBonusMultiplier { get; private set; }

	public float FurlUnfurlSpeedBonusMultiplier { get; private set; }

	public float RudderSurfaceAreaBonusMultiplier { get; private set; }

	public float MaxRudderForceBonusMultiplier { get; private set; }

	public BasicCultureObject RequiredCulture2 { get; private set; }

	public SiegeEngineType SiegeEngine { get; private set; }

	internal static void AutoGeneratedStaticCollectObjectsShipUpgradePiece(object o, List<object> collectedObjects)
	{
		((ShipUpgradePiece)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		base.AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	public override void Deserialize(MBObjectManager objectManager, XmlNode node)
	{
		base.Deserialize(objectManager, node);
		Name = new TextObject(node.Attributes["name"].Value);
		Description = new TextObject(node.Attributes["description"].Value);
		SlotPrefabChildTagId = ((node.Attributes["slot_prefab_child_id"] != null) ? node.Attributes["slot_prefab_child_id"].Value : base.StringId);
		NotMerchandise = node.Attributes["not_merchandise"] != null && bool.Parse(node.Attributes["not_merchandise"].Value);
		LightValue = Convert.ToInt32(node.Attributes["light_value"].Value);
		MediumValue = Convert.ToInt32(node.Attributes["medium_value"].Value);
		HeavyValue = Convert.ToInt32(node.Attributes["heavy_value"].Value);
		RequiredPortLevel = ((node.Attributes["required_port_level"] != null) ? Convert.ToInt32(node.Attributes["required_port_level"].Value) : 0);
		RequiredCulture1 = (BasicCultureObject)objectManager.ReadObjectReferenceFromXml("required_culture_1_id", typeof(BasicCultureObject), node);
		RequiredCulture2 = (BasicCultureObject)objectManager.ReadObjectReferenceFromXml("required_culture_2_id", typeof(BasicCultureObject), node);
		CrewCapacityBonusMultiplier = ((node.Attributes["crew_capacity_bonus_multiplier"] != null) ? float.Parse(node.Attributes["crew_capacity_bonus_multiplier"].Value) : 0f);
		ShipWeightBonusMultiplier = ((node.Attributes["ship_weight_bonus_multiplier"] != null) ? float.Parse(node.Attributes["ship_weight_bonus_multiplier"].Value) : 0f);
		CombatFactor = ((node.Attributes["combat_factor_bonus_multiplier"] != null) ? float.Parse(node.Attributes["combat_factor_bonus_multiplier"].Value) : 0f);
		DecreaseForwardDragMultiplier = ((node.Attributes["decrease_forward_drag_multiplier"] != null) ? float.Parse(node.Attributes["decrease_forward_drag_multiplier"].Value) : 0f);
		CampaignSpeedBonusMultiplier = ((node.Attributes["campaign_speed_bonus_multiplier"] != null) ? float.Parse(node.Attributes["campaign_speed_bonus_multiplier"].Value) : 0f);
		MaxHitPointsBonusMultiplier = ((node.Attributes["max_hit_points_bonus_multiplier"] != null) ? float.Parse(node.Attributes["max_hit_points_bonus_multiplier"].Value) : 0f);
		MaxSailHitPointsBonusMultiplier = ((node.Attributes["max_sail_hit_points_bonus_multiplier"] != null) ? float.Parse(node.Attributes["max_sail_hit_points_bonus_multiplier"].Value) : 0f);
		SeaWorthinessBonus = ((node.Attributes["sea_worthiness_bonus"] != null) ? int.Parse(node.Attributes["sea_worthiness_bonus"].Value) : 0);
		CrewShieldHitPointsBonusMultiplier = ((node.Attributes["crew_shield_hit_points_bonus_multiplier"] != null) ? float.Parse(node.Attributes["crew_shield_hit_points_bonus_multiplier"].Value) : 0f);
		InventoryCapacityBonusMultiplier = ((node.Attributes["inventory_capacity_bonus_multiplier"] != null) ? float.Parse(node.Attributes["inventory_capacity_bonus_multiplier"].Value) : 0f);
		AdditionalAmmoBonus = ((node.Attributes["additional_ammo_bonus"] != null) ? int.Parse(node.Attributes["additional_ammo_bonus"].Value) : 0);
		MaxOarPowerBonusMultiplier = ((node.Attributes["max_oar_power_bonus_multiplier"] != null) ? float.Parse(node.Attributes["max_oar_power_bonus_multiplier"].Value) : 0f);
		MaxOarForceBonusMultiplier = ((node.Attributes["max_oar_force_bonus_multiplier"] != null) ? float.Parse(node.Attributes["max_oar_force_bonus_multiplier"].Value) : 0f);
		SailForceBonusMultiplier = ((node.Attributes["sail_force_bonus_multiplier"] != null) ? float.Parse(node.Attributes["sail_force_bonus_multiplier"].Value) : 0f);
		CrewMeleeDamageBonusMultiplier = ((node.Attributes["crew_melee_damage_bonus_multiplier"] != null) ? float.Parse(node.Attributes["crew_melee_damage_bonus_multiplier"].Value) : 0f);
		ArcherQuiverBonus = ((node.Attributes["archer_quiver_bonus"] != null) ? int.Parse(node.Attributes["archer_quiver_bonus"].Value) : 0);
		ThrowingWeaponStackBonus = ((node.Attributes["throwing_weapon_stack_bonus"] != null) ? int.Parse(node.Attributes["throwing_weapon_stack_bonus"].Value) : 0);
		SailRotationSpeedBonusMultiplier = ((node.Attributes["sail_rotation_speed_bonus_multiplier"] != null) ? float.Parse(node.Attributes["sail_rotation_speed_bonus_multiplier"].Value) : 0f);
		FurlUnfurlSpeedBonusMultiplier = ((node.Attributes["furl_unfurl_speed_bonus_multipler"] != null) ? float.Parse(node.Attributes["furl_unfurl_speed_bonus_multipler"].Value) : 0f);
		RudderSurfaceAreaBonusMultiplier = ((node.Attributes["rudder_surface_area_bonus_multiplier"] != null) ? float.Parse(node.Attributes["rudder_surface_area_bonus_multiplier"].Value) : 0f);
		MaxRudderForceBonusMultiplier = ((node.Attributes["max_rudder_force_bonus_multiplier"] != null) ? float.Parse(node.Attributes["max_rudder_force_bonus_multiplier"].Value) : 0f);
		SiegeEngine = objectManager.ReadObjectReferenceFromXml<SiegeEngineType>("siege_engine", node);
		List<ShipSlot> list = new List<ShipSlot>();
		foreach (XmlNode childNode in node.ChildNodes)
		{
			if (!(childNode.Name == "TargetSlots"))
			{
				continue;
			}
			foreach (XmlNode childNode2 in childNode.ChildNodes)
			{
				ShipSlot shipSlot = (ShipSlot)MBObjectManager.Instance.CreateObjectFromXmlNode(childNode2);
				shipSlot.AddMatchingPiece(this);
				list.Add(shipSlot);
			}
		}
		if (_targetSlots == null)
		{
			_targetSlots = list.ToMBList();
		}
		else
		{
			_targetSlots.AddRange(list);
		}
	}

	public override string ToString()
	{
		return Name.ToString();
	}

	public override TextObject GetName()
	{
		return Name;
	}

	public bool DoesPieceMatchSlot(ShipSlot slot)
	{
		return TargetSlots.Contains(slot);
	}

	internal void AddTargetSlot(ShipSlot slot)
	{
		if (!_targetSlots.Contains(slot))
		{
			_targetSlots.Add(slot);
		}
	}
}
