from pathlib import Path
import sys,re,json,argparse,hashlib,subprocess,importlib.util
R=Path(__file__).resolve().parents[4];H=Path(__file__).parent
sys.path.insert(0,str(R/'tests'))
from output_isolation import new_run_root,minimal_test_environment
p=argparse.ArgumentParser();p.add_argument('--run-root',type=Path,required=True);p.add_argument('--mutate',choices=['guide_id','omit_public','append_flag']);a=p.parse_args();out=new_run_root(R,'ExternalScenePrompt',a.run_root)
s=importlib.util.spec_from_file_location('ex',R/'tests/modules/AF.Module.Conversation/ChannelCutoverBoundaryTests/run.py');ex=importlib.util.module_from_spec(s);s.loader.exec_module(ex)
main=(R/'src/modules/AF.Module.Conversation/Channels/Scene/ShoutBehavior.cs').read_text(encoding='utf-8-sig');forward=ex.declaration(main,'public static DetachedInteractionPromptSections BuildSceneShoutDetachedPromptSectionsForExternal(')
assert 'instance.CreateSceneExternalPromptCaptureAdapter().Build(playerText, targetAgentIndex)' in forward
paths=['src/AF.GameAdapter.Bannerlord/Composition/SceneExternalPromptCapturePorts.cs','src/AF.GameAdapter.Bannerlord/Composition/SceneExternalPromptCaptureAdapter.cs','src/modules/AF.Module.Conversation/Channels/Scene/ShoutBehavior.ExternalPromptCapture.cs']
comp=[R/x for x in paths]
assembly=(R/'src/modules/AF.Module.Prompt/Composition/MainPromptMessageAssemblyOwner.cs').read_text(encoding='utf-8-sig');history=(R/'src/modules/AF.Module.Prompt/Composition/HistorySectionProjectionOwner.cs').read_text(encoding='utf-8-sig');contracts=(R/'src/AF.Contracts/Internal/InteractionContracts.cs').read_text(encoding='utf-8-sig')
pure='using System;using System.Collections.Generic;using System.Linq;using System.Text;\nnamespace AnimusForge {internal static class MainPromptMessageAssemblyOwner{'+ex.declaration(assembly,'internal static string BuildSceneCompositeUserBlock(')+ex.declaration(assembly,'internal static AnimusForge.Refactor.Contracts.DetachedInteractionPromptSections BuildExternalScenePromptSections(')+'} internal static class HistorySectionProjectionOwner{'+ex.declaration(history,'internal static void SplitPersistedHeroHistorySections(')+ex.declaration(history,'internal static bool IsPrivateRecentWindowHeader(')+'}}'
contract='using System;using System.Collections.Generic;using System.Linq;\nnamespace AnimusForge.Refactor.Contracts {'+''.join(ex.declaration(contracts,'public sealed class '+n+'\n') for n in ['DetachedPromptSections','DetachedPostprocessPromptSections','DetachedInteractionPromptSections'])+'internal static class ContractCollections{'+ex.declaration(contracts,'public static IReadOnlyList<string> CopyStrings(')+'}}'
if a.mutate=='append_flag':assert pure.count('appendCurrentPlayerInput: true')==1;pure=pure.replace('appendCurrentPlayerInput: true','appendCurrentPlayerInput: false')
elif a.mutate:
 source=comp[1].read_text(encoding='utf-8');before,after={'guide_id':('summonTargets.Max(item => item?.PromptId ?? 0) + 1','summonTargets.Max(item => item?.PromptId ?? 0)'), 'omit_public':('privateRecent, persistedWithoutRecent, scenePublicHistory','privateRecent, persistedWithoutRecent, string.Empty')}[a.mutate];assert source.count(before)==1;(out/'MutatedAdapter.cs').write_text(source.replace(before,after),encoding='utf-8');comp.pop(1)
(out/'Pure.cs').write_text(pure,encoding='utf-8');(out/'Contracts.cs').write_text(contract,encoding='utf-8');(out/'Program.cs').write_text((H/'Harness.cs.txt').read_text(encoding='utf-8'),encoding='utf-8');(out/'Leaves.cs').write_text((H/'GameLeafStubs.cs.txt').read_text(encoding='utf-8').replace('@@LEGACY@@',(H/'LegacyBody.cs.txt').read_text(encoding='utf-8')).replace('@@FORWARD@@',forward),encoding='utf-8')
(out/'Tests.csproj').write_text('<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><NoWarn>CS0649</NoWarn></PropertyGroup><ItemGroup>'+''.join('<Compile Include="'+str(x)+'" />' for x in comp)+'</ItemGroup></Project>',encoding='utf-8');(out/'NuGet.Config').write_text('<configuration><packageSources><clear/></packageSources></configuration>',encoding='utf-8')
d=R/'local/dotnet/8.0.425/dotnet.exe';r=subprocess.run([str(d),'run','--project',str(out/'Tests.csproj'),'-c','Release'],cwd=out,env=minimal_test_environment(d,out),capture_output=True,text=True,encoding='utf-8',errors='replace',timeout=120);(out/'run.log').write_text(r.stdout+r.stderr,encoding='utf-8');print(r.stdout+r.stderr,end='')
paths+=['src/modules/AF.Module.Prompt/Composition/MainPromptMessageAssemblyOwner.cs','src/modules/AF.Module.Prompt/Composition/HistorySectionProjectionOwner.cs','src/AF.Contracts/Internal/InteractionContracts.cs']
(out/'receipt.json').write_text(json.dumps({'exit_code':r.returncode,'source_sha256':{x:hashlib.sha256((R/x).read_bytes()).hexdigest() for x in paths},'fixture_sha256':{x.name:hashlib.sha256(x.read_bytes()).hexdigest() for x in H.iterdir() if x.is_file()},'consumer':'actual public facade and whole typed factory; original full135 oracle; query leaves synthetic; pure real owner methods and real contracts source extracted','live':'NOT_RUN'},indent=2),encoding='utf-8');sys.exit(r.returncode)
