using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.CampaignBehaviors;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.Core;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Election;

public class StartAllianceDecision : KingdomDecision
{
	public class StartAllianceDecisionOutcome : DecisionOutcome
	{
		[SaveableField(100)]
		public readonly bool ShouldAllianceBeStarted;

		[SaveableField(110)]
		public readonly Kingdom Kingdom;

		[SaveableField(120)]
		public readonly Kingdom KingdomToStartAllianceWith;

		public StartAllianceDecisionOutcome(bool shouldAllianceBeStarted, Kingdom kingdom, Kingdom kingdomToStartAllianceWith)
		{
			ShouldAllianceBeStarted = shouldAllianceBeStarted;
			Kingdom = kingdom;
			KingdomToStartAllianceWith = kingdomToStartAllianceWith;
		}

		public override TextObject GetDecisionTitle()
		{
			TextObject textObject = new TextObject("{=kakxnaN5}{?SUPPORT}Yes{?}No{\\?}");
			textObject.SetTextVariable("SUPPORT", ShouldAllianceBeStarted ? 1 : 0);
			return textObject;
		}

		public override TextObject GetDecisionDescription()
		{
			if (ShouldAllianceBeStarted)
			{
				TextObject textObject = new TextObject("{=k3418kiP}It is time to form alliance with {KINGDOM_NAME}.");
				textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.Name);
				return textObject;
			}
			TextObject textObject2 = new TextObject("{=M1X2R8Uv}We oppose forming an alliance with {KINGDOM_NAME}.");
			textObject2.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.Name);
			return textObject2;
		}

		public override string GetDecisionLink()
		{
			return null;
		}

		public override ImageIdentifier GetDecisionImageIdentifier()
		{
			return null;
		}
	}

	[SaveableField(101)]
	public readonly Kingdom KingdomToStartAllianceWith;

	private IAllianceCampaignBehavior _allianceCampaignBehavior;

	public IAllianceCampaignBehavior AllianceCampaignBehavior
	{
		get
		{
			if (_allianceCampaignBehavior == null)
			{
				_allianceCampaignBehavior = Campaign.Current.GetCampaignBehavior<IAllianceCampaignBehavior>();
			}
			return _allianceCampaignBehavior;
		}
	}

	internal static void AutoGeneratedStaticCollectObjectsStartAllianceDecision(object o, List<object> collectedObjects)
	{
		((StartAllianceDecision)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		collectedObjects.Add(KingdomToStartAllianceWith);
	}

	internal static object AutoGeneratedGetMemberValueKingdomToStartAllianceWith(object o)
	{
		return ((StartAllianceDecision)o).KingdomToStartAllianceWith;
	}

	public StartAllianceDecision(Clan proposerClan, Kingdom kingdomToStartAllianceWith)
		: base(proposerClan)
	{
		KingdomToStartAllianceWith = kingdomToStartAllianceWith;
	}

	public override bool IsAllowed()
	{
		TextObject reason;
		return Campaign.Current.Models.KingdomDecisionPermissionModel.IsStartAllianceDecisionAllowedBetweenKingdoms(base.Kingdom, KingdomToStartAllianceWith, out reason);
	}

	public override int GetProposalInfluenceCost()
	{
		return Campaign.Current.Models.AllianceModel.GetInfluenceCostOfProposingStartingAlliance(base.ProposerClan);
	}

	public override TextObject GetGeneralTitle()
	{
		TextObject textObject = new TextObject("{=aE7OQDMS}Form alliance with the {KINGDOM_NAME}");
		textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.InformalName);
		return textObject;
	}

	public override TextObject GetSupportTitle()
	{
		TextObject textObject = new TextObject("{=iOmgCFDI}Vote to form an alliance with the {KINGDOM_NAME}.");
		textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.InformalName);
		return textObject;
	}

	public override TextObject GetChooseTitle()
	{
		TextObject textObject = new TextObject("{=KlATZEbb}Forming an Alliance with the {KINGDOM_NAME}.");
		textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.InformalName);
		return textObject;
	}

	public override TextObject GetSupportDescription()
	{
		TextObject textObject = new TextObject("{=wijL0mTy}{FACTION_LEADER} will decide if an alliance will be formed with the {KINGDOM_NAME}. You can pick your stance regarding this decision.");
		textObject.SetTextVariable("FACTION_LEADER", DetermineChooser().Leader.Name);
		textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.InformalName);
		return textObject;
	}

	public override TextObject GetChooseDescription()
	{
		TextObject textObject = new TextObject("{=eAhgrwkZ}As {RULER_NAME_AND_TITLE}, you must decide if an alliance will be formed with the {KINGDOM_NAME}.");
		textObject.SetCharacterProperties("RULER", base.Kingdom.Leader.CharacterObject);
		textObject.SetTextVariable("RULER_NAME_AND_TITLE", GameTexts.FindText("str_faction_ruler_name_with_title", base.Kingdom.Culture.StringId));
		textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.InformalName);
		return textObject;
	}

	public override IEnumerable<DecisionOutcome> DetermineInitialCandidates()
	{
		yield return new StartAllianceDecisionOutcome(shouldAllianceBeStarted: true, base.Kingdom, KingdomToStartAllianceWith);
		yield return new StartAllianceDecisionOutcome(shouldAllianceBeStarted: false, base.Kingdom, KingdomToStartAllianceWith);
	}

	public override Clan DetermineChooser()
	{
		return base.Kingdom.RulingClan;
	}

	protected override bool ShouldBeCancelledInternal()
	{
		TextObject reason;
		return !CanMakeDecision(out reason);
	}

	public override void DetermineSponsors(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
	{
		foreach (DecisionOutcome possibleOutcome in possibleOutcomes)
		{
			if (((StartAllianceDecisionOutcome)possibleOutcome).ShouldAllianceBeStarted)
			{
				possibleOutcome.SetSponsor(base.ProposerClan);
			}
			else
			{
				AssignDefaultSponsor(possibleOutcome);
			}
		}
	}

	public override void ApplyChosenOutcome(DecisionOutcome chosenOutcome)
	{
		if (((StartAllianceDecisionOutcome)chosenOutcome).ShouldAllianceBeStarted)
		{
			AllianceCampaignBehavior.StartAlliance(base.Kingdom, KingdomToStartAllianceWith);
		}
	}

	public override bool OnShowDecision()
	{
		if (KingdomToStartAllianceWith == Clan.PlayerClan.Kingdom && !Hero.MainHero.Clan.IsUnderMercenaryService)
		{
			AllianceCampaignBehavior.OnAllianceOfferedToPlayerKingdom(base.Kingdom);
			return false;
		}
		return true;
	}

	public override void ApplySecondaryEffects(MBReadOnlyList<DecisionOutcome> possibleOutcomes, DecisionOutcome chosenOutcome)
	{
	}

	public override TextObject GetSecondaryEffects()
	{
		return new TextObject("{=!}All supporters gains some relation with each other.");
	}

	public override TextObject GetChosenOutcomeText(DecisionOutcome chosenOutcome, SupportStatus supportStatus, bool isShortVersion = false)
	{
		TextObject textObject = (((StartAllianceDecisionOutcome)chosenOutcome).ShouldAllianceBeStarted ? (IsSingleClanDecision() ? new TextObject("{=INfHUqxT}{RULER.NAME} has decided to form an alliance with the {KINGDOM_NAME}.") : (supportStatus switch
		{
			SupportStatus.Majority => new TextObject("{=FNCq25P1}{RULER.NAME} has decided to form an alliance with the {KINGDOM_NAME} with the support of {?RULER.GENDER}her{?}his{\\?} council."), 
			SupportStatus.Minority => new TextObject("{=bYmc9fi3}{RULER.NAME} has decided to form an alliance with the {KINGDOM_NAME} despite the opposition of {?RULER.GENDER}her{?}his{\\?} council."), 
			_ => new TextObject("{=izwKmH2I}{RULER.NAME} has decided to form an alliance with the {KINGDOM_NAME} with the support of half of {?RULER.GENDER}her{?}his{\\?} council."), 
		})) : (IsSingleClanDecision() ? new TextObject("{=o4IxXHnB}{RULER.NAME} has decided against forming an alliance with the {KINGDOM_NAME}.") : (supportStatus switch
		{
			SupportStatus.Majority => new TextObject("{=bR7MIkFi}{RULER.NAME} has decided against forming an alliance with the {KINGDOM_NAME} with the support of {?RULER.GENDER}her{?}his{\\?} council."), 
			SupportStatus.Minority => new TextObject("{=F7CMsDyG}{RULER.NAME} has decided against forming an alliance with the {KINGDOM_NAME} despite the opposition of {?RULER.GENDER}her{?}his{\\?} council."), 
			_ => new TextObject("{=jaioXYDc}{RULER.NAME} has decided against forming an alliance with the {KINGDOM_NAME} with the support of half of {?RULER.GENDER}her{?}his{\\?} council."), 
		})));
		StringHelpers.SetCharacterProperties("RULER", base.Kingdom.Leader.CharacterObject, textObject);
		textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.Name);
		return textObject;
	}

	public override DecisionOutcome GetQueriedDecisionOutcome(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
	{
		return possibleOutcomes.FirstOrDefault((DecisionOutcome t) => ((StartAllianceDecisionOutcome)t).ShouldAllianceBeStarted);
	}

	public float CalculateSupport(Clan clan, out TextObject hint, bool includeDescriptions = false)
	{
		return DetermineSupport(clan, new StartAllianceDecisionOutcome(shouldAllianceBeStarted: true, base.Kingdom, KingdomToStartAllianceWith), out hint, includeDescriptions);
	}

	public override float DetermineSupport(Clan clan, DecisionOutcome possibleOutcome)
	{
		TextObject hint;
		return DetermineSupport(clan, possibleOutcome, out hint, includeDescriptions: false);
	}

	private float DetermineSupport(Clan clan, DecisionOutcome possibleOutcome, out TextObject hint, bool includeDescriptions)
	{
		StartAllianceDecisionOutcome obj = (StartAllianceDecisionOutcome)possibleOutcome;
		float supportScoreOfStartingAllianceForClan = Campaign.Current.Models.AllianceModel.GetSupportScoreOfStartingAllianceForClan(base.Kingdom, KingdomToStartAllianceWith, clan, out hint, includeDescriptions);
		if (obj.ShouldAllianceBeStarted)
		{
			return supportScoreOfStartingAllianceForClan;
		}
		return 0f - supportScoreOfStartingAllianceForClan;
	}

	public override bool CanMakeDecision(out TextObject reason, bool includeReason = false)
	{
		return Campaign.Current.Models.AllianceModel.CanMakeAlliance(base.Kingdom, KingdomToStartAllianceWith, base.ProposerClan, out reason, includeReason);
	}
}
